In [1]:
import feedparser
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

clean_path = "../data/clean/"
raw_path = "../data/raw/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
pdf_path = "../PDF/"

pd.set_option('display.max_colwidth', 255)
pd.set_option('display.max_rows',None)
url = "https://feeds.feedburner.com/Setorth-form45-en"

today = date.today()
year = 2022
mmdd_str = today.strftime('%m%d')
mmdd_str

'0218'

In [2]:
today = date(2023, 2, 17)
mmdd_str = today.strftime('%m%d')
mmdd_str

'0217'

In [3]:
rss_source = feedparser.parse(url)
f45_number = len(rss_source.entries)
print("Number of F45: ", f45_number)

Number of F45:  31

In [4]:
f45_items = []

for x in range(f45_number):
    f45_content = rss_source.entries[x]
    f45_item = {}
    
    print("\n----------------------------------\n")
    
    print("F45: " + str(x))
    title_ary = f45_content.title.partition(' ')
    f45_item['name'] = title_ary[0].strip() 
    print("Title: ", f45_item['name'])  
    f45_item['year'] = year
    print("Year: ", f45_item['year'])      
    qtr_ary = title_ary[2].partition(' (F45)')
    f45_item['quarter'] = qtr_ary[0][-1]    
    print("Quarter: ", f45_item['quarter'])    
    f45_item['link'] = f45_content.link
    print("Link: ", f45_item['link'])
    f45_item['published'] = f45_content.published
    print("Published: ", f45_item['published'])  
    f45_items.append(f45_item)

----------------------------------

F45: 0
Title:  TFM
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519400&symbol=TFM
Published:  Fri, 17 Feb 2023 21:58:38 +0700

----------------------------------

F45: 1
Title:  PSH
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519340&symbol=PSH
Published:  Fri, 17 Feb 2023 21:57:02 +0700

----------------------------------

F45: 2
Title:  SNC
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519160&symbol=SNC
Published:  Fri, 17 Feb 2023 21:47:10 +0700

----------------------------------

F45: 3
Title:  CPNREIT
Year:  2022
Quarter:  e
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517840&symbol=CPNREIT
Published:  Fri, 17 Feb 2023 20:43:48 +0700

----------------------------------

F45: 4
Title:  APP
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517720&symbol=APP
Published:  Fri, 17 Feb 2023 20:38:59 +0700

----------------------------------

F45: 5
Title:  SCB
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517250&symbol=SCB
Published:  Fri, 17 Feb 2023 20:13:25 +0700

----------------------------------

F45: 6
Title:  STGT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517170&symbol=STGT
Published:  Fri, 17 Feb 2023 20:09:56 +0700

----------------------------------

F45: 7
Title:  TIDLOR
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516950&symbol=TIDLOR
Published:  Fri, 17 Feb 2023 20:03:18 +0700

----------------------------------

F45: 8
Title:  STA
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516900&symbol=STA
Published:  Fri, 17 Feb 2023 19:56:31 +0700

----------------------------------

F45: 9
Title:  ROH
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516700&symbol=ROH
Published:  Fri, 17 Feb 2023 19:48:55 +0700

----------------------------------

F45: 10
Title:  PRAPAT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516160&symbol=PRAPAT
Published:  Fri, 17 Feb 2023 19:39:58 +0700

----------------------------------

F45: 11
Title:  PHOL
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910515000&symbol=PHOL
Published:  Fri, 17 Feb 2023 19:24:42 +0700

----------------------------------

F45: 12
Title:  CBG
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910513020&symbol=CBG
Published:  Fri, 17 Feb 2023 18:56:30 +0700

----------------------------------

F45: 13
Title:  HENG
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910512940&symbol=HENG
Published:  Fri, 17 Feb 2023 18:51:18 +0700

----------------------------------

F45: 14
Title:  MST
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910511990&symbol=MST
Published:  Fri, 17 Feb 2023 18:38:01 +0700

----------------------------------

F45: 15
Title:  MGT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910509880&symbol=MGT
Published:  Fri, 17 Feb 2023 18:17:12 +0700

----------------------------------

F45: 16
Title:  AUCT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910507850&symbol=AUCT
Published:  Fri, 17 Feb 2023 18:01:32 +0700

----------------------------------

F45: 17
Title:  MST
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910506960&symbol=MST
Published:  Fri, 17 Feb 2023 17:52:30 +0700

----------------------------------

F45: 18
Title:  XO
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910506450&symbol=XO
Published:  Fri, 17 Feb 2023 17:49:26 +0700

----------------------------------

F45: 19
Title:  PRAPAT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910504500&symbol=PRAPAT
Published:  Fri, 17 Feb 2023 17:35:38 +0700

----------------------------------

F45: 20
Title:  IFS
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910504190&symbol=IFS
Published:  Fri, 17 Feb 2023 17:34:25 +0700

----------------------------------

F45: 21
Title:  HPF
Year:  2022
Quarter:  e
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910503820&symbol=HPF
Published:  Fri, 17 Feb 2023 17:30:46 +0700

----------------------------------

F45: 22
Title:  MNIT2
Year:  2022
Quarter:  e
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502600&symbol=MNIT2
Published:  Fri, 17 Feb 2023 17:26:05 +0700

----------------------------------

F45: 23
Title:  NER
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502080&symbol=NER
Published:  Fri, 17 Feb 2023 17:23:59 +0700

----------------------------------

F45: 24
Title:  TASCO
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910501140&symbol=TASCO
Published:  Fri, 17 Feb 2023 17:18:23 +0700

----------------------------------

F45: 25
Title:  AHC
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910498540&symbol=AHC
Published:  Fri, 17 Feb 2023 17:04:03 +0700

----------------------------------

F45: 26
Title:  AI
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910484010&symbol=AI
Published:  Fri, 17 Feb 2023 12:51:13 +0700

----------------------------------

F45: 27
Title:  MNIT
Year:  2022
Quarter:  e
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483690&symbol=MNIT
Published:  Fri, 17 Feb 2023 12:43:02 +0700

----------------------------------

F45: 28
Title:  AIE
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483670&symbol=AIE
Published:  Fri, 17 Feb 2023 12:42:47 +0700

----------------------------------

F45: 29
Title:  WGE
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910477050&symbol=WGE
Published:  Fri, 17 Feb 2023 08:45:54 +0700

----------------------------------

F45: 30
Title:  TPCH
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910476140&symbol=TPCH
Published:  Fri, 17 Feb 2023 08:28:39 +0700

In [5]:
df = pd.DataFrame(f45_items)
df[['name','year','quarter','published']]

       name  year quarter                        published
0       TFM  2022       y  Fri, 17 Feb 2023 21:58:38 +0700
1       PSH  2022       y  Fri, 17 Feb 2023 21:57:02 +0700
2       SNC  2022       y  Fri, 17 Feb 2023 21:47:10 +0700
3   CPNREIT  2022       e  Fri, 17 Feb 2023 20:43:48 +0700
4       APP  2022       y  Fri, 17 Feb 2023 20:38:59 +0700
5       SCB  2022       y  Fri, 17 Feb 2023 20:13:25 +0700
6      STGT  2022       y  Fri, 17 Feb 2023 20:09:56 +0700
7    TIDLOR  2022       y  Fri, 17 Feb 2023 20:03:18 +0700
8       STA  2022       y  Fri, 17 Feb 2023 19:56:31 +0700
9       ROH  2022       y  Fri, 17 Feb 2023 19:48:55 +0700
10   PRAPAT  2022       y  Fri, 17 Feb 2023 19:39:58 +0700
11     PHOL  2022       y  Fri, 17 Feb 2023 19:24:42 +0700
12      CBG  2022       y  Fri, 17 Feb 2023 18:56:30 +0700
13     HENG  2022       y  Fri, 17 Feb 2023 18:51:18 +0700
14      MST  2022       y  Fri, 17 Feb 2023 18:38:01 +0700
15      MGT  2022       y  Fri, 17 Feb 2023 18:17:12 +0700
16     AUCT  2022       y  Fri, 17 Feb 2023 18:01:32 +0700
17      MST  2022       y  Fri, 17 Feb 2023 17:52:30 +0700
18       XO  2022       y  Fri, 17 Feb 2023 17:49:26 +0700
19   PRAPAT  2022       y  Fri, 17 Feb 2023 17:35:38 +0700
20      IFS  2022       y  Fri, 17 Feb 2023 17:34:25 +0700
21      HPF  2022       e  Fri, 17 Feb 2023 17:30:46 +0700
22    MNIT2  2022       e  Fri, 17 Feb 2023 17:26:05 +0700
23      NER  2022       y  Fri, 17 Feb 2023 17:23:59 +0700
24    TASCO  2022       y  Fri, 17 Feb 2023 17:18:23 +0700
25      AHC  2022       y  Fri, 17 Feb 2023 17:04:03 +0700
26       AI  2022       y  Fri, 17 Feb 2023 12:51:13 +0700
27     MNIT  2022       e  Fri, 17 Feb 2023 12:43:02 +0700
28      AIE  2022       y  Fri, 17 Feb 2023 12:42:47 +0700
29      WGE  2022       y  Fri, 17 Feb 2023 08:45:54 +0700
30     TPCH  2022       y  Fri, 17 Feb 2023 08:28:39 +0700

In [6]:
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 e           4     4          4
     y          27    27         27

In [7]:
df.loc[(df.quarter == 'y') ,['year','quarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 e           4     4          4
     4          27    27         27

In [8]:
df.loc[(df.quarter == 'e') ,['year','quarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 4          31    31         31

In [10]:
df.loc[(df.quarter == 'S') ,['year','quarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 1           1     1          1
     3           9     9          9
     3           1     1          1
     4          13    13         13

In [8]:
df.loc[(df.quarter == ')') ,['year','quarter']] = ['2022','3']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 1           1     1          1
     2           1     1          1
     3           9     9          9
     S           1     1          1
     3           1     1          1
     4          11    11         11

In [10]:
df.loc[(df.quarter == '2') ,['year','qAuarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 1           1     1          1
     3           1     1          1
     4           6     6          6

In [11]:
df.loc[(df.name == 'GVREIT') ,['year','quarter']] = ['2023','1']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 3           9     9          9
     3           1     1          1
     4          13    13         13
2023 1           1     1          1

### After change all illogical quarters

In [9]:
df.quarter = df.quarter.astype(int)
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 4          31    31         31

In [10]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='name', keep='first')
df.shape

(29, 5)

In [11]:
file_name = 'F45-RAW-' + mmdd_str + '.csv'
raw_file = raw_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name

df[['name','year','quarter','published']].to_csv(output_file, header=True, index=False, sep=',')
df[['name','year','quarter','published']].to_csv(one_file,    header=True, index=False, sep=',')
df[['name','year','quarter','published']].to_csv(raw_file,    header=True, index=False, sep=',')

In [12]:
sql = '''
SELECT *
FROM exempts
ORDER BY name'''
df_exempts = pd.read_sql(sql, conlt)
df_exempts.shape[0]

403

In [13]:
df_merge = pd.merge(df, df_exempts, on='name', how='outer', indicator=True)
df_merge.shape

(423, 7)

### Tickers that are in Exempts table

In [14]:
in_exempts = df_merge.loc[
    df_merge['_merge'] == 'both',
    ['name','year','quarter','published','link']
    
]
in_exempts.year = in_exempts.year.astype(int)
in_exempts.quarter = in_exempts.quarter.astype(int)
in_exempts.sort_values(by=['published'],ascending=[False])

,name,year,quarter,published,link
9,ROH,2022,4,"Fri, 17 Feb 2023 19:48:55 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516700&symbol=ROH
11,PHOL,2022,4,"Fri, 17 Feb 2023 19:24:42 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910515000&symbol=PHOL
15,MGT,2022,4,"Fri, 17 Feb 2023 18:17:12 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910509880&symbol=MGT
16,AUCT,2022,4,"Fri, 17 Feb 2023 18:01:32 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910507850&symbol=AUCT
17,XO,2022,4,"Fri, 17 Feb 2023 17:49:26 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910506450&symbol=XO
18,IFS,2022,4,"Fri, 17 Feb 2023 17:34:25 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910504190&symbol=IFS
23,AHC,2022,4,"Fri, 17 Feb 2023 17:04:03 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910498540&symbol=AHC
24,AI,2022,4,"Fri, 17 Feb 2023 12:51:13 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910484010&symbol=AI
28,TPCH,2022,4,"Fri, 17 Feb 2023 08:28:39 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910476140&symbol=TPCH

In [15]:
in_exempts.sort_values(by=['published'],ascending=[False]).shape[0]

9

### Not in exempts table

In [18]:
df_out = df_merge.loc[
    df_merge['_merge'] == 'left_only',
    ['name','year','quarter','published','link']
]
df_out.year = df_out.year.astype(int)
df_out.quarter = df_out.quarter.astype(int)
df_out.sort_values(by=['published'],ascending=[False])

,name,year,quarter,published,link
0,TFM,2022,4,"Fri, 17 Feb 2023 21:58:38 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519400&symbol=TFM
1,PSH,2022,4,"Fri, 17 Feb 2023 21:57:02 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519340&symbol=PSH
2,SNC,2022,4,"Fri, 17 Feb 2023 21:47:10 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519160&symbol=SNC
3,CPNREIT,2022,4,"Fri, 17 Feb 2023 20:43:48 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517840&symbol=CPNREIT
4,APP,2022,4,"Fri, 17 Feb 2023 20:38:59 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517720&symbol=APP
5,SCB,2022,4,"Fri, 17 Feb 2023 20:13:25 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517250&symbol=SCB
6,STGT,2022,4,"Fri, 17 Feb 2023 20:09:56 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517170&symbol=STGT
7,TIDLOR,2022,4,"Fri, 17 Feb 2023 20:03:18 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516950&symbol=TIDLOR
8,STA,2022,4,"Fri, 17 Feb 2023 19:56:31 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516900&symbol=STA
10,PRAPAT,2022,4,"Fri, 17 Feb 2023 19:39:58 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516160&symbol=PRAPAT
12,CBG,2022,4,"Fri, 17 Feb 2023 18:56:30 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910513020&symbol=CBG
13,HENG,2022,4,"Fri, 17 Feb 2023 18:51:18 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910512940&symbol=HENG
14,MST,2022,4,"Fri, 17 Feb 2023 18:38:01 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910511990&symbol=MST
19,HPF,2022,4,"Fri, 17 Feb 2023 17:30:46 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910503820&symbol=HPF
20,MNIT2,2022,4,"Fri, 17 Feb 2023 17:26:05 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502600&symbol=MNIT2
21,NER,2022,4,"Fri, 17 Feb 2023 17:23:59 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502080&symbol=NER
22,TASCO,2022,4,"Fri, 17 Feb 2023 17:18:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910501140&symbol=TASCO
25,MNIT,2022,4,"Fri, 17 Feb 2023 12:43:02 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483690&symbol=MNIT
26,AIE,2022,4,"Fri, 17 Feb 2023 12:42:47 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483670&symbol=AIE
27,WGE,2022,4,"Fri, 17 Feb 2023 08:45:54 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910477050&symbol=WGE

In [19]:
#df_out = df_out.drop(df_out.index[df_out['name'] == "SCC"])
df_out.shape[0]

20

In [20]:
sql = '''
SELECT *
FROM tickers
ORDER BY name'''
df_tickers = pd.read_sql(sql, conlt)
df_tickers.shape

(401, 9)

In [21]:
df_merge2 = pd.merge(df_out, df_tickers, on='name', how='outer', indicator=True)
df_merge2.shape

(409, 14)

### There are no ticker records

In [22]:
df_merge2.loc[
    df_merge2['_merge'] == 'left_only',
    ['name','year','quarter','published','link']
]

,name,year,quarter,published,link
0,TFM,2022.0,4.0,"Fri, 17 Feb 2023 21:58:38 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519400&symbol=TFM
4,APP,2022.0,4.0,"Fri, 17 Feb 2023 20:38:59 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517720&symbol=APP
9,PRAPAT,2022.0,4.0,"Fri, 17 Feb 2023 19:39:58 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516160&symbol=PRAPAT
11,HENG,2022.0,4.0,"Fri, 17 Feb 2023 18:51:18 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910512940&symbol=HENG
13,HPF,2022.0,4.0,"Fri, 17 Feb 2023 17:30:46 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910503820&symbol=HPF
14,MNIT2,2022.0,4.0,"Fri, 17 Feb 2023 17:26:05 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502600&symbol=MNIT2
17,MNIT,2022.0,4.0,"Fri, 17 Feb 2023 12:43:02 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483690&symbol=MNIT
19,WGE,2022.0,4.0,"Fri, 17 Feb 2023 08:45:54 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910477050&symbol=WGE

In [23]:
df_merge2.loc[
    df_merge2['_merge'] == 'left_only',
    ['name','year','quarter','published','link','id','market']
].shape

(8, 7)

### There are ticker records

In [24]:
df_out2 = df_merge2.loc[
    df_merge2['_merge'] == 'both',
    ['name','year','quarter','published','link','id','market']
]
df_out2

,name,year,quarter,published,link,id,market
1,PSH,2022.0,4.0,"Fri, 17 Feb 2023 21:57:02 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519340&symbol=PSH,377.0,SETTHSI
2,SNC,2022.0,4.0,"Fri, 17 Feb 2023 21:47:10 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519160&symbol=SNC,457.0,sSET / SETTHSI
3,CPNREIT,2022.0,4.0,"Fri, 17 Feb 2023 20:43:48 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517840&symbol=CPNREIT,647.0,SET
5,SCB,2022.0,4.0,"Fri, 17 Feb 2023 20:13:25 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517250&symbol=SCB,426.0,SET50 / SETCLMV / SETTHSI
6,STGT,2022.0,4.0,"Fri, 17 Feb 2023 20:09:56 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517170&symbol=STGT,714.0,SET100 / SETTHSI
7,TIDLOR,2022.0,4.0,"Fri, 17 Feb 2023 20:03:18 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516950&symbol=TIDLOR,723.0,SET50
8,STA,2022.0,4.0,"Fri, 17 Feb 2023 19:56:31 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516900&symbol=STA,481.0,SET100 / SETTHSI / SETWB
10,CBG,2022.0,4.0,"Fri, 17 Feb 2023 18:56:30 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910513020&symbol=CBG,87.0,SET50 / SETCLMV / SETWB
12,MST,2022.0,4.0,"Fri, 17 Feb 2023 18:38:01 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910511990&symbol=MST,290.0,SET
15,NER,2022.0,4.0,"Fri, 17 Feb 2023 17:23:59 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502080&symbol=NER,680.0,sSET
16,TASCO,2022.0,4.0,"Fri, 17 Feb 2023 17:18:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910501140&symbol=TASCO,502.0,SET100 / SETCLMV / SETHD / SETTHSI
18,AIE,2022.0,4.0,"Fri, 17 Feb 2023 12:42:47 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483670&symbol=AIE,720.0,sSET

In [25]:
df_out2 = df_out2[df_out2.year.notnull()]
df_out2.shape

(12, 7)

In [26]:
df_out2['year'] = df_out2['year'].astype(int)
df_out2['quarter'] = df_out2['quarter'].astype(int)
df_out2.shape

(12, 7)

In [27]:
file_name = 'F45-CLEAN-' + mmdd_str + '.csv'
clean_file = clean_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name

df_out2[['name','year','quarter','published','market']].sort_values(['published'],ascending=[False]).to_csv(output_file, header=True, index=False, sep=',')
df_out2[['name','year','quarter','published','market']].sort_values(['published'],ascending=[False]).to_csv(clean_file, header=True, index=False, sep=',')
df_out2[['name','year','quarter','published','market']].sort_values(['published'],ascending=[False]).to_csv(one_file, header=True, index=False, sep=',')

In [28]:
sql = '''
SELECT * 
FROM epss
WHERE year = 2022'''
df_epss = pd.read_sql(sql, conlt)
df_epss.shape

(757, 14)

In [29]:
df_merge3 = pd.merge(df_out2, df_epss, on=['name','year','quarter'], how='outer', indicator=True)
df_merge3.shape

(768, 19)

### Already input, display profit amt & eps to check with new F45

In [30]:
df_merge3[df_merge3['_merge'] == 'both']

,name,year,quarter,published,link,id_x,market,id_y,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date,_merge
3,SCB,2022,4,"Fri, 17 Feb 2023 20:13:25 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517250&symbol=SCB,426.0,SET50 / SETCLMV / SETTHSI,22172.0,7142603.0,7871906.0,37546011.0,35589987.0,2.13,2.32,11.12,10.47,426.0,2023-01-20,both

In [31]:
df_merge3[df_merge3['_merge'] == 'both'].shape

(1, 19)

### New F-45

In [32]:
df_inp2 = df_merge3[df_merge3['_merge'] == 'left_only']
df_inp3 = df_inp2.copy()
df_inp3.shape

(11, 19)

In [33]:
df_inp3['year'] = df_inp3['year'].astype(str)
df_inp3['quarter'] = df_inp3['quarter'].astype(str)
final = df_inp3.sort_values('name',ascending=True)
final_str = final.name+' '+final.year+' '+final.quarter+' '+final.link
final_str

11            AIE 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483670&symbol=AIE
7             CBG 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910513020&symbol=CBG
2     CPNREIT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517840&symbol=CPNREIT
8             MST 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910511990&symbol=MST
9             NER 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502080&symbol=NER
0             PSH 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519340&symbol=PSH
1             SNC 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519160&symbol=SNC
6             STA 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516900&symbol=STA
4           STGT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517170&symbol=STGT
10        TASCO 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910501140&symbol=TASCO
5       TIDLOR 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516950&symbol=TIDLOR
dtype: object

In [34]:
df_inp3_q3 = df_inp3[df_inp3['quarter'] == '4']
final_q3 = df_inp3_q3.sort_values('name',ascending=True)
final_str_q3 = final_q3.name+' '+final_q3.year+' '+final_q3.quarter+' '+final_q3.link
final_str_q3

11            AIE 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910483670&symbol=AIE
7             CBG 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910513020&symbol=CBG
2     CPNREIT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517840&symbol=CPNREIT
8             MST 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910511990&symbol=MST
9             NER 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910502080&symbol=NER
0             PSH 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519340&symbol=PSH
1             SNC 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910519160&symbol=SNC
6             STA 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516900&symbol=STA
4           STGT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910517170&symbol=STGT
10        TASCO 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910501140&symbol=TASCO
5       TIDLOR 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765910516950&symbol=TIDLOR
dtype: object

In [35]:
df_inp3_q1 = df_inp3[df_inp3['quarter'] != '4']
final_q1 = df_inp3_q1.sort_values('name',ascending=True)
final_str_q1 = final_q1.name+' '+final_q1.year+' '+final_q1.quarter+' '+final_q1.link
final_str_q1

Series([], dtype: object)