In [1]:
import feedparser
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

clean_path = "../data/clean/"
raw_path = "../data/raw/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
pdf_path = "../PDF/"

pd.set_option('display.max_colwidth', 255)
pd.set_option('display.max_rows',None)
url = "https://feeds.feedburner.com/Setorth-form45-en"

today = date.today()
year = 2022
mmdd_str = today.strftime('%m%d')
mmdd_str

'0216'

In [2]:
#today = date(2023, 2, 10)
mmdd_str = today.strftime('%m%d')
mmdd_str

'0216'

In [3]:
rss_source = feedparser.parse(url)
f45_number = len(rss_source.entries)
print("Number of F45: ", f45_number)

Number of F45:  23

In [4]:
f45_items = []

for x in range(f45_number):
    f45_content = rss_source.entries[x]
    f45_item = {}
    
    print("\n----------------------------------\n")
    
    print("F45: " + str(x))
    title_ary = f45_content.title.partition(' ')
    f45_item['name'] = title_ary[0].strip() 
    print("Title: ", f45_item['name'])  
    f45_item['year'] = year
    print("Year: ", f45_item['year'])      
    qtr_ary = title_ary[2].partition(' (F45)')
    f45_item['quarter'] = qtr_ary[0][-1]    
    print("Quarter: ", f45_item['quarter'])    
    f45_item['link'] = f45_content.link
    print("Link: ", f45_item['link'])
    f45_item['published'] = f45_content.published
    print("Published: ", f45_item['published'])  
    f45_items.append(f45_item)

----------------------------------

F45: 0
Title:  SC
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029831700&symbol=SC
Published:  Thu, 16 Feb 2023 21:52:34 +0700

----------------------------------

F45: 1
Title:  ASEFA
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029830100&symbol=ASEFA
Published:  Thu, 16 Feb 2023 20:59:23 +0700

----------------------------------

F45: 2
Title:  GIFT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829580&symbol=GIFT
Published:  Thu, 16 Feb 2023 20:18:25 +0700

----------------------------------

F45: 3
Title:  S11
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829280&symbol=S11
Published:  Thu, 16 Feb 2023 20:11:07 +0700

----------------------------------

F45: 4
Title:  KDH
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029827650&symbol=KDH
Published:  Thu, 16 Feb 2023 19:02:16 +0700

----------------------------------

F45: 5
Title:  AIT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029826600&symbol=AIT
Published:  Thu, 16 Feb 2023 18:49:06 +0700

----------------------------------

F45: 6
Title:  PTT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029825220&symbol=PTT
Published:  Thu, 16 Feb 2023 18:35:56 +0700

----------------------------------

F45: 7
Title:  WIIK
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029824290&symbol=WIIK
Published:  Thu, 16 Feb 2023 18:22:51 +0700

----------------------------------

F45: 8
Title:  SPVI
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029824250&symbol=SPVI
Published:  Thu, 16 Feb 2023 18:22:26 +0700

----------------------------------

F45: 9
Title:  BBGI
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029822030&symbol=BBGI
Published:  Thu, 16 Feb 2023 18:04:31 +0700

----------------------------------

F45: 10
Title:  GULF
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821600&symbol=GULF
Published:  Thu, 16 Feb 2023 17:58:26 +0700

----------------------------------

F45: 11
Title:  GLORY
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821030&symbol=GLORY
Published:  Thu, 16 Feb 2023 17:54:09 +0700

----------------------------------

F45: 12
Title:  KBSPIF
Year:  2022
Quarter:  e
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029819880&symbol=KBSPIF
Published:  Thu, 16 Feb 2023 17:45:26 +0700

----------------------------------

F45: 13
Title:  SVI
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029817000&symbol=SVI
Published:  Thu, 16 Feb 2023 17:14:00 +0700

----------------------------------

F45: 14
Title:  LPN
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029805030&symbol=LPN
Published:  Thu, 16 Feb 2023 13:03:23 +0700

----------------------------------

F45: 15
Title:  PT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029803950&symbol=PT
Published:  Thu, 16 Feb 2023 12:37:12 +0700

----------------------------------

F45: 16
Title:  BVG
Year:  2022
Quarter:  3
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029796620&symbol=BVG
Published:  Thu, 16 Feb 2023 08:47:42 +0700

----------------------------------

F45: 17
Title:  BVG
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029796220&symbol=BVG
Published:  Thu, 16 Feb 2023 08:44:43 +0700

----------------------------------

F45: 18
Title:  PDG
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794670&symbol=PDG
Published:  Thu, 16 Feb 2023 08:24:39 +0700

----------------------------------

F45: 19
Title:  BH
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794610&symbol=BH
Published:  Thu, 16 Feb 2023 08:22:23 +0700

----------------------------------

F45: 20
Title:  DRT
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794150&symbol=DRT
Published:  Thu, 16 Feb 2023 08:05:33 +0700

----------------------------------

F45: 21
Title:  SKR
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794050&symbol=SKR
Published:  Thu, 16 Feb 2023 08:00:41 +0700

----------------------------------

F45: 22
Title:  THANI
Year:  2022
Quarter:  y
Link:  https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029793810&symbol=THANI
Published:  Thu, 16 Feb 2023 07:40:05 +0700

In [5]:
df = pd.DataFrame(f45_items)
df[['name','year','quarter','published']]

      name  year quarter                        published
0       SC  2022       y  Thu, 16 Feb 2023 21:52:34 +0700
1    ASEFA  2022       y  Thu, 16 Feb 2023 20:59:23 +0700
2     GIFT  2022       y  Thu, 16 Feb 2023 20:18:25 +0700
3      S11  2022       y  Thu, 16 Feb 2023 20:11:07 +0700
4      KDH  2022       y  Thu, 16 Feb 2023 19:02:16 +0700
5      AIT  2022       y  Thu, 16 Feb 2023 18:49:06 +0700
6      PTT  2022       y  Thu, 16 Feb 2023 18:35:56 +0700
7     WIIK  2022       y  Thu, 16 Feb 2023 18:22:51 +0700
8     SPVI  2022       y  Thu, 16 Feb 2023 18:22:26 +0700
9     BBGI  2022       y  Thu, 16 Feb 2023 18:04:31 +0700
10    GULF  2022       y  Thu, 16 Feb 2023 17:58:26 +0700
11   GLORY  2022       y  Thu, 16 Feb 2023 17:54:09 +0700
12  KBSPIF  2022       e  Thu, 16 Feb 2023 17:45:26 +0700
13     SVI  2022       y  Thu, 16 Feb 2023 17:14:00 +0700
14     LPN  2022       y  Thu, 16 Feb 2023 13:03:23 +0700
15      PT  2022       y  Thu, 16 Feb 2023 12:37:12 +0700
16     BVG  2022       3  Thu, 16 Feb 2023 08:47:42 +0700
17     BVG  2022       y  Thu, 16 Feb 2023 08:44:43 +0700
18     PDG  2022       y  Thu, 16 Feb 2023 08:24:39 +0700
19      BH  2022       y  Thu, 16 Feb 2023 08:22:23 +0700
20     DRT  2022       y  Thu, 16 Feb 2023 08:05:33 +0700
21     SKR  2022       y  Thu, 16 Feb 2023 08:00:41 +0700
22   THANI  2022       y  Thu, 16 Feb 2023 07:40:05 +0700

In [6]:
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 3           1     1          1
     e           1     1          1
     y          21    21         21

In [7]:
df.loc[(df.quarter == 'y') ,['year','quarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 3           1     1          1
     e           1     1          1
     4          21    21         21

In [8]:
df.loc[(df.quarter == 'e') ,['year','quarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 3           1     1          1
     4          22    22         22

In [10]:
df.loc[(df.quarter == 'S') ,['year','quarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 1           1     1          1
     3           9     9          9
     3           1     1          1
     4          13    13         13

In [8]:
df.loc[(df.quarter == ')') ,['year','quarter']] = ['2022','3']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 1           1     1          1
     2           1     1          1
     3           9     9          9
     S           1     1          1
     3           1     1          1
     4          11    11         11

In [10]:
df.loc[(df.quarter == '2') ,['year','qAuarter']] = ['2022','4']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 1           1     1          1
     3           1     1          1
     4           6     6          6

In [11]:
df.loc[(df.name == 'GVREIT') ,['year','quarter']] = ['2023','1']
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 3           9     9          9
     3           1     1          1
     4          13    13         13
2023 1           1     1          1

### After change all illogical quarters

In [9]:
df.quarter = df.quarter.astype(int)
df.groupby(['year','quarter']).count()

              name  link  published
year quarter
2022 3           1     1          1
     4          22    22         22

In [10]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='name', keep='first')
df.shape

(22, 5)

In [11]:
file_name = 'F45-RAW-' + mmdd_str + '.csv'
raw_file = raw_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name

df[['name','year','quarter','published']].to_csv(output_file, header=True, index=False, sep=',')
df[['name','year','quarter','published']].to_csv(one_file,    header=True, index=False, sep=',')
df[['name','year','quarter','published']].to_csv(raw_file,    header=True, index=False, sep=',')

In [12]:
sql = '''
SELECT *
FROM exempts
ORDER BY name'''
df_exempts = pd.read_sql(sql, conlt)
df_exempts.shape[0]

403

In [13]:
df_merge = pd.merge(df, df_exempts, on='name', how='outer', indicator=True)
df_merge.shape

(419, 7)

### Tickers that are in Exempts table

In [14]:
in_exempts = df_merge.loc[
    df_merge['_merge'] == 'both',
    ['name','year','quarter','published','link']
    
]
in_exempts.year = in_exempts.year.astype(int)
in_exempts.quarter = in_exempts.quarter.astype(int)
in_exempts.sort_values(by=['published'],ascending=[False])

,name,year,quarter,published,link
1,ASEFA,2022,4,"Thu, 16 Feb 2023 20:59:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029830100&symbol=ASEFA
2,GIFT,2022,4,"Thu, 16 Feb 2023 20:18:25 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829580&symbol=GIFT
4,KDH,2022,4,"Thu, 16 Feb 2023 19:02:16 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029827650&symbol=KDH
7,WIIK,2022,4,"Thu, 16 Feb 2023 18:22:51 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029824290&symbol=WIIK
8,SPVI,2022,4,"Thu, 16 Feb 2023 18:22:26 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029824250&symbol=SPVI
15,PT,2022,4,"Thu, 16 Feb 2023 12:37:12 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029803950&symbol=PT

In [15]:
in_exempts.sort_values(by=['published'],ascending=[False]).shape[0]

6

### Not in exempts table

In [16]:
df_out = df_merge.loc[
    df_merge['_merge'] == 'left_only',
    ['name','year','quarter','published','link']
]
df_out.year = df_out.year.astype(int)
df_out.quarter = df_out.quarter.astype(int)
df_out.sort_values(by=['published'],ascending=[False])

,name,year,quarter,published,link
0,SC,2022,4,"Thu, 16 Feb 2023 21:52:34 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029831700&symbol=SC
3,S11,2022,4,"Thu, 16 Feb 2023 20:11:07 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829280&symbol=S11
5,AIT,2022,4,"Thu, 16 Feb 2023 18:49:06 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029826600&symbol=AIT
6,PTT,2022,4,"Thu, 16 Feb 2023 18:35:56 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029825220&symbol=PTT
9,BBGI,2022,4,"Thu, 16 Feb 2023 18:04:31 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029822030&symbol=BBGI
10,GULF,2022,4,"Thu, 16 Feb 2023 17:58:26 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821600&symbol=GULF
11,GLORY,2022,4,"Thu, 16 Feb 2023 17:54:09 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821030&symbol=GLORY
12,KBSPIF,2022,4,"Thu, 16 Feb 2023 17:45:26 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029819880&symbol=KBSPIF
13,SVI,2022,4,"Thu, 16 Feb 2023 17:14:00 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029817000&symbol=SVI
14,LPN,2022,4,"Thu, 16 Feb 2023 13:03:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029805030&symbol=LPN
16,BVG,2022,3,"Thu, 16 Feb 2023 08:47:42 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029796620&symbol=BVG
17,PDG,2022,4,"Thu, 16 Feb 2023 08:24:39 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794670&symbol=PDG
18,BH,2022,4,"Thu, 16 Feb 2023 08:22:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794610&symbol=BH
19,DRT,2022,4,"Thu, 16 Feb 2023 08:05:33 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794150&symbol=DRT
20,SKR,2022,4,"Thu, 16 Feb 2023 08:00:41 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794050&symbol=SKR
21,THANI,2022,4,"Thu, 16 Feb 2023 07:40:05 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029793810&symbol=THANI

In [17]:
#df_out = df_out.drop(df_out.index[df_out['name'] == "SCC"])
df_out.shape[0]

16

In [18]:
sql = '''
SELECT *
FROM tickers
ORDER BY name'''
df_tickers = pd.read_sql(sql, conlt)
df_tickers.shape

(401, 9)

In [19]:
df_merge2 = pd.merge(df_out, df_tickers, on='name', how='outer', indicator=True)
df_merge2.shape

(405, 14)

### There are no ticker records

In [20]:
df_merge2.loc[
    df_merge2['_merge'] == 'left_only',
    ['name','year','quarter','published','link']
]

,name,year,quarter,published,link
4,BBGI,2022.0,4.0,"Thu, 16 Feb 2023 18:04:31 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029822030&symbol=BBGI
6,GLORY,2022.0,4.0,"Thu, 16 Feb 2023 17:54:09 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821030&symbol=GLORY
7,KBSPIF,2022.0,4.0,"Thu, 16 Feb 2023 17:45:26 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029819880&symbol=KBSPIF
10,BVG,2022.0,3.0,"Thu, 16 Feb 2023 08:47:42 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029796620&symbol=BVG

In [21]:
df_merge2.loc[
    df_merge2['_merge'] == 'left_only',
    ['name','year','quarter','published','link','id','market']
].shape

(4, 7)

### There are ticker records

In [22]:
df_out2 = df_merge2.loc[
    df_merge2['_merge'] == 'both',
    ['name','year','quarter','published','link','id','market']
]
df_out2

,name,year,quarter,published,link,id,market
0,SC,2022.0,4.0,"Thu, 16 Feb 2023 21:52:34 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029831700&symbol=SC,425.0,sSET / SETTHSI
1,S11,2022.0,4.0,"Thu, 16 Feb 2023 20:11:07 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829280&symbol=S11,412.0,sSET
2,AIT,2022.0,4.0,"Thu, 16 Feb 2023 18:49:06 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029826600&symbol=AIT,11.0,sSET
3,PTT,2022.0,4.0,"Thu, 16 Feb 2023 18:35:56 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029825220&symbol=PTT,383.0,SET50 / SETCLMV / SETHD / SETTHSI
5,GULF,2022.0,4.0,"Thu, 16 Feb 2023 17:58:26 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821600&symbol=GULF,653.0,SET50 / SETCLMV / SETTHSI
8,SVI,2022.0,4.0,"Thu, 16 Feb 2023 17:14:00 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029817000&symbol=SVI,491.0,SET
9,LPN,2022.0,4.0,"Thu, 16 Feb 2023 13:03:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029805030&symbol=LPN,276.0,sSET / SETTHSI
11,PDG,2022.0,4.0,"Thu, 16 Feb 2023 08:24:39 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794670&symbol=PDG,347.0,mai
12,BH,2022.0,4.0,"Thu, 16 Feb 2023 08:22:23 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794610&symbol=BH,61.0,SET50 / SETCLMV / SETWB
13,DRT,2022.0,4.0,"Thu, 16 Feb 2023 08:05:33 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794150&symbol=DRT,143.0,sSET / SETCLMV / SETTHSI
14,SKR,2022.0,4.0,"Thu, 16 Feb 2023 08:00:41 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794050&symbol=SKR,451.0,SET
15,THANI,2022.0,4.0,"Thu, 16 Feb 2023 07:40:05 +0700",https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029793810&symbol=THANI,522.0,SET100 / SETHD / SETTHSI

In [23]:
df_out2 = df_out2[df_out2.year.notnull()]
df_out2.shape

(12, 7)

In [24]:
df_out2['year'] = df_out2['year'].astype(int)
df_out2['quarter'] = df_out2['quarter'].astype(int)
df_out2.shape

(12, 7)

In [25]:
file_name = 'F45-CLEAN-' + mmdd_str + '.csv'
clean_file = clean_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name

df_out2[['name','year','quarter','published','market']].sort_values(['published'],ascending=[False]).to_csv(output_file, header=True, index=False, sep=',')
df_out2[['name','year','quarter','published','market']].sort_values(['published'],ascending=[False]).to_csv(clean_file, header=True, index=False, sep=',')
df_out2[['name','year','quarter','published','market']].sort_values(['published'],ascending=[False]).to_csv(one_file, header=True, index=False, sep=',')

In [26]:
sql = '''
SELECT * 
FROM epss
WHERE year = 2022'''
df_epss = pd.read_sql(sql, conlt)
df_epss.shape

(745, 14)

In [27]:
df_merge3 = pd.merge(df_out2, df_epss, on=['name','year','quarter'], how='outer', indicator=True)
df_merge3.shape

(757, 19)

### Already input, display profit amt & eps to check with new F45

In [28]:
df_merge3[df_merge3['_merge'] == 'both']

Empty DataFrame
Columns: [name, year, quarter, published, link, id_x, market, id_y, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps, ticker_id, publish_date, _merge]
Index: []

In [29]:
df_merge3[df_merge3['_merge'] == 'both'].shape

(0, 19)

### New F-45

In [30]:
df_inp2 = df_merge3[df_merge3['_merge'] == 'left_only']
df_inp3 = df_inp2.copy()
df_inp3.shape

(12, 19)

In [31]:
df_inp3['year'] = df_inp3['year'].astype(str)
df_inp3['quarter'] = df_inp3['quarter'].astype(str)
final = df_inp3.sort_values('name',ascending=True)
final_str = final.name+' '+final.year+' '+final.quarter+' '+final.link
final_str

2         AIT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029826600&symbol=AIT
8           BH 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794610&symbol=BH
9         DRT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794150&symbol=DRT
4       GULF 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821600&symbol=GULF
6         LPN 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029805030&symbol=LPN
7         PDG 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794670&symbol=PDG
3         PTT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029825220&symbol=PTT
1         S11 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829280&symbol=S11
0           SC 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029831700&symbol=SC
10        SKR 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794050&symbol=SKR
5         SVI 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029817000&symbol=SVI
11    THANI 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029793810&symbol=THANI
dtype: object

In [32]:
df_inp3_q3 = df_inp3[df_inp3['quarter'] == '4']
final_q3 = df_inp3_q3.sort_values('name',ascending=True)
final_str_q3 = final_q3.name+' '+final_q3.year+' '+final_q3.quarter+' '+final_q3.link
final_str_q3

2         AIT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029826600&symbol=AIT
8           BH 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794610&symbol=BH
9         DRT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794150&symbol=DRT
4       GULF 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029821600&symbol=GULF
6         LPN 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029805030&symbol=LPN
7         PDG 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794670&symbol=PDG
3         PTT 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029825220&symbol=PTT
1         S11 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029829280&symbol=S11
0           SC 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029831700&symbol=SC
10        SKR 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029794050&symbol=SKR
5         SVI 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029817000&symbol=SVI
11    THANI 2022 4 https://www.set.or.th/en/market/news-and-alert/newsdetails?id=16765029793810&symbol=THANI
dtype: object

In [33]:
df_inp3_q1 = df_inp3[df_inp3['quarter'] != '4']
final_q1 = df_inp3_q1.sort_values('name',ascending=True)
final_str_q1 = final_q1.name+' '+final_q1.year+' '+final_q1.quarter+' '+final_q1.link
final_str_q1

Series([], dtype: object)