### portmy database: profits, stocks tables
### portpg database: consensus, tickers tables
### csv files: consensus-ORD.csv

In [2]:
import pandas as pd
import numpy as np
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()
engine = create_engine('mysql+pymysql://root:@localhost:3306/stock')
const = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

# Define a formatting function to format integers with zero decimal places and floats with two decimal places
def format_cell(x):
    if isinstance(x, int):
        return "{:,.0f}".format(x)
    elif isinstance(x, float):
        return "{:.2f}".format(x)
    else:
        return x

pd.options.display.max_rows = 11
#pd.options.display.float_format = '{:.2f}'.format

today = date.today()
today

datetime.date(2023, 3, 6)

### Process after last business day, yesterday must be last business day

In [3]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-03-06
yesterday: 2023-03-03 00:00:00

In [4]:
# find the beginning of the week for the given yesterday
week_start = yesterday.to_period('W').start_time
week_end = yesterday.to_period('W').end_time
week_start = week_start.date()
week_end = week_end.date()
print(f'week start: {week_start}')
print(f'week end: {week_end}')

week start: 2023-02-27
week end: 2023-03-05

In [5]:
yesterday = yesterday.date()
week_start, yesterday

(datetime.date(2023, 2, 27), datetime.date(2023, 3, 3))

### Restart and Run All Cells

In [6]:
cols = 'quarter price target_price upside buy hold sell yield max_price min_price pe pbv dly_vol beta'.split()
colt = 'name price target_price upside buy hold sell market sector subsector dly_vol beta yield'.split()
colu = 'price target_price upside buy hold sell mrkt yield'.split()

format_dict = {
    'latest_amt_y':'{:,}','previous_amt_y':'{:,}','inc_amt_y':'{:,}',   
    'latest_amt_q':'{:,}','previous_amt_q':'{:,}','inc_amt_q':'{:,}',    
    'q_amt_c':'{:,}','y_amt': '{:,}','inc_amt_py':'{:,}', 
    'q_amt_p': '{:,}','inc_amt_pq':'{:,}', 
    'inc_pct_y': '{:.2f}%','inc_pct_q': '{:.2f}%',
    'inc_pct_py': '{:.2f}%','inc_pct_pq': '{:.2f}%',
    'mean_pct': '{:.2f}%','std_pct': '{:.2f}%','upside': '{:.2f}%', 
    
    'price':'{:.2f}','target_price':'{:.2f}','diff':'{:.2f}',
    'eps_a':'{:.2f}','eps_b':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'yield':'{:.2f}%',
    
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',   
    'daily_volume':'{:,.2f}','beta':'{:,.2f}', 
    'dly_vol':'{:,.2f}',    
}

In [7]:
sql = """
SELECT * FROM profits 
ORDER BY id DESC 
LIMIT 1
"""
tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

In [8]:
names = tmp['name'].values.tolist()
names

['SIRI']

In [9]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'SIRI'"

In [10]:
sql = '''
SELECT * FROM stocks 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT * FROM stocks
WHERE name IN ('SIRI')

In [11]:
sql = '''
SELECT * FROM tickers 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT * FROM tickers
WHERE name IN ('SIRI')

In [13]:
sql = '''
SELECT name, kind, year, quarter
FROM profits
ORDER BY name'''
#WHERE quarter = 4
my_profits = pd.read_sql(sql, conmy)
my_profits

     name  kind  year  quarter
0   AMATA     1  2022        4
1     ASK     1  2022        4
2     ASW     1  2022        4
3     AWC     1  2022        4
4   BANPU     1  2022        3
..    ...   ...   ...      ...
19    SNC     1  2022        4
20    TTB     1  2022        4
21    WHA     1  2022        4
22  WHART     1  2022        4
23   WICE     1  2022        4

[24 rows x 4 columns]

In [14]:
sql = """
SELECT name, price, target_price, 
buy, hold, sell, yield, 
date(updated_at), ('%s'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0
"""
sql = sql % (today)
print(sql)
#sql = sql % (today, today)
#AND ('%s'::date - date(updated_at)::date) < 15
consensus = pd.read_sql(sql, conpg)
consensus.set_index('name', inplace=True)
consensus['diff'] = consensus['target_price'] - consensus['price']
consensus['upside'] = round(consensus['diff']/consensus['price']*100,2)
consensus.shape

SELECT name, price, target_price,
buy, hold, sell, yield,
date(updated_at), ('2023-03-06'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0

(210, 10)

In [ ]:
#consensus.loc['TSTH',['target','upside']] = [1.52,1]

In [ ]:
prf_css = pd.merge(my_profits, consensus, on='name', how='inner')
prf_css.sample(10).style.format(format_dict)

In [ ]:
prf_css.days.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [ ]:
names = prf_css.loc[prf_css.days == 21]['name']
names

In [ ]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [ ]:
sqlDel = '''
DELETE FROM consensus 
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

In [ ]:
#rp = conpg.execute(sqlDel)
#rp.rowcount

### If there are deleted records, must rerun from select consensus

### Profits w/o consensus

In [ ]:
df_tmp = pd.merge(my_profits, consensus, on='name', how='outer',indicator=True)
prf_wo_css = df_tmp['_merge'] == 'left_only'
df_tmp[prf_wo_css]

In [ ]:
names = df_tmp[prf_wo_css]['name']
names

In [ ]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [ ]:
sqlDel = '''
DELETE FROM profits
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

In [ ]:
rp = conmy.execute(sqlDel)
rp.rowcount

### If there are deleted records, must rerun from select profits

### Start of Gain Percentage Calculation

In [15]:
sql = '''
SELECT name, max_price, min_price, pe, pbv, daily_volume AS dly_vol, beta, market
FROM stocks
'''
my_stocks = pd.read_sql(sql, conmy)
my_stocks.sample(10)

,name,max_price,min_price,pe,pbv,dly_vol,beta,market
150,SMPC,16.80,12.30,7.16,2.72,6.75,0.63,sSET
243,PSL,21.80,12.80,4.16,1.38,140.31,1.41,SET100 / SETTHSI
89,KSL,4.16,3.22,12.02,0.76,12.58,0.90,sSET / SETCLMV
91,KTC,68.00,52.00,22.16,4.97,407.59,0.99,SET50 / SETTHSI
93,LALIN,11.80,8.35,6.45,1.00,2.46,0.84,sSET
234,OR,28.00,22.50,20.05,2.56,399.87,0.77,SET50 / SETCLMV / SETTHSI
123,PSH,15.60,11.80,11.24,0.68,15.49,0.66,SETTHSI
204,PRM,8.10,4.90,11.63,1.93,92.04,1.34,sSET
85,KBANK,175.00,137.50,8.14,0.69,3135.49,0.97,SET50 / SETCLMV / SETTHSI
214,AIMIRT,13.00,11.70,999.99,1.00,2.58,0.09,SET

In [16]:
filters = [
   (my_stocks.market.str.contains('SET50')),
   (my_stocks.market.str.contains('SET100')),
   (my_stocks.market.str.contains('mai'))]
values = ['SET50','SET100','mai']
my_stocks["mrkt"] = np.select(filters, values, default='SET999')

In [17]:
my_stocks["mrkt"].value_counts()

SET999    148
SET50      50
SET100     46
mai         9
Name: mrkt, dtype: int64

In [18]:
prf_css_stk = pd.merge(prf_css, my_stocks, on='name', how='inner')
prf_css_stk.set_index('name', inplace=True)
prf_css_stk.shape

NameError: name 'prf_css' is not defined

In [ ]:
set50 = prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside >= s50_pct)
flt_set50 = prf_css_stk[set50]
flt_set50[cols].style.format(format_dict)

In [ ]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside < s50_pct)]\
    [cols].style.format(format_dict)

In [ ]:
set100 = prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside >= s100_pct)
flt_set100 = prf_css_stk[set100]
flt_set100[cols].style.format(format_dict)

In [ ]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside < s100_pct)]\
    [cols].style.format(format_dict)

In [ ]:
set999 = prf_css_stk.mrkt.str.contains('SET999') & (prf_css_stk.upside >= s999_pct) 
flt_set999 = prf_css_stk[set999]
flt_set999[cols].style.format(format_dict)

In [ ]:
prf_css_stk.loc\
    [(prf_css_stk.mrkt.str.contains('SET999')) & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [ ]:
mai = prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside >= s999_pct)
flt_mai = prf_css_stk[mai]
flt_mai[cols].style.format(format_dict)

In [ ]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [ ]:
flt_all = pd.concat([flt_set50,flt_set100,flt_set999,flt_mai])
flt_all.sort_values(['upside'],ascending=[False]).style.format(format_dict)

In [ ]:
flt_all[colu].sort_values(by='name',ascending=True).style.format(format_dict)

In [ ]:
'candidates to buy = ' + str(flt_all.shape[0]) + ' stocks'

In [ ]:
sql = '''
SELECT name, sector, subsector
FROM tickers'''
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape[0]

In [ ]:
final = pd.merge(flt_all, pg_tickers, on='name', how='inner')
final.reset_index()
final[colt].sort_values(['name'],ascending=[True]).to_json("C:/ClearStep/dist/consensus.json", orient="table")

### Final result to update to port_lite stocks

In [ ]:
final[colt].sort_values(['name'],ascending=[True]).style.format(format_dict)

In [ ]:
final.shape

### Matching check with Buy table in MySql database to filter only records not yet in stocks

In [19]:
sql = """
SELECT name
FROM buy
WHERE active = 1"""
buy_df = pd.read_sql(sql, const)
buy_df.shape

(26, 1)

In [20]:
final_buy = pd.merge(my_profits, buy_df, on='name', how='outer', indicator=True)
final_buy.shape

(45, 5)

In [25]:
final_buy.dtypes

name         object
kind        float64
year        float64
quarter     float64
_merge     category
dtype: object

In [21]:
not_in_port = final_buy.loc[
    final_buy['_merge'] == 'left_only']
not_in_port

     name  kind    year  quarter     _merge
0   AMATA  1.00 2022.00     4.00  left_only
2     ASW  1.00 2022.00     4.00  left_only
3     AWC  1.00 2022.00     4.00  left_only
5      BH  1.00 2022.00     4.00  left_only
6     BJC  1.00 2022.00     4.00  left_only
..    ...   ...     ...      ...        ...
18   SIRI  1.00 2022.00     4.00  left_only
19    SNC  1.00 2022.00     4.00  left_only
20    TTB  1.00 2022.00     4.00  left_only
21    WHA  1.00 2022.00     4.00  left_only
23   WICE  1.00 2022.00     4.00  left_only

[19 rows x 5 columns]

In [24]:
not_in_port.dtypes

name         object
kind        float64
year        float64
quarter     float64
_merge     category
dtype: object

In [26]:
not_in_port2 = not_in_port.copy()
not_in_port2

     name  kind    year  quarter     _merge
0   AMATA  1.00 2022.00     4.00  left_only
2     ASW  1.00 2022.00     4.00  left_only
3     AWC  1.00 2022.00     4.00  left_only
5      BH  1.00 2022.00     4.00  left_only
6     BJC  1.00 2022.00     4.00  left_only
..    ...   ...     ...      ...        ...
18   SIRI  1.00 2022.00     4.00  left_only
19    SNC  1.00 2022.00     4.00  left_only
20    TTB  1.00 2022.00     4.00  left_only
21    WHA  1.00 2022.00     4.00  left_only
23   WICE  1.00 2022.00     4.00  left_only

[19 rows x 5 columns]

In [27]:
file_name = 'consensus-ORD.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

not_in_port.sort_values(['name'],ascending=[True]).to_csv(output_file, index=False)
not_in_port.sort_values(['name'],ascending=[True]).to_csv(data_file, index=False)
not_in_port.sort_values(['name'],ascending=[True]).to_csv(box_file, index=False)
not_in_port.sort_values(['name'],ascending=[True]).to_csv(one_file, index=False)

In [ ]:
sql = """
SELECT *
FROM stocks"""
stocks = pd.read_sql(sql, conlite)
stocks.shape

In [ ]:
df_merge4 = pd.merge(not_in_port2, stocks, on='name', how='outer', indicator=True)
df_merge4.shape

In [ ]:
df_merge4[df_merge4['_merge'] == 'left_only'].sort_values('name',ascending=True)