### portmy database: profits, stocks tables
### portpg database: consensus, tickers tables
### csv files: consensus-ORD.csv

In [1]:
import pandas as pd
import numpy as np
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()
engine = create_engine('mysql+pymysql://root:@localhost:3306/stock')
const = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

pd.set_option('display.max_row', None)
pd.set_option('display.max_column', None)

today = date.today()
today

datetime.date(2022, 12, 24)

### Process after last business day, yesterday must be last business day

In [4]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2022-12-24
yesterday: 2022-12-23 00:00:00

In [5]:
# find the beginning of the week for the given yesterday
week_start = yesterday.to_period('W').start_time
week_end = yesterday.to_period('W').end_time
week_start = week_start.date()
week_end = week_end.date()
print(f'week start: {week_start}')
print(f'week end: {week_end}')

week start: 2022-12-19
week end: 2022-12-25

In [6]:
yesterday = yesterday.date()
week_start, yesterday

(datetime.date(2022, 12, 19), datetime.date(2022, 12, 23))

In [7]:
s50_pct = 25
s100_pct = 30
s999_pct = 35

### Restart and Run All Cells

In [8]:
cols = 'quarter price target_price upside buy hold sell yield max_price min_price pe pbv dly_vol beta'.split()
colt = 'name price target_price upside buy hold sell market sector subsector dly_vol beta yield'.split()
colu = 'price target_price upside buy hold sell mrkt yield'.split()

format_dict = {
    'latest_amt_y':'{:,}','previous_amt_y':'{:,}','inc_amt_y':'{:,}',   
    'latest_amt_q':'{:,}','previous_amt_q':'{:,}','inc_amt_q':'{:,}',    
    'q_amt_c':'{:,}','y_amt': '{:,}','inc_amt_py':'{:,}', 
    'q_amt_p': '{:,}','inc_amt_pq':'{:,}', 
    'inc_pct_y': '{:.2f}%','inc_pct_q': '{:.2f}%',
    'inc_pct_py': '{:.2f}%','inc_pct_pq': '{:.2f}%',
    'mean_pct': '{:.2f}%','std_pct': '{:.2f}%','upside': '{:.2f}%', 
    
    'price':'{:.2f}','target_price':'{:.2f}','diff':'{:.2f}',
    'eps_a':'{:.2f}','eps_b':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'yield':'{:.2f}%',
    
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',   
    'daily_volume':'{:,.2f}','beta':'{:,.2f}', 
    'dly_vol':'{:,.2f}',    
}

In [9]:
sql = """
SELECT * FROM profits 
ORDER BY id DESC 
LIMIT 1
"""
tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

In [10]:
names = tmp['name'].values.tolist()
names

['SIRI']

In [11]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'SIRI'"

In [12]:
sql = '''
SELECT * 
FROM consensus 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT *
FROM consensus
WHERE name IN ('SIRI')

In [13]:
sql = '''
SELECT * FROM stocks 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT * FROM stocks
WHERE name IN ('SIRI')

In [14]:
sql = '''
SELECT * FROM tickers 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT * FROM tickers
WHERE name IN ('SIRI')

In [15]:
sql = '''
SELECT name, kind, year, quarter
FROM profits
ORDER BY name'''
my_profits = pd.read_sql(sql, conmy)
my_profits

     name  kind  year  quarter
0      AH     1  2022        3
1     AIT     1  2022        3
2   BANPU     1  2022        3
3     BBL     1  2022        3
4    BDMS     1  2022        3
5     BEM     1  2022        3
6      BH     1  2022        3
7      CK     1  2022        3
8     CKP     1  2022        3
9    COM7     1  2022        3
10  CPALL     1  2022        3
11    CPF     1  2022        3
12    CPN     1  2022        3
13     EA     1  2022        3
14   GFPT     1  2022        3
15  HMPRO     1  2022        3
16   ICHI     1  2022        3
17    III     1  2022        3
18  JMART     1  2022        3
19    JMT     1  2022        3
20    KCE     1  2022        3
21    KKP     1  2022        3
22    KTB     1  2022        3
23     LH     1  2022        3
24   MEGA     1  2022        3
25    NER     1  2022        3
26    PTL     1  2022        1
27  PTTEP     1  2022        3
28     QH     1  2022        3
29  SAPPE     1  2022        3
30     SC     1  2022        3
31    SCB     1  2022        3
32   SIRI     1  2022        3
33  SPALI     1  2022        3
34    SVI     1  2022        3
35  SYNEX     1  2022        3
36    TFG     1  2022        3
37    TTB     1  2022        3

In [16]:
sql = """
SELECT name, price, target_price, 
buy, hold, sell, yield, 
date(updated_at), ('%s'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0
"""
sql = sql % (today)
print(sql)
#sql = sql % (today, today)
#AND ('%s'::date - date(updated_at)::date) < 15
consensus = pd.read_sql(sql, conpg)
consensus.set_index('name', inplace=True)
consensus['diff'] = consensus['target_price'] - consensus['price']
consensus['upside'] = round(consensus['diff']/consensus['price']*100,2)
consensus.shape

SELECT name, price, target_price,
buy, hold, sell, yield,
date(updated_at), ('2022-12-24'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0

(210, 10)

In [17]:
#consensus.loc['TSTH',['target','upside']] = [1.52,1]

In [18]:
prf_css = pd.merge(my_profits, consensus, on='name', how='inner')
prf_css.sample(10).style.format(format_dict)

In [19]:
prf_css.days.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [20]:
names = prf_css.loc[prf_css.days == 0]['name']
names

0        AH
1       AIT
2     BANPU
5       BEM
6        BH
7        CK
8       CKP
9      COM7
10    CPALL
11      CPF
12      CPN
13       EA
14     GFPT
15    HMPRO
18    JMART
19      JMT
20      KCE
21      KKP
22      KTB
23       LH
25      NER
26      PTL
27    PTTEP
29    SAPPE
30       SC
31      SCB
32     SIRI
33    SPALI
34      SVI
35    SYNEX
36      TFG
Name: name, dtype: object

In [21]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'AH', 'AIT', 'BANPU', 'BEM', 'BH', 'CK', 'CKP', 'COM7', 'CPALL', 'CPF', 'CPN', 'EA', 'GFPT', 'HMPRO', 'JMART', 'JMT', 'KCE', 'KKP', 'KTB', 'LH', 'NER', 'PTL', 'PTTEP', 'SAPPE', 'SC', 'SCB', 'SIRI', 'SPALI', 'SVI', 'SYNEX', 'TFG'"

In [22]:
sqlDel = '''
DELETE FROM consensus 
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

DELETE FROM consensus
WHERE name IN ('AH', 'AIT', 'BANPU', 'BEM', 'BH', 'CK', 'CKP', 'COM7', 'CPALL', 'CPF', 'CPN', 'EA', 'GFPT', 'HMPRO', 'JMART', 'JMT', 'KCE', 'KKP', 'KTB', 'LH', 'NER', 'PTL', 'PTTEP', 'SAPPE', 'SC', 'SCB', 'SIRI', 'SPALI', 'SVI', 'SYNEX', 'TFG')

In [ ]:
#rp = conpg.execute(sqlDel)
#rp.rowcount

### If there are deleted records, must rerun from select consensus

### Profits w/o consensus

In [23]:
df_tmp = pd.merge(my_profits, consensus, on='name', how='outer',indicator=True)
prf_wo_css = df_tmp['_merge'] == 'left_only'
df_tmp[prf_wo_css]

Empty DataFrame
Columns: [name, kind, year, quarter, price, target_price, buy, hold, sell, yield, date, days, diff, upside, _merge]
Index: []

In [24]:
names = df_tmp[prf_wo_css]['name']
names

Series([], Name: name, dtype: object)

In [25]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

''

In [26]:
sqlDel = '''
DELETE FROM profits
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

DELETE FROM profits
WHERE name IN ()

In [27]:
rp = conmy.execute(sqlDel)
rp.rowcount

0

### If there are deleted records, must rerun from select profits

### Start of Gain Percentage Calculation

In [28]:
sql = '''
SELECT name, max_price, min_price, pe, pbv, daily_volume AS dly_vol, beta, market
FROM stocks
'''
my_stocks = pd.read_sql(sql, conmy)
my_stocks.sample(10)

,name,max_price,min_price,pe,pbv,dly_vol,beta,market
171,TIPH,90.00,45.00,27.58,3.13,315.64,1.14,SET100
103,MAJOR,22.40,16.30,57.31,2.43,91.47,0.71,SET100 / SETCLMV / SETTHSI
106,MST,14.80,10.80,10.31,1.32,2.22,0.53,SET
181,TOP,63.25,47.25,3.29,0.80,828.34,1.10,SET50 / SETCLMV / SETTHSI
155,SPPT,6.00,3.20,999.99,1.95,5.42,0.74,SET
187,TSTH,1.67,0.99,6.19,0.72,16.94,1.12,sSET / SETCLMV / SETTHSI
173,TISCO,101.50,86.00,10.99,1.93,420.26,0.39,SET50 / SETHD / SETTHSI
239,VNG,8.75,5.55,8.12,1.30,12.40,0.55,sSET / SETCLMV
18,BCP,37.00,24.70,2.99,0.66,224.10,0.75,SET100 / SETCLMV / SETTHSI
218,NER,7.80,5.40,5.49,1.75,69.57,0.90,sSET

In [29]:
filters = [
   (my_stocks.market.str.contains('SET50')),
   (my_stocks.market.str.contains('SET100')),
   (my_stocks.market.str.contains('mai'))]
values = ['SET50','SET100','mai']
my_stocks["mrkt"] = np.select(filters, values, default='SET999')

In [30]:
my_stocks["mrkt"].value_counts()

SET999    144
SET50      50
SET100     50
mai         9
Name: mrkt, dtype: int64

In [31]:
prf_css_stk = pd.merge(prf_css, my_stocks, on='name', how='inner')
prf_css_stk.set_index('name', inplace=True)
prf_css_stk.shape

(38, 21)

In [32]:
set50 = prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside >= s50_pct)
flt_set50 = prf_css_stk[set50]
flt_set50[cols].style.format(format_dict)

In [33]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside < s50_pct)]\
    [cols].style.format(format_dict)

In [34]:
set100 = prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside >= s100_pct)
flt_set100 = prf_css_stk[set100]
flt_set100[cols].style.format(format_dict)

In [35]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside < s100_pct)]\
    [cols].style.format(format_dict)

In [36]:
set999 = prf_css_stk.mrkt.str.contains('SET999') & (prf_css_stk.upside >= s999_pct) 
flt_set999 = prf_css_stk[set999]
flt_set999[cols].style.format(format_dict)

In [37]:
prf_css_stk.loc\
    [(prf_css_stk.mrkt.str.contains('SET999')) & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [38]:
mai = prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside >= s999_pct)
flt_mai = prf_css_stk[mai]
flt_mai[cols].style.format(format_dict)

In [39]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [40]:
flt_all = pd.concat([flt_set50,flt_set100,flt_set999,flt_mai])
flt_all.sort_values(['upside'],ascending=[False]).style.format(format_dict)

In [41]:
flt_all[colu].sort_values(by='name',ascending=True).style.format(format_dict)

In [42]:
'candidates to buy = ' + str(flt_all.shape[0]) + ' stocks'

'candidates to buy = 13 stocks'

In [43]:
sql = '''
SELECT name, sector, subsector
FROM tickers'''
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape[0]

403

In [44]:
final = pd.merge(flt_all, pg_tickers, on='name', how='inner')
final.reset_index()
final[colt].sort_values(['name'],ascending=[True]).to_json("C:/ClearStep/dist/consensus.json", orient="table")

### Final result to update to port_lite stocks

In [45]:
final[colt].sort_values(['name'],ascending=[True]).style.format(format_dict)

In [46]:
final.shape

(13, 24)

### Matching check with Buy table in MySql database to filter only records not yet in stocks

In [47]:
sql = """
SELECT name
FROM buy
WHERE active = 1"""
buy_df = pd.read_sql(sql, const)
buy_df.shape

(26, 1)

In [48]:
final_buy = pd.merge(final, buy_df, on='name', how='outer', indicator=True)
final_buy.shape

(36, 25)

In [49]:
not_in_port = final_buy.loc[
    final_buy['_merge'] == 'left_only']
not_in_port[colt].shape

(10, 13)

In [50]:
not_in_port2 = not_in_port[colt].copy()
not_in_port2

,name,price,target_price,upside,buy,hold,sell,market,sector,subsector,dly_vol,beta,yield
0,BANPU,13.40,16.78,25.22,8.0,2.0,0.0,SET50 / SETCLMV / SETTHSI,Resources,Energy & Utilities,1606.13,0.75,9.7
1,CPF,24.60,31.52,28.13,13.0,1.0,0.0,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,Agro & Food Industry,Food & Beverage,624.48,0.83,3.1
3,JMT,65.00,81.61,25.55,9.0,0.0,0.0,SET50,Financials,Finance & Securities,752.61,1.61,1.4
4,SCB,105.00,143.10,36.29,7.0,0.0,0.0,SET50 / SETCLMV / SETTHSI,Financials,Banking,1528.75,1.35,4.2
5,CKP,4.64,6.45,39.01,7.0,1.0,0.0,SET100 / SETCLMV / SETTHSI,Resources,Energy & Utilities,82.61,1.07,2.2
6,MEGA,45.25,59.25,30.94,8.0,2.0,0.0,SET100 / SETCLMV / SETWB,Services,Commerce,164.58,1.07,3.2
7,AH,29.50,41.10,39.32,7.0,1.0,0.0,sSET / SETTHSI,Industrials,Automotive,66.06,1.43,5.2
9,III,13.00,18.25,40.38,6.0,0.0,0.0,sSET,Services,Transportation & Logistics,81.55,0.98,3.2
11,SVI,9.45,15.23,61.16,4.0,0.0,0.0,SET,Technology,Electronic Components,81.49,2.23,2.5
12,TFG,5.15,8.85,71.84,5.0,0.0,0.0,SET,Agro & Food Industry,Food & Beverage,71.53,1.13,6.6

In [51]:
file_name = 'consensus-ORD.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(output_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(data_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(box_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(one_file, index=False)

In [52]:
sql = """
SELECT *
FROM stocks"""
stocks = pd.read_sql(sql, conlite)
stocks.shape

(62, 18)

In [53]:
df_merge4 = pd.merge(not_in_port2, stocks, on='name', how='outer', indicator=True)
df_merge4.shape

(62, 31)

In [54]:
df_merge4[df_merge4['_merge'] == 'left_only'].sort_values('name',ascending=True)

Empty DataFrame
Columns: [name, price, target_price, upside, buy, hold, sell, market_x, sector, subsector, dly_vol, beta_x, yield, id, max_price, min_price, status, buy_target, sell_target, volume, beta_y, cost, qty, buy_spread, sell_spread, available_qty, bl, sh, reason, market_y, _merge]
Index: []