### portmy database: stocks table
### stock database: buy, price tables

In [1]:
import pandas as pd
import numpy as np
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
conmy = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.float_format','{:,.2f}'.format)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"

today = date.today()
today

datetime.date(2023, 1, 28)

### Process after last business day, yesterday must be last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-28
yesterday: 2023-01-27 00:00:00

In [3]:
yesterday = yesterday.date()
week_ago = yesterday -timedelta(days = 7)
print(f'a week ago: {week_ago}')
print(f'yesterday: {yesterday}')

a week ago: 2023-01-20
yesterday: 2023-01-27

### Restart & Run All Cells

### This process affects only already in port stocks. To highlight price changes in percent.

In [4]:
cols = 'name price_w price_d percent perform mrkt '.split()

format_dict = {
    'qty':'{:,}',    
    'price':'{:.2f}','price_d':'{:.2f}','price_w':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','opnp':'{:.2f}',    
    'pct':'{:,.2f}%','percent':'{:,.2f}%',
    
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',
    'daily_volume':'{:,.2f}','beta':'{:,.2f}', 
    'dly_vol':'{:,.2f}', 
}

In [5]:
sql = """
SELECT name, date, price 
FROM buy 
ORDER BY date DESC 
LIMIT 1
"""
df_buy = pd.read_sql(sql, const)
df_buy.style.format(format_dict)

In [6]:
names = df_buy['name']
name = names.to_string(index=False)

sql = '''
SELECT * FROM stocks WHERE name = '%s'
'''
sql = sql % name
print(sql)

df_stocks = pd.read_sql(sql, conmy)
df_stocks.style.format(format_dict)

SELECT * FROM stocks WHERE name = 'JMT'

In [7]:
sql = '''
SELECT * FROM price WHERE name = "%s" ORDER BY date DESC LIMIT 5
'''
sql = sql % name
print(sql)

df_price = pd.read_sql(sql, const)
df_price.style.format(format_dict)

SELECT * FROM price WHERE name = "JMT" ORDER BY date DESC LIMIT 5

In [8]:
sql = '''
SELECT name
FROM buy 
WHERE active = 1
ORDER BY name'''
df_price = pd.read_sql(sql, const)

names = df_price.name.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))

sql = """
SELECT name, price AS price_d 
FROM price 
WHERE date = '%s' AND name IN (%s)
ORDER BY name, date"""
sql = sql % (yesterday, in_p)
print(sql)

df_today = pd.read_sql(sql, const)
df_today.shape[0]

SELECT name, price AS price_d
FROM price
WHERE date = '2023-01-27' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name, date

27

In [9]:
sql = """
SELECT name, price AS price_w
FROM price 
WHERE date = '%s' AND name IN (%s) 
ORDER BY name"""
sql = sql % (week_ago, in_p)
print(sql)

df_wkago = pd.read_sql(sql, const)
df_wkago.shape[0]

SELECT name, price AS price_w
FROM price
WHERE date = '2023-01-20' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name

27

In [10]:
trend = pd.merge(df_today, df_wkago, on='name',how='inner')
trend.shape

(27, 3)

In [11]:
def performance(vals):
    price_d, price_w = vals
    if (price_d > price_w):
        return 'Better'
    elif (price_d < price_w):
        return 'Worse'
    else:
        return 'No Change'

In [12]:
trend['percent'] = (trend.price_d-trend.price_w)/trend.price_w * 100

In [13]:
trend

       name  price_d  price_w  percent
0       ASP     3.10     3.08     0.65
1     BANPU    12.30    12.70    -3.15
2       BCH    20.90    21.10    -0.95
3   CPNREIT    19.50    20.40    -4.41
4       DCC     2.82     2.84    -0.70
5       DIF    13.70    13.60     0.74
6    GVREIT     9.45     9.30     1.61
7       IVL    41.25    42.25    -2.37
8     JASIF     8.15     8.25    -1.21
9     JMART    37.25    39.00    -4.49
10      JMT    55.50    64.75   -14.29
11      KCE    50.25    49.00     2.55
12      MCS    10.10     9.75     3.59
13      NER     6.60     6.35     3.94
14      ORI    11.90    11.90     0.00
15    PTTGC    50.50    50.00     1.00
16      RCL    31.75    31.00     2.42
17      SCC   340.00   355.00    -4.23
18     SCCC   158.50   159.00    -0.31
19     SENA     3.92     3.94    -0.51
20   SINGER    27.50    28.00    -1.79
21      STA    22.90    21.00     9.05
22    SYNEX    16.10    16.60    -3.01
23    TFFIF     8.15     8.10     0.62
24      TMT     8.35     8.05     3.73
25    WHAIR     7.80     7.95    -1.89
26    WHART    11.80    11.80     0.00

In [14]:
trend["perform"] = trend[["price_d","price_w"]].apply(performance, axis=1)

In [15]:
trend.sort_values(by=['percent'],ascending=[True]).style.format(format_dict)

### Filter only performance = "Worse"

In [16]:
mask = trend.perform == 'Worse'
trend[mask]

       name  price_d  price_w  percent perform
1     BANPU    12.30    12.70    -3.15   Worse
2       BCH    20.90    21.10    -0.95   Worse
3   CPNREIT    19.50    20.40    -4.41   Worse
4       DCC     2.82     2.84    -0.70   Worse
7       IVL    41.25    42.25    -2.37   Worse
8     JASIF     8.15     8.25    -1.21   Worse
9     JMART    37.25    39.00    -4.49   Worse
10      JMT    55.50    64.75   -14.29   Worse
17      SCC   340.00   355.00    -4.23   Worse
18     SCCC   158.50   159.00    -0.31   Worse
19     SENA     3.92     3.94    -0.51   Worse
20   SINGER    27.50    28.00    -1.79   Worse
22    SYNEX    16.10    16.60    -3.01   Worse
25    WHAIR     7.80     7.95    -1.89   Worse

In [17]:
trend.perform.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [18]:
sql = '''
SELECT name, max_price AS max, min_price AS min, pe, pbv, daily_volume AS volume, beta, market
FROM stocks
'''
my_stocks = pd.read_sql(sql, conmy)
my_stocks.shape

(253, 8)

In [19]:
filters = [
   (my_stocks.market.str.contains('SET50')),
   (my_stocks.market.str.contains('SET100')),
   (my_stocks.market.str.contains('mai'))]
values = ['SET50','SET100','mai']
my_stocks["mrkt"] = np.select(filters, values, default='SET999')

In [20]:
trend2 = pd.merge(trend, my_stocks, on='name', how='inner')
trend2.sort_values(['percent'],ascending=[True]).shape

(27, 13)

In [21]:
set50 = trend2.mrkt.str.contains('SET50') 
flt_set50 = trend2[set50]
flt_set50[cols].sort_values(by=['percent','name'],ascending=[True,True]).style.format(format_dict)

In [22]:
flt_set50.perform.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [23]:
set100 = trend2.mrkt.str.contains('SET100')
flt_set100 = trend2[set100]
flt_set100[cols].sort_values(by=['percent','name'],ascending=[True,True]).style.format(format_dict)

In [24]:
flt_set100[cols].perform.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [25]:
set999 = trend2.mrkt.str.contains('SET999')
flt_set999 = trend2[set999]
flt_set999[cols].sort_values(by=['percent','name'],ascending=[True,True]).style.format(format_dict)

In [26]:
flt_set999[cols].perform.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [27]:
setmai = trend2.mrkt.str.contains('mai')
flt_setmai = trend2[setmai]
flt_setmai[cols].sort_values(by=['percent','name'],ascending=[True,True]).style.format(format_dict)

In [28]:
flt_setmai[cols].perform.value_counts(normalize=True).to_frame().style.format('{:.2%}')