### portpg: stocks
### stock:  price

### Restart & Run All Cells

In [1]:
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine

engine1 = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine1.connect()

engine2 = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine2.connect()

pd.set_option('display.float_format','{:,.2f}'.format)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"

today = date.today()
week_str = today.strftime('%Y-%U')
today, week_str

(datetime.date(2023, 2, 4), '2023-05')

In [2]:
sql = '''
SELECT name, market
FROM stocks
'''
stocks_lite = pd.read_sql(sql, conlite)
stocks_lite

       name  market
0       MCS     SET
1     PTTGC   SET50
2     JASIF     SET
3       DIF     SET
4     WHAIR     SET
5       STA  SET100
6       SCC   SET50
7       NER     SET
8     SYNEX     SET
9       BCH  SET100
10      KCE  SET100
11      TMT     SET
12      RCL  SET100
13    WHART     SET
14      ASP     SET
15     SCCC     SET
16     SENA     SET
17      ORI  SET100
18      DCC     SET
19      ASK     SET
20       BH   SET50
21      IVL   SET50
22    BANPU   SET50
23      TTB   SET50
24    PTTEP   SET50
25      CKP  SET100
26   GVREIT     SET
27  CPNREIT     SET
28    JMART   SET50
29      JMT   SET50
30    SAPPE     SET
31    SPALI  SET100
32      SVI     SET
33    TFFIF     SET
34      AIT     SET
35      BEM   SET50
36      BPP     SET
37    CPALL   SET50
38      CPN   SET50
39       EA   SET50
40    HMPRO   SET50
41     ICHI     SET
42      III     SET
43       LH   SET50
44      PSH     SET
45       QH  SET100
46       SC     SET
47      TFG     SET
48     COM7   SET50
49      CPF   SET50
50     BDMS   SET50
51       CK  SET100
52     MEGA  SET100
53     SIRI     SET
54       AH     SET
55   SINGER  SET100
56       AP  SET100
57      BCP  SET100
58      PTT   SET50
59      TOP   SET50

In [3]:
sql = '''
SELECT name, market, id
FROM stocks
'''
stocks_pg = pd.read_sql(sql, conpg)
stocks_pg

      name                                         market   id
0      BAY                                        SET      739
1      BBL          SET50 / SETCLMV / SETHD / SETTHSI      740
2      BCH           SET100 / SETCLMV / SETHD / SETWB      741
3      BAM                           SET100 / SETTHSI      737
4      CKP                 SET100 / SETCLMV / SETTHSI      764
..     ...                                            ...  ...
228    BE8                                        mai      951
229    BPP                          SETCLMV / SETTHSI      757
230  CPALL                    SET50 / SETTHSI / SETWB      767
231    CPF  SET50 / SETCLMV / SETHD / SETTHSI / SETWB      768
232    CRC          SET50 / SETCLMV / SETTHSI / SETWB      773

[233 rows x 3 columns]

In [4]:
df_merge = pd.merge(stocks_lite, stocks_pg, on='name', how='inner')
df_merge

       name market_x                                       market_y   id
0       MCS      SET                                       sSET      842
1     PTTGC    SET50                  SET50 / SETCLMV / SETTHSI      866
2     JASIF      SET                                        SET      814
3       DIF      SET                                        SET      777
4     WHAIR      SET                                        SET      802
5       STA   SET100                   SET100 / SETTHSI / SETWB      898
6       SCC    SET50          SET50 / SETCLMV / SETHD / SETTHSI      879
7       NER      SET                             sSET / SETTHSI      847
8     SYNEX      SET                             sSET / SETTHSI      906
9       BCH   SET100           SET100 / SETCLMV / SETHD / SETWB      741
10      KCE   SET100                                     SET100      819
11      TMT      SET                             sSET / SETTHSI      921
12      RCL   SET100                   SET100 / SETCLMV / SETWB      870
13    WHART      SET                                        SET      945
14      ASP      SET                                       sSET      733
15     SCCC      SET                          SETCLMV / SETTHSI      880
16     SENA      SET                                       sSET      882
17      ORI   SET100                   SET100 / SETHD / SETTHSI      851
18      DCC      SET                                        SET      774
19      ASK      SET                                        SET      732
20       BH    SET50                    SET50 / SETCLMV / SETWB      752
21      IVL    SET50                            SET50 / SETTHSI      813
22    BANPU    SET50                  SET50 / SETCLMV / SETTHSI      738
23      TTB    SET50                    SET50 / SETHD / SETTHSI      933
24    PTTEP    SET50          SET50 / SETCLMV / SETHD / SETTHSI      865
25      CKP   SET100                 SET100 / SETCLMV / SETTHSI      764
26   GVREIT      SET                                        SET      798
27  CPNREIT      SET                                        SET      771
28    JMART    SET50                                      SET50      815
29      JMT    SET50                                      SET50      816
30    SAPPE      SET                             sSET / SETTHSI      875
31    SPALI   SET100                   SET100 / SETHD / SETTHSI      892
32      SVI      SET                                        SET      905
33    TFFIF      SET                                        SET      909
34      AIT      SET                                       sSET      724
35      BEM    SET50                    SET50 / SETTHSI / SETWB      748
36      BPP      SET                          SETCLMV / SETTHSI      757
37    CPALL    SET50                    SET50 / SETTHSI / SETWB      767
38      CPN    SET50                            SET50 / SETTHSI      769
39       EA    SET50                            SET50 / SETTHSI      781
40    HMPRO    SET50                    SET50 / SETTHSI / SETWB      801
41     ICHI      SET                   sSET / SETCLMV / SETTHSI      804
42      III      SET                                       sSET      953
43       LH    SET50                              SET50 / SETHD      829
44      PSH      SET                                    SETTHSI      860
45       QH   SET100                             SET100 / SETHD      867
46       SC      SET                             sSET / SETTHSI      878
47      TFG      SET                                        SET      910
48     COM7    SET50                    SET50 / SETTHSI / SETWB      765
49      CPF    SET50  SET50 / SETCLMV / SETHD / SETTHSI / SETWB      768
50     BDMS    SET50          SET50 / SETCLMV / SETTHSI / SETWB      745
51       CK   SET100                           SET100 / SETCLMV      763
52     MEGA   SET100         SET100 / SETCLMV / SETTHSI / SETWB      843
53     SIRI      SET                                    SETTHSI      886
54       AH      SET                             sSET / SETTHSI      721
55   SINGER   SET100                             SET100 / SETWB      885
56       AP   SET100                   SET100 / SETHD / SETTHSI      730
57      BCP   SET100                 SET100 / SETCLMV / SETTHSI      742
58      PTT    SET50          SET50 / SETCLMV / SETHD / SETTHSI      864
59      TOP    SET50                  SET50 / SETCLMV / SETTHSI      924

In [5]:
set50 = df_merge.market_y.str.contains('SET50')
filter_50 = df_merge[set50].copy()
filter_50['market_x'] = 'SET50'
filter_50.sort_values(by=['name'],ascending=[True])

     name market_x                                       market_y   id
22  BANPU    SET50                  SET50 / SETCLMV / SETTHSI      738
50   BDMS    SET50          SET50 / SETCLMV / SETTHSI / SETWB      745
35    BEM    SET50                    SET50 / SETTHSI / SETWB      748
20     BH    SET50                    SET50 / SETCLMV / SETWB      752
48   COM7    SET50                    SET50 / SETTHSI / SETWB      765
37  CPALL    SET50                    SET50 / SETTHSI / SETWB      767
49    CPF    SET50  SET50 / SETCLMV / SETHD / SETTHSI / SETWB      768
38    CPN    SET50                            SET50 / SETTHSI      769
39     EA    SET50                            SET50 / SETTHSI      781
40  HMPRO    SET50                    SET50 / SETTHSI / SETWB      801
21    IVL    SET50                            SET50 / SETTHSI      813
28  JMART    SET50                                      SET50      815
29    JMT    SET50                                      SET50      816
43     LH    SET50                              SET50 / SETHD      829
58    PTT    SET50          SET50 / SETCLMV / SETHD / SETTHSI      864
24  PTTEP    SET50          SET50 / SETCLMV / SETHD / SETTHSI      865
1   PTTGC    SET50                  SET50 / SETCLMV / SETTHSI      866
6     SCC    SET50          SET50 / SETCLMV / SETHD / SETTHSI      879
59    TOP    SET50                  SET50 / SETCLMV / SETTHSI      924
23    TTB    SET50                    SET50 / SETHD / SETTHSI      933

In [6]:
set100 = df_merge.market_y.str.contains('SET100')
filter_100 = df_merge[set100].copy()
filter_100['market_x'] = 'SET100'
filter_100.sort_values(by=['name'],ascending=[True])

      name market_x                                market_y   id
56      AP   SET100            SET100 / SETHD / SETTHSI      730
9      BCH   SET100    SET100 / SETCLMV / SETHD / SETWB      741
57     BCP   SET100          SET100 / SETCLMV / SETTHSI      742
51      CK   SET100                    SET100 / SETCLMV      763
25     CKP   SET100          SET100 / SETCLMV / SETTHSI      764
10     KCE   SET100                              SET100      819
52    MEGA   SET100  SET100 / SETCLMV / SETTHSI / SETWB      843
17     ORI   SET100            SET100 / SETHD / SETTHSI      851
45      QH   SET100                      SET100 / SETHD      867
12     RCL   SET100            SET100 / SETCLMV / SETWB      870
55  SINGER   SET100                      SET100 / SETWB      885
31   SPALI   SET100            SET100 / SETHD / SETTHSI      892
5      STA   SET100            SET100 / SETTHSI / SETWB      898

In [7]:
setmai = df_merge.market_y.str.contains('mai')
filter_mai = df_merge[setmai].copy()
filter_mai['market_x'] = 'mai'
filter_mai.sort_values(by=['name'],ascending=[True])

Empty DataFrame
Columns: [name, market_x, market_y, id]
Index: []

In [8]:
filter_set = df_merge[~(set100 | set50 | setmai)].copy()
filter_set['market_x'] = 'SET'
filter_set.sort_values(by=['name'],ascending=[True])

       name market_x                      market_y   id
54       AH      SET            sSET / SETTHSI      721
34      AIT      SET                      sSET      724
19      ASK      SET                       SET      732
14      ASP      SET                      sSET      733
36      BPP      SET         SETCLMV / SETTHSI      757
27  CPNREIT      SET                       SET      771
18      DCC      SET                       SET      774
3       DIF      SET                       SET      777
26   GVREIT      SET                       SET      798
41     ICHI      SET  sSET / SETCLMV / SETTHSI      804
42      III      SET                      sSET      953
2     JASIF      SET                       SET      814
0       MCS      SET                      sSET      842
7       NER      SET            sSET / SETTHSI      847
44      PSH      SET                   SETTHSI      860
30    SAPPE      SET            sSET / SETTHSI      875
46       SC      SET            sSET / SETTHSI      878
15     SCCC      SET         SETCLMV / SETTHSI      880
16     SENA      SET                      sSET      882
53     SIRI      SET                   SETTHSI      886
32      SVI      SET                       SET      905
8     SYNEX      SET            sSET / SETTHSI      906
33    TFFIF      SET                       SET      909
47      TFG      SET                       SET      910
11      TMT      SET            sSET / SETTHSI      921
4     WHAIR      SET                       SET      802
13    WHART      SET                       SET      945

In [9]:
filter_all = pd.concat([filter_50, filter_100, filter_mai, filter_set], axis=0)
type(filter_all)

pandas.core.frame.DataFrame

In [10]:
filter_all.to_sql('filter_all', engine1, if_exists='replace')

In [11]:
sql = '''
UPDATE stocks
  SET
    market = (SELECT filter_all.market_x FROM filter_all WHERE filter_all.name = stocks.name)
'''
rp = conlite.execute(sql)
rp.rowcount

60