### Restart and Run All

In [1]:
import calendar
import os
import pandas as pd
import panel as pn

from datetime import date, timedelta
from sqlalchemy import create_engine

pn.extension('tabulator')

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 2, 27)

In [2]:
cols = 'trade name qty price active reason market xdate'.split()
colt = 'trade name qty target active reason market xdate'.split()

In [3]:
pd.read_sql_query('SELECT * FROM orders ORDER BY name', conlite)

    id trade    name    qty   price  active   reason  market       xdate
0    1     B     ASK   4500   29.00       0      DTD     SET  2023-02-28
1    9     B     ASW  12000    8.00       0      XXX     SET  2022-12-22
2    2     B   BANPU   6000   10.80       0      DTD   SET50  2023-04-10
3   10     B      BH    500  200.00       0     5pct   SET50  2022-12-22
4   11     B     BJC   2400   37.00       0      XXX     SET  2022-12-22
5   12     B    COM7   3000   30.00       0      XXX   SET50  2022-12-22
6   23     S     DIF  10000   13.40       0      CUT     SET  2023-02-10
7   13     B    GULF   1800   52.00       0      XXX   SET50  2022-12-22
8   26     S     IVL   2400   44.25       0      DTD   SET50  2023-05-03
9    3     B   JMART   1200   27.25       0  RD25pct   SET50  2023-04-11
10   4     B     JMT    200   44.25       0      DTD   SET50  2023-04-11
11   5     B     KCE   1000   44.25       0  RD40pct  SET100  2023-03-21
12  25     S     ORI  15000   12.50       0     CP1S  SET100  2023-05-09
13  14     B     PSH   7500   13.00       0      XXX     SET  2023-03-10
14  15     B      QH  45000    2.30       0      XXX  SET100  2023-04-28
15   6     B     RCL   3000   28.75       0       HD  SET100  2023-03-16
16  16     B     SAT   5000   20.00       0              SET  2023-03-08
17  17     B      SC  20000    4.40       0      XXX     SET  2023-04-29
18   7     B  SINGER   1200   20.00       0  RD20pct  SET100  2023-05-03
19  18     B     SNC   7500   13.50       0      XXX     SET  2023-03-02
20  19     B    TCAP   2400   42.00       0           SET100  2023-04-19
21  24     S     TMT  12000    8.70       0     C9.0     SET  2023-04-18
22  20     B     TTB  90000    1.35       0     52WL   SET50  2022-12-22
23  21     B     WHA  24000    3.90       0      XXX  SET100  2022-12-22
24   8     B   WHART  10000    0.00       0    C10.5     SET  2023-03-08
25  22     B    WICE      0    0.00       0      XXX     SET  2022-12-22

In [4]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Weekly'

In [5]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [6]:
!ruby ruby\\order-log.rb

trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
B,ASK,266,DTD,SET,4500,29.0,0.0,0.0,0.00%,0,2023-02-28
B,ASW,310,XXX,SET,12000,8.0,0.0,0.0,0.00%,0,2022-12-22
B,BANPU,208,DTD,SET50,6000,10.8,0.0,0.0,0.00%,0,2023-04-10
B,BH,600,5pct,SET50,500,200.0,0.0,0.0,0.00%,0,2022-12-22
B,BJC,298,XXX,SET,2400,37.0,0.0,0.0,0.00%,0,2022-12-22
B,COM7,270,XXX,SET50,3000,30.0,0.0,0.0,0.00%,0,2022-12-22
B,GULF,358,XXX,SET50,1800,52.0,0.0,0.0,0.00%,0,2022-12-22
B,JMART,259,RD25pct,SET50,1200,27.25,0.0,0.0,0.00%,0,2023-04-11
B,JMT,327,DTD,SET50,200,44.25,0.0,0.0,0.00%,0,2023-04-11
B,KCE,327,RD40pct,SET100,1000,44.25,0.0,0.0,0.00%,0,2023-03-21
B,PSH,230,XXX,SET,7500,13.0,0.0,0.0,0.00%,0,2023-03-10
B,QH,215,XXX,SET100,45000,2.3,0.0,0.0,0.00%,0,2023-04-28
B,RCL,265,HD,SET100,3000,28.75,0.0,0.0,0.00%,0,2023-03-16
B,SAT,300,,SET,5000,20.0,0.0,0.0,0.00%,0,2023-03-08
B,SC,320,XXX,SET,20000,4.4,0.0,0.0,0.00%,0,2023-04-29
B,SINGER,300,RD20pct,SET100,1200,20.0,0.0,0.0,0.00%,0,2023-05-03
B,SNC,235,XXX,SET,7500,13.5,0.0,0.0,0.00%,0,2023-03-02
B,TCAP,318,,SET100,2400,42.0,0.0,0.0,0.00%,0,2023-04-19
B,TTB,135,52WL,SET50,90000,1.35,0.0,0.0,0.00%,0,2022-12-22
B,WHA,295,XXX,SET100,24000,3.9,0.0,0.0,0.00%,0,2022-12-22
B,WHART,0,C10.5,SET,10000,0.0,0.0,0.0,0.00%,0,2023-03-08
B,WICE,0,XXX,SET,0,0.0,0.0,0.0,0.00%,0,2022-12-22
S,DIF,234,CUT,SET,10000,13.4,0.0,0.0,0.00%,0,2023-02-10
S,IVL,327,DTD,SET50,2400,44.25,0.0,0.0,0.00%,0,2023-05-03
S,ORI,225,CP1S,SET100,15000,12.5,0.0,0.0,0.00%,0,2023-05-09
S,TMT,324,C9.0,SET,12000,8.7,0.0,0.0,0.00%,0,2023-04-18

In [7]:
os.chdir("C:\\users\\user\\onedrive\\a7\\weekly")
%pwd

'C:\\users\\user\\onedrive\\a7\\weekly'

In [8]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
#col_names   = ['trade','name','spreads','reason','market','qty','target_price','set_price','chg_amt','chg_pct','active']
df_log = pd.read_csv(input_file, sep=',',  index_col=None)
df_log

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
0,B,ASK,266,DTD,SET,4500,29.00,0.0,0.0,0.00%,0,2023-02-28
1,B,ASW,310,XXX,SET,12000,8.00,0.0,0.0,0.00%,0,2022-12-22
2,B,BANPU,208,DTD,SET50,6000,10.80,0.0,0.0,0.00%,0,2023-04-10
3,B,BH,600,5pct,SET50,500,200.00,0.0,0.0,0.00%,0,2022-12-22
4,B,BJC,298,XXX,SET,2400,37.00,0.0,0.0,0.00%,0,2022-12-22
5,B,COM7,270,XXX,SET50,3000,30.00,0.0,0.0,0.00%,0,2022-12-22
6,B,GULF,358,XXX,SET50,1800,52.00,0.0,0.0,0.00%,0,2022-12-22
7,B,JMART,259,RD25pct,SET50,1200,27.25,0.0,0.0,0.00%,0,2023-04-11
8,B,JMT,327,DTD,SET50,200,44.25,0.0,0.0,0.00%,0,2023-04-11
9,B,KCE,327,RD40pct,SET100,1000,44.25,0.0,0.0,0.00%,0,2023-03-21
10,B,PSH,230,XXX,SET,7500,13.00,0.0,0.0,0.00%,0,2023-03-10
11,B,QH,215,XXX,SET100,45000,2.30,0.0,0.0,0.00%,0,2023-04-28
12,B,RCL,265,HD,SET100,3000,28.75,0.0,0.0,0.00%,0,2023-03-16
13,B,SAT,300,NaN,SET,5000,20.00,0.0,0.0,0.00%,0,2023-03-08
14,B,SC,320,XXX,SET,20000,4.40,0.0,0.0,0.00%,0,2023-04-29
15,B,SINGER,300,RD20pct,SET100,1200,20.00,0.0,0.0,0.00%,0,2023-05-03
16,B,SNC,235,XXX,SET,7500,13.50,0.0,0.0,0.00%,0,2023-03-02
17,B,TCAP,318,NaN,SET100,2400,42.00,0.0,0.0,0.00%,0,2023-04-19
18,B,TTB,135,52WL,SET50,90000,1.35,0.0,0.0,0.00%,0,2022-12-22
19,B,WHA,295,XXX,SET100,24000,3.90,0.0,0.0,0.00%,0,2022-12-22
20,B,WHART,0,C10.5,SET,10000,0.00,0.0,0.0,0.00%,0,2023-03-08
21,B,WICE,0,XXX,SET,0,0.00,0.0,0.0,0.00%,0,2022-12-22
22,S,DIF,234,CUT,SET,10000,13.40,0.0,0.0,0.00%,0,2023-02-10
23,S,IVL,327,DTD,SET50,2400,44.25,0.0,0.0,0.00%,0,2023-05-03
24,S,ORI,225,CP1S,SET100,15000,12.50,0.0,0.0,0.00%,0,2023-05-09
25,S,TMT,324,C9.0,SET,12000,8.70,0.0,0.0,0.00%,0,2023-04-18

In [9]:
def calc(vals):
    spreads = vals
    if abs(spreads) < 10:
        return 1
    else:
        return 0

In [10]:
df_log['active'] = df_log['spd'].apply(calc)

In [11]:
df_log.groupby('active')['trade'].count()

active
0    24
1     2
Name: trade, dtype: int64

In [12]:
sql = '''
DELETE FROM orders'''
rp = conlite.execute(sql)
rp.rowcount

27

In [13]:
final = df_log[colt]
final

   trade    name    qty  target  active   reason  market       xdate
0      B     ASK   4500   29.00       0      DTD     SET  2023-02-28
1      B     ASW  12000    8.00       0      XXX     SET  2022-12-22
2      B   BANPU   6000   10.80       0      DTD   SET50  2023-04-10
3      B      BH    500  200.00       0     5pct   SET50  2022-12-22
4      B     BJC   2400   37.00       0      XXX     SET  2022-12-22
5      B    COM7   3000   30.00       0      XXX   SET50  2022-12-22
6      B    GULF   1800   52.00       0      XXX   SET50  2022-12-22
7      B   JMART   1200   27.25       0  RD25pct   SET50  2023-04-11
8      B     JMT    200   44.25       0      DTD   SET50  2023-04-11
9      B     KCE   1000   44.25       0  RD40pct  SET100  2023-03-21
10     B     PSH   7500   13.00       0      XXX     SET  2023-03-10
11     B      QH  45000    2.30       0      XXX  SET100  2023-04-28
12     B     RCL   3000   28.75       0       HD  SET100  2023-03-16
13     B     SAT   5000   20.00       0      NaN     SET  2023-03-08
14     B      SC  20000    4.40       0      XXX     SET  2023-04-29
15     B  SINGER   1200   20.00       0  RD20pct  SET100  2023-05-03
16     B     SNC   7500   13.50       0      XXX     SET  2023-03-02
17     B    TCAP   2400   42.00       0      NaN  SET100  2023-04-19
18     B     TTB  90000    1.35       0     52WL   SET50  2022-12-22
19     B     WHA  24000    3.90       0      XXX  SET100  2022-12-22
20     B   WHART  10000    0.00       1    C10.5     SET  2023-03-08
21     B    WICE      0    0.00       1      XXX     SET  2022-12-22
22     S     DIF  10000   13.40       0      CUT     SET  2023-02-10
23     S     IVL   2400   44.25       0      DTD   SET50  2023-05-03
24     S     ORI  15000   12.50       0     CP1S  SET100  2023-05-09
25     S     TMT  12000    8.70       0     C9.0     SET  2023-04-18

In [14]:
rcds = final.values.tolist()
rcds

[['B', 'ASK', 4500, 29.0, 0, 'DTD', 'SET', '2023-02-28'],
 ['B', 'ASW', 12000, 8.0, 0, 'XXX', 'SET', '2022-12-22'],
 ['B', 'BANPU', 6000, 10.8, 0, 'DTD', 'SET50', '2023-04-10'],
 ['B', 'BH', 500, 200.0, 0, '5pct', 'SET50', '2022-12-22'],
 ['B', 'BJC', 2400, 37.0, 0, 'XXX', 'SET', '2022-12-22'],
 ['B', 'COM7', 3000, 30.0, 0, 'XXX', 'SET50', '2022-12-22'],
 ['B', 'GULF', 1800, 52.0, 0, 'XXX', 'SET50', '2022-12-22'],
 ['B', 'JMART', 1200, 27.25, 0, 'RD25pct', 'SET50', '2023-04-11'],
 ['B', 'JMT', 200, 44.25, 0, 'DTD', 'SET50', '2023-04-11'],
 ['B', 'KCE', 1000, 44.25, 0, 'RD40pct', 'SET100', '2023-03-21'],
 ['B', 'PSH', 7500, 13.0, 0, 'XXX', 'SET', '2023-03-10'],
 ['B', 'QH', 45000, 2.3, 0, 'XXX', 'SET100', '2023-04-28'],
 ['B', 'RCL', 3000, 28.75, 0, 'HD', 'SET100', '2023-03-16'],
 ['B', 'SAT', 5000, 20.0, 0, nan, 'SET', '2023-03-08'],
 ['B', 'SC', 20000, 4.4, 0, 'XXX', 'SET', '2023-04-29'],
 ['B', 'SINGER', 1200, 20.0, 0, 'RD20pct', 'SET100', '2023-05-03'],
 ['B', 'SNC', 7500, 13.5, 0, 'XXX', 'SET', '2023-03-02'],
 ['B', 'TCAP', 2400, 42.0, 0, nan, 'SET100', '2023-04-19'],
 ['B', 'TTB', 90000, 1.35, 0, '52WL', 'SET50', '2022-12-22'],
 ['B', 'WHA', 24000, 3.9, 0, 'XXX', 'SET100', '2022-12-22'],
 ['B', 'WHART', 10000, 0.0, 1, 'C10.5', 'SET', '2023-03-08'],
 ['B', 'WICE', 0, 0.0, 1, 'XXX', 'SET', '2022-12-22'],
 ['S', 'DIF', 10000, 13.4, 0, 'CUT', 'SET', '2023-02-10'],
 ['S', 'IVL', 2400, 44.25, 0, 'DTD', 'SET50', '2023-05-03'],
 ['S', 'ORI', 15000, 12.5, 0, 'CP1S', 'SET100', '2023-05-09'],
 ['S', 'TMT', 12000, 8.7, 0, 'C9.0', 'SET', '2023-04-18']]

In [15]:
for rcd in rcds:
    print(rcd)

['B', 'ASK', 4500, 29.0, 0, 'DTD', 'SET', '2023-02-28']
['B', 'ASW', 12000, 8.0, 0, 'XXX', 'SET', '2022-12-22']
['B', 'BANPU', 6000, 10.8, 0, 'DTD', 'SET50', '2023-04-10']
['B', 'BH', 500, 200.0, 0, '5pct', 'SET50', '2022-12-22']
['B', 'BJC', 2400, 37.0, 0, 'XXX', 'SET', '2022-12-22']
['B', 'COM7', 3000, 30.0, 0, 'XXX', 'SET50', '2022-12-22']
['B', 'GULF', 1800, 52.0, 0, 'XXX', 'SET50', '2022-12-22']
['B', 'JMART', 1200, 27.25, 0, 'RD25pct', 'SET50', '2023-04-11']
['B', 'JMT', 200, 44.25, 0, 'DTD', 'SET50', '2023-04-11']
['B', 'KCE', 1000, 44.25, 0, 'RD40pct', 'SET100', '2023-03-21']
['B', 'PSH', 7500, 13.0, 0, 'XXX', 'SET', '2023-03-10']
['B', 'QH', 45000, 2.3, 0, 'XXX', 'SET100', '2023-04-28']
['B', 'RCL', 3000, 28.75, 0, 'HD', 'SET100', '2023-03-16']
['B', 'SAT', 5000, 20.0, 0, nan, 'SET', '2023-03-08']
['B', 'SC', 20000, 4.4, 0, 'XXX', 'SET', '2023-04-29']
['B', 'SINGER', 1200, 20.0, 0, 'RD20pct', 'SET100', '2023-05-03']
['B', 'SNC', 7500, 13.5, 0, 'XXX', 'SET', '2023-03-02']
['B', 'TCAP', 2400, 42.0, 0, nan, 'SET100', '2023-04-19']
['B', 'TTB', 90000, 1.35, 0, '52WL', 'SET50', '2022-12-22']
['B', 'WHA', 24000, 3.9, 0, 'XXX', 'SET100', '2022-12-22']
['B', 'WHART', 10000, 0.0, 1, 'C10.5', 'SET', '2023-03-08']
['B', 'WICE', 0, 0.0, 1, 'XXX', 'SET', '2022-12-22']
['S', 'DIF', 10000, 13.4, 0, 'CUT', 'SET', '2023-02-10']
['S', 'IVL', 2400, 44.25, 0, 'DTD', 'SET50', '2023-05-03']
['S', 'ORI', 15000, 12.5, 0, 'CP1S', 'SET100', '2023-05-09']
['S', 'TMT', 12000, 8.7, 0, 'C9.0', 'SET', '2023-04-18']

In [16]:
sql = """
INSERT INTO orders (trade, name, qty, price, active, reason, market, xdate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
"""
print(sql)

INSERT INTO orders (trade, name, qty, price, active, reason, market, xdate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)

In [17]:
for rcd in rcds:
    conlite.execute(sql, rcd)

In [18]:
sql = '''
SELECT *
FROM orders
ORDER BY trade, name'''
df_orders = pd.read_sql(sql, conlite)
df_tab = pn.widgets.Tabulator(df_orders, layout='fit_data', width=800)
df_tab

Tabulator(layout='fit_data', value=    id trade  ..., width=800)

In [19]:
file_name = 'orders.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(box_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(one_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(osd_file, header=True, index=False)

In [20]:
df_orders.shape

(26, 9)