### After call Ord-Log.bat which calculates spreads between target price and SET price.

### Restart and Run All

In [1]:
import calendar
import pandas as pd
import panel as pn

from datetime import date, timedelta
from sqlalchemy import create_engine

pn.extension('tabulator')

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
today

datetime.date(2023, 1, 7)

In [2]:
cols = 'trade name qty price active reason market xdate'.split()
colt = 'trade name qty target active reason market xdate'.split()

In [3]:
pd.read_sql_query('SELECT * FROM orders ORDER BY name', conlite)

    id trade     name    qty  price  active   reason  market       xdate
0   17     S      ASP  10000    3.1       0     5pct     SET  2023-03-10
1   19     S    BANPU  12000   13.0       0      DTD   SET50  2023-04-08
2   15     S      BCH   3000   22.5       0     5pct  SET100  2023-05-10
3    7     B      CKP  20000    4.5       0       3L  SET100  2022-12-22
4    8     B      CPF   4000   24.0       0      XXX   SET50  2022-12-22
5    1     B  CPNREIT  10000   19.5       0  RD05pct     SET  2023-03-01
6    9     B     GFPT   3600   12.5       0      DTD     SET  2023-03-07
7    2     B   GVREIT  10000    8.9       0    C8.90     SET  2023-02-23
8    3     B      IVL   2400   37.0       0       5%   SET50  2023-05-06
9   20     S    JMART   3000   42.0       0       1L   SET50  2023-04-19
10  10     B      LPF  10000   12.5       0      DOS     SET  2023-01-28
11  18     S    MAKRO   2500   43.0       0     5pct     SET  2023-03-03
12  11     B      PTT   3600   31.0       0      XXX   SET50  2023-03-03
13  13     S      SCC    300  355.0       0     5pct   SET50  2023-04-07
14   4     B   SINGER   1200   25.5       0      DTD  SET100  2023-04-29
15  14     S    SYNEX   3000   17.5       0     5pct     SET  2023-03-10
16   5     B    TFFIF  10000    7.4       0      DOS     SET  2023-03-03
17  12     B      TFG  20000    5.0       0      XXX     SET  2022-12-22
18  16     S      TMT  12000    8.0       0     C9.0     SET  2023-04-18
19   6     B    WHAIR  10000    7.2       0  RD15pct     SET  2023-03-04

In [4]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
#col_names   = ['trade','name','spreads','reason','market','qty','target_price','set_price','chg_amt','chg_pct','active']
df_log = pd.read_csv(input_file, sep=',',  index_col=None)
df_log

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
0,B,CKP,-5,3L,SET100,20000,4.5,4.60,0.00,0.00%,0,2022-12-22
1,B,CPF,-2,XXX,SET50,4000,24.0,24.20,0.00,0.00%,0,2022-12-22
2,B,CPNREIT,0,RD05pct,SET,10000,19.5,19.50,0.00,0.00%,0,2023-03-01
3,B,GFPT,-4,DTD,SET,3600,12.5,12.90,0.20,+1.57%,0,2023-03-07
4,B,GVREIT,-2,C8.90,SET,10000,8.9,9.00,-0.05,-0.55%,0,2023-02-23
5,B,IVL,-3,5%,SET50,2400,37.0,37.75,-2.00,-5.03%,0,2023-05-06
6,B,LPF,-2,DOS,SET,10000,12.5,12.70,-0.10,-0.78%,0,2023-01-28
7,B,PTT,-6,XXX,SET50,3600,31.0,32.50,0.25,+0.78%,0,2023-03-03
8,B,SINGER,-6,DTD,SET100,1200,25.5,27.00,0.00,0.00%,0,2023-04-29
9,B,TFFIF,-6,DOS,SET,10000,7.4,7.70,0.00,0.00%,0,2023-03-03
10,B,TFG,-1,XXX,SET,20000,5.0,5.05,-0.10,-1.94%,0,2022-12-22
11,B,WHAIR,-6,RD15pct,SET,10000,7.2,7.50,-0.05,-0.66%,0,2023-03-04
12,S,ASP,6,5pct,SET,10000,3.1,2.98,0.02,+0.68%,0,2023-03-10
13,S,BANPU,7,DTD,SET50,12000,13.0,12.30,-0.50,-3.91%,0,2023-04-08
14,S,BCH,6,5pct,SET100,3000,22.5,21.90,0.60,+2.82%,0,2023-05-10
15,S,JMART,7,1L,SET50,3000,42.0,40.25,0.25,+0.62%,0,2023-04-19
16,S,MAKRO,2,5pct,SET,2500,43.0,42.50,0.25,+0.59%,0,2023-03-03
17,S,SCC,5,5pct,SET50,300,355.0,350.00,1.00,+0.29%,0,2023-04-07
18,S,SYNEX,5,5pct,SET,3000,17.5,17.00,0.50,+3.03%,0,2023-03-10
19,S,TMT,6,C9.0,SET,12000,8.0,7.70,0.05,+0.65%,0,2023-04-18

In [5]:
def calc(vals):
    spreads = vals
    if abs(spreads) < 10:
        return 1
    else:
        return 0

In [6]:
df_log['active'] = df_log['spd'].apply(calc)

In [7]:
df_log.groupby('active')['trade'].count()

active
1    20
Name: trade, dtype: int64

In [8]:
sql = '''
DELETE FROM orders'''
rp = conlite.execute(sql)
rp.rowcount

20

In [9]:
final = df_log[colt]
final

   trade     name    qty  target  active   reason  market       xdate
0      B      CKP  20000     4.5       1       3L  SET100  2022-12-22
1      B      CPF   4000    24.0       1      XXX   SET50  2022-12-22
2      B  CPNREIT  10000    19.5       1  RD05pct     SET  2023-03-01
3      B     GFPT   3600    12.5       1      DTD     SET  2023-03-07
4      B   GVREIT  10000     8.9       1    C8.90     SET  2023-02-23
5      B      IVL   2400    37.0       1       5%   SET50  2023-05-06
6      B      LPF  10000    12.5       1      DOS     SET  2023-01-28
7      B      PTT   3600    31.0       1      XXX   SET50  2023-03-03
8      B   SINGER   1200    25.5       1      DTD  SET100  2023-04-29
9      B    TFFIF  10000     7.4       1      DOS     SET  2023-03-03
10     B      TFG  20000     5.0       1      XXX     SET  2022-12-22
11     B    WHAIR  10000     7.2       1  RD15pct     SET  2023-03-04
12     S      ASP  10000     3.1       1     5pct     SET  2023-03-10
13     S    BANPU  12000    13.0       1      DTD   SET50  2023-04-08
14     S      BCH   3000    22.5       1     5pct  SET100  2023-05-10
15     S    JMART   3000    42.0       1       1L   SET50  2023-04-19
16     S    MAKRO   2500    43.0       1     5pct     SET  2023-03-03
17     S      SCC    300   355.0       1     5pct   SET50  2023-04-07
18     S    SYNEX   3000    17.5       1     5pct     SET  2023-03-10
19     S      TMT  12000     8.0       1     C9.0     SET  2023-04-18

In [10]:
rcds = final.values.tolist()
rcds

[['B', 'CKP', 20000, 4.5, 1, '3L', 'SET100', '2022-12-22'],
 ['B', 'CPF', 4000, 24.0, 1, 'XXX', 'SET50', '2022-12-22'],
 ['B', 'CPNREIT', 10000, 19.5, 1, 'RD05pct', 'SET', '2023-03-01'],
 ['B', 'GFPT', 3600, 12.5, 1, 'DTD', 'SET', '2023-03-07'],
 ['B', 'GVREIT', 10000, 8.9, 1, 'C8.90', 'SET', '2023-02-23'],
 ['B', 'IVL', 2400, 37.0, 1, '5%', 'SET50', '2023-05-06'],
 ['B', 'LPF', 10000, 12.5, 1, 'DOS', 'SET', '2023-01-28'],
 ['B', 'PTT', 3600, 31.0, 1, 'XXX', 'SET50', '2023-03-03'],
 ['B', 'SINGER', 1200, 25.5, 1, 'DTD', 'SET100', '2023-04-29'],
 ['B', 'TFFIF', 10000, 7.4, 1, 'DOS', 'SET', '2023-03-03'],
 ['B', 'TFG', 20000, 5.0, 1, 'XXX', 'SET', '2022-12-22'],
 ['B', 'WHAIR', 10000, 7.2, 1, 'RD15pct', 'SET', '2023-03-04'],
 ['S', 'ASP', 10000, 3.1, 1, '5pct', 'SET', '2023-03-10'],
 ['S', 'BANPU', 12000, 13.0, 1, 'DTD', 'SET50', '2023-04-08'],
 ['S', 'BCH', 3000, 22.5, 1, '5pct', 'SET100', '2023-05-10'],
 ['S', 'JMART', 3000, 42.0, 1, '1L', 'SET50', '2023-04-19'],
 ['S', 'MAKRO', 2500, 43.0, 1, '5pct', 'SET', '2023-03-03'],
 ['S', 'SCC', 300, 355.0, 1, '5pct', 'SET50', '2023-04-07'],
 ['S', 'SYNEX', 3000, 17.5, 1, '5pct', 'SET', '2023-03-10'],
 ['S', 'TMT', 12000, 8.0, 1, 'C9.0', 'SET', '2023-04-18']]

In [11]:
for rcd in rcds:
    print(rcd)

['B', 'CKP', 20000, 4.5, 1, '3L', 'SET100', '2022-12-22']
['B', 'CPF', 4000, 24.0, 1, 'XXX', 'SET50', '2022-12-22']
['B', 'CPNREIT', 10000, 19.5, 1, 'RD05pct', 'SET', '2023-03-01']
['B', 'GFPT', 3600, 12.5, 1, 'DTD', 'SET', '2023-03-07']
['B', 'GVREIT', 10000, 8.9, 1, 'C8.90', 'SET', '2023-02-23']
['B', 'IVL', 2400, 37.0, 1, '5%', 'SET50', '2023-05-06']
['B', 'LPF', 10000, 12.5, 1, 'DOS', 'SET', '2023-01-28']
['B', 'PTT', 3600, 31.0, 1, 'XXX', 'SET50', '2023-03-03']
['B', 'SINGER', 1200, 25.5, 1, 'DTD', 'SET100', '2023-04-29']
['B', 'TFFIF', 10000, 7.4, 1, 'DOS', 'SET', '2023-03-03']
['B', 'TFG', 20000, 5.0, 1, 'XXX', 'SET', '2022-12-22']
['B', 'WHAIR', 10000, 7.2, 1, 'RD15pct', 'SET', '2023-03-04']
['S', 'ASP', 10000, 3.1, 1, '5pct', 'SET', '2023-03-10']
['S', 'BANPU', 12000, 13.0, 1, 'DTD', 'SET50', '2023-04-08']
['S', 'BCH', 3000, 22.5, 1, '5pct', 'SET100', '2023-05-10']
['S', 'JMART', 3000, 42.0, 1, '1L', 'SET50', '2023-04-19']
['S', 'MAKRO', 2500, 43.0, 1, '5pct', 'SET', '2023-03-03']
['S', 'SCC', 300, 355.0, 1, '5pct', 'SET50', '2023-04-07']
['S', 'SYNEX', 3000, 17.5, 1, '5pct', 'SET', '2023-03-10']
['S', 'TMT', 12000, 8.0, 1, 'C9.0', 'SET', '2023-04-18']

In [12]:
sql = """
INSERT INTO orders (trade, name, qty, price, active, reason, market, xdate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
"""
print(sql)

INSERT INTO orders (trade, name, qty, price, active, reason, market, xdate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)

In [13]:
for rcd in rcds:
    conlite.execute(sql, rcd)

In [14]:
sql = '''
SELECT *
FROM orders
ORDER BY trade, name'''
df_orders = pd.read_sql(sql, conlite)
df_tab = pn.widgets.Tabulator(df_orders, layout='fit_data', width=800)
df_tab

Tabulator(layout='fit_data', value=    id trade  ..., width=800)

In [15]:
file_name = 'orders.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(box_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(one_file, header=True, index=False)

In [16]:
df_orders.shape

(20, 9)