<a href="https://colab.research.google.com/github/santimcs/A8/blob/main/PL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install google.colab

Collecting google.colab
  Downloading google-colab-1.0.0.tar.gz (72 kB)
     ---------------------------------------- 72.9/72.9 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting google-auth~=1.4.0
  Downloading google_auth-1.4.2-py2.py3-none-any.whl (64 kB)
     ---------------------------------------- 64.2/64.2 kB ? eta 0:00:00
Collecting ipykernel~=4.6.0
  Downloading ipykernel-4.6.1-py3-none-any.whl (104 kB)
     -------------------------------------- 104.5/104.5 kB 3.0 MB/s eta 0:00:00
Collecting ipython~=5.5.0
  Downloading ipython-5.5.0-py3-none-any.whl (758 kB)

WARNING: Ignoring invalid distribution -p (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [841 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pandas
  copying pandas\conftest.py -> build\lib.win-amd64-3.8\pandas
  copying pandas\testing.py -> build\lib.win-amd64-3.8\pandas
  copying pandas\_version.py -> build\lib.win-amd64-3.8\pandas
  copying pandas\__init__.py -> build\lib.win-amd64-3.8\pandas
  creating build\lib.win-amd64-3.8\pandas\api
  copying pandas\api\__init__.py -> build\lib.win-amd64-3.8\pandas\api
  creating build\lib.win-amd64-3.8\pandas\arrays
  copying pandas\arrays\__init__.py -> build\lib.win-amd64-3.8\pandas\arrays
  creating build\lib.win-amd64-3.8\pandas\compat
  copying pandas\compat\chainmap.py -> build\lib.win-amd64-3.8\pandas\compat
  copying pandas\compat\chainmap_impl.py -> build\lib.win-amd64-3.8\pandas\compat
  copying pandas\compat\pickle_compat.py -> build\lib.win-amd64-3.8\pandas\compat
  copying pandas\compat\__init__.py -> build\lib.win-amd64-3.8\pandas\compat
  creating build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\accessor.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\algorithms.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\api.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\apply.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\base.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\categorical.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\common.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\config.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\config_init.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\frame.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\generic.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\index.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\indexing.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\missing.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\nanops.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\ops.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\panel.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\resample.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\series.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\sorting.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\strings.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\window.py -> build\lib.win-amd64-3.8\pandas\core
  copying pandas\core\__init__.py -> build\lib.win-amd64-3.8\pandas\core
  creating build\lib.win-amd64-3.8\pandas\errors
  copying pandas\errors\__init__.py -> build\lib.win-amd64-3.8\pandas\errors
  creating build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\api.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\clipboards.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\common.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\date_converters.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\excel.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\feather_format.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\gbq.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\gcs.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\html.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\packers.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\parquet.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\parsers.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\pickle.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\pytables.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\s3.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\sql.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\stata.py -> build\lib.win-amd64-3.8\pandas\io
  copying pandas\io\__init__.py -> build\lib.win-amd64-3.8\pandas\io
  creating build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_compat.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_converter.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_core.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_misc.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_style.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_timeseries.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\_tools.py -> build\lib.win-amd64-3.8\pandas\plotting
  copying pandas\plotting\__init__.py -> build\lib.win-amd64-3.8\pandas\plotting
  creating build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_algos.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_base.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_common.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_compat.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_config.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_downstream.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_errors.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_expressions.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_join.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_lib.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_multilevel.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_nanops.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_panel.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_register_accessor.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_sorting.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_strings.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_take.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\test_window.py -> build\lib.win-amd64-3.8\pandas\tests
  copying pandas\tests\__init__.py -> build\lib.win-amd64-3.8\pandas\tests
  creating build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\api.py -> build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\converter.py -> build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\frequencies.py -> build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\holiday.py -> build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\offsets.py -> build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\plotting.py -> build\lib.win-amd64-3.8\pandas\tseries
  copying pandas\tseries\__init__.py -> build\lib.win-amd64-3.8\pandas\tseries
  creating build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\testing.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_decorators.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_depr_module.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_doctools.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_exceptions.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_print_versions.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_tester.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_test_decorators.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\_validators.py -> build\lib.win-amd64-3.8\pandas\util
  copying pandas\util\__init__.py -> build\lib.win-amd64-3.8\pandas\util
  creating build\lib.win-amd64-3.8\pandas\_libs
  copying pandas\_libs\__init__.py -> build\lib.win-amd64-3.8\pandas\_libs
  creating build\lib.win-amd64-3.8\pandas\api\extensions
  copying pandas\api\extensions\__init__.py -> build\lib.win-amd64-3.8\pandas\api\extensions
  creating build\lib.win-amd64-3.8\pandas\api\types
  copying pandas\api\types\__init__.py -> build\lib.win-amd64-3.8\pandas\api\types
  creating build\lib.win-amd64-3.8\pandas\compat\numpy
  copying pandas\compat\numpy\function.py -> build\lib.win-amd64-3.8\pandas\compat\numpy
  copying pandas\compat\numpy\__init__.py -> build\lib.win-amd64-3.8\pandas\compat\numpy
  creating build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\array_.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\base.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\categorical.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\datetimelike.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\datetimes.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\integer.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\interval.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\numpy_.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\period.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\sparse.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\timedeltas.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\_ranges.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  copying pandas\core\arrays\__init__.py -> build\lib.win-amd64-3.8\pandas\core\arrays
  creating build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\align.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\api.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\check.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\common.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\engines.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\eval.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\expr.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\expressions.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\ops.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\pytables.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\scope.py -> build\lib.win-amd64-3.8\pandas\core\computation
  copying pandas\core\computation\__init__.py -> build\lib.win-amd64-3.8\pandas\core\computation
  creating build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\api.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\base.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\cast.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\common.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\concat.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\dtypes.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\generic.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\inference.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\missing.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  copying pandas\core\dtypes\__init__.py -> build\lib.win-amd64-3.8\pandas\core\dtypes
  creating build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\base.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\categorical.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\generic.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\groupby.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\grouper.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\ops.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  copying pandas\core\groupby\__init__.py -> build\lib.win-amd64-3.8\pandas\core\groupby
  creating build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\accessors.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\api.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\base.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\category.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\datetimelike.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\datetimes.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\frozen.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\interval.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\multi.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\numeric.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\period.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\range.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\timedeltas.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  copying pandas\core\indexes\__init__.py -> build\lib.win-amd64-3.8\pandas\core\indexes
  creating build\lib.win-amd64-3.8\pandas\core\internals
  copying pandas\core\internals\arrays.py -> build\lib.win-amd64-3.8\pandas\core\internals
  copying pandas\core\internals\blocks.py -> build\lib.win-amd64-3.8\pandas\core\internals
  copying pandas\core\internals\concat.py -> build\lib.win-amd64-3.8\pandas\core\internals
  copying pandas\core\internals\construction.py -> build\lib.win-amd64-3.8\pandas\core\internals
  copying pandas\core\internals\managers.py -> build\lib.win-amd64-3.8\pandas\core\internals
  copying pandas\core\internals\__init__.py -> build\lib.win-amd64-3.8\pandas\core\internals
  creating build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\api.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\concat.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\melt.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\merge.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\pivot.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\reshape.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\tile.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\util.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  copying pandas\core\reshape\__init__.py -> build\lib.win-amd64-3.8\pandas\core\reshape
  creating build\lib.win-amd64-3.8\pandas\core\sparse
  copying pandas\core\sparse\api.py -> build\lib.win-amd64-3.8\pandas\core\sparse
  copying pandas\core\sparse\frame.py -> build\lib.win-amd64-3.8\pandas\core\sparse
  copying pandas\core\sparse\scipy_sparse.py -> build\lib.win-amd64-3.8\pandas\core\sparse
  copying pandas\core\sparse\series.py -> build\lib.win-amd64-3.8\pandas\core\sparse
  copying pandas\core\sparse\__init__.py -> build\lib.win-amd64-3.8\pandas\core\sparse
  creating build\lib.win-amd64-3.8\pandas\core\tools
  copying pandas\core\tools\datetimes.py -> build\lib.win-amd64-3.8\pandas\core\tools
  copying pandas\core\tools\numeric.py -> build\lib.win-amd64-3.8\pandas\core\tools
  copying pandas\core\tools\timedeltas.py -> build\lib.win-amd64-3.8\pandas\core\tools
  copying pandas\core\tools\__init__.py -> build\lib.win-amd64-3.8\pandas\core\tools
  creating build\lib.win-amd64-3.8\pandas\core\util
  copying pandas\core\util\hashing.py -> build\lib.win-amd64-3.8\pandas\core\util
  copying pandas\core\util\__init__.py -> build\lib.win-amd64-3.8\pandas\core\util
  creating build\lib.win-amd64-3.8\pandas\io\clipboard
  copying pandas\io\clipboard\clipboards.py -> build\lib.win-amd64-3.8\pandas\io\clipboard
  copying pandas\io\clipboard\exceptions.py -> build\lib.win-amd64-3.8\pandas\io\clipboard

     -------------------------------------- 758.9/758.9 kB 4.4 MB/s eta 0:00:00
Collecting notebook~=5.2.0
  Downloading notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
     ---------------------------------------- 8.0/8.0 MB 4.5 MB/s eta 0:00:00
Collecting six~=1.12.0
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting pandas~=0.24.0
  Downloading pandas-0.24.2.tar.gz (11.8 MB)
     ---------------------------------------- 11.8/11.8 MB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting portpicker~=1.2.0
  Downloading portpicker-1.2.0.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting requests~=2.21.0
  Downloading requests-2.21.0-py2.py3-none-any.whl (57 kB)
     ---------------------------------------- 58.0/58.0 kB 3.2 MB/s eta 0:00:00
Collecting tornado~=4.5.0
  Downloading tornado-4.5.3.tar.gz (484 kB)
     -------------------------------------- 484.2/484.2 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\programdata\anaconda3\lib\site-packages (from google-auth~=1.4.0->google.colab) (0.2.8)
Requirement already satisfied: cachetools>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth~=1.4.0->google.colab) (4.2.0)
Requirement already satisfied: rsa>=3.1.4 in c:\programdata\anaconda3\lib\site-packages (from google-auth~=1.4.0->google.colab) (4.6)
Requirement already satisfied: jupyter-client in c:\programdata\anaconda3\lib\site-packages (from ipykernel~=4.6.0->google.colab) (7.0.1)
Requirement already satisfied: traitlets>=4.1.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel~=4.6.0->google.colab) (5.1.0)
Requirement already satisfied: setuptools>=18.5 in c:\programdata\anaconda3\lib\site-packages (from ipython~=5.5.0->google.colab) (58.0.4)
Requirement already satisfied: pickleshare in c:\programdata\anaconda3\lib\site-packages (from ipython~=5.5.0->google.colab) (0.7.5)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython~=5.5.0->google.colab) (5.1.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython~=5.5.0->google.colab) (0.4.4)
Requirement already satisfied: simplegeneric>0.8 in c:\programdata\anaconda3\lib\site-packages (from ipython~=5.5.0->google.colab) (0.8.1)

  copying pandas\io\clipboard\windows.py -> build\lib.win-amd64-3.8\pandas\io\clipboard
  copying pandas\io\clipboard\__init__.py -> build\lib.win-amd64-3.8\pandas\io\clipboard
  creating build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\console.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\css.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\csvs.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\excel.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\format.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\html.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\latex.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\printing.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\style.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\terminal.py -> build\lib.win-amd64-3.8\pandas\io\formats
  copying pandas\io\formats\__init__.py -> build\lib.win-amd64-3.8\pandas\io\formats
  creating build\lib.win-amd64-3.8\pandas\io\json
  copying pandas\io\json\json.py -> build\lib.win-amd64-3.8\pandas\io\json
  copying pandas\io\json\normalize.py -> build\lib.win-amd64-3.8\pandas\io\json
  copying pandas\io\json\table_schema.py -> build\lib.win-amd64-3.8\pandas\io\json
  copying pandas\io\json\__init__.py -> build\lib.win-amd64-3.8\pandas\io\json
  creating build\lib.win-amd64-3.8\pandas\io\msgpack
  copying pandas\io\msgpack\exceptions.py -> build\lib.win-amd64-3.8\pandas\io\msgpack
  copying pandas\io\msgpack\_version.py -> build\lib.win-amd64-3.8\pandas\io\msgpack
  copying pandas\io\msgpack\__init__.py -> build\lib.win-amd64-3.8\pandas\io\msgpack
  creating build\lib.win-amd64-3.8\pandas\io\sas
  copying pandas\io\sas\sas7bdat.py -> build\lib.win-amd64-3.8\pandas\io\sas
  copying pandas\io\sas\sasreader.py -> build\lib.win-amd64-3.8\pandas\io\sas
  copying pandas\io\sas\sas_constants.py -> build\lib.win-amd64-3.8\pandas\io\sas
  copying pandas\io\sas\sas_xport.py -> build\lib.win-amd64-3.8\pandas\io\sas
  copying pandas\io\sas\__init__.py -> build\lib.win-amd64-3.8\pandas\io\sas
  creating build\lib.win-amd64-3.8\pandas\tests\api
  copying pandas\tests\api\test_api.py -> build\lib.win-amd64-3.8\pandas\tests\api
  copying pandas\tests\api\test_types.py -> build\lib.win-amd64-3.8\pandas\tests\api
  copying pandas\tests\api\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\api
  creating build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\test_datetime64.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\test_numeric.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\test_object.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\test_period.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\test_timedelta64.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  copying pandas\tests\arithmetic\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\arithmetic
  creating build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_array.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_datetimelike.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_datetimes.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_integer.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_numpy.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_period.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\test_timedeltas.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  copying pandas\tests\arrays\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\arrays
  creating build\lib.win-amd64-3.8\pandas\tests\computation
  copying pandas\tests\computation\test_compat.py -> build\lib.win-amd64-3.8\pandas\tests\computation
  copying pandas\tests\computation\test_eval.py -> build\lib.win-amd64-3.8\pandas\tests\computation
  copying pandas\tests\computation\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\computation
  creating build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\test_common.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\test_concat.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\test_dtypes.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\test_generic.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\test_inference.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\test_missing.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  copying pandas\tests\dtypes\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\dtypes
  creating build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_categorical.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_common.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_datetime.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_external_block.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_integer.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_interval.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_period.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\test_sparse.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  copying pandas\tests\extension\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\extension
  creating build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\common.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_alter_axes.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_analytics.py -> build\lib.win-amd64-3.8\pandas\tests\frame

Requirement already satisfied: pygments in c:\programdata\anaconda3\lib\site-packages (from ipython~=5.5.0->google.colab) (2.10.0)
Collecting prompt-toolkit<2.0.0,>=1.0.4
  Downloading prompt_toolkit-1.0.18-py3-none-any.whl (245 kB)
     -------------------------------------- 245.4/245.4 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: ipython-genutils in c:\programdata\anaconda3\lib\site-packages (from notebook~=5.2.0->google.colab) (0.2.0)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from notebook~=5.2.0->google.colab) (2.11.3)
Requirement already satisfied: jupyter-core in c:\programdata\anaconda3\lib\site-packages (from notebook~=5.2.0->google.colab) (4.7.1)
Requirement already satisfied: nbconvert in c:\programdata\anaconda3\lib\site-packages (from notebook~=5.2.0->google.colab) (6.1.0)
Requirement already satisfied: nbformat in c:\programdata\anaconda3\lib\site-packages (from notebook~=5.2.0->google.colab) (5.1.3)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\programdata\anaconda3\lib\site-packages (from pandas~=0.24.0->google.colab) (2.8.2)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas~=0.24.0->google.colab) (2021.1)
Requirement already satisfied: numpy>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from pandas~=0.24.0->google.colab) (1.20.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.21.0->google.colab) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.21.0->google.colab) (2022.9.24)
Collecting idna<2.9,>=2.5
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
     ---------------------------------------- 58.6/58.6 kB 3.2 MB/s eta 0:00:00
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
     -------------------------------------- 118.8/118.8 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython~=5.5.0->google.colab) (0.2.5)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\programdata\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=1.4.0->google.colab) (0.4.8)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2->notebook~=5.2.0->google.colab) (2.0.1)
Requirement already satisfied: pyzmq>=13 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client->ipykernel~=4.6.0->google.colab) (22.2.1)
Requirement already satisfied: entrypoints in c:\programdata\anaconda3\lib\site-packages (from jupyter-client->ipykernel~=4.6.0->google.colab) (0.3)
Requirement already satisfied: nest-asyncio>=1.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client->ipykernel~=4.6.0->google.colab) (1.5.1)
Requirement already satisfied: pywin32>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core->notebook~=5.2.0->google.colab) (228)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (4.0.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (0.5.3)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (0.8.4)
Requirement already satisfied: testpath in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (0.5.0)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (0.1.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook~=5.2.0->google.colab) (1.4.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\programdata\anaconda3\lib\site-packages (from nbformat->notebook~=5.2.0->google.colab) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook~=5.2.0->google.colab) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook~=5.2.0->google.colab) (21.2.0)
Requirement already satisfied: async-generator in c:\programdata\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook~=5.2.0->google.colab) (1.10)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert->notebook~=5.2.0->google.colab) (21.0)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert->notebook~=5.2.0->google.colab) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook~=5.2.0->google.colab) (2.4.7)
Building wheels for collected packages: google.colab, pandas, portpicker, tornado
  Building wheel for google.colab (setup.py): started
  Building wheel for google.colab (setup.py): finished with status 'done'
  Created wheel for google.colab: filename=google_colab-1.0.0-py2.py3-none-any.whl size=102293 sha256=8f6a9dbb7ece6466b4444dbc8af3687ab59617b76c00d191c0ec0d175935dbd1
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\19\34\a2\627b318cc611024c3f61f16dc74c21d0636fc01d2a772a3ed0
  Building wheel for pandas (setup.py): started
  Building wheel for pandas (setup.py): finished with status 'error'
  Running setup.py clean for pandas
  Building wheel for portpicker (setup.py): started
  Building wheel for portpicker (setup.py): finished with status 'done'
  Created wheel for portpicker: filename=portpicker-1.2.0-py3-none-any.whl size=13385 sha256=61f85f4124903203f0e8b3040bfe26da567d297294525f54ec713c150b9e00ed
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\3b\ef\63\cb17c0dde7b5af62f17527706af085192464a757e7fc3fcefc
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-4.5.3-cp38-cp38-win_amd64.whl size=420781 sha256=b62c0dd9f86c28241f9c4f3901eace4399c084038a27b24e6b01ab805c42a4d6
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\d7\8b\64\40fe9e59e04e9c8fae85255cd87123c580185b26c3972b00bf
Successfully built google.colab portpicker tornado
Failed to build pandas
Installing collected packages: tornado, portpicker, urllib3, six, idna, requests, prompt-toolkit, google-auth, pandas, ipython, ipykernel, notebook, google.colab
  Attempting uninstall: tornado
    Found existing installation: tornado 6.1
    Uninstalling tornado-6.1:

  copying pandas\tests\frame\test_api.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_apply.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_arithmetic.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_asof.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_axis_select_reindex.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_block_internals.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_combine_concat.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_constructors.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_convert_to.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_dtypes.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_duplicates.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_indexing.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_join.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_missing.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_mutate_columns.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_nonunique_indexes.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_operators.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_period.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_quantile.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_query_eval.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_rank.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_replace.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_repr_info.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_reshape.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_sorting.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_sort_values_level_as_str.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_subclass.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_timeseries.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_timezones.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_to_csv.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\test_validate.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  copying pandas\tests\frame\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\frame
  creating build\lib.win-amd64-3.8\pandas\tests\generic
  copying pandas\tests\generic\test_frame.py -> build\lib.win-amd64-3.8\pandas\tests\generic
  copying pandas\tests\generic\test_generic.py -> build\lib.win-amd64-3.8\pandas\tests\generic
  copying pandas\tests\generic\test_label_or_level_utils.py -> build\lib.win-amd64-3.8\pandas\tests\generic
  copying pandas\tests\generic\test_panel.py -> build\lib.win-amd64-3.8\pandas\tests\generic
  copying pandas\tests\generic\test_series.py -> build\lib.win-amd64-3.8\pandas\tests\generic
  copying pandas\tests\generic\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\generic
  creating build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_apply.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_bin_groupby.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_categorical.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_counting.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_filters.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_function.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_groupby.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_grouping.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_index_as_string.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_nth.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_rank.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_timegrouper.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_transform.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_value_counts.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\test_whitelist.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  copying pandas\tests\groupby\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\groupby
  creating build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\common.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\datetimelike.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\test_base.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\test_category.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\test_common.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\test_frozen.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\test_numeric.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\test_range.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  copying pandas\tests\indexes\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\indexes
  creating build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\common.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_callable.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_categorical.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_chaining_and_caching.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_coercion.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_datetime.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_floats.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_iloc.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_indexing.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_indexing_engines.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_indexing_slow.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_ix.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_loc.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_panel.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_partial.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_scalar.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\test_timedelta.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  copying pandas\tests\indexing\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\indexing
  creating build\lib.win-amd64-3.8\pandas\tests\internals
  copying pandas\tests\internals\test_internals.py -> build\lib.win-amd64-3.8\pandas\tests\internals
  copying pandas\tests\internals\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\internals
  creating build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\generate_legacy_storage_files.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_clipboard.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_common.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_compression.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_date_converters.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_excel.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_feather.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_gbq.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_gcs.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_html.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_packers.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_parquet.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_pickle.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_pytables.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_s3.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_sql.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\test_stata.py -> build\lib.win-amd64-3.8\pandas\tests\io
  copying pandas\tests\io\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\io
  creating build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\common.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_boxplot_method.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_converter.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_datetimelike.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_frame.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_groupby.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_hist_method.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_misc.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\test_series.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  copying pandas\tests\plotting\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\plotting
  creating build\lib.win-amd64-3.8\pandas\tests\reductions
  copying pandas\tests\reductions\test_reductions.py -> build\lib.win-amd64-3.8\pandas\tests\reductions
  copying pandas\tests\reductions\test_stat_reductions.py -> build\lib.win-amd64-3.8\pandas\tests\reductions
  copying pandas\tests\reductions\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\reductions
  creating build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_base.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_datetime_index.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_period_index.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_resampler_grouper.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_resample_api.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_timedelta.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\test_time_grouper.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  copying pandas\tests\resample\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\resample
  creating build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_concat.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_cut.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_melt.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_pivot.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_qcut.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_reshape.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_union_categoricals.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\test_util.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  copying pandas\tests\reshape\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\reshape
  creating build\lib.win-amd64-3.8\pandas\tests\scalar
  copying pandas\tests\scalar\test_nat.py -> build\lib.win-amd64-3.8\pandas\tests\scalar
  copying pandas\tests\scalar\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\scalar
  creating build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\common.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_alter_axes.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_analytics.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_api.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_apply.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_arithmetic.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_asof.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_block_internals.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_combine_concat.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_constructors.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_datetime_values.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_dtypes.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_duplicates.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_internals.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_io.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_missing.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_operators.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_period.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_quantile.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_rank.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_replace.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_repr.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_sorting.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_subclass.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_timeseries.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_timezones.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\test_validate.py -> build\lib.win-amd64-3.8\pandas\tests\series
  copying pandas\tests\series\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\series
  creating build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\common.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\test_combine_concat.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\test_format.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\test_groupby.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\test_indexing.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\test_pivot.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\test_reshape.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  copying pandas\tests\sparse\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\sparse
  creating build\lib.win-amd64-3.8\pandas\tests\tools
  copying pandas\tests\tools\test_numeric.py -> build\lib.win-amd64-3.8\pandas\tests\tools
  copying pandas\tests\tools\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\tools
  creating build\lib.win-amd64-3.8\pandas\tests\tseries
  copying pandas\tests\tseries\test_frequencies.py -> build\lib.win-amd64-3.8\pandas\tests\tseries
  copying pandas\tests\tseries\test_holiday.py -> build\lib.win-amd64-3.8\pandas\tests\tseries
  copying pandas\tests\tseries\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\tseries
  creating build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_api.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_array_to_datetime.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_ccalendar.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_conversion.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_libfrequencies.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_liboffsets.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_normalize_date.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_parse_iso8601.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_parsing.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_period_asfreq.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_timedeltas.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_timezones.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  copying pandas\tests\tslibs\__init__.py -> build\lib.win-amd64-3.8\pandas\tests\tslibs
  creating build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\conftest.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_almost_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_categorical_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_extension_array_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_frame_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_index_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_interval_array_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util
  copying pandas\tests\util\test_assert_numpy_array_equal.py -> build\lib.win-amd64-3.8\pandas\tests\util

In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from google.colab import data_table
data_table.enable_dataframe_formatter()

ModuleNotFoundError: No module named 'google.colab'

In [2]:
url = 'https://www.bbc.com/sport/football/tables'
r = requests.get(url)
html = r.text
soup = BeautifulSoup(html, 'html.parser')
table = soup.find('table')
df = pd.read_html(str(table))[0]
df

,Unnamed: 0,Unnamed: 1,Team,P,W,D,L,F,A,GD,Pts,Form
0,1,team hasn't moved,Arsenal,14,12,1,1,33,11,22,37,WWon 1 - 0 against Leeds United on October 16t...
1,2,team hasn't moved,Newcastle,16,9,6,1,32,11,21,33,WWon 1 - 0 against Everton on October 19th 202...
2,3,team hasn't moved,Man City,14,10,2,2,40,14,26,32,LLost 0 - 1 against Liverpool on October 16th ...
3,4,team hasn't moved,Tottenham,16,9,3,4,33,23,10,30,LLost 1 - 2 against Newcastle United on Octobe...
4,5,team hasn't moved,Man Utd,14,8,2,4,20,20,0,26,WWon 2 - 0 against Tottenham Hotspur on Octobe...
5,6,team hasn't moved,Brighton,15,7,3,5,26,20,6,24,DDrew 0 - 0 against Nottingham Forest on Octob...
6,7,team hasn't moved,Liverpool,14,6,4,4,28,17,11,22,WWon 1 - 0 against West Ham United on October ...
7,8,team hasn't moved,Fulham,16,6,4,6,27,26,1,22,WWon 3 - 0 against Aston Villa on October 20th...
8,9,team hasn't moved,Chelsea,14,6,3,5,17,17,0,21,DDrew 0 - 0 against Brentford on October 19th ...
9,10,team hasn't moved,Brentford,16,4,8,4,25,27,-2,20,LLost 0 - 4 against Aston Villa on October 23r...
10,11,team hasn't moved,Crystal Palace,15,5,4,6,15,21,-6,19,WWon 2 - 1 against Wolverhampton Wanderers on ...
11,12,team hasn't moved,Aston Villa,15,5,3,7,16,22,-6,18,LLost 0 - 3 against Fulham on October 20th 202...
12,13,team hasn't moved,Leicester,16,5,2,9,25,28,-3,17,WWon 2 - 0 against Leeds United on October 20t...
13,14,team hasn't moved,Bournemouth,15,4,4,7,18,32,-14,16,LLost 0 - 1 against Southampton on October 19t...
14,15,team hasn't moved,Leeds,14,4,3,7,22,26,-4,15,LLost 0 - 2 against Leicester City on October ...
15,16,team hasn't moved,West Ham,15,4,2,9,12,17,-5,14,LLost 0 - 1 against Liverpool on October 19th ...
16,17,team hasn't moved,Everton,16,3,5,8,12,19,-7,14,LLost 0 - 1 against Newcastle United on Octobe...
17,18,team hasn't moved,Wolves,16,3,4,9,10,25,-15,13,LLost 1 - 2 against Crystal Palace on October ...
18,19,team hasn't moved,Nottm Forest,15,3,4,8,11,30,-19,13,DDrew 0 - 0 against Brighton & Hove Albion on ...
19,20,team hasn't moved,Southampton,16,3,3,10,14,30,-16,12,WWon 1 - 0 against AFC Bournemouth on October ...
20,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53,Last updated 26th December 2022 at 16:53

In [3]:
df.drop(columns=['Unnamed: 0','Unnamed: 1','Form'],inplace=True)
df.drop([20],inplace=True)
df

              Team   P   W  D   L   F   A   GD Pts
0          Arsenal  14  12  1   1  33  11   22  37
1        Newcastle  16   9  6   1  32  11   21  33
2         Man City  14  10  2   2  40  14   26  32
3        Tottenham  16   9  3   4  33  23   10  30
4          Man Utd  14   8  2   4  20  20    0  26
5         Brighton  15   7  3   5  26  20    6  24
6        Liverpool  14   6  4   4  28  17   11  22
7           Fulham  16   6  4   6  27  26    1  22
8          Chelsea  14   6  3   5  17  17    0  21
9        Brentford  16   4  8   4  25  27   -2  20
10  Crystal Palace  15   5  4   6  15  21   -6  19
11     Aston Villa  15   5  3   7  16  22   -6  18
12       Leicester  16   5  2   9  25  28   -3  17
13     Bournemouth  15   4  4   7  18  32  -14  16
14           Leeds  14   4  3   7  22  26   -4  15
15        West Ham  15   4  2   9  12  17   -5  14
16         Everton  16   3  5   8  12  19   -7  14
17          Wolves  16   3  4   9  10  25  -15  13
18    Nottm Forest  15   3  4   8  11  30  -19  13
19     Southampton  16   3  3  10  14  30  -16  12