In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 14), datetime.date(2023, 2, 13))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-14
yesterday: 2023-02-13 00:00:00

In [3]:
yesterday = yesterday.date()
a_year_ago = yesterday - timedelta(days=365)
yesterday, a_year_ago

(datetime.date(2023, 2, 13), datetime.date(2022, 2, 13))

### Restart and Run All Cells

In [4]:
#cols = 'fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','chg_acc':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','%chg_acc':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### When orders file changes.

In [5]:
pd.read_sql_query('SELECT COUNT(*) AS records FROM sales', conlite)

   records
0     1996

In [6]:
sqlDel = """DELETE FROM sales"""
rp = conlite.execute(sqlDel)
rp.rowcount

2287

In [7]:
sql = """
SELECT name
FROM orders 
ORDER BY name
"""
df = pd.read_sql(sql, conlite)

names = df['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'BANPU', 'CK', 'CKP', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MC', 'MEGA', 'ORI', 'PTT', 'RCL', 'SAT', 'SINGER', 'TCAP', 'TMT', 'TTB', 'WHAIR'"

In [8]:
len(in_p.split(','))

20

### Get past one year data

In [9]:
sql = """
SELECT name, date, price, qty, maxp, minp 
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (a_year_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-02-13' AND name IN ('BANPU', 'CK', 'CKP', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MC', 'MEGA', 'ORI', 'PTT', 'RCL', 'SAT', 'SINGER', 'TCAP', 'TMT', 'TTB', 'WHAIR')
ORDER BY name, date

In [10]:
df = pd.read_sql(sql, const)
df.sample(5)

       name        date  price        qty   maxp   minp
3317    RCL  2022-11-04  28.50    7084110  29.00  27.50
2917    PTT  2022-03-08  38.25  112185188  38.75  37.25
2702    ORI  2022-04-20  11.20    6517836  11.40  11.10
1718    JMT  2022-03-23  69.75    6810264  70.25  68.75
147   BANPU  2022-09-26  12.80  220303605  13.30  12.70

In [11]:
data_path = "../data/"
file_name = "Yearly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

#df.set_index("name", inplace=True)
df.to_csv(output_file, header=True, index=False)
df.to_csv(osd_file, header=True, index=False)

### Create monitors from orders

In [12]:
sql = """
SELECT name,trade 
FROM orders 
WHERE name IN (%s)
ORDER BY name
"""
sql = sql % in_p
orders = pd.read_sql(sql, conlite)
orders.set_index(['name'],inplace=True)
orders

       trade
name
BANPU      B
CK         B
CKP        B
DIF        S
IVL        S
JASIF      S
JMART      S
JMT        B
KCE        B
MC         B
MEGA       B
ORI        S
PTT        B
RCL        B
SAT        B
SINGER     S
TCAP       B
TMT        S
TTB        B
WHAIR      S

In [13]:
file_name = "monitors.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
osd_file = osd_path + file_name

orders.to_csv(data_file, header=None)
orders.to_csv(output_file)
orders.to_csv(osd_file, header=True, index=False)

In [14]:
sql = """
SELECT trade, COUNT(*) AS items 
FROM orders
GROUP BY trade
ORDER BY trade
"""
grp = pd.read_sql(sql, conlite)
grp

  trade  items
0     B     12
1     S      8

### Call ruby ruby\crt-sales.rb

In [15]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Ad hoc'

In [16]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [17]:
!ruby ruby\\crt-sales.rb

ruby/../Data/Yearly-Price-by-Name.csv
name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,trend,nbr,ttl_qty
BANPU|2022-02-14|2022-02-14|1|11.5|11.5|0.0|0.0|1|1|11.8|11.3||2|246,130,330
BANPU|2022-02-15|2022-02-21|5|11.4|10.8|-0.6|-5.26|-5|-1|11.6|10.6|Downward|6|592,311,157
BANPU|2022-02-22|2022-02-23|2|10.9|11.1|0.2|1.83|3|1|11.1|10.6|Upward|8|182,695,270
BANPU|2022-02-24|2022-02-24|1|10.8|10.8|0.0|0.0|1|1|11.0|10.5|Downward|9|258,873,337
BANPU|2022-02-25|2022-03-03|5|10.9|12.5|1.6|14.68|17|3|12.8|10.7|Upward|14|1,550,958,765
BANPU|2022-03-04|2022-03-04|1|11.7|11.7|0.0|0.0|1|1|12.2|11.6|Downward|15|277,021,796
BANPU|2022-03-07|2022-03-07|1|12.1|12.1|0.0|0.0|1|1|12.3|11.6|Upward|16|434,107,397
BANPU|2022-03-08|2022-03-10|3|11.7|11.3|-0.4|-3.42|-3|-1|12.0|11.1|Downward|19|940,613,021
BANPU|2022-03-11|2022-03-11|1|11.5|11.5|0.0|0.0|1|1|11.6|11.1|Upward|20|164,323,990
BANPU|2022-03-14|2022-03-15|2|11.2|10.8|-0.4|-3.57|-3|-2|11.5|10.8|Downward|22|325,605,335
BANPU|2022-03-16|2022-03-18|3|11.0|11.1|0.1|0.91|2|0|11.1|10.8|Upward|25|228,466,071
BANPU|2022-03-21|2022-03-21|1|11.0|11.0|0.0|0.0|1|1|11.1|10.9|Downward|26|26,013,349
BANPU|2022-03-22|2022-03-29|6|11.2|11.5|0.3|2.68|4|0|11.6|10.9|Upward|32|530,215,079
BANPU|2022-03-30|2022-03-31|2|11.2|11.0|-0.2|-1.79|-1|-1|11.5|11.0|Downward|34|191,081,381
BANPU|2022-04-01|2022-04-07|5|11.1|11.3|0.2|1.8|3|0|11.3|11.0|Upward|38|224,653,150
BANPU|2022-04-08|2022-04-12|3|11.1|10.8|-0.3|-2.7|-2|-1|11.1|10.8|Downward|41|190,789,616
BANPU|2022-04-18|2022-04-22|5|11.2|11.9|0.7|6.25|8|1|11.9|10.9|Upward|46|740,602,506
BANPU|2022-04-25|2022-04-27|3|11.6|11.6|0.0|0.0|1|0|11.8|11.3|Downward|49|357,262,827
BANPU|2022-04-28|2022-04-29|2|12.2|12.3|0.1|0.82|2|1|12.4|11.6|Upward|51|558,843,916
BANPU|2022-05-03|2022-05-03|1|12.2|12.2|0.0|0.0|1|1|12.4|12.1|Downward|52|186,934,828
BANPU|2022-05-05|2022-05-09|3|12.4|12.5|0.1|0.81|2|0|12.7|12.1|Upward|55|535,608,872
BANPU|2022-05-10|2022-05-12|3|12.1|11.5|-0.6|-4.96|-5|-2|12.4|11.3|Downward|58|694,680,301
BANPU|2022-05-13|2022-05-18|4|11.6|11.9|0.3|2.59|4|1|12.0|11.4|Upward|61|338,974,617
BANPU|2022-05-19|2022-05-19|1|11.7|11.7|0.0|0.0|1|1|11.8|11.5|Downward|62|124,415,429
BANPU|2022-05-20|2022-05-23|2|12.2|12.2|0.0|0.0|1|0|12.3|11.8|Upward|64|285,078,675
BANPU|2022-05-24|2022-05-25|2|12.1|11.8|-0.3|-2.48|-2|-1|12.2|11.8|Downward|66|187,743,713
BANPU|2022-05-26|2022-05-26|1|12.2|12.2|0.0|0.0|1|1|12.2|11.8|Upward|67|106,630,355
BANPU|2022-05-27|2022-05-30|2|12.1|12.1|0.0|0.0|1|0|12.3|12.0|Downward|69|89,168,485
BANPU|2022-05-31|2022-06-07|6|12.4|13.3|0.9|7.26|10|1|13.4|12.1|Upward|74|915,446,165
BANPU|2022-06-08|2022-06-08|1|13.0|13.0|0.0|0.0|1|1|13.3|12.9|Downward|75|160,972,040
BANPU|2022-06-09|2022-06-09|1|13.1|13.1|0.0|0.0|1|1|13.2|12.9|Upward|76|157,839,899
BANPU|2022-06-10|2022-06-13|2|13.0|13.0|0.0|0.0|1|0|13.2|12.7|Downward|78|240,828,092
BANPU|2022-06-14|2022-06-14|1|13.4|13.4|0.0|0.0|1|1|13.5|13.0|Upward|79|239,685,280
BANPU|2022-06-15|2022-06-20|4|13.3|12.5|-0.8|-6.02|-7|-2|13.5|12.3|Downward|83|696,095,717
BANPU|2022-06-21|2022-06-21|1|12.8|12.8|0.0|0.0|1|1|13.0|12.6|Upward|84|140,825,413
BANPU|2022-06-22|2022-06-24|3|12.7|12.2|-0.5|-3.94|-4|-2|12.8|11.9|Downward|87|488,664,876
BANPU|2022-06-27|2022-06-30|4|12.5|12.6|0.1|0.8|2|0|12.8|12.2|Upward|91|395,411,835
BANPU|2022-07-01|2022-07-04|2|12.4|12.2|-0.2|-1.61|-1|-1|12.7|12.1|Downward|93|216,333,669
BANPU|2022-07-05|2022-07-05|1|12.5|12.5|0.0|0.0|1|1|12.6|12.2|Upward|94|159,706,679
BANPU|2022-07-06|2022-07-06|1|12.2|12.2|0.0|0.0|1|1|12.4|12.1|Downward|95|182,498,480
BANPU|2022-07-07|2022-07-11|3|12.4|12.9|0.5|4.03|6|2|12.9|12.0|Upward|98|417,084,136
BANPU|2022-07-12|2022-07-15|4|12.8|12.5|-0.3|-2.34|-2|-1|12.9|12.1|Downward|101|299,727,319
BANPU|2022-07-18|2022-07-19|2|12.8|12.9|0.1|0.78|2|1|12.9|12.4|Upward|103|218,847,313
BANPU|2022-07-20|2022-07-21|2|12.8|12.8|0.0|0.0|1|0|13.2|12.7|Downward|105|250,004,248
BANPU|2022-07-22|2022-07-27|4|12.9|13.4|0.5|3.88|6|1|13.5|12.7|Upward|109|392,825,172
BANPU|2022-08-01|2022-08-02|2|13.3|13.1|-0.2|-1.5|-1|-1|13.4|12.9|Downward|111|235,107,306
BANPU|2022-08-03|2022-08-03|1|13.3|13.3|0.0|0.0|1|1|13.3|13.0|Upward|112|103,627,813
BANPU|2022-08-04|2022-08-08|3|12.8|12.6|-0.2|-1.56|-1|-1|13.3|12.4|Downward|115|582,505,013
BANPU|2022-08-09|2022-08-17|7|12.7|14.0|1.3|10.24|14|2|14.0|12.6|Upward|121|934,607,936
BANPU|2022-08-18|2022-08-22|3|13.9|13.9|0.0|0.0|1|0|14.1|13.5|Downward|124|501,627,871
BANPU|2022-08-23|2022-08-30|6|14.5|14.9|0.4|2.76|5|0|15.0|13.9|Upward|130|1,531,431,374
BANPU|2022-08-31|2022-09-02|3|14.5|13.9|-0.6|-4.14|-5|-2|14.9|13.7|Downward|133|797,500,635
BANPU|2022-09-05|2022-09-06|2|14.3|14.5|0.2|1.4|3|1|14.6|14.0|Upward|135|397,607,475
BANPU|2022-09-07|2022-09-08|2|14.2|14.0|-0.2|-1.41|-1|-1|14.4|13.9|Downward|137|240,833,129
BANPU|2022-09-09|2022-09-12|2|14.3|14.4|0.1|0.7|2|1|14.5|14.1|Upward|139|168,622,790
BANPU|2022-09-13|2022-09-19|5|14.3|13.3|-1.0|-6.99|-9|-2|14.5|13.2|Downward|144|715,638,095
BANPU|2022-09-20|2022-09-21|2|13.4|13.7|0.3|2.24|4|2|13.9|13.2|Upward|146|195,381,616
BANPU|2022-09-22|2022-10-03|8|13.6|12.1|-1.5|-11.03|-14|-2|13.8|12.1|Downward|154|948,932,027
BANPU|2022-10-04|2022-10-06|3|12.4|12.7|0.3|2.42|4|1|12.8|12.2|Upward|157|240,471,957
BANPU|2022-10-07|2022-10-07|1|12.3|12.3|0.0|0.0|1|1|12.7|12.3|Downward|158|110,535,627
BANPU|2022-10-10|2022-10-17|6|12.6|12.8|0.2|1.59|3|0|12.8|12.1|Upward|162|442,829,447
BANPU|2022-10-18|2022-10-19|2|12.7|12.4|-0.3|-2.36|-2|-1|12.9|12.4|Downward|164|218,377,354
BANPU|2022-10-20|2022-10-20|1|12.7|12.7|0.0|0.0|1|1|12.7|12.4|Upward|165|68,849,546
BANPU|2022-10-21|2022-10-25|3|12.6|12.4|-0.2|-1.59|-1|-1|12.7|12.3|Downward|167|133,502,963
BANPU|2022-10-26|2022-10-27|2|12.5|12.5|0.0|0.0|1|0|12.5|12.3|Upward|169|145,374,786
BANPU|2022-10-28|2022-10-28|1|12.3|12.3|0.0|0.0|1|1|12.5|12.3|Downward|170|35,572,911
BANPU|2022-10-31|2022-11-01|2|12.5|12.6|0.1|0.8|2|1|12.7|12.4|Upward|172|185,418,551
BANPU|2022-11-02|2022-11-02|1|12.5|12.5|0.0|0.0|1|1|12.7|12.5|Downward|173|56,586,222
BANPU|2022-11-03|2022-11-07|3|12.6|13.0|0.4|3.17|5|1|13.2|12.5|Upward|176|324,332,864
BANPU|2022-11-08|2022-11-09|2|12.9|12.6|-0.3|-2.33|-2|-1|13.1|12.5|Downward|178|144,359,887
BANPU|2022-11-10|2022-11-11|2|12.7|12.8|0.1|0.79|2|1|13.0|12.3|Upward|180|278,114,895
BANPU|2022-11-14|2022-11-18|5|12.7|12.4|-0.3|-2.36|-2|-1|12.8|12.3|Downward|185|385,796,690
BANPU|2022-11-21|2022-11-24|4|12.6|13.1|0.5|3.97|6|1|13.2|12.5|Upward|189|431,298,904
BANPU|2022-11-25|2022-11-28|2|13.0|12.7|-0.3|-2.31|-2|-1|13.2|12.7|Downward|191|111,861,104
BANPU|2022-11-29|2022-12-06|6|12.9|13.5|0.6|4.65|7|1|13.5|12.8|Upward|196|454,857,208
BANPU|2022-12-07|2022-12-08|2|13.4|13.3|-0.1|-0.75|0|0|13.5|13.2|Downward|198|131,408,863
BANPU|2022-12-09|2022-12-14|4|13.6|13.7|0.1|0.74|2|0|13.8|13.2|Upward|201|266,639,931
BANPU|2022-12-15|2022-12-19|3|13.6|13.5|-0.1|-0.74|0|0|13.7|13.5|Downward|204|224,438,223
BANPU|2022-12-20|2022-12-20|1|13.6|13.6|0.0|0.0|1|1|13.6|13.4|Upward|205|75,293,568
BANPU|2022-12-21|2022-12-21|1|13.5|13.5|0.0|0.0|1|1|13.7|13.4|Downward|206|39,862,227
BANPU|2022-12-22|2022-12-22|1|13.6|13.6|0.0|0.0|1|1|13.7|13.5|Upward|207|62,947,205
BANPU|2022-12-23|2022-12-23|1|13.4|13.4|0.0|0.0|1|1|13.6|13.4|Downward|208|56,515,404
BANPU|2022-12-26|2022-12-26|1|13.5|13.5|0.0|0.0|1|1|13.6|13.3|Upward|209|54,412,026
BANPU|2022-12-27|2022-12-27|1|13.4|13.4|0.0|0.0|1|1|13.5|13.4|Downward|210|39,796,280
BANPU|2022-12-28|2022-12-30|3|13.7|13.7|0.0|0.0|1|0|13.8|13.4|Upward|213|166,355,695
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-10|-3|13.7|12.3|Downward|217|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|1|0|12.6|12.2|Upward|219|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|0|0|12.5|12.1|Downward|221|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|1|1|12.5|12.2|Upward|222|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|0|0|12.5|12.2|Downward|226|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|1|1|12.7|12.3|Upward|227|193,937,283
BANPU|2023-01-23|2023-02-10|15|12.5|10.9|-1.6|-12.8|-15|-1|12.6|10.7|Downward|242|2,058,642,124
BANPU|2023-02-13|2023-02-13|1|11.1|11.1|0.0|0.0|1|1|11.2|10.9|Upward|243|90,540,091
CK|2022-02-14|2022-02-15|2|21.0|21.1|0.1|0.48|2|1|21.4|21.0|Upward|245|10,735,721
CK|2022-02-17|2022-02-24|6|21.0|20.2|-0.8|-3.81|-7|-2|21.3|20.1|Downward|251|25,392,988
CK|2022-02-25|2022-02-28|2|20.8|21.0|0.2|0.96|3|1|21.0|20.4|Upward|253|6,432,813
CK|2022-03-01|2022-03-07|5|20.8|19.0|-1.8|-8.65|-17|-4|21.0|18.9|Downward|258|39,002,947
CK|2022-03-08|2022-03-10|3|19.5|20.7|1.2|6.15|13|4|20.8|18.9|Upward|261|22,727,393
CK|2022-03-11|2022-03-15|3|20.6|20.1|-0.5|-2.43|-4|-2|20.8|20.0|Downward|264|8,919,196
CK|2022-03-16|2022-03-16|1|20.7|20.7|0.0|0.0|1|1|20.7|20.1|Upward|265|3,318,003
CK|2022-03-17|2022-03-17|1|20.5|20.5|0.0|0.0|1|1|20.8|20.5|Downward|266|2,089,923
CK|2022-03-18|2022-03-22|3|20.7|20.9|0.2|0.97|3|1|21.0|20.4|Upward|269|14,563,557
CK|2022-03-23|2022-03-29|5|20.8|20.3|-0.5|-2.4|-4|-1|20.9|20.1|Downward|274|23,421,002
CK|2022-03-30|2022-03-30|1|20.5|20.5|0.0|0.0|1|1|20.5|20.2|Upward|275|6,185,745
CK|2022-03-31|2022-04-07|6|20.2|20.0|-0.2|-0.99|-1|-1|20.5|19.9|Downward|280|13,100,350
CK|2022-04-08|2022-04-08|1|20.7|20.7|0.0|0.0|1|1|20.7|19.9|Upward|281|10,857,128
CK|2022-04-11|2022-04-20|8|20.6|20.1|-0.5|-2.43|-4|-1|20.7|20.1|Downward|286|19,137,608
CK|2022-04-21|2022-04-21|1|20.2|20.2|0.0|0.0|1|1|20.5|20.0|Upward|287|7,247,266
CK|2022-04-22|2022-04-28|5|19.9|19.0|-0.9|-4.52|-8|-2|20.2|18.7|Downward|292|48,364,377
CK|2022-04-29|2022-05-05|5|19.5|19.6|0.1|0.51|2|0|19.8|19.1|Upward|295|14,806,014
CK|2022-05-06|2022-05-11|4|19.5|18.4|-1.1|-5.64|-10|-3|19.7|18.4|Downward|299|24,089,889
CK|2022-05-12|2022-05-30|13|18.5|21.3|2.8|15.14|29|2|21.5|17.9|Upward|311|117,996,816
CK|2022-05-31|2022-06-06|5|20.9|20.6|-0.3|-1.44|-2|-1|21.4|20.5|Downward|315|15,826,600
CK|2022-06-07|2022-06-07|1|20.9|20.9|0.0|0.0|1|1|20.9|20.3|Upward|316|4,592,865
CK|2022-06-08|2022-06-08|1|20.5|20.5|0.0|0.0|1|1|20.9|20.5|Downward|317|2,993,048
CK|2022-06-09|2022-06-09|1|20.7|20.7|0.0|0.0|1|1|20.8|20.4|Upward|318|2,018,190
CK|2022-06-10|2022-06-16|5|20.6|19.5|-1.1|-5.34|-10|-2|20.9|19.5|Downward|323|19,119,646
CK|2022-06-17|2022-06-21|3|19.6|20.0|0.4|2.04|5|1|20.0|19.2|Upward|326|8,161,918
CK|2022-06-22|2022-06-23|2|19.9|19.7|-0.2|-1.01|-1|-1|20.0|19.6|Downward|328|3,456,519
CK|2022-06-24|2022-06-24|1|20.0|20.0|0.0|0.0|1|1|20.0|19.7|Upward|329|1,660,541
CK|2022-06-27|2022-06-27|1|19.8|19.8|0.0|0.0|1|1|20.1|19.8|Downward|330|1,266,767
CK|2022-06-28|2022-06-29|2|20.3|20.3|0.0|0.0|1|0|20.4|19.8|Upward|332|6,903,140
CK|2022-06-30|2022-07-06|5|20.2|19.7|-0.5|-2.48|-4|-1|20.3|19.4|Downward|337|13,495,214
CK|2022-07-07|2022-07-07|1|19.8|19.8|0.0|0.0|1|1|19.9|19.6|Upward|338|2,600,239
CK|2022-07-08|2022-07-08|1|19.4|19.4|0.0|0.0|1|1|19.9|19.4|Downward|339|3,845,312
CK|2022-07-11|2022-07-12|2|19.6|19.9|0.3|1.53|4|2|19.9|19.4|Upward|341|3,374,041
CK|2022-07-14|2022-07-14|1|19.8|19.8|0.0|0.0|1|1|20.2|19.6|Downward|342|3,221,034
CK|2022-07-15|2022-07-19|3|20.0|20.1|0.1|0.5|2|0|20.2|19.8|Upward|345|5,471,700
CK|2022-07-20|2022-07-21|2|20.0|19.6|-0.4|-2.0|-3|-2|20.2|19.5|Downward|347|6,014,481
CK|2022-07-22|2022-07-27|4|19.8|21.4|1.6|8.08|17|4|21.4|19.7|Upward|351|28,855,573
CK|2022-08-01|2022-08-02|2|21.1|20.9|-0.2|-0.95|-1|-1|21.2|20.8|Downward|353|6,441,012
CK|2022-08-03|2022-08-03|1|21.4|21.4|0.0|0.0|1|1|21.4|21.0|Upward|354|5,745,284
CK|2022-08-04|2022-08-04|1|21.1|21.1|0.0|0.0|1|1|21.4|21.1|Downward|355|6,159,669
CK|2022-08-05|2022-08-05|1|21.3|21.3|0.0|0.0|1|1|21.6|21.2|Upward|356|6,048,532
CK|2022-08-08|2022-08-08|1|20.7|20.7|0.0|0.0|1|1|21.2|20.6|Downward|357|14,065,382
CK|2022-08-09|2022-08-11|3|20.8|21.1|0.3|1.44|4|1|21.2|20.6|Upward|360|11,611,161
CK|2022-08-15|2022-08-16|2|21.0|20.3|-0.7|-3.33|-6|-3|21.3|20.3|Downward|362|15,755,424
CK|2022-08-17|2022-08-17|1|20.5|20.5|0.0|0.0|1|1|20.7|20.3|Upward|363|5,259,171
CK|2022-08-18|2022-08-18|1|20.4|20.4|0.0|0.0|1|1|20.8|20.4|Downward|364|3,103,052
CK|2022-08-19|2022-08-19|1|20.5|20.5|0.0|0.0|1|1|20.6|20.3|Upward|365|3,620,902
CK|2022-08-22|2022-08-22|1|20.4|20.4|0.0|0.0|1|1|20.7|20.3|Downward|366|918,156
CK|2022-08-23|2022-08-23|1|20.7|20.7|0.0|0.0|1|1|20.9|20.3|Upward|367|7,111,783
CK|2022-08-24|2022-08-24|1|20.6|20.6|0.0|0.0|1|1|21.1|20.6|Downward|368|8,318,547
CK|2022-08-25|2022-08-26|2|20.7|20.9|0.2|0.97|3|1|21.1|20.6|Upward|370|9,476,797
CK|2022-08-29|2022-08-29|1|20.6|20.6|0.0|0.0|1|1|20.8|20.4|Downward|371|2,371,540
CK|2022-08-30|2022-08-31|2|20.8|21.0|0.2|0.96|3|1|21.1|20.5|Upward|373|10,151,650
CK|2022-09-01|2022-09-05|3|20.8|20.6|-0.2|-0.96|-1|-1|21.1|20.5|Downward|376|7,408,845
CK|2022-09-06|2022-09-09|4|21.7|22.1|0.4|1.84|5|1|22.2|20.6|Upward|380|70,198,582
CK|2022-09-12|2022-09-12|1|21.7|21.7|0.0|0.0|1|1|22.2|21.7|Downward|381|7,061,216
CK|2022-09-13|2022-09-14|2|22.0|22.3|0.3|1.36|4|2|22.4|21.7|Upward|383|22,562,569
CK|2022-09-15|2022-09-15|1|22.2|22.2|0.0|0.0|1|1|22.3|21.9|Downward|384|10,777,555
CK|2022-09-16|2022-09-20|3|22.7|22.9|0.2|0.88|3|1|23.1|22.2|Upward|387|37,598,285
CK|2022-09-21|2022-09-29|7|22.7|21.5|-1.2|-5.29|-11|-2|22.9|21.3|Downward|394|24,418,785
CK|2022-09-30|2022-10-10|7|21.7|22.5|0.8|3.69|9|1|22.5|21.5|Upward|401|25,096,504
CK|2022-10-11|2022-10-11|1|22.0|22.0|0.0|0.0|1|1|22.5|22.0|Downward|402|3,255,117
CK|2022-10-12|2022-10-20|7|22.2|22.7|0.5|2.25|6|0|22.8|21.8|Upward|407|16,723,625
CK|2022-10-21|2022-10-25|3|22.5|22.5|0.0|0.0|1|0|22.7|22.3|Downward|409|5,009,431
CK|2022-10-26|2022-11-03|7|22.8|23.5|0.7|3.07|8|1|23.7|22.5|Upward|416|46,317,326
CK|2022-11-04|2022-11-07|2|23.3|23.3|0.0|0.0|1|0|23.7|23.3|Downward|418|10,978,861
CK|2022-11-08|2022-11-08|1|23.5|23.5|0.0|0.0|1|1|23.9|23.4|Upward|419|9,180,497
CK|2022-11-09|2022-11-10|2|23.3|23.3|0.0|0.0|1|0|23.6|23.2|Downward|421|6,780,463

CK|2022-11-11|2022-11-14|2|23.4|23.4|0.0|0.0|1|0|23.6|23.1|Upward|423|8,366,247
CK|2022-11-15|2022-11-15|1|23.2|23.2|0.0|0.0|1|1|23.6|23.2|Downward|424|2,481,567
CK|2022-11-16|2022-11-23|6|23.5|24.3|0.8|3.4|9|1|24.4|23.1|Upward|430|40,565,884
CK|2022-11-24|2022-11-25|2|24.1|24.1|0.0|0.0|1|0|24.4|24.0|Downward|432|3,638,258
CK|2022-11-28|2022-11-30|3|24.2|24.7|0.5|2.07|6|2|24.7|24.1|Upward|435|17,407,396
CK|2022-12-01|2022-12-02|2|24.4|24.3|-0.1|-0.41|0|0|24.8|24.3|Downward|437|7,765,745
CK|2022-12-06|2022-12-06|1|24.5|24.5|0.0|0.0|1|1|24.5|24.2|Upward|438|3,729,331
CK|2022-12-07|2022-12-07|1|24.0|24.0|0.0|0.0|1|1|24.5|23.9|Downward|439|5,569,251
CK|2022-12-08|2022-12-09|2|24.3|24.5|0.2|0.82|3|1|24.5|24.0|Upward|441|5,888,268
CK|2022-12-13|2022-12-13|1|24.1|24.1|0.0|0.0|1|1|24.6|23.9|Downward|442|6,262,701
CK|2022-12-14|2022-12-16|3|24.2|24.5|0.3|1.24|4|1|24.5|24.1|Upward|445|11,819,757
CK|2022-12-19|2022-12-21|3|24.4|23.2|-1.2|-4.92|-11|-4|24.6|23.2|Downward|448|15,439,525
CK|2022-12-22|2022-12-27|4|23.4|23.9|0.5|2.14|6|1|24.3|23.2|Upward|452|14,226,583
CK|2022-12-28|2022-12-28|1|23.8|23.8|0.0|0.0|1|1|24.0|23.7|Downward|453|3,624,869
CK|2022-12-29|2022-12-30|2|24.2|24.3|0.1|0.41|2|1|24.3|23.8|Upward|455|7,843,794
CK|2023-01-03|2023-01-10|6|23.9|23.5|-0.4|-1.67|-3|-1|24.5|23.2|Downward|461|38,379,065
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|2|1|24.0|23.4|Upward|463|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|1|0|23.9|23.4|Downward|465|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|1|1|24.2|23.8|Upward|466|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|1|1|24.0|23.4|Downward|467|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|1|1|24.1|23.6|Upward|468|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-1|-1|24.1|23.4|Downward|471|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|1|1|23.8|23.5|Upward|472|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-5|-3|23.7|22.6|Downward|474|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|1|1|23.0|22.6|Upward|475|2,492,389
CK|2023-01-31|2023-02-01|2|22.6|22.6|0.0|0.0|1|0|23.1|22.4|Downward|477|14,195,847
CK|2023-02-02|2023-02-02|1|22.8|22.8|0.0|0.0|1|1|23.2|22.7|Upward|478|6,126,236
CK|2023-02-03|2023-02-08|4|22.7|22.4|-0.3|-1.32|-2|-1|22.9|22.3|Downward|482|12,475,240
CK|2023-02-09|2023-02-09|1|22.5|22.5|0.0|0.0|1|1|22.5|22.2|Upward|483|3,740,704
CK|2023-02-10|2023-02-10|1|22.1|22.1|0.0|0.0|1|1|22.6|22.1|Downward|484|3,006,254
CK|2023-02-13|2023-02-13|1|22.3|22.3|0.0|0.0|1|1|22.3|22.0|Upward|485|2,398,287
CKP|2022-02-14|2022-02-18|5|5.0|5.2|0.2|4.0|5|1|5.25|5.0|Upward|489|64,967,429
CKP|2022-02-21|2022-02-21|1|5.1|5.1|0.0|0.0|1|1|5.25|5.1|Downward|490|13,328,418
CKP|2022-02-22|2022-02-23|2|5.15|5.25|0.1|1.94|3|1|5.35|5.05|Upward|492|54,775,184
CKP|2022-02-24|2022-02-24|1|5.05|5.05|0.0|0.0|1|1|5.3|5.0|Downward|493|42,624,209
CKP|2022-02-25|2022-02-25|1|5.15|5.15|0.0|0.0|1|1|5.15|5.05|Upward|494|11,066,514
CKP|2022-02-28|2022-03-08|7|5.1|4.84|-0.26|-5.1|-9|-2|5.2|4.7|Downward|501|146,727,824
CKP|2022-03-09|2022-03-09|1|5.05|5.05|0.0|0.0|1|1|5.05|4.86|Upward|502|20,171,361
CKP|2022-03-10|2022-03-10|1|5.0|5.0|0.0|0.0|1|1|5.1|4.98|Downward|503|12,089,688
CKP|2022-03-11|2022-03-11|1|5.05|5.05|0.0|0.0|1|1|5.1|5.0|Upward|504|8,061,867
CKP|2022-03-14|2022-03-15|2|5.0|4.94|-0.06|-1.2|-2|-1|5.1|4.94|Downward|506|16,850,574
CKP|2022-03-16|2022-03-18|3|4.98|5.05|0.07|1.41|3|1|5.05|4.94|Upward|509|24,429,331
CKP|2022-03-21|2022-03-21|1|4.98|4.98|0.0|0.0|1|1|5.05|4.96|Downward|510|9,236,451
CKP|2022-03-22|2022-03-22|1|5.05|5.05|0.0|0.0|1|1|5.05|4.98|Upward|511|8,603,901
CKP|2022-03-23|2022-03-29|5|4.98|4.98|0.0|0.0|1|0|5.05|4.92|Downward|516|26,229,659
CKP|2022-03-30|2022-03-31|2|5.0|5.2|0.2|4.0|5|2|5.2|4.98|Upward|518|32,560,729
CKP|2022-04-01|2022-04-07|5|5.1|5.0|-0.1|-1.96|-1|-1|5.25|5.0|Downward|522|20,594,570
CKP|2022-04-08|2022-04-08|1|5.05|5.05|0.0|0.0|1|1|5.1|5.0|Upward|523|7,604,570
CKP|2022-04-11|2022-04-18|6|4.98|4.94|-0.04|-0.8|-1|-1|5.1|4.92|Downward|526|29,637,085
CKP|2022-04-19|2022-04-26|6|4.98|5.1|0.12|2.41|4|0|5.1|4.94|Upward|532|44,511,971
CKP|2022-04-27|2022-04-27|1|5.05|5.05|0.0|0.0|1|1|5.1|5.0|Downward|533|11,935,285
CKP|2022-04-28|2022-04-29|2|5.35|5.45|0.1|1.87|3|1|5.5|5.1|Upward|535|119,670,470
CKP|2022-05-03|2022-05-09|5|5.35|5.2|-0.15|-2.8|-2|-1|5.5|5.2|Downward|539|96,253,229
CKP|2022-05-10|2022-05-18|7|5.45|5.65|0.2|3.67|5|0|5.65|5.1|Upward|545|185,351,343
CKP|2022-05-19|2022-05-20|2|5.55|5.55|0.0|0.0|1|0|5.7|5.5|Downward|547|40,629,825
CKP|2022-05-23|2022-05-23|1|5.6|5.6|0.0|0.0|1|1|5.75|5.6|Upward|548|28,969,393
CKP|2022-05-24|2022-05-25|2|5.55|5.45|-0.1|-1.8|-1|-1|5.65|5.4|Downward|550|44,039,128
CKP|2022-05-26|2022-05-26|1|5.6|5.6|0.0|0.0|1|1|5.65|5.45|Upward|551|26,923,978
CKP|2022-05-27|2022-05-31|3|5.55|5.45|-0.1|-1.8|-1|-1|5.65|5.4|Downward|554|69,679,898
CKP|2022-06-01|2022-06-02|2|5.5|5.5|0.0|0.0|1|0|5.6|5.45|Upward|556|32,032,524
CKP|2022-06-06|2022-06-07|2|5.3|5.3|0.0|0.0|1|0|5.5|5.25|Downward|558|49,752,405
CKP|2022-06-08|2022-06-10|3|5.4|5.6|0.2|3.7|5|1|5.6|5.3|Upward|561|47,934,885
CKP|2022-06-13|2022-06-13|1|5.4|5.4|0.0|0.0|1|1|5.55|5.4|Downward|562|17,776,236
CKP|2022-06-14|2022-06-15|2|5.5|5.5|0.0|0.0|1|0|5.6|5.35|Upward|564|36,809,070
CKP|2022-06-16|2022-06-16|1|5.4|5.4|0.0|0.0|1|1|5.6|5.4|Downward|565|21,431,612
CKP|2022-06-17|2022-06-23|5|5.55|5.8|0.25|4.5|6|1|5.9|5.35|Upward|570|129,943,775
CKP|2022-06-24|2022-06-30|5|5.75|5.55|-0.2|-3.48|-3|-1|5.85|5.5|Downward|575|47,300,978
CKP|2022-07-01|2022-07-04|2|5.7|5.7|0.0|0.0|1|0|5.7|5.55|Upward|577|15,623,244
CKP|2022-07-05|2022-07-05|1|5.45|5.45|0.0|0.0|1|1|5.7|5.4|Downward|578|21,396,964
CKP|2022-07-06|2022-07-07|2|5.55|5.55|0.0|0.0|1|0|5.65|5.4|Upward|580|42,655,254
CKP|2022-07-08|2022-07-08|1|5.4|5.4|0.0|0.0|1|1|5.55|5.4|Downward|581|15,187,698
CKP|2022-07-11|2022-07-11|1|5.5|5.5|0.0|0.0|1|1|5.5|5.35|Upward|582|8,157,212
CKP|2022-07-12|2022-07-14|3|5.45|5.4|-0.05|-0.92|0|0|5.5|5.4|Downward|584|11,789,642
CKP|2022-07-15|2022-07-18|2|5.45|5.45|0.0|0.0|1|0|5.55|5.4|Upward|586|33,848,645
CKP|2022-07-19|2022-07-20|2|5.3|5.25|-0.05|-0.94|0|0|5.45|5.25|Downward|588|35,866,053
CKP|2022-07-21|2022-07-21|1|5.3|5.3|0.0|0.0|1|1|5.3|5.25|Upward|589|1,835,888
CKP|2022-07-22|2022-07-26|3|5.2|5.15|-0.05|-0.96|0|0|5.3|5.15|Downward|592|40,931,149
CKP|2022-07-27|2022-07-27|1|5.35|5.35|0.0|0.0|1|1|5.35|5.15|Upward|593|13,818,184
CKP|2022-08-01|2022-08-01|1|5.3|5.3|0.0|0.0|1|1|5.35|5.25|Downward|594|9,430,318
CKP|2022-08-02|2022-08-02|1|5.35|5.35|0.0|0.0|1|1|5.35|5.25|Upward|595|3,252,596
CKP|2022-08-03|2022-08-04|2|5.2|5.15|-0.05|-0.96|0|0|5.35|5.15|Downward|597|27,827,712
CKP|2022-08-05|2022-08-09|3|5.2|5.45|0.25|4.81|6|2|5.5|5.15|Upward|600|47,198,094
CKP|2022-08-10|2022-08-22|9|5.4|5.1|-0.3|-5.56|-5|-1|5.45|5.05|Downward|608|134,252,681
CKP|2022-08-23|2022-08-23|1|5.2|5.2|0.0|0.0|1|1|5.2|5.05|Upward|609|11,663,230
CKP|2022-08-24|2022-08-24|1|5.1|5.1|0.0|0.0|1|1|5.2|5.1|Downward|610|15,131,426
CKP|2022-08-25|2022-08-26|2|5.15|5.15|0.0|0.0|1|0|5.15|5.1|Upward|612|5,451,469
CKP|2022-08-29|2022-08-29|1|5.1|5.1|0.0|0.0|1|1|5.15|5.05|Downward|613|6,719,502
CKP|2022-08-30|2022-08-30|1|5.15|5.15|0.0|0.0|1|1|5.25|5.1|Upward|614|19,176,498
CKP|2022-08-31|2022-08-31|1|5.1|5.1|0.0|0.0|1|1|5.2|5.1|Downward|615|12,366,300
CKP|2022-09-01|2022-09-07|5|5.15|5.3|0.15|2.91|4|0|5.3|5.1|Upward|620|51,534,703
CKP|2022-09-08|2022-09-12|3|5.25|5.2|-0.05|-0.95|0|0|5.3|5.2|Downward|623|19,471,000
CKP|2022-09-13|2022-09-13|1|5.3|5.3|0.0|0.0|1|1|5.3|5.25|Upward|624|7,655,512
CKP|2022-09-14|2022-09-16|3|5.25|5.15|-0.1|-1.9|-1|-1|5.3|5.1|Downward|627|41,174,897
CKP|2022-09-19|2022-09-20|2|5.25|5.3|0.05|0.95|2|1|5.3|5.2|Upward|629|26,378,554
CKP|2022-09-21|2022-09-21|1|5.2|5.2|0.0|0.0|1|1|5.3|5.2|Downward|630|10,661,654
CKP|2022-09-22|2022-09-22|1|5.4|5.4|0.0|0.0|1|1|5.45|5.2|Upward|631|41,019,836
CKP|2022-09-23|2022-10-03|7|5.35|4.92|-0.43|-8.04|-10|-2|5.45|4.92|Downward|638|139,701,564
CKP|2022-10-04|2022-10-04|1|5.0|5.0|0.0|0.0|1|1|5.05|4.96|Upward|639|12,806,613
CKP|2022-10-05|2022-10-05|1|4.98|4.98|0.0|0.0|1|1|5.05|4.96|Downward|640|5,943,412
CKP|2022-10-06|2022-10-06|1|5.05|5.05|0.0|0.0|1|1|5.05|5.0|Upward|641|8,666,090
CKP|2022-10-07|2022-10-10|2|4.94|4.78|-0.16|-3.24|-7|-4|5.05|4.74|Downward|643|84,923,876
CKP|2022-10-11|2022-10-11|1|4.82|4.82|0.0|0.0|1|1|4.86|4.76|Upward|644|12,109,228
CKP|2022-10-12|2022-10-12|1|4.8|4.8|0.0|0.0|1|1|4.84|4.76|Downward|645|7,351,165
CKP|2022-10-17|2022-10-20|4|4.82|4.96|0.14|2.9|8|2|5.0|4.74|Upward|649|42,858,406
CKP|2022-10-21|2022-10-21|1|4.88|4.88|0.0|0.0|1|1|4.94|4.86|Downward|650|12,751,499
CKP|2022-10-25|2022-10-27|3|4.9|5.0|0.1|2.04|6|2|5.05|4.86|Upward|653|23,327,767
CKP|2022-10-28|2022-10-28|1|4.92|4.92|0.0|0.0|1|1|5.05|4.92|Downward|654|11,412,565
CKP|2022-10-31|2022-11-02|3|4.94|4.98|0.04|0.81|3|1|5.05|4.92|Upward|657|28,917,471
CKP|2022-11-03|2022-11-03|1|4.94|4.94|0.0|0.0|1|1|4.98|4.92|Downward|658|13,609,231
CKP|2022-11-04|2022-11-07|2|4.98|5.05|0.07|1.41|3|1|5.05|4.94|Upward|660|14,968,327
CKP|2022-11-08|2022-11-10|3|5.0|5.0|0.0|0.0|1|0|5.1|4.98|Downward|663|19,677,591
CKP|2022-11-11|2022-11-11|1|5.05|5.05|0.0|0.0|1|1|5.1|5.0|Upward|664|13,730,022
CKP|2022-11-14|2022-11-16|3|4.98|4.84|-0.14|-2.81|-6|-2|5.05|4.82|Downward|667|64,545,743
CKP|2022-11-17|2022-11-21|3|4.9|4.96|0.06|1.22|4|1|4.96|4.84|Upward|670|23,671,357
CKP|2022-11-22|2022-11-28|5|4.88|4.82|-0.06|-1.23|-2|-1|4.96|4.8|Downward|675|35,621,612
CKP|2022-11-29|2022-11-30|2|4.84|4.88|0.04|0.83|3|1|4.88|4.8|Upward|677|7,644,815
CKP|2022-12-01|2022-12-02|2|4.86|4.76|-0.1|-2.06|-4|-2|4.92|4.76|Downward|679|28,452,677
CKP|2022-12-06|2022-12-06|1|4.8|4.8|0.0|0.0|1|1|4.86|4.76|Upward|680|14,756,917
CKP|2022-12-07|2022-12-13|5|4.78|4.68|-0.1|-2.09|-4|-1|4.84|4.66|Downward|684|56,007,746
CKP|2022-12-14|2022-12-14|1|4.72|4.72|0.0|0.0|1|1|4.72|4.66|Upward|685|6,431,831
CKP|2022-12-15|2022-12-15|1|4.66|4.66|0.0|0.0|1|1|4.72|4.64|Downward|686|10,676,441
CKP|2022-12-16|2022-12-19|2|4.68|4.78|0.1|2.14|6|3|4.78|4.62|Upward|688|18,396,247
CKP|2022-12-20|2022-12-22|3|4.66|4.62|-0.04|-0.86|-1|-1|4.76|4.6|Downward|691|36,974,023
CKP|2022-12-23|2022-12-27|3|4.64|4.64|0.0|0.0|1|0|4.68|4.6|Upward|694|24,367,034
CKP|2022-12-28|2023-01-03|5|4.6|4.52|-0.08|-1.74|-3|-1|4.66|4.52|Downward|698|72,153,852
CKP|2023-01-04|2023-01-12|7|4.58|4.74|0.16|3.49|9|1|4.76|4.52|Upward|705|72,062,088
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-8|-2|4.76|4.5|Downward|709|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|5|2|4.66|4.52|Upward|711|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-4|-1|4.64|4.48|Downward|715|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|1|1|4.56|4.52|Upward|716|6,963,352
CKP|2023-01-30|2023-01-31|2|4.52|4.52|0.0|0.0|1|0|4.58|4.5|Downward|718|15,946,162
CKP|2023-02-01|2023-02-01|1|4.56|4.56|0.0|0.0|1|1|4.58|4.52|Upward|719|20,374,772
CKP|2023-02-02|2023-02-02|1|4.54|4.54|0.0|0.0|1|1|4.6|4.5|Downward|720|14,870,177
CKP|2023-02-03|2023-02-07|3|4.56|4.68|0.12|2.63|7|2|4.72|4.54|Upward|723|38,604,423
CKP|2023-02-08|2023-02-13|4|4.66|4.58|-0.08|-1.72|-3|-1|4.74|4.54|Downward|727|64,190,558
DIF|2022-02-14|2022-02-15|2|14.2|14.2|0.0|0.0|1|0|14.3|14.2|Downward|729|11,062,721
DIF|2022-02-17|2022-02-18|2|14.3|14.4|0.1|0.7|2|1|14.5|14.2|Upward|731|38,390,867
DIF|2022-02-21|2022-02-24|4|14.3|14.0|-0.3|-2.1|-2|-1|14.4|13.8|Downward|735|58,949,024
DIF|2022-02-25|2022-03-03|5|14.1|14.2|0.1|0.71|2|0|14.3|14.1|Upward|740|35,678,759
DIF|2022-03-04|2022-03-08|3|14.1|13.8|-0.3|-2.13|-2|-1|14.3|13.5|Downward|743|103,659,001
DIF|2022-03-09|2022-03-09|1|14.0|14.0|0.0|0.0|1|1|14.1|13.8|Upward|744|22,934,691
DIF|2022-03-10|2022-03-14|3|13.9|13.9|0.0|0.0|1|0|14.1|13.8|Downward|747|43,288,218
DIF|2022-03-15|2022-03-22|6|14.0|14.2|0.2|1.43|3|0|14.2|13.9|Upward|753|46,634,909
DIF|2022-03-23|2022-03-23|1|14.1|14.1|0.0|0.0|1|1|14.2|14.1|Downward|754|2,870,701
DIF|2022-03-24|2022-03-28|3|14.2|14.2|0.0|0.0|1|0|14.3|14.1|Upward|757|23,009,323
DIF|2022-03-29|2022-03-31|3|14.1|14.1|0.0|0.0|1|0|14.3|14.0|Downward|760|37,266,496
DIF|2022-04-01|2022-04-01|1|14.2|14.2|0.0|0.0|1|1|14.2|14.1|Upward|761|6,517,554
DIF|2022-04-04|2022-04-04|1|14.1|14.1|0.0|0.0|1|1|14.3|14.1|Downward|762|13,179,505
DIF|2022-04-05|2022-04-08|4|14.2|14.2|0.0|0.0|1|0|14.2|14.1|Upward|765|11,629,053
DIF|2022-04-11|2022-04-12|2|14.1|14.1|0.0|0.0|1|0|14.2|14.1|Downward|767|5,721,862
DIF|2022-04-18|2022-04-20|3|14.2|14.2|0.0|0.0|1|0|14.2|14.1|Upward|770|11,707,181
DIF|2022-04-21|2022-04-21|1|14.1|14.1|0.0|0.0|1|1|14.2|14.1|Downward|771|9,260,594
DIF|2022-04-22|2022-04-25|2|14.2|14.2|0.0|0.0|1|0|14.2|14.1|Upward|773|7,439,479
DIF|2022-04-26|2022-04-26|1|14.1|14.1|0.0|0.0|1|1|14.2|14.1|Downward|774|6,398,651
DIF|2022-04-27|2022-04-27|1|14.2|14.2|0.0|0.0|1|1|14.2|14.1|Upward|775|4,766,776
DIF|2022-04-28|2022-04-29|2|14.1|14.1|0.0|0.0|1|0|14.2|14.1|Downward|777|13,486,507
DIF|2022-05-03|2022-05-05|3|14.2|14.2|0.0|0.0|1|0|14.2|14.1|Upward|779|22,491,339
DIF|2022-05-06|2022-05-06|1|14.1|14.1|0.0|0.0|1|1|14.2|14.1|Downward|780|6,881,118
DIF|2022-05-09|2022-05-13|5|14.3|14.3|0.0|0.0|1|0|14.3|14.1|Upward|785|72,640,747
DIF|2022-05-17|2022-05-25|7|14.0|13.9|-0.1|-0.71|0|0|14.1|13.9|Downward|792|88,481,154
DIF|2022-05-26|2022-05-30|3|14.0|14.1|0.1|0.71|2|0|14.1|13.9|Upward|795|26,091,751
DIF|2022-05-31|2022-06-10|9|14.0|13.5|-0.5|-3.57|-4|-1|14.1|13.2|Downward|803|540,142,419
DIF|2022-06-13|2022-06-13|1|13.6|13.6|0.0|0.0|1|1|13.6|13.5|Upward|804|10,347,241
DIF|2022-06-14|2022-06-16|3|13.5|13.3|-0.2|-1.48|-1|-1|13.6|13.3|Downward|807|95,209,542
DIF|2022-06-17|2022-06-17|1|13.5|13.5|0.0|0.0|1|1|13.5|13.2|Upward|808|41,479,951
DIF|2022-06-20|2022-06-24|5|13.4|13.1|-0.3|-2.24|-2|-1|13.5|13.0|Downward|813|103,156,407
DIF|2022-06-27|2022-06-29|3|13.3|13.5|0.2|1.5|3|1|13.6|13.1|Upward|816|31,870,416
DIF|2022-06-30|2022-06-30|1|13.4|13.4|0.0|0.0|1|1|13.6|13.4|Downward|817|12,981,004
DIF|2022-07-01|2022-07-04|2|13.5|13.5|0.0|0.0|1|0|13.6|13.4|Upward|819|17,206,364
DIF|2022-07-05|2022-07-06|2|13.2|13.1|-0.1|-0.76|0|0|13.5|13.1|Downward|821|42,440,109
DIF|2022-07-07|2022-07-12|4|13.3|13.4|0.1|0.75|2|0|13.4|13.1|Upward|825|24,582,810
DIF|2022-07-14|2022-07-15|2|13.3|13.2|-0.1|-0.75|0|0|13.4|13.2|Downward|827|18,526,593
DIF|2022-07-18|2022-08-04|14|13.3|14.0|0.7|5.26|8|0|14.0|13.2|Upward|839|131,888,462
DIF|2022-08-05|2022-08-05|1|13.7|13.7|0.0|0.0|1|1|14.0|13.7|Downward|840|17,602,712
DIF|2022-08-08|2022-08-08|1|14.0|14.0|0.0|0.0|1|1|14.0|13.7|Upward|841|17,044,757
DIF|2022-08-09|2022-08-10|2|13.9|13.8|-0.1|-0.72|0|0|14.0|13.8|Downward|843|19,887,714
DIF|2022-08-11|2022-08-15|3|13.9|13.9|0.0|0.0|1|0|13.9|13.8|Upward|845|19,146,047
DIF|2022-08-16|2022-08-16|1|13.6|13.6|0.0|0.0|1|1|13.8|13.5|Downward|846|23,109,155
DIF|2022-08-17|2022-08-22|4|13.7|13.7|0.0|0.0|1|0|13.8|13.6|Upward|850|10,556,548
DIF|2022-08-23|2022-08-23|1|13.5|13.5|0.0|0.0|1|1|13.6|13.5|Downward|851|12,338,702
DIF|2022-08-24|2022-08-24|1|13.6|13.6|0.0|0.0|1|1|13.6|13.5|Upward|852|10,367,952
DIF|2022-08-25|2022-08-30|4|13.4|13.4|0.0|0.0|1|0|13.6|13.3|Downward|856|42,970,035
DIF|2022-08-31|2022-09-07|6|13.5|13.7|0.2|1.48|3|0|13.8|13.4|Upward|862|41,481,452
DIF|2022-09-08|2022-09-09|2|13.6|13.6|0.0|0.0|1|0|13.8|13.6|Downward|864|17,320,586
DIF|2022-09-12|2022-09-16|5|13.7|13.8|0.1|0.73|2|0|13.8|13.6|Upward|869|61,342,817
DIF|2022-09-19|2022-09-19|1|13.6|13.6|0.0|0.0|1|1|13.8|13.6|Downward|870|10,202,738
DIF|2022-09-20|2022-09-20|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|871|6,326,296
DIF|2022-09-21|2022-09-21|1|13.6|13.6|0.0|0.0|1|1|13.7|13.6|Downward|872|12,690,171
DIF|2022-09-22|2022-09-22|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|873|4,478,373
DIF|2022-09-23|2022-10-05|9|13.6|13.4|-0.2|-1.47|-1|-1|13.7|13.3|Downward|882|110,344,724
DIF|2022-10-06|2022-10-06|1|13.5|13.5|0.0|0.0|1|1|13.5|13.4|Upward|883|6,413,292
DIF|2022-10-07|2022-10-10|2|13.4|13.4|0.0|0.0|1|0|13.5|13.4|Downward|885|9,983,030
DIF|2022-10-11|2022-10-19|7|13.5|13.6|0.1|0.74|2|0|13.6|13.4|Upward|890|20,935,510
DIF|2022-10-20|2022-10-31|8|13.5|13.5|0.0|0.0|1|0|13.6|13.4|Downward|897|52,775,264
DIF|2022-11-01|2022-11-01|1|13.7|13.7|0.0|0.0|1|1|13.7|13.5|Upward|898|6,176,665
DIF|2022-11-02|2022-11-04|3|13.6|13.4|-0.2|-1.47|-1|-1|13.7|13.4|Downward|901|74,519,595
DIF|2022-11-07|2022-11-10|4|13.5|13.5|0.0|0.0|1|0|13.6|13.4|Upward|905|50,310,468
DIF|2022-11-11|2022-11-18|6|13.4|13.1|-0.3|-2.24|-2|-1|13.4|13.1|Downward|911|91,079,210
DIF|2022-11-21|2022-11-24|4|13.2|13.2|0.0|0.0|1|0|13.3|13.1|Upward|915|21,079,228
DIF|2022-11-25|2022-11-25|1|13.1|13.1|0.0|0.0|1|1|13.2|13.1|Downward|916|3,302,708
DIF|2022-11-28|2022-11-28|1|13.2|13.2|0.0|0.0|1|1|13.2|13.1|Upward|917|2,786,956
DIF|2022-11-29|2022-11-30|2|13.1|13.1|0.0|0.0|1|0|13.2|13.1|Downward|919|7,461,412
DIF|2022-12-01|2022-12-06|4|13.2|13.3|0.1|0.76|2|0|13.3|13.1|Upward|922|24,446,746
DIF|2022-12-07|2022-12-09|3|13.2|13.2|0.0|0.0|1|0|13.3|13.1|Downward|925|30,485,158
DIF|2022-12-13|2022-12-13|1|13.3|13.3|0.0|0.0|1|1|13.3|13.1|Upward|926|7,015,604
DIF|2022-12-14|2022-12-16|3|13.2|13.1|-0.1|-0.76|0|0|13.3|13.1|Downward|929|27,098,343
DIF|2022-12-19|2022-12-19|1|13.2|13.2|0.0|0.0|1|1|13.2|13.1|Upward|930|3,890,222
DIF|2022-12-20|2022-12-20|1|13.1|13.1|0.0|0.0|1|1|13.2|13.1|Downward|931|1,736,699
DIF|2022-12-21|2023-01-04|11|13.2|13.3|0.1|0.76|2|0|13.3|13.1|Upward|941|48,510,404
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|1|0|13.3|13.2|Downward|943|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|5|0|13.7|13.2|Upward|952|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|1|0|13.7|13.6|Downward|955|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|956|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|1|1|13.7|13.5|Downward|957|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|1|1|13.7|13.5|Upward|958|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|1|0|13.7|13.6|Downward|960|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|961|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|1|0|13.7|13.6|Downward|965|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|966|8,569,954
DIF|2023-02-10|2023-02-13|2|13.3|13.3|0.0|0.0|1|0|13.4|13.2|Downward|968|27,112,524
IVL|2022-02-14|2022-02-14|1|50.75|50.75|0.0|0.0|1|1|51.75|50.75|Downward|969|13,006,881
IVL|2022-02-15|2022-02-17|3|51.25|51.25|0.0|0.0|1|0|52.0|50.5|Upward|971|36,642,727
IVL|2022-02-18|2022-02-21|2|49.75|46.0|-3.75|-7.54|-14|-7|51.25|45.75|Downward|973|99,025,653
IVL|2022-02-22|2022-02-23|2|47.25|48.0|0.75|1.59|4|2|48.0|46.0|Upward|975|45,668,797
IVL|2022-02-24|2022-02-28|3|47.0|45.0|-2.0|-4.26|-7|-3|47.75|43.5|Downward|978|82,651,941
IVL|2022-03-01|2022-03-02|2|45.5|46.75|1.25|2.75|6|3|47.0|45.0|Upward|980|49,613,143
IVL|2022-03-03|2022-03-08|4|46.0|42.5|-3.5|-7.61|-13|-4|47.25|41.0|Downward|984|149,361,939
IVL|2022-03-09|2022-03-11|3|43.25|44.5|1.25|2.89|6|2|44.75|41.75|Upward|987|86,908,854
IVL|2022-03-14|2022-03-15|2|44.0|43.25|-0.75|-1.7|-2|-1|44.5|42.75|Downward|989|25,908,496
IVL|2022-03-16|2022-03-17|2|44.25|46.25|2.0|4.52|9|4|47.0|43.5|Upward|991|63,903,935
IVL|2022-03-18|2022-03-21|2|46.0|45.5|-0.5|-1.09|-1|-1|46.75|45.0|Downward|993|34,116,867
IVL|2022-03-22|2022-03-23|2|46.0|46.25|0.25|0.54|2|1|46.75|45.25|Upward|995|32,162,437
IVL|2022-03-24|2022-03-25|2|46.0|45.5|-0.5|-1.09|-1|-1|46.5|45.25|Downward|997|17,340,769
IVL|2022-03-28|2022-03-30|3|45.75|47.0|1.25|2.73|6|2|47.5|45.25|Upward|1000|65,303,981
IVL|2022-03-31|2022-04-04|3|46.5|45.5|-1.0|-2.15|-3|-1|47.0|45.0|Downward|1003|40,885,987
IVL|2022-04-05|2022-04-05|1|46.25|46.25|0.0|0.0|1|1|46.75|45.75|Upward|1004|12,546,110
IVL|2022-04-07|2022-04-07|1|45.0|45.0|0.0|0.0|1|1|46.0|45.0|Downward|1005|12,779,839
IVL|2022-04-08|2022-04-08|1|45.5|45.5|0.0|0.0|1|1|46.0|45.0|Upward|1006|10,522,505
IVL|2022-04-11|2022-04-12|2|45.25|45.25|0.0|0.0|1|0|45.75|44.75|Downward|1008|13,448,602

IVL|2022-11-18|2022-11-18|1|42.5|42.5|0.0|0.0|1|1|42.5|42.25|Upward|1152|4,716,312
IVL|2022-11-21|2022-11-29|7|42.25|41.75|-0.5|-1.18|-1|-1|42.75|41.25|Downward|1159|56,312,011
IVL|2022-11-30|2022-12-01|2|42.5|42.5|0.0|0.0|1|0|43.0|41.75|Upward|1161|23,480,637
IVL|2022-12-02|2022-12-07|4|41.75|40.75|-1.0|-2.4|-3|-1|42.5|40.75|Downward|1164|34,865,974
IVL|2022-12-08|2022-12-08|1|41.0|41.0|0.0|0.0|1|1|41.25|40.5|Upward|1165|7,060,851
IVL|2022-12-09|2022-12-13|3|40.75|40.25|-0.5|-1.23|-1|-1|41.0|40.0|Downward|1167|19,343,033
IVL|2022-12-14|2022-12-14|1|40.5|40.5|0.0|0.0|1|1|40.75|40.25|Upward|1168|4,346,908
IVL|2022-12-15|2022-12-23|7|40.0|39.5|-0.5|-1.25|-1|-1|40.75|39.0|Downward|1175|60,511,933
IVL|2022-12-26|2022-12-30|5|39.75|40.75|1.0|2.52|5|1|41.25|39.5|Upward|1180|56,581,013
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-9|-3|41.0|37.0|Downward|1184|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|16|2|42.75|37.75|Upward|1192|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|1|1|42.25|41.5|Downward|1193|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|1|1|42.5|41.75|Upward|1194|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-6|-2|42.5|40.0|Downward|1198|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|1|0|41.5|40.25|Upward|1200|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|1|1|41.25|40.5|Downward|1201|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|1|1|41.25|40.5|Upward|1202|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|0|0|41.25|40.25|Downward|1204|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|1|1|41.25|39.75|Upward|1205|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|1|1|41.0|40.25|Downward|1206|11,842,657
IVL|2023-02-08|2023-02-09|2|40.75|40.75|0.0|0.0|1|0|41.5|40.25|Upward|1208|22,518,750
IVL|2023-02-10|2023-02-13|2|40.5|40.0|-0.5|-1.23|-1|-1|40.75|39.75|Downward|1210|18,080,401
JASIF|2022-02-14|2022-02-14|1|10.9|10.9|0.0|0.0|1|1|11.0|10.8|Downward|1211|19,365,895
JASIF|2022-02-15|2022-02-22|6|11.0|11.2|0.2|1.82|3|0|11.2|10.9|Upward|1216|107,450,100
JASIF|2022-02-23|2022-02-24|2|11.1|10.9|-0.2|-1.8|-1|-1|11.2|10.9|Downward|1218|74,272,748
JASIF|2022-02-25|2022-03-01|3|11.0|11.3|0.3|2.73|4|1|11.3|10.9|Upward|1221|65,767,468
JASIF|2022-03-02|2022-03-08|5|11.2|10.4|-0.8|-7.14|-7|-2|11.3|10.0|Downward|1226|259,824,265
JASIF|2022-03-09|2022-03-14|4|10.7|10.7|0.0|0.0|1|0|10.8|10.4|Upward|1230|61,623,593
JASIF|2022-03-15|2022-03-15|1|10.6|10.6|0.0|0.0|1|1|10.8|10.6|Downward|1231|13,250,820
JASIF|2022-03-16|2022-03-25|8|10.8|11.0|0.2|1.85|3|0|11.1|10.6|Upward|1239|75,430,726
JASIF|2022-03-28|2022-03-28|1|10.9|10.9|0.0|0.0|1|1|11.0|10.9|Downward|1240|4,388,772
JASIF|2022-03-29|2022-03-29|1|11.0|11.0|0.0|0.0|1|1|11.0|10.9|Upward|1241|3,750,579
JASIF|2022-03-30|2022-03-30|1|10.9|10.9|0.0|0.0|1|1|11.0|10.9|Downward|1242|3,344,154
JASIF|2022-03-31|2022-03-31|1|11.0|11.0|0.0|0.0|1|1|11.0|10.9|Upward|1243|7,720,546
JASIF|2022-04-01|2022-04-01|1|10.9|10.9|0.0|0.0|1|1|11.0|10.9|Downward|1244|3,582,689
JASIF|2022-04-04|2022-04-04|1|11.0|11.0|0.0|0.0|1|1|11.0|10.9|Upward|1245|8,866,642
JASIF|2022-04-05|2022-04-08|4|10.9|10.8|-0.1|-0.92|0|0|11.0|10.8|Downward|1248|46,126,930
JASIF|2022-04-11|2022-04-22|10|10.9|11.0|0.1|0.92|2|0|11.0|10.8|Upward|1255|34,672,881
JASIF|2022-04-25|2022-04-26|2|10.9|10.8|-0.1|-0.92|0|0|11.0|10.8|Downward|1257|30,127,294
JASIF|2022-04-27|2022-05-10|10|10.9|11.0|0.1|0.92|2|0|11.1|10.8|Upward|1265|125,545,810
JASIF|2022-05-11|2022-05-12|2|10.9|10.9|0.0|0.0|1|0|11.1|10.9|Downward|1267|42,138,755
JASIF|2022-05-13|2022-05-18|4|11.0|11.1|0.1|0.91|2|0|11.1|10.9|Upward|1270|53,882,007
JASIF|2022-05-19|2022-05-23|3|11.0|10.8|-0.2|-1.82|-1|-1|11.1|10.8|Downward|1273|65,182,783
JASIF|2022-05-24|2022-05-31|6|10.9|11.0|0.1|0.92|2|0|11.0|10.8|Upward|1279|48,433,639
JASIF|2022-06-01|2022-06-17|13|10.9|10.5|-0.4|-3.67|-3|-1|11.0|10.4|Downward|1291|203,969,047
JASIF|2022-06-20|2022-06-20|1|10.6|10.6|0.0|0.0|1|1|10.6|10.5|Upward|1292|14,435,313
JASIF|2022-06-21|2022-06-22|2|10.5|10.3|-0.2|-1.9|-1|-1|10.6|10.3|Downward|1294|58,777,152
JASIF|2022-06-23|2022-06-28|4|9.25|9.95|0.7|7.57|15|3|9.95|9.2|Upward|1298|642,006,468
JASIF|2022-06-29|2022-07-05|5|9.75|8.8|-0.95|-9.74|-18|-4|9.95|8.8|Downward|1303|475,737,327
JASIF|2022-07-06|2022-07-07|2|8.9|8.9|0.0|0.0|1|0|9.05|8.6|Upward|1305|101,669,045
JASIF|2022-07-08|2022-07-08|1|8.8|8.8|0.0|0.0|1|1|8.9|8.75|Downward|1306|20,374,264
JASIF|2022-07-11|2022-07-14|4|8.85|8.85|0.0|0.0|1|0|8.9|8.75|Upward|1309|27,955,760
JASIF|2022-07-15|2022-07-15|1|8.8|8.8|0.0|0.0|1|1|8.85|8.7|Downward|1310|10,784,246
JASIF|2022-07-18|2022-07-18|1|8.9|8.9|0.0|0.0|1|1|8.9|8.85|Upward|1311|9,640,342
JASIF|2022-07-19|2022-07-21|3|8.85|8.8|-0.05|-0.56|0|0|8.9|8.8|Downward|1314|28,432,242
JASIF|2022-07-22|2022-07-25|2|8.9|8.9|0.0|0.0|1|0|8.9|8.8|Upward|1316|16,195,203
JASIF|2022-07-26|2022-07-27|2|8.85|8.8|-0.05|-0.56|0|0|8.9|8.8|Downward|1318|29,112,938
JASIF|2022-08-01|2022-08-04|4|8.95|9.1|0.15|1.68|4|1|9.15|8.8|Upward|1322|53,030,442
JASIF|2022-08-05|2022-08-09|3|9.05|8.9|-0.15|-1.66|-2|-1|9.15|8.9|Downward|1325|43,264,326
JASIF|2022-08-10|2022-08-17|6|8.95|9.1|0.15|1.68|4|0|9.1|8.9|Upward|1330|103,348,580
JASIF|2022-08-18|2022-09-08|16|9.05|7.6|-1.45|-16.02|-28|-2|9.1|7.15|Downward|1346|590,465,454
JASIF|2022-09-09|2022-09-09|1|8.05|8.05|0.0|0.0|1|1|8.3|7.6|Upward|1347|116,032,412
JASIF|2022-09-12|2022-09-14|3|7.9|7.85|-0.05|-0.63|0|0|8.25|7.75|Downward|1350|101,598,941
JASIF|2022-09-15|2022-09-23|7|8.0|8.45|0.45|5.62|10|1|8.45|7.95|Upward|1357|142,030,128
JASIF|2022-09-26|2022-10-03|6|8.4|8.05|-0.35|-4.17|-6|-1|8.55|8.05|Downward|1363|92,360,797
JASIF|2022-10-04|2022-10-04|1|8.15|8.15|0.0|0.0|1|1|8.2|8.05|Upward|1364|10,855,432
JASIF|2022-10-05|2022-10-12|6|8.1|8.0|-0.1|-1.23|-1|-1|8.2|7.95|Downward|1370|44,431,678
JASIF|2022-10-17|2022-10-18|2|8.1|8.35|0.25|3.09|6|3|8.35|8.0|Upward|1372|28,645,220
JASIF|2022-10-19|2022-10-26|6|8.0|7.9|-0.1|-1.25|-1|-1|8.15|7.8|Downward|1377|95,439,527
JASIF|2022-10-27|2022-10-28|2|8.0|8.0|0.0|0.0|1|0|8.05|7.9|Upward|1379|12,719,691
JASIF|2022-10-31|2022-10-31|1|7.95|7.95|0.0|0.0|1|1|8.05|7.9|Downward|1380|9,766,033
JASIF|2022-11-01|2022-11-04|4|8.0|8.15|0.15|1.88|4|1|8.15|7.95|Upward|1384|27,655,203
JASIF|2022-11-07|2022-11-07|1|8.1|8.1|0.0|0.0|1|1|8.2|8.1|Downward|1385|6,407,477
JASIF|2022-11-08|2022-11-08|1|8.2|8.2|0.0|0.0|1|1|8.2|8.1|Upward|1386|3,176,386
JASIF|2022-11-09|2022-11-11|3|8.15|8.15|0.0|0.0|1|0|8.2|8.1|Downward|1389|26,160,317
JASIF|2022-11-14|2022-11-17|4|8.2|8.7|0.5|6.1|11|2|8.8|8.15|Upward|1393|117,666,385
JASIF|2022-11-18|2022-11-22|3|8.5|8.05|-0.45|-5.29|-8|-3|8.65|8.05|Downward|1396|67,428,802
JASIF|2022-11-23|2022-11-24|2|8.1|8.15|0.05|0.62|2|1|8.15|8.05|Upward|1398|7,839,072
JASIF|2022-11-25|2022-11-30|4|8.1|8.0|-0.1|-1.23|-1|-1|8.15|7.95|Downward|1402|19,531,054
JASIF|2022-12-01|2022-12-02|2|8.05|8.05|0.0|0.0|1|0|8.05|7.95|Upward|1404|16,193,734
JASIF|2022-12-06|2022-12-09|4|8.0|8.0|0.0|0.0|1|0|8.05|7.95|Downward|1408|16,432,500
JASIF|2022-12-13|2022-12-16|4|8.05|8.05|0.0|0.0|1|0|8.1|8.0|Upward|1412|19,932,502
JASIF|2022-12-19|2022-12-19|1|8.0|8.0|0.0|0.0|1|1|8.1|8.0|Downward|1413|3,086,098
JASIF|2022-12-20|2022-12-21|2|8.05|8.05|0.0|0.0|1|0|8.05|8.0|Upward|1415|4,132,295
JASIF|2022-12-22|2022-12-26|3|8.0|8.0|0.0|0.0|1|0|8.1|7.95|Downward|1418|17,969,777
JASIF|2022-12-27|2022-12-27|1|8.05|8.05|0.0|0.0|1|1|8.05|8.0|Upward|1419|1,607,162
JASIF|2022-12-28|2022-12-28|1|8.0|8.0|0.0|0.0|1|1|8.05|8.0|Downward|1420|3,249,547
JASIF|2022-12-29|2023-01-12|11|8.05|8.25|0.2|2.48|5|0|8.3|8.0|Upward|1430|47,932,471
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|1|1|8.25|8.2|Downward|1431|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|1|0|8.25|8.2|Upward|1433|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|1|1|8.25|8.2|Downward|1434|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|1|0|8.25|8.2|Upward|1438|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|0|0|8.25|8.15|Downward|1442|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|2|1|8.25|8.15|Upward|1444|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|1|1|8.25|8.2|Downward|1445|3,117,519
JASIF|2023-02-03|2023-02-08|4|8.25|8.25|0.0|0.0|1|0|8.25|8.2|Upward|1449|12,746,881
JASIF|2023-02-10|2023-02-13|2|8.2|8.2|0.0|0.0|1|0|8.25|8.15|Downward|1451|8,015,731
JMART|2022-02-14|2022-02-14|1|50.0|50.0|0.0|0.0|1|1|51.75|49.5|Downward|1452|11,305,597
JMART|2022-02-15|2022-02-15|1|51.5|51.5|0.0|0.0|1|1|51.75|50.25|Upward|1453|5,453,862
JMART|2022-02-17|2022-02-18|2|50.5|49.75|-0.75|-1.49|-2|-1|52.0|49.75|Downward|1455|10,694,042
JMART|2022-02-21|2022-02-23|3|50.5|54.0|3.5|6.93|15|5|54.25|49.25|Upward|1458|27,368,563
JMART|2022-02-24|2022-02-24|1|52.75|52.75|0.0|0.0|1|1|55.0|52.0|Downward|1459|17,659,939
JMART|2022-02-25|2022-02-28|2|54.0|56.5|2.5|4.63|11|5|56.5|53.0|Upward|1461|24,269,386
JMART|2022-03-01|2022-03-08|6|56.25|50.75|-5.5|-9.78|-21|-4|56.5|48.75|Downward|1467|50,749,677
JMART|2022-03-09|2022-03-09|1|52.75|52.75|0.0|0.0|1|1|52.75|50.25|Upward|1468|7,640,538
JMART|2022-03-10|2022-03-10|1|52.25|52.25|0.0|0.0|1|1|53.75|52.25|Downward|1469|5,445,308
JMART|2022-03-11|2022-03-11|1|53.0|53.0|0.0|0.0|1|1|53.25|51.75|Upward|1470|2,684,489
JMART|2022-03-14|2022-03-15|2|52.5|52.25|-0.25|-0.48|0|0|53.5|52.0|Downward|1472|4,702,322
JMART|2022-03-16|2022-03-21|4|53.75|55.0|1.25|2.33|6|1|55.5|52.75|Upward|1476|32,370,833
JMART|2022-03-22|2022-03-22|1|54.5|54.5|0.0|0.0|1|1|55.5|54.5|Downward|1477|4,003,662
JMART|2022-03-23|2022-03-23|1|55.75|55.75|0.0|0.0|1|1|56.25|55.0|Upward|1478|6,668,578
JMART|2022-03-24|2022-03-25|2|55.5|55.0|-0.5|-0.9|-1|-1|56.0|54.75|Downward|1480|6,500,119
JMART|2022-03-28|2022-04-08|10|56.0|61.25|5.25|9.38|22|2|61.75|55.0|Upward|1489|114,545,576
JMART|2022-04-11|2022-04-11|1|61.0|61.0|0.0|0.0|1|1|61.25|59.75|Downward|1490|6,313,874
JMART|2022-04-12|2022-04-12|1|63.25|63.25|0.0|0.0|1|1|64.0|60.25|Upward|1491|21,018,673
JMART|2022-04-18|2022-04-20|3|62.25|59.25|-3.0|-4.82|-11|-4|63.5|59.0|Downward|1494|31,717,382
JMART|2022-04-21|2022-04-25|3|60.25|61.5|1.25|2.07|6|2|61.75|59.5|Upward|1497|20,947,760
JMART|2022-04-26|2022-04-27|2|60.5|60.25|-0.25|-0.41|0|0|62.5|59.5|Downward|1499|20,910,894
JMART|2022-04-28|2022-04-29|2|61.5|62.5|1.0|1.63|5|2|62.5|60.0|Upward|1501|14,506,713
JMART|2022-05-03|2022-05-09|5|60.75|54.25|-6.5|-10.7|-25|-5|62.5|53.75|Downward|1505|64,378,726
JMART|2022-05-10|2022-05-10|1|57.5|57.5|0.0|0.0|1|1|57.75|53.75|Upward|1506|13,012,373
JMART|2022-05-11|2022-05-12|2|54.75|51.25|-3.5|-6.39|-13|-7|57.25|51.25|Downward|1508|26,199,697
JMART|2022-05-13|2022-05-18|4|51.5|55.0|3.5|6.8|15|3|55.25|51.0|Upward|1511|32,429,379
JMART|2022-05-19|2022-05-19|1|53.0|53.0|0.0|0.0|1|1|54.25|52.75|Downward|1512|9,492,078
JMART|2022-05-20|2022-05-31|8|54.25|60.75|6.5|11.98|27|3|61.25|54.0|Upward|1520|75,023,821
JMART|2022-06-01|2022-06-02|2|59.5|59.0|-0.5|-0.84|-1|-1|61.5|58.5|Downward|1522|16,159,787
JMART|2022-06-06|2022-06-06|1|59.75|59.75|0.0|0.0|1|1|60.0|58.5|Upward|1523|3,095,793
JMART|2022-06-07|2022-06-07|1|58.25|58.25|0.0|0.0|1|1|59.75|58.25|Downward|1524|5,271,342
JMART|2022-06-08|2022-06-08|1|58.5|58.5|0.0|0.0|1|1|59.0|58.0|Upward|1525|3,337,626
JMART|2022-06-09|2022-06-09|1|56.5|56.5|0.0|0.0|1|1|58.25|56.0|Downward|1526|12,080,072
JMART|2022-06-10|2022-06-10|1|57.25|57.25|0.0|0.0|1|1|57.25|55.75|Upward|1527|5,705,532
JMART|2022-06-13|2022-06-13|1|55.25|55.25|0.0|0.0|1|1|56.75|55.25|Downward|1528|6,846,740
JMART|2022-06-14|2022-06-15|2|55.75|56.25|0.5|0.9|3|1|56.5|54.75|Upward|1530|11,499,586
JMART|2022-06-16|2022-06-16|1|55.0|55.0|0.0|0.0|1|1|57.25|54.75|Downward|1531|8,797,318
JMART|2022-06-17|2022-06-17|1|55.5|55.5|0.0|0.0|1|1|56.0|53.5|Upward|1532|10,720,299
JMART|2022-06-20|2022-06-20|1|52.5|52.5|0.0|0.0|1|1|55.5|52.25|Downward|1533|11,822,325
JMART|2022-06-21|2022-06-21|1|55.0|55.0|0.0|0.0|1|1|55.25|53.5|Upward|1534|8,345,384
JMART|2022-06-22|2022-06-22|1|53.5|53.5|0.0|0.0|1|1|55.0|53.25|Downward|1535|8,720,773
JMART|2022-06-23|2022-06-28|4|53.75|55.0|1.25|2.33|6|1|56.0|53.25|Upward|1539|24,218,155
JMART|2022-06-29|2022-06-30|2|54.0|51.0|-3.0|-5.56|-11|-6|55.25|50.75|Downward|1541|35,178,714
JMART|2022-07-01|2022-07-01|1|51.75|51.75|0.0|0.0|1|1|52.25|49.25|Upward|1542|18,258,697
JMART|2022-07-04|2022-07-06|3|51.0|45.0|-6.0|-11.76|-23|-8|51.75|44.5|Downward|1545|62,443,861
JMART|2022-07-07|2022-07-07|1|46.75|46.75|0.0|0.0|1|1|46.75|45.0|Upward|1546|10,821,051
JMART|2022-07-08|2022-07-14|5|45.75|44.0|-1.75|-3.83|-6|-2|47.5|43.5|Downward|1550|43,090,551
JMART|2022-07-15|2022-07-15|1|44.75|44.75|0.0|0.0|1|1|45.25|43.75|Upward|1551|8,848,080
JMART|2022-07-18|2022-07-19|2|44.5|43.75|-0.75|-1.69|-2|-1|45.25|42.75|Downward|1553|19,010,681
JMART|2022-07-20|2022-07-25|4|45.25|48.0|2.75|6.08|12|3|48.25|44.25|Upward|1557|37,810,758
JMART|2022-07-26|2022-07-26|1|47.5|47.5|0.0|0.0|1|1|48.25|47.25|Downward|1558|3,610,571
JMART|2022-07-27|2022-08-02|5|47.75|49.75|2.0|4.19|9|1|50.25|46.75|Upward|1561|24,815,666
JMART|2022-08-03|2022-08-04|2|49.25|49.25|0.0|0.0|1|0|50.0|48.5|Downward|1563|16,950,708
JMART|2022-08-05|2022-08-10|4|49.5|51.0|1.5|3.03|7|1|51.25|49.0|Upward|1567|23,281,228
JMART|2022-08-11|2022-08-11|1|50.5|50.5|0.0|0.0|1|1|53.25|50.0|Downward|1568|20,173,228
JMART|2022-08-15|2022-08-15|1|50.75|50.75|0.0|0.0|1|1|51.25|50.25|Upward|1569|5,636,966
JMART|2022-08-16|2022-08-16|1|49.5|49.5|0.0|0.0|1|1|51.25|49.25|Downward|1570|6,599,255
JMART|2022-08-17|2022-08-18|2|49.75|50.5|0.75|1.51|4|2|51.0|48.75|Upward|1572|9,384,287
JMART|2022-08-19|2022-08-22|2|49.25|49.0|-0.25|-0.51|0|0|50.75|48.75|Downward|1574|9,653,111
JMART|2022-08-23|2022-08-23|1|50.25|50.25|0.0|0.0|1|1|50.25|49.0|Upward|1575|6,231,441
JMART|2022-08-24|2022-08-24|1|50.0|50.0|0.0|0.0|1|1|50.25|49.25|Downward|1576|3,375,725
JMART|2022-08-25|2022-08-26|2|51.75|52.25|0.5|0.97|3|1|52.25|50.25|Upward|1578|19,536,674
JMART|2022-08-29|2022-08-29|1|51.0|51.0|0.0|0.0|1|1|51.5|50.5|Downward|1579|10,013,596
JMART|2022-08-30|2022-09-01|3|51.5|52.75|1.25|2.43|6|2|53.25|50.75|Upward|1582|25,792,923
JMART|2022-09-02|2022-09-05|2|52.25|51.5|-0.75|-1.44|-2|-1|53.0|50.75|Downward|1584|11,362,995
JMART|2022-09-06|2022-09-06|1|52.5|52.5|0.0|0.0|1|1|53.0|51.0|Upward|1585|6,790,686
JMART|2022-09-07|2022-09-07|1|52.25|52.25|0.0|0.0|1|1|52.75|51.75|Downward|1586|4,700,980
JMART|2022-09-08|2022-09-13|4|52.75|54.0|1.25|2.37|6|1|54.75|52.5|Upward|1590|24,343,752
JMART|2022-09-14|2022-09-14|1|53.75|53.75|0.0|0.0|1|1|53.75|53.0|Downward|1591|4,810,656
JMART|2022-09-15|2022-09-15|1|54.0|54.0|0.0|0.0|1|1|54.5|53.5|Upward|1592|6,232,881
JMART|2022-09-16|2022-09-19|2|52.75|51.25|-1.5|-2.84|-5|-3|53.75|51.25|Downward|1594|14,640,614
JMART|2022-09-20|2022-09-20|1|51.5|51.5|0.0|0.0|1|1|52.0|51.5|Upward|1595|3,630,981
JMART|2022-09-21|2022-09-21|1|50.25|50.25|0.0|0.0|1|1|51.75|50.0|Downward|1596|5,556,798
JMART|2022-09-22|2022-09-22|1|51.5|51.5|0.0|0.0|1|1|51.75|50.0|Upward|1597|7,044,441
JMART|2022-09-23|2022-09-29|5|50.25|46.25|-4.0|-7.96|-15|-3|51.5|46.25|Downward|1602|37,944,840
JMART|2022-09-30|2022-09-30|1|46.5|46.5|0.0|0.0|1|1|47.25|45.75|Upward|1603|6,640,670
JMART|2022-10-03|2022-10-03|1|44.0|44.0|0.0|0.0|1|1|46.75|43.75|Downward|1604|10,620,331
JMART|2022-10-04|2022-10-05|2|46.5|47.25|0.75|1.61|4|2|48.25|45.25|Upward|1606|15,850,761
JMART|2022-10-06|2022-10-10|3|46.75|43.75|-3.0|-6.42|-11|-4|47.75|43.75|Downward|1609|16,589,622
JMART|2022-10-11|2022-10-18|6|44.5|47.25|2.75|6.18|12|2|47.5|42.75|Upward|1613|20,695,947
JMART|2022-10-19|2022-10-19|1|46.5|46.5|0.0|0.0|1|1|47.5|46.25|Downward|1614|3,970,630
JMART|2022-10-20|2022-10-20|1|47.25|47.25|0.0|0.0|1|1|47.25|46.0|Upward|1615|3,524,207
JMART|2022-10-21|2022-10-21|1|46.5|46.5|0.0|0.0|1|1|47.5|46.5|Downward|1616|2,116,117
JMART|2022-10-25|2022-10-25|1|47.0|47.0|0.0|0.0|1|1|47.5|46.75|Upward|1617|2,489,389
JMART|2022-10-26|2022-10-26|1|46.75|46.75|0.0|0.0|1|1|48.0|46.75|Downward|1618|3,176,289
JMART|2022-10-27|2022-10-27|1|47.0|47.0|0.0|0.0|1|1|47.5|46.75|Upward|1619|1,599,539
JMART|2022-10-28|2022-10-31|2|46.25|45.25|-1.0|-2.16|-3|-2|47.25|45.0|Downward|1621|6,844,883
JMART|2022-11-01|2022-11-01|1|46.0|46.0|0.0|0.0|1|1|46.25|45.25|Upward|1622|2,636,344
JMART|2022-11-02|2022-11-03|2|45.75|44.75|-1.0|-2.19|-3|-2|46.5|44.75|Downward|1624|5,774,138
JMART|2022-11-04|2022-11-04|1|45.0|45.0|0.0|0.0|1|1|45.5|44.75|Upward|1625|2,213,317
JMART|2022-11-07|2022-11-07|1|43.25|43.25|0.0|0.0|1|1|45.25|42.75|Downward|1626|11,374,029
JMART|2022-11-08|2022-11-15|6|44.0|47.5|3.5|7.95|15|2|48.25|43.5|Upward|1632|38,253,579
JMART|2022-11-16|2022-11-22|5|46.0|41.0|-5.0|-10.87|-19|-4|47.0|40.0|Downward|1637|43,884,588
JMART|2022-11-23|2022-11-25|3|42.0|43.0|1.0|2.38|5|1|43.75|41.25|Upward|1640|16,173,087
JMART|2022-11-28|2022-11-29|2|42.75|42.0|-0.75|-1.75|-2|-1|42.75|41.75|Downward|1642|8,845,827
JMART|2022-11-30|2022-12-01|2|43.75|44.25|0.5|1.14|3|1|45.0|41.5|Upward|1644|20,834,696
JMART|2022-12-02|2022-12-08|5|44.0|42.25|-1.75|-3.98|-6|-2|44.5|41.75|Downward|1648|21,537,427
JMART|2022-12-09|2022-12-09|1|42.5|42.5|0.0|0.0|1|1|43.0|41.5|Upward|1649|7,853,409
JMART|2022-12-13|2022-12-13|1|42.0|42.0|0.0|0.0|1|1|42.75|41.75|Downward|1650|3,500,724
JMART|2022-12-14|2022-12-14|1|42.25|42.25|0.0|0.0|1|1|42.5|42.0|Upward|1651|1,948,040
JMART|2022-12-15|2022-12-15|1|40.5|40.5|0.0|0.0|1|1|42.0|40.5|Downward|1652|10,760,779
JMART|2022-12-16|2022-12-19|2|40.75|41.0|0.25|0.61|2|1|41.5|40.0|Upward|1654|8,369,164
JMART|2022-12-20|2022-12-20|1|40.0|40.0|0.0|0.0|1|1|41.5|39.5|Downward|1655|7,189,408
JMART|2022-12-21|2022-12-22|2|40.25|40.5|0.25|0.62|2|1|41.0|40.25|Upward|1657|4,223,468
JMART|2022-12-23|2022-12-23|1|39.25|39.25|0.0|0.0|1|1|40.25|39.0|Downward|1658|6,170,257
JMART|2022-12-26|2022-12-29|4|39.5|41.5|2.0|5.06|9|2|41.5|39.25|Upward|1662|19,466,777
JMART|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|1|1|41.75|40.75|Downward|1663|6,010,236
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|1|1|41.25|40.75|Upward|1664|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-2|-1|41.5|40.0|Downward|1666|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|10|1|43.5|40.0|Upward|1672|44,921,819
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-24|-3|42.75|35.25|Downward|1681|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|1|1|37.5|36.0|Upward|1682|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|1|1|38.0|36.5|Downward|1683|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|2|0|38.25|36.5|Upward|1686|17,299,441
JMART|2023-02-03|2023-02-13|7|37.25|33.25|-4.0|-10.74|-15|-3|37.75|33.0|Downward|1693|71,781,151
JMT|2022-02-14|2022-02-14|1|61.75|61.75|0.0|0.0|1|1|62.75|59.75|Downward|1694|8,569,209
JMT|2022-02-15|2022-02-15|1|63.5|63.5|0.0|0.0|1|1|63.5|61.75|Upward|1695|6,380,200
JMT|2022-02-17|2022-02-18|2|62.75|62.75|0.0|0.0|1|0|64.0|62.25|Downward|1697|8,092,647
JMT|2022-02-21|2022-02-23|3|63.75|67.25|3.5|5.49|15|5|67.75|62.25|Upward|1700|38,330,131
JMT|2022-02-24|2022-02-24|1|67.0|67.0|0.0|0.0|1|1|68.75|65.75|Downward|1701|28,289,250
JMT|2022-02-25|2022-03-01|3|67.5|68.0|0.5|0.74|3|1|68.75|66.75|Upward|1704|25,078,333
JMT|2022-03-02|2022-03-08|5|67.5|64.0|-3.5|-5.19|-13|-3|68.25|62.25|Downward|1709|44,526,623
JMT|2022-03-09|2022-03-09|1|66.25|66.25|0.0|0.0|1|1|66.5|63.5|Upward|1710|7,814,375
JMT|2022-03-10|2022-03-14|3|66.0|65.5|-0.5|-0.76|-1|-1|68.0|64.5|Downward|1713|22,698,924
JMT|2022-03-15|2022-03-23|7|65.75|69.75|4.0|6.08|17|2|70.25|65.25|Upward|1720|65,721,180
JMT|2022-03-24|2022-03-25|2|69.25|68.5|-0.75|-1.08|-2|-1|69.75|67.75|Downward|1722|9,605,660
JMT|2022-03-28|2022-04-07|9|69.5|79.75|10.25|14.75|42|4|80.25|68.25|Upward|1730|106,597,277
JMT|2022-04-08|2022-04-08|1|79.5|79.5|0.0|0.0|1|1|80.25|78.5|Downward|1731|9,065,504
JMT|2022-04-11|2022-04-12|2|79.75|84.5|4.75|5.96|20|10|86.25|78.5|Upward|1733|32,848,568
JMT|2022-04-18|2022-04-18|1|82.5|82.5|0.0|0.0|1|1|84.0|81.75|Downward|1734|15,547,699

In [18]:
os.chdir("C:\\users\\user\\onedrive\\a7\\Ad hoc")
%pwd

'C:\\users\\user\\onedrive\\a7\\Ad hoc'

### call rails runner db/crt_sales.rb

In [19]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-13' AND t.status IN ("B","I", "O", "S")
ORDER BY a.name

In [20]:
df = pd.read_sql(sql, conlite)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('chg_acc = to_price - fm_price',inplace=True)
df['%chg_acc'] = round(df['chg_acc']/df['fm_price']*100,2)
df

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,status,market,chg_acc,%chg_acc
0,BANPU,2023-02-13,2023-02-13,11.10,11.10,90540091,11.20,10.90,B,SET50,0.00,0.00
1,CK,2023-02-13,2023-02-13,22.30,22.30,2398287,22.30,22.00,O,SET100,0.00,0.00
2,CKP,2023-02-08,2023-02-13,4.66,4.58,64190558,4.74,4.54,O,SET100,-0.08,-1.72
3,DIF,2023-02-10,2023-02-13,13.30,13.30,27112524,13.40,13.20,I,SET,0.00,0.00
4,IVL,2023-02-10,2023-02-13,40.50,40.00,18080401,40.75,39.75,I,SET50,-0.50,-1.23
5,JASIF,2023-02-10,2023-02-13,8.20,8.20,8015731,8.25,8.15,I,SET,0.00,0.00
6,JMART,2023-02-03,2023-02-13,37.25,33.25,71781151,37.75,33.00,I,SET50,-4.00,-10.74
7,JMT,2023-02-10,2023-02-13,50.50,49.50,35100334,52.00,48.75,I,SET50,-1.00,-1.98
8,KCE,2023-02-13,2023-02-13,48.00,48.00,16263448,48.25,46.75,B,SET100,0.00,0.00
9,MC,2023-02-13,2023-02-13,12.10,12.10,2731504,12.50,12.10,O,sSET,0.00,0.00
10,MEGA,2023-02-10,2023-02-13,51.50,50.75,4106884,52.00,50.00,O,SET100,-0.75,-1.46
11,ORI,2023-02-13,2023-02-13,11.80,11.80,7001060,12.00,11.70,I,SET100,0.00,0.00
12,PTT,2023-02-09,2023-02-13,32.50,32.25,90879375,32.75,32.25,O,SET50,-0.25,-0.77
13,RCL,2023-02-13,2023-02-13,29.50,29.50,4790203,30.75,29.25,B,SET100,0.00,0.00
14,SAT,2023-02-07,2023-02-13,21.50,20.90,3877147,21.70,20.70,O,SET,-0.60,-2.79
15,SINGER,2023-02-10,2023-02-13,26.75,26.50,6268152,27.50,26.25,I,SET100,-0.25,-0.93
16,TCAP,2023-02-08,2023-02-13,42.75,42.75,4890441,43.00,42.50,O,SET100,0.00,0.00
17,TMT,2023-02-13,2023-02-13,8.05,8.05,288153,8.10,8.00,S,SET,0.00,0.00
18,TTB,2023-02-13,2023-02-13,1.41,1.41,153475351,1.42,1.39,O,SET50,0.00,0.00
19,WHAIR,2023-02-13,2023-02-13,7.95,7.95,192301,7.95,7.80,I,SET,0.00,0.00