In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 16), datetime.date(2023, 2, 15))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-16
yesterday: 2023-02-15 00:00:00

In [3]:
yesterday = yesterday.date()
a_year_ago = yesterday - timedelta(days=365)
yesterday, a_year_ago

(datetime.date(2023, 2, 15), datetime.date(2022, 2, 15))

### Restart and Run All Cells

In [4]:
#cols = 'fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','chg_acc':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','%chg_acc':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

In [5]:
pd.read_sql_query('SELECT COUNT(*) AS records FROM sales', conlite)

   records
0     2015

In [6]:
sqlDel = """DELETE FROM sales"""
rp = conlite.execute(sqlDel)
rp.rowcount

2310

In [7]:
sql = """
SELECT name
FROM orders 
ORDER BY name
"""
df = pd.read_sql(sql, conlite)

names = df['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASK', 'BANPU', 'CK', 'CKP', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MC', 'MEGA', 'ORI', 'PTT', 'RCL', 'SAT', 'SINGER', 'TCAP', 'TMT', 'TTB', 'WHAIR'"

In [8]:
len(in_p.split(','))

21

### Get past one year data

In [9]:
sql = """
SELECT name, date, price, qty, maxp, minp 
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (a_year_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-02-15' AND name IN ('ASK', 'BANPU', 'CK', 'CKP', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MC', 'MEGA', 'ORI', 'PTT', 'RCL', 'SAT', 'SINGER', 'TCAP', 'TMT', 'TTB', 'WHAIR')
ORDER BY name, date

In [10]:
df = pd.read_sql(sql, const)
df.sample(5)

       name        date  price       qty   maxp  minp
838     CKP  2022-08-19   5.10   7788775   5.15   5.1
1370    IVL  2022-10-28  41.75  21518571  42.25  41.5
3494    RCL  2022-07-26  36.75   1865550  37.25  36.5
481      CK  2022-02-24  20.20   8330697  21.00  20.1
4990  WHAIR  2022-09-21   7.40     40300   7.45   7.4

In [11]:
data_path = "../data/"
file_name = "Yearly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df.to_csv(output_file, header=True, index=False)
df.to_csv(osd_file, header=True, index=False)

### Create monitors from orders

In [12]:
sql = """
SELECT name,trade 
FROM orders 
WHERE name IN (%s)
ORDER BY name
"""
sql = sql % in_p
orders = pd.read_sql(sql, conlite)
orders.set_index(['name'],inplace=True)
orders

       trade
name
ASK        B
BANPU      B
CK         B
CKP        B
DIF        S
IVL        S
JASIF      S
JMART      B
JMT        B
KCE        B
MC         B
MEGA       B
ORI        S
PTT        B
RCL        B
SAT        B
SINGER     B
TCAP       B
TMT        S
TTB        B
WHAIR      S

In [13]:
file_name = "monitors.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
osd_file = osd_path + file_name

orders.to_csv(data_file, header=None)
orders.to_csv(output_file)
orders.to_csv(osd_file, header=True, index=False)

In [14]:
sql = """
SELECT trade, COUNT(*) AS items 
FROM orders
GROUP BY trade
ORDER BY trade
"""
grp = pd.read_sql(sql, conlite)
grp

  trade  items
0     B     15
1     S      6

### Call ruby ruby\crt-sales.rb

In [15]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Ad hoc'

In [16]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [17]:
!ruby ruby\\crt-sales.rb

ruby/../Data/Yearly-Price-by-Name.csv
name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,trend,nbr,ttl_qty
ASK|2022-02-15|2022-02-15|1|43.5|43.5|0.0|0.0|1|1|44.25|43.0||2|628,767
ASK|2022-02-17|2022-02-17|1|44.75|44.75|0.0|0.0|1|1|45.0|44.0|Upward|3|1,297,147
ASK|2022-02-18|2022-02-18|1|44.5|44.5|0.0|0.0|1|1|44.75|44.0|Downward|4|380,490
ASK|2022-02-21|2022-02-23|3|45.0|46.5|1.5|3.33|7|2|48.0|44.25|Upward|7|5,763,452
ASK|2022-02-24|2022-02-24|1|45.75|45.75|0.0|0.0|1|1|47.0|44.75|Downward|8|1,077,191
ASK|2022-02-25|2022-02-28|2|47.0|49.0|2.0|4.26|9|4|49.0|45.25|Upward|10|3,991,436
ASK|2022-03-01|2022-03-08|6|48.75|44.25|-4.5|-9.23|-17|-3|49.5|42.25|Downward|16|4,888,704
ASK|2022-03-09|2022-03-10|2|46.0|46.0|0.0|0.0|1|0|47.5|43.75|Upward|18|3,008,196
ASK|2022-03-11|2022-03-14|2|45.25|44.5|-0.75|-1.66|-2|-1|46.0|44.0|Downward|20|1,497,100
ASK|2022-03-15|2022-03-17|3|45.0|45.75|0.75|1.67|4|1|46.5|44.25|Upward|23|1,264,457
ASK|2022-03-18|2022-03-25|6|45.5|44.0|-1.5|-3.3|-5|-1|46.0|44.0|Downward|29|4,145,777
ASK|2022-03-28|2022-03-31|4|44.5|48.0|3.5|7.87|15|3|48.0|44.0|Upward|33|6,734,575
ASK|2022-04-01|2022-04-07|5|45.75|44.25|-1.5|-3.28|-5|-1|47.5|44.25|Downward|37|4,883,785
ASK|2022-04-08|2022-04-08|1|44.75|44.75|0.0|0.0|1|1|45.0|44.5|Upward|38|216,281
ASK|2022-04-11|2022-04-18|6|44.5|44.25|-0.25|-0.56|0|0|45.0|44.25|Downward|41|1,125,419
ASK|2022-04-19|2022-04-21|3|44.75|45.25|0.5|1.12|3|1|45.5|44.5|Upward|44|1,936,306
ASK|2022-04-22|2022-04-25|2|44.75|43.25|-1.5|-3.35|-5|-3|45.5|43.0|Downward|46|2,631,718
ASK|2022-04-26|2022-04-26|1|44.25|44.25|0.0|0.0|1|1|44.25|43.5|Upward|47|1,446,564
ASK|2022-04-27|2022-04-28|2|43.5|43.0|-0.5|-1.15|-1|-1|44.0|42.0|Downward|49|2,089,021
ASK|2022-04-29|2022-04-29|1|43.5|43.5|0.0|0.0|1|1|43.5|42.0|Upward|50|1,365,072
ASK|2022-05-03|2022-05-09|5|42.0|37.75|-4.25|-10.12|-16|-4|43.5|36.0|Downward|54|9,925,210
ASK|2022-05-10|2022-05-10|1|40.5|40.5|0.0|0.0|1|1|41.5|37.75|Upward|55|4,080,604
ASK|2022-05-11|2022-05-12|2|39.75|38.0|-1.75|-4.4|-6|-3|40.5|37.75|Downward|57|2,526,097
ASK|2022-05-13|2022-05-18|4|40.25|43.0|2.75|6.83|12|3|43.0|38.25|Upward|60|6,294,453
ASK|2022-05-19|2022-05-19|1|40.75|40.75|0.0|0.0|1|1|42.25|40.5|Downward|61|1,360,145
ASK|2022-05-20|2022-05-20|1|42.0|42.0|0.0|0.0|1|1|42.5|40.75|Upward|62|1,162,562
ASK|2022-05-23|2022-05-25|3|41.75|41.25|-0.5|-1.2|-1|-1|42.5|41.0|Downward|65|1,462,685
ASK|2022-05-26|2022-05-30|3|41.5|43.25|1.75|4.22|8|2|43.25|41.0|Upward|68|2,761,998
ASK|2022-05-31|2022-06-07|6|42.25|39.0|-3.25|-7.69|-12|-2|43.5|39.0|Downward|73|11,699,787
ASK|2022-06-08|2022-06-08|1|40.5|40.5|0.0|0.0|1|1|40.5|39.25|Upward|74|1,078,282
ASK|2022-06-09|2022-06-09|1|38.75|38.75|0.0|0.0|1|1|40.25|38.25|Downward|75|3,560,611
ASK|2022-06-10|2022-06-10|1|39.0|39.0|0.0|0.0|1|1|39.5|38.0|Upward|76|1,096,966
ASK|2022-06-13|2022-06-13|1|37.0|37.0|0.0|0.0|1|1|37.75|36.5|Downward|77|3,310,090
ASK|2022-06-14|2022-06-14|1|37.25|37.25|0.0|0.0|1|1|37.25|36.25|Upward|78|1,526,655
ASK|2022-06-15|2022-06-16|2|35.5|33.25|-2.25|-6.34|-8|-4|37.0|33.25|Downward|80|5,695,095
ASK|2022-06-17|2022-06-20|2|33.75|34.75|1.0|2.96|5|2|34.75|32.75|Upward|82|2,878,191
ASK|2022-06-21|2022-06-22|2|33.75|33.25|-0.5|-1.48|-1|-1|34.75|32.75|Downward|84|1,779,888
ASK|2022-06-23|2022-06-27|3|34.25|34.25|0.0|0.0|1|0|35.0|33.0|Upward|87|1,760,971
ASK|2022-06-28|2022-07-05|6|33.5|28.5|-5.0|-14.93|-19|-4|34.0|28.5|Downward|93|8,516,125
ASK|2022-07-06|2022-07-07|2|29.75|31.25|1.5|5.04|7|3|31.5|28.25|Upward|95|3,013,561
ASK|2022-07-08|2022-07-08|1|30.25|30.25|0.0|0.0|1|1|31.5|30.0|Downward|96|1,331,379
ASK|2022-07-11|2022-07-11|1|30.75|30.75|0.0|0.0|1|1|31.0|30.0|Upward|97|654,217
ASK|2022-07-12|2022-07-12|1|30.25|30.25|0.0|0.0|1|1|31.0|30.25|Downward|98|828,393
ASK|2022-07-14|2022-07-14|1|30.5|30.5|0.0|0.0|1|1|31.0|30.0|Upward|99|614,196
ASK|2022-07-15|2022-07-15|1|30.0|30.0|0.0|0.0|1|1|30.5|29.5|Downward|100|664,132
ASK|2022-07-18|2022-07-25|6|31.25|36.0|4.75|15.2|20|3|36.0|30.25|Upward|106|9,433,293
ASK|2022-07-26|2022-07-26|1|35.75|35.75|0.0|0.0|1|1|36.25|35.0|Downward|107|1,594,906
ASK|2022-07-27|2022-08-01|4|36.0|37.5|1.5|4.17|7|1|37.5|35.0|Upward|109|1,826,313
ASK|2022-08-02|2022-08-04|3|36.75|36.5|-0.25|-0.68|0|0|37.5|34.75|Downward|112|3,662,467
ASK|2022-08-05|2022-08-05|1|37.75|37.75|0.0|0.0|1|1|38.0|36.75|Upward|113|1,253,637
ASK|2022-08-08|2022-08-08|1|37.5|37.5|0.0|0.0|1|1|37.75|37.0|Downward|114|218,020
ASK|2022-08-09|2022-08-09|1|37.75|37.75|0.0|0.0|1|1|37.75|35.5|Upward|115|1,220,703
ASK|2022-08-10|2022-08-16|5|36.75|34.75|-2.0|-5.44|-7|-2|37.25|34.25|Downward|119|4,693,293
ASK|2022-08-17|2022-08-19|3|36.5|38.25|1.75|4.79|8|2|41.5|34.5|Upward|122|11,914,073
ASK|2022-08-22|2022-08-22|1|37.5|37.5|0.0|0.0|1|1|39.0|37.25|Downward|123|2,308,143
ASK|2022-08-23|2022-08-23|1|37.75|37.75|0.0|0.0|1|1|38.75|36.75|Upward|124|2,246,619
ASK|2022-08-24|2022-08-30|5|37.25|34.75|-2.5|-6.71|-9|-2|38.0|34.5|Downward|129|14,226,082
ASK|2022-08-31|2022-08-31|1|35.75|35.75|0.0|0.0|1|1|35.75|34.75|Upward|130|1,495,731
ASK|2022-09-01|2022-09-01|1|34.5|34.5|0.0|0.0|1|1|35.25|34.25|Downward|131|1,287,282
ASK|2022-09-02|2022-09-02|1|35.0|35.0|0.0|0.0|1|1|35.5|34.25|Upward|132|780,407
ASK|2022-09-05|2022-09-07|3|34.5|34.25|-0.25|-0.72|0|0|35.0|34.0|Downward|135|1,618,284
ASK|2022-09-08|2022-09-14|5|35.0|37.25|2.25|6.43|10|2|37.25|34.25|Upward|140|7,472,629
ASK|2022-09-15|2022-09-19|3|36.5|35.75|-0.75|-2.05|-2|-1|37.75|35.75|Downward|143|2,282,379
ASK|2022-09-20|2022-09-20|1|36.0|36.0|0.0|0.0|1|1|36.25|35.25|Upward|144|789,165
ASK|2022-09-21|2022-10-03|9|35.75|31.0|-4.75|-13.29|-18|-2|35.75|30.75|Downward|153|9,546,320
ASK|2022-10-04|2022-10-04|1|32.5|32.5|0.0|0.0|1|1|32.75|31.0|Upward|154|1,753,881
ASK|2022-10-05|2022-10-05|1|31.25|31.25|0.0|0.0|1|1|32.75|31.25|Downward|155|729,663
ASK|2022-10-06|2022-10-06|1|32.0|32.0|0.0|0.0|1|1|32.75|31.5|Upward|156|935,700
ASK|2022-10-07|2022-10-10|2|31.25|29.5|-1.75|-5.6|-6|-3|32.25|29.5|Downward|158|2,516,064
ASK|2022-10-11|2022-10-18|6|30.75|33.25|2.5|8.13|11|1|33.5|30.0|Upward|162|3,487,209
ASK|2022-10-19|2022-10-19|1|32.75|32.75|0.0|0.0|1|1|33.25|32.0|Downward|163|935,036
ASK|2022-10-20|2022-10-20|1|33.0|33.0|0.0|0.0|1|1|33.0|32.25|Upward|164|181,514
ASK|2022-10-21|2022-10-25|3|32.0|31.75|-0.25|-0.78|0|0|33.25|31.75|Downward|166|1,644,729
ASK|2022-10-26|2022-10-27|2|32.0|33.25|1.25|3.91|6|3|33.75|31.75|Upward|168|5,846,729
ASK|2022-10-28|2022-10-31|2|33.0|32.5|-0.5|-1.52|-1|-1|33.25|32.25|Downward|170|2,580,336
ASK|2022-11-01|2022-11-01|1|33.0|33.0|0.0|0.0|1|1|33.5|32.5|Upward|171|527,534
ASK|2022-11-02|2022-11-03|2|32.75|32.75|0.0|0.0|1|0|33.0|32.5|Downward|173|1,331,121
ASK|2022-11-04|2022-11-04|1|33.0|33.0|0.0|0.0|1|1|33.25|32.75|Upward|174|1,500,856
ASK|2022-11-07|2022-11-07|1|32.75|32.75|0.0|0.0|1|1|33.75|32.75|Downward|175|2,219,311
ASK|2022-11-08|2022-11-11|4|33.0|36.0|3.0|9.09|13|3|36.25|32.75|Upward|179|7,008,785
ASK|2022-11-14|2022-11-14|1|35.25|35.25|0.0|0.0|1|1|36.0|35.0|Downward|180|3,785,715
ASK|2022-11-15|2022-11-15|1|35.75|35.75|0.0|0.0|1|1|35.75|35.0|Upward|181|1,933,159
ASK|2022-11-16|2022-11-17|2|35.0|33.75|-1.25|-3.57|-4|-2|35.75|33.5|Downward|183|3,349,461
ASK|2022-11-18|2022-11-18|1|34.5|34.5|0.0|0.0|1|1|34.5|33.5|Upward|184|1,050,414
ASK|2022-11-21|2022-11-22|2|34.0|34.0|0.0|0.0|1|0|34.75|33.5|Downward|186|960,510
ASK|2022-11-23|2022-11-23|1|34.5|34.5|0.0|0.0|1|1|34.75|33.75|Upward|187|802,308
ASK|2022-11-24|2022-11-29|4|34.25|34.25|0.0|0.0|1|0|34.75|34.0|Downward|191|1,371,569
ASK|2022-11-30|2022-12-08|7|35.25|38.0|2.75|7.8|12|1|38.5|34.0|Upward|197|11,593,152
ASK|2022-12-09|2022-12-13|3|37.25|36.75|-0.5|-1.34|-1|-1|38.0|36.5|Downward|199|1,211,557
ASK|2022-12-14|2022-12-14|1|37.5|37.5|0.0|0.0|1|1|38.0|37.0|Upward|200|1,334,473
ASK|2022-12-15|2022-12-20|4|37.25|34.5|-2.75|-7.38|-10|-3|37.75|34.5|Downward|204|5,518,482
ASK|2022-12-21|2022-12-23|3|35.0|35.75|0.75|2.14|4|1|36.0|34.25|Upward|207|2,965,233
ASK|2022-12-26|2023-01-05|9|35.5|34.25|-1.25|-3.52|-4|-1|36.25|34.25|Downward|215|7,569,963
ASK|2023-01-06|2023-01-10|3|34.5|35.5|1.0|2.9|5|1|35.75|32.5|Upward|218|8,787,300
ASK|2023-01-11|2023-01-12|2|35.25|35.25|0.0|0.0|1|0|36.0|34.75|Downward|220|1,248,446
ASK|2023-01-13|2023-01-13|1|35.75|35.75|0.0|0.0|1|1|36.25|35.25|Upward|221|1,975,689
ASK|2023-01-16|2023-01-25|8|35.0|32.25|-2.75|-7.86|-10|-2|36.0|32.25|Downward|229|10,850,406
ASK|2023-01-26|2023-01-27|2|32.75|33.0|0.25|0.76|2|1|33.25|32.25|Upward|231|1,394,991
ASK|2023-01-30|2023-01-31|2|32.75|32.75|0.0|0.0|1|0|33.25|32.5|Downward|233|2,796,821
BANPU|2022-02-15|2022-02-21|5|11.4|10.8|-0.6|-5.26|-5|-1|11.6|10.6|Downward|237|592,311,157
BANPU|2022-02-22|2022-02-23|2|10.9|11.1|0.2|1.83|3|1|11.1|10.6|Upward|239|182,695,270
BANPU|2022-02-24|2022-02-24|1|10.8|10.8|0.0|0.0|1|1|11.0|10.5|Downward|240|258,873,337
BANPU|2022-02-25|2022-03-03|5|10.9|12.5|1.6|14.68|17|3|12.8|10.7|Upward|245|1,550,958,765
BANPU|2022-03-04|2022-03-04|1|11.7|11.7|0.0|0.0|1|1|12.2|11.6|Downward|246|277,021,796
BANPU|2022-03-07|2022-03-07|1|12.1|12.1|0.0|0.0|1|1|12.3|11.6|Upward|247|434,107,397
BANPU|2022-03-08|2022-03-10|3|11.7|11.3|-0.4|-3.42|-3|-1|12.0|11.1|Downward|250|940,613,021
BANPU|2022-03-11|2022-03-11|1|11.5|11.5|0.0|0.0|1|1|11.6|11.1|Upward|251|164,323,990
BANPU|2022-03-14|2022-03-15|2|11.2|10.8|-0.4|-3.57|-3|-2|11.5|10.8|Downward|253|325,605,335
BANPU|2022-03-16|2022-03-18|3|11.0|11.1|0.1|0.91|2|0|11.1|10.8|Upward|256|228,466,071
BANPU|2022-03-21|2022-03-21|1|11.0|11.0|0.0|0.0|1|1|11.1|10.9|Downward|257|26,013,349
BANPU|2022-03-22|2022-03-29|6|11.2|11.5|0.3|2.68|4|0|11.6|10.9|Upward|263|530,215,079
BANPU|2022-03-30|2022-03-31|2|11.2|11.0|-0.2|-1.79|-1|-1|11.5|11.0|Downward|265|191,081,381
BANPU|2022-04-01|2022-04-07|5|11.1|11.3|0.2|1.8|3|0|11.3|11.0|Upward|269|224,653,150
BANPU|2022-04-08|2022-04-12|3|11.1|10.8|-0.3|-2.7|-2|-1|11.1|10.8|Downward|272|190,789,616
BANPU|2022-04-18|2022-04-22|5|11.2|11.9|0.7|6.25|8|1|11.9|10.9|Upward|277|740,602,506
BANPU|2022-04-25|2022-04-27|3|11.6|11.6|0.0|0.0|1|0|11.8|11.3|Downward|280|357,262,827
BANPU|2022-04-28|2022-04-29|2|12.2|12.3|0.1|0.82|2|1|12.4|11.6|Upward|282|558,843,916
BANPU|2022-05-03|2022-05-03|1|12.2|12.2|0.0|0.0|1|1|12.4|12.1|Downward|283|186,934,828
BANPU|2022-05-05|2022-05-09|3|12.4|12.5|0.1|0.81|2|0|12.7|12.1|Upward|286|535,608,872
BANPU|2022-05-10|2022-05-12|3|12.1|11.5|-0.6|-4.96|-5|-2|12.4|11.3|Downward|289|694,680,301
BANPU|2022-05-13|2022-05-18|4|11.6|11.9|0.3|2.59|4|1|12.0|11.4|Upward|292|338,974,617
BANPU|2022-05-19|2022-05-19|1|11.7|11.7|0.0|0.0|1|1|11.8|11.5|Downward|293|124,415,429
BANPU|2022-05-20|2022-05-23|2|12.2|12.2|0.0|0.0|1|0|12.3|11.8|Upward|295|285,078,675
BANPU|2022-05-24|2022-05-25|2|12.1|11.8|-0.3|-2.48|-2|-1|12.2|11.8|Downward|297|187,743,713
BANPU|2022-05-26|2022-05-26|1|12.2|12.2|0.0|0.0|1|1|12.2|11.8|Upward|298|106,630,355
BANPU|2022-05-27|2022-05-30|2|12.1|12.1|0.0|0.0|1|0|12.3|12.0|Downward|300|89,168,485
BANPU|2022-05-31|2022-06-07|6|12.4|13.3|0.9|7.26|10|1|13.4|12.1|Upward|305|915,446,165
BANPU|2022-06-08|2022-06-08|1|13.0|13.0|0.0|0.0|1|1|13.3|12.9|Downward|306|160,972,040
BANPU|2022-06-09|2022-06-09|1|13.1|13.1|0.0|0.0|1|1|13.2|12.9|Upward|307|157,839,899
BANPU|2022-06-10|2022-06-13|2|13.0|13.0|0.0|0.0|1|0|13.2|12.7|Downward|309|240,828,092
BANPU|2022-06-14|2022-06-14|1|13.4|13.4|0.0|0.0|1|1|13.5|13.0|Upward|310|239,685,280
BANPU|2022-06-15|2022-06-20|4|13.3|12.5|-0.8|-6.02|-7|-2|13.5|12.3|Downward|314|696,095,717
BANPU|2022-06-21|2022-06-21|1|12.8|12.8|0.0|0.0|1|1|13.0|12.6|Upward|315|140,825,413
BANPU|2022-06-22|2022-06-24|3|12.7|12.2|-0.5|-3.94|-4|-2|12.8|11.9|Downward|318|488,664,876
BANPU|2022-06-27|2022-06-30|4|12.5|12.6|0.1|0.8|2|0|12.8|12.2|Upward|322|395,411,835
BANPU|2022-07-01|2022-07-04|2|12.4|12.2|-0.2|-1.61|-1|-1|12.7|12.1|Downward|324|216,333,669
BANPU|2022-07-05|2022-07-05|1|12.5|12.5|0.0|0.0|1|1|12.6|12.2|Upward|325|159,706,679
BANPU|2022-07-06|2022-07-06|1|12.2|12.2|0.0|0.0|1|1|12.4|12.1|Downward|326|182,498,480
BANPU|2022-07-07|2022-07-11|3|12.4|12.9|0.5|4.03|6|2|12.9|12.0|Upward|329|417,084,136
BANPU|2022-07-12|2022-07-15|4|12.8|12.5|-0.3|-2.34|-2|-1|12.9|12.1|Downward|332|299,727,319
BANPU|2022-07-18|2022-07-19|2|12.8|12.9|0.1|0.78|2|1|12.9|12.4|Upward|334|218,847,313
BANPU|2022-07-20|2022-07-21|2|12.8|12.8|0.0|0.0|1|0|13.2|12.7|Downward|336|250,004,248
BANPU|2022-07-22|2022-07-27|4|12.9|13.4|0.5|3.88|6|1|13.5|12.7|Upward|340|392,825,172
BANPU|2022-08-01|2022-08-02|2|13.3|13.1|-0.2|-1.5|-1|-1|13.4|12.9|Downward|342|235,107,306
BANPU|2022-08-03|2022-08-03|1|13.3|13.3|0.0|0.0|1|1|13.3|13.0|Upward|343|103,627,813
BANPU|2022-08-04|2022-08-08|3|12.8|12.6|-0.2|-1.56|-1|-1|13.3|12.4|Downward|346|582,505,013
BANPU|2022-08-09|2022-08-17|7|12.7|14.0|1.3|10.24|14|2|14.0|12.6|Upward|352|934,607,936
BANPU|2022-08-18|2022-08-22|3|13.9|13.9|0.0|0.0|1|0|14.1|13.5|Downward|355|501,627,871
BANPU|2022-08-23|2022-08-30|6|14.5|14.9|0.4|2.76|5|0|15.0|13.9|Upward|361|1,531,431,374
BANPU|2022-08-31|2022-09-02|3|14.5|13.9|-0.6|-4.14|-5|-2|14.9|13.7|Downward|364|797,500,635
BANPU|2022-09-05|2022-09-06|2|14.3|14.5|0.2|1.4|3|1|14.6|14.0|Upward|366|397,607,475
BANPU|2022-09-07|2022-09-08|2|14.2|14.0|-0.2|-1.41|-1|-1|14.4|13.9|Downward|368|240,833,129
BANPU|2022-09-09|2022-09-12|2|14.3|14.4|0.1|0.7|2|1|14.5|14.1|Upward|370|168,622,790
BANPU|2022-09-13|2022-09-19|5|14.3|13.3|-1.0|-6.99|-9|-2|14.5|13.2|Downward|375|715,638,095
BANPU|2022-09-20|2022-09-21|2|13.4|13.7|0.3|2.24|4|2|13.9|13.2|Upward|377|195,381,616
BANPU|2022-09-22|2022-10-03|8|13.6|12.1|-1.5|-11.03|-14|-2|13.8|12.1|Downward|385|948,932,027
BANPU|2022-10-04|2022-10-06|3|12.4|12.7|0.3|2.42|4|1|12.8|12.2|Upward|388|240,471,957
BANPU|2022-10-07|2022-10-07|1|12.3|12.3|0.0|0.0|1|1|12.7|12.3|Downward|389|110,535,627
BANPU|2022-10-10|2022-10-17|6|12.6|12.8|0.2|1.59|3|0|12.8|12.1|Upward|393|442,829,447
BANPU|2022-10-18|2022-10-19|2|12.7|12.4|-0.3|-2.36|-2|-1|12.9|12.4|Downward|395|218,377,354
BANPU|2022-10-20|2022-10-20|1|12.7|12.7|0.0|0.0|1|1|12.7|12.4|Upward|396|68,849,546
BANPU|2022-10-21|2022-10-25|3|12.6|12.4|-0.2|-1.59|-1|-1|12.7|12.3|Downward|398|133,502,963
BANPU|2022-10-26|2022-10-27|2|12.5|12.5|0.0|0.0|1|0|12.5|12.3|Upward|400|145,374,786
BANPU|2022-10-28|2022-10-28|1|12.3|12.3|0.0|0.0|1|1|12.5|12.3|Downward|401|35,572,911
BANPU|2022-10-31|2022-11-01|2|12.5|12.6|0.1|0.8|2|1|12.7|12.4|Upward|403|185,418,551
BANPU|2022-11-02|2022-11-02|1|12.5|12.5|0.0|0.0|1|1|12.7|12.5|Downward|404|56,586,222
BANPU|2022-11-03|2022-11-07|3|12.6|13.0|0.4|3.17|5|1|13.2|12.5|Upward|407|324,332,864
BANPU|2022-11-08|2022-11-09|2|12.9|12.6|-0.3|-2.33|-2|-1|13.1|12.5|Downward|409|144,359,887
BANPU|2022-11-10|2022-11-11|2|12.7|12.8|0.1|0.79|2|1|13.0|12.3|Upward|411|278,114,895
BANPU|2022-11-14|2022-11-18|5|12.7|12.4|-0.3|-2.36|-2|-1|12.8|12.3|Downward|416|385,796,690
BANPU|2022-11-21|2022-11-24|4|12.6|13.1|0.5|3.97|6|1|13.2|12.5|Upward|420|431,298,904
BANPU|2022-11-25|2022-11-28|2|13.0|12.7|-0.3|-2.31|-2|-1|13.2|12.7|Downward|422|111,861,104
BANPU|2022-11-29|2022-12-06|6|12.9|13.5|0.6|4.65|7|1|13.5|12.8|Upward|427|454,857,208
BANPU|2022-12-07|2022-12-08|2|13.4|13.3|-0.1|-0.75|0|0|13.5|13.2|Downward|429|131,408,863
BANPU|2022-12-09|2022-12-14|4|13.6|13.7|0.1|0.74|2|0|13.8|13.2|Upward|432|266,639,931
BANPU|2022-12-15|2022-12-19|3|13.6|13.5|-0.1|-0.74|0|0|13.7|13.5|Downward|435|224,438,223
BANPU|2022-12-20|2022-12-20|1|13.6|13.6|0.0|0.0|1|1|13.6|13.4|Upward|436|75,293,568
BANPU|2022-12-21|2022-12-21|1|13.5|13.5|0.0|0.0|1|1|13.7|13.4|Downward|437|39,862,227
BANPU|2022-12-22|2022-12-22|1|13.6|13.6|0.0|0.0|1|1|13.7|13.5|Upward|438|62,947,205
BANPU|2022-12-23|2022-12-23|1|13.4|13.4|0.0|0.0|1|1|13.6|13.4|Downward|439|56,515,404
BANPU|2022-12-26|2022-12-26|1|13.5|13.5|0.0|0.0|1|1|13.6|13.3|Upward|440|54,412,026
BANPU|2022-12-27|2022-12-27|1|13.4|13.4|0.0|0.0|1|1|13.5|13.4|Downward|441|39,796,280
BANPU|2022-12-28|2022-12-30|3|13.7|13.7|0.0|0.0|1|0|13.8|13.4|Upward|444|166,355,695
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-10|-3|13.7|12.3|Downward|448|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|1|0|12.6|12.2|Upward|450|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|0|0|12.5|12.1|Downward|452|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|1|1|12.5|12.2|Upward|453|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|0|0|12.5|12.2|Downward|457|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|1|1|12.7|12.3|Upward|458|193,937,283
BANPU|2023-01-23|2023-02-10|15|12.5|10.9|-1.6|-12.8|-15|-1|12.6|10.7|Downward|473|2,058,642,124
BANPU|2023-02-13|2023-02-13|1|11.1|11.1|0.0|0.0|1|1|11.2|10.9|Upward|474|90,540,091
BANPU|2023-02-14|2023-02-15|2|11.0|11.0|0.0|0.0|1|0|11.3|10.9|Downward|476|219,310,115
CK|2022-02-15|2022-02-24|8|21.1|20.2|-0.9|-4.27|-8|-1|21.4|20.1|Downward|483|29,572,566
CK|2022-02-25|2022-02-28|2|20.8|21.0|0.2|0.96|3|1|21.0|20.4|Upward|485|6,432,813
CK|2022-03-01|2022-03-07|5|20.8|19.0|-1.8|-8.65|-17|-4|21.0|18.9|Downward|490|39,002,947
CK|2022-03-08|2022-03-10|3|19.5|20.7|1.2|6.15|13|4|20.8|18.9|Upward|493|22,727,393
CK|2022-03-11|2022-03-15|3|20.6|20.1|-0.5|-2.43|-4|-2|20.8|20.0|Downward|496|8,919,196
CK|2022-03-16|2022-03-16|1|20.7|20.7|0.0|0.0|1|1|20.7|20.1|Upward|497|3,318,003
CK|2022-03-17|2022-03-17|1|20.5|20.5|0.0|0.0|1|1|20.8|20.5|Downward|498|2,089,923
CK|2022-03-18|2022-03-22|3|20.7|20.9|0.2|0.97|3|1|21.0|20.4|Upward|501|14,563,557
CK|2022-03-23|2022-03-29|5|20.8|20.3|-0.5|-2.4|-4|-1|20.9|20.1|Downward|506|23,421,002
CK|2022-03-30|2022-03-30|1|20.5|20.5|0.0|0.0|1|1|20.5|20.2|Upward|507|6,185,745
CK|2022-03-31|2022-04-07|6|20.2|20.0|-0.2|-0.99|-1|-1|20.5|19.9|Downward|512|13,100,350
CK|2022-04-08|2022-04-08|1|20.7|20.7|0.0|0.0|1|1|20.7|19.9|Upward|513|10,857,128
CK|2022-04-11|2022-04-20|8|20.6|20.1|-0.5|-2.43|-4|-1|20.7|20.1|Downward|518|19,137,608
CK|2022-04-21|2022-04-21|1|20.2|20.2|0.0|0.0|1|1|20.5|20.0|Upward|519|7,247,266
CK|2022-04-22|2022-04-28|5|19.9|19.0|-0.9|-4.52|-8|-2|20.2|18.7|Downward|524|48,364,377
CK|2022-04-29|2022-05-05|5|19.5|19.6|0.1|0.51|2|0|19.8|19.1|Upward|527|14,806,014
CK|2022-05-06|2022-05-11|4|19.5|18.4|-1.1|-5.64|-10|-3|19.7|18.4|Downward|531|24,089,889
CK|2022-05-12|2022-05-30|13|18.5|21.3|2.8|15.14|29|2|21.5|17.9|Upward|543|117,996,816
CK|2022-05-31|2022-06-06|5|20.9|20.6|-0.3|-1.44|-2|-1|21.4|20.5|Downward|547|15,826,600
CK|2022-06-07|2022-06-07|1|20.9|20.9|0.0|0.0|1|1|20.9|20.3|Upward|548|4,592,865
CK|2022-06-08|2022-06-08|1|20.5|20.5|0.0|0.0|1|1|20.9|20.5|Downward|549|2,993,048
CK|2022-06-09|2022-06-09|1|20.7|20.7|0.0|0.0|1|1|20.8|20.4|Upward|550|2,018,190
CK|2022-06-10|2022-06-16|5|20.6|19.5|-1.1|-5.34|-10|-2|20.9|19.5|Downward|555|19,119,646
CK|2022-06-17|2022-06-21|3|19.6|20.0|0.4|2.04|5|1|20.0|19.2|Upward|558|8,161,918
CK|2022-06-22|2022-06-23|2|19.9|19.7|-0.2|-1.01|-1|-1|20.0|19.6|Downward|560|3,456,519
CK|2022-06-24|2022-06-24|1|20.0|20.0|0.0|0.0|1|1|20.0|19.7|Upward|561|1,660,541
CK|2022-06-27|2022-06-27|1|19.8|19.8|0.0|0.0|1|1|20.1|19.8|Downward|562|1,266,767
CK|2022-06-28|2022-06-29|2|20.3|20.3|0.0|0.0|1|0|20.4|19.8|Upward|564|6,903,140
CK|2022-06-30|2022-07-06|5|20.2|19.7|-0.5|-2.48|-4|-1|20.3|19.4|Downward|569|13,495,214
CK|2022-07-07|2022-07-07|1|19.8|19.8|0.0|0.0|1|1|19.9|19.6|Upward|570|2,600,239
CK|2022-07-08|2022-07-08|1|19.4|19.4|0.0|0.0|1|1|19.9|19.4|Downward|571|3,845,312
CK|2022-07-11|2022-07-12|2|19.6|19.9|0.3|1.53|4|2|19.9|19.4|Upward|573|3,374,041
CK|2022-07-14|2022-07-14|1|19.8|19.8|0.0|0.0|1|1|20.2|19.6|Downward|574|3,221,034
CK|2022-07-15|2022-07-19|3|20.0|20.1|0.1|0.5|2|0|20.2|19.8|Upward|577|5,471,700
CK|2022-07-20|2022-07-21|2|20.0|19.6|-0.4|-2.0|-3|-2|20.2|19.5|Downward|579|6,014,481
CK|2022-07-22|2022-07-27|4|19.8|21.4|1.6|8.08|17|4|21.4|19.7|Upward|583|28,855,573
CK|2022-08-01|2022-08-02|2|21.1|20.9|-0.2|-0.95|-1|-1|21.2|20.8|Downward|585|6,441,012
CK|2022-08-03|2022-08-03|1|21.4|21.4|0.0|0.0|1|1|21.4|21.0|Upward|586|5,745,284
CK|2022-08-04|2022-08-04|1|21.1|21.1|0.0|0.0|1|1|21.4|21.1|Downward|587|6,159,669

DIF|2022-12-14|2022-12-16|3|13.2|13.1|-0.1|-0.76|0|0|13.3|13.1|Downward|1163|27,098,343
DIF|2022-12-19|2022-12-19|1|13.2|13.2|0.0|0.0|1|1|13.2|13.1|Upward|1164|3,890,222
DIF|2022-12-20|2022-12-20|1|13.1|13.1|0.0|0.0|1|1|13.2|13.1|Downward|1165|1,736,699
DIF|2022-12-21|2023-01-04|11|13.2|13.3|0.1|0.76|2|0|13.3|13.1|Upward|1175|48,510,404
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|1|0|13.3|13.2|Downward|1177|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|5|0|13.7|13.2|Upward|1186|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|1|0|13.7|13.6|Downward|1189|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|1190|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|1|1|13.7|13.5|Downward|1191|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|1|1|13.7|13.5|Upward|1192|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|1|0|13.7|13.6|Downward|1194|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|1195|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|1|0|13.7|13.6|Downward|1199|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|1|1|13.7|13.6|Upward|1200|8,569,954
DIF|2023-02-10|2023-02-15|4|13.3|13.2|-0.1|-0.75|0|0|13.4|13.2|Downward|1204|48,275,264
IVL|2022-02-15|2022-02-21|5|51.25|46.0|-5.25|-10.24|-20|-4|52.0|45.75|Downward|1208|135,668,380
IVL|2022-02-22|2022-02-23|2|47.25|48.0|0.75|1.59|4|2|48.0|46.0|Upward|1210|45,668,797
IVL|2022-02-24|2022-02-28|3|47.0|45.0|-2.0|-4.26|-7|-3|47.75|43.5|Downward|1213|82,651,941
IVL|2022-03-01|2022-03-02|2|45.5|46.75|1.25|2.75|6|3|47.0|45.0|Upward|1215|49,613,143
IVL|2022-03-03|2022-03-08|4|46.0|42.5|-3.5|-7.61|-13|-4|47.25|41.0|Downward|1219|149,361,939
IVL|2022-03-09|2022-03-11|3|43.25|44.5|1.25|2.89|6|2|44.75|41.75|Upward|1222|86,908,854
IVL|2022-03-14|2022-03-15|2|44.0|43.25|-0.75|-1.7|-2|-1|44.5|42.75|Downward|1224|25,908,496
IVL|2022-03-16|2022-03-17|2|44.25|46.25|2.0|4.52|9|4|47.0|43.5|Upward|1226|63,903,935
IVL|2022-03-18|2022-03-21|2|46.0|45.5|-0.5|-1.09|-1|-1|46.75|45.0|Downward|1228|34,116,867
IVL|2022-03-22|2022-03-23|2|46.0|46.25|0.25|0.54|2|1|46.75|45.25|Upward|1230|32,162,437
IVL|2022-03-24|2022-03-25|2|46.0|45.5|-0.5|-1.09|-1|-1|46.5|45.25|Downward|1232|17,340,769
IVL|2022-03-28|2022-03-30|3|45.75|47.0|1.25|2.73|6|2|47.5|45.25|Upward|1235|65,303,981
IVL|2022-03-31|2022-04-04|3|46.5|45.5|-1.0|-2.15|-3|-1|47.0|45.0|Downward|1238|40,885,987
IVL|2022-04-05|2022-04-05|1|46.25|46.25|0.0|0.0|1|1|46.75|45.75|Upward|1239|12,546,110
IVL|2022-04-07|2022-04-07|1|45.0|45.0|0.0|0.0|1|1|46.0|45.0|Downward|1240|12,779,839
IVL|2022-04-08|2022-04-08|1|45.5|45.5|0.0|0.0|1|1|46.0|45.0|Upward|1241|10,522,505
IVL|2022-04-11|2022-04-12|2|45.25|45.25|0.0|0.0|1|0|45.75|44.75|Downward|1243|13,448,602
IVL|2022-04-18|2022-04-21|4|45.5|47.25|1.75|3.85|8|2|47.5|44.75|Upward|1247|48,297,777
IVL|2022-04-22|2022-04-27|4|47.0|43.5|-3.5|-7.45|-13|-4|47.0|42.25|Downward|1251|77,959,070
IVL|2022-04-28|2022-05-03|4|45.0|45.25|0.25|0.56|2|0|45.75|43.5|Upward|1254|38,958,573
IVL|2022-05-05|2022-05-10|4|44.75|43.75|-1.0|-2.23|-3|-1|46.0|43.0|Downward|1258|41,221,330
IVL|2022-05-11|2022-05-18|6|44.25|49.0|4.75|10.73|20|3|49.25|42.75|Upward|1263|159,094,800
IVL|2022-05-19|2022-05-19|1|48.5|48.5|0.0|0.0|1|1|49.0|47.75|Downward|1264|20,536,197
IVL|2022-05-20|2022-05-23|2|48.75|49.25|0.5|1.03|3|1|49.75|48.75|Upward|1266|19,942,928
IVL|2022-05-24|2022-05-24|1|48.5|48.5|0.0|0.0|1|1|49.25|48.0|Downward|1267|15,324,704
IVL|2022-05-25|2022-05-25|1|49.5|49.5|0.0|0.0|1|1|50.5|48.75|Upward|1268|33,282,171
IVL|2022-05-26|2022-05-26|1|49.0|49.0|0.0|0.0|1|1|49.75|48.75|Downward|1269|8,987,377
IVL|2022-05-27|2022-05-31|3|49.25|49.25|0.0|0.0|1|0|49.75|48.5|Upward|1272|36,120,971
IVL|2022-06-01|2022-06-01|1|49.0|49.0|0.0|0.0|1|1|49.25|48.25|Downward|1273|10,709,826
IVL|2022-06-02|2022-06-02|1|49.75|49.75|0.0|0.0|1|1|50.0|48.75|Upward|1274|20,349,470
IVL|2022-06-06|2022-06-07|2|49.0|49.0|0.0|0.0|1|0|50.0|48.75|Downward|1276|15,183,369
IVL|2022-06-08|2022-06-09|2|49.25|51.5|2.25|4.57|10|5|52.0|48.75|Upward|1278|42,973,302
IVL|2022-06-10|2022-06-13|2|51.25|49.5|-1.75|-3.41|-6|-3|51.5|49.25|Downward|1280|32,257,220
IVL|2022-06-14|2022-06-14|1|51.25|51.25|0.0|0.0|1|1|52.75|49.75|Upward|1281|33,465,472
IVL|2022-06-15|2022-06-17|3|51.0|47.5|-3.5|-6.86|-13|-5|51.5|47.5|Downward|1284|61,435,233
IVL|2022-06-20|2022-06-23|4|47.75|48.25|0.5|1.05|3|0|49.25|47.0|Upward|1288|59,994,253
IVL|2022-06-24|2022-06-27|2|47.5|47.5|0.0|0.0|1|0|48.5|46.75|Downward|1290|36,252,175
IVL|2022-06-28|2022-06-29|2|47.75|47.75|0.0|0.0|1|0|48.0|47.0|Upward|1292|18,035,373
IVL|2022-06-30|2022-07-06|5|47.0|44.75|-2.25|-4.79|-8|-2|47.75|44.0|Downward|1297|80,385,947
IVL|2022-07-07|2022-07-08|2|45.0|46.25|1.25|2.78|6|3|46.75|44.0|Upward|1299|37,068,245
IVL|2022-07-11|2022-07-15|5|46.0|43.75|-2.25|-4.89|-8|-2|46.5|42.75|Downward|1303|83,464,915
IVL|2022-07-18|2022-07-20|3|44.5|45.0|0.5|1.12|3|1|45.75|44.0|Upward|1306|43,170,669
IVL|2022-07-21|2022-07-21|1|44.75|44.75|0.0|0.0|1|1|45.25|44.5|Downward|1307|14,441,605
IVL|2022-07-22|2022-07-25|2|45.75|46.0|0.25|0.55|2|1|46.25|44.75|Upward|1309|30,112,488
IVL|2022-07-26|2022-07-27|2|44.0|43.75|-0.25|-0.57|0|0|45.75|43.0|Downward|1311|70,343,836
IVL|2022-08-01|2022-08-03|3|44.5|44.5|0.0|0.0|1|0|45.5|44.0|Upward|1314|60,040,066
IVL|2022-08-04|2022-08-08|3|44.0|42.75|-1.25|-2.84|-4|-2|45.0|41.75|Downward|1317|99,810,970
IVL|2022-08-09|2022-08-10|2|43.0|44.0|1.0|2.33|5|2|44.5|42.25|Upward|1319|80,562,402
IVL|2022-08-11|2022-08-11|1|42.75|42.75|0.0|0.0|1|1|44.75|42.25|Downward|1320|76,679,345
IVL|2022-08-15|2022-08-18|4|43.25|44.5|1.25|2.89|6|1|44.75|42.75|Upward|1324|100,998,067
IVL|2022-08-19|2022-08-22|2|43.75|43.75|0.0|0.0|1|0|44.5|43.25|Downward|1326|36,309,010
IVL|2022-08-23|2022-08-25|3|44.0|46.0|2.0|4.55|9|3|46.25|43.25|Upward|1329|88,940,162
IVL|2022-08-26|2022-09-02|6|45.5|40.75|-4.75|-10.44|-18|-3|46.25|40.5|Downward|1335|204,855,503
IVL|2022-09-05|2022-09-12|6|41.0|42.25|1.25|3.05|6|1|42.5|40.5|Upward|1341|106,561,639
IVL|2022-09-13|2022-09-19|5|42.0|40.25|-1.75|-4.17|-6|-2|42.5|40.0|Downward|1346|83,038,031
IVL|2022-09-20|2022-09-20|1|40.75|40.75|0.0|0.0|1|1|41.25|40.5|Upward|1347|10,826,748
IVL|2022-09-21|2022-09-21|1|40.5|40.5|0.0|0.0|1|1|41.0|40.25|Downward|1348|12,058,280
IVL|2022-09-22|2022-09-23|2|40.75|40.75|0.0|0.0|1|0|41.25|40.0|Upward|1350|43,946,715
IVL|2022-09-26|2022-09-29|4|40.0|38.75|-1.25|-3.13|-4|-1|40.5|38.75|Downward|1354|84,853,940
IVL|2022-09-30|2022-10-06|5|39.0|39.75|0.75|1.92|4|0|40.0|38.5|Upward|1359|75,419,166
IVL|2022-10-07|2022-10-11|3|38.75|38.5|-0.25|-0.65|0|0|40.0|38.0|Downward|1362|34,239,042
IVL|2022-10-12|2022-10-20|7|38.75|40.75|2.0|5.16|9|1|40.75|38.25|Upward|1367|70,267,427
IVL|2022-10-21|2022-10-21|1|40.5|40.5|0.0|0.0|1|1|41.0|40.25|Downward|1368|5,197,049
IVL|2022-10-25|2022-10-27|3|40.75|42.0|1.25|3.07|6|2|42.25|40.5|Upward|1371|45,260,836
IVL|2022-10-28|2022-10-28|1|41.75|41.75|0.0|0.0|1|1|42.25|41.5|Downward|1372|21,518,571
IVL|2022-10-31|2022-11-01|2|42.0|42.25|0.25|0.6|2|1|42.5|41.5|Upward|1374|23,831,354
IVL|2022-11-02|2022-11-03|2|42.0|41.75|-0.25|-0.6|0|0|42.5|41.75|Downward|1376|24,055,500
IVL|2022-11-04|2022-11-08|3|42.25|43.0|0.75|1.78|4|1|43.5|42.0|Upward|1379|54,043,737
IVL|2022-11-09|2022-11-10|2|42.75|42.75|0.0|0.0|1|0|43.25|41.5|Downward|1381|35,465,321
IVL|2022-11-11|2022-11-15|3|43.0|43.25|0.25|0.58|2|0|43.5|42.5|Upward|1384|38,944,103
IVL|2022-11-16|2022-11-17|2|42.5|42.25|-0.25|-0.59|0|0|43.0|42.0|Downward|1386|25,958,388
IVL|2022-11-18|2022-11-18|1|42.5|42.5|0.0|0.0|1|1|42.5|42.25|Upward|1387|4,716,312
IVL|2022-11-21|2022-11-29|7|42.25|41.75|-0.5|-1.18|-1|-1|42.75|41.25|Downward|1394|56,312,011
IVL|2022-11-30|2022-12-01|2|42.5|42.5|0.0|0.0|1|0|43.0|41.75|Upward|1396|23,480,637
IVL|2022-12-02|2022-12-07|4|41.75|40.75|-1.0|-2.4|-3|-1|42.5|40.75|Downward|1399|34,865,974
IVL|2022-12-08|2022-12-08|1|41.0|41.0|0.0|0.0|1|1|41.25|40.5|Upward|1400|7,060,851
IVL|2022-12-09|2022-12-13|3|40.75|40.25|-0.5|-1.23|-1|-1|41.0|40.0|Downward|1402|19,343,033
IVL|2022-12-14|2022-12-14|1|40.5|40.5|0.0|0.0|1|1|40.75|40.25|Upward|1403|4,346,908
IVL|2022-12-15|2022-12-23|7|40.0|39.5|-0.5|-1.25|-1|-1|40.75|39.0|Downward|1410|60,511,933
IVL|2022-12-26|2022-12-30|5|39.75|40.75|1.0|2.52|5|1|41.25|39.5|Upward|1415|56,581,013
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-9|-3|41.0|37.0|Downward|1419|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|16|2|42.75|37.75|Upward|1427|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|1|1|42.25|41.5|Downward|1428|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|1|1|42.5|41.75|Upward|1429|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-6|-2|42.5|40.0|Downward|1433|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|1|0|41.5|40.25|Upward|1435|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|1|1|41.25|40.5|Downward|1436|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|1|1|41.25|40.5|Upward|1437|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|0|0|41.25|40.25|Downward|1439|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|1|1|41.25|39.75|Upward|1440|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|1|1|41.0|40.25|Downward|1441|11,842,657
IVL|2023-02-08|2023-02-09|2|40.75|40.75|0.0|0.0|1|0|41.5|40.25|Upward|1443|22,518,750
IVL|2023-02-10|2023-02-13|2|40.5|40.0|-0.5|-1.23|-1|-1|40.75|39.75|Downward|1445|18,080,401
IVL|2023-02-14|2023-02-14|1|40.25|40.25|0.0|0.0|1|1|40.75|40.0|Upward|1446|8,413,044
IVL|2023-02-15|2023-02-15|1|40.0|40.0|0.0|0.0|1|1|40.5|39.5|Downward|1447|9,498,388
JASIF|2022-02-15|2022-02-17|3|11.0|11.0|0.0|0.0|1|0|11.1|10.9|Downward|1449|26,479,585
JASIF|2022-02-18|2022-02-22|3|11.1|11.2|0.1|0.9|2|0|11.2|11.0|Upward|1452|80,970,515
JASIF|2022-02-23|2022-02-24|2|11.1|10.9|-0.2|-1.8|-1|-1|11.2|10.9|Downward|1454|74,272,748
JASIF|2022-02-25|2022-03-01|3|11.0|11.3|0.3|2.73|4|1|11.3|10.9|Upward|1457|65,767,468
JASIF|2022-03-02|2022-03-08|5|11.2|10.4|-0.8|-7.14|-7|-2|11.3|10.0|Downward|1462|259,824,265
JASIF|2022-03-09|2022-03-14|4|10.7|10.7|0.0|0.0|1|0|10.8|10.4|Upward|1466|61,623,593
JASIF|2022-03-15|2022-03-15|1|10.6|10.6|0.0|0.0|1|1|10.8|10.6|Downward|1467|13,250,820
JASIF|2022-03-16|2022-03-25|8|10.8|11.0|0.2|1.85|3|0|11.1|10.6|Upward|1475|75,430,726
JASIF|2022-03-28|2022-03-28|1|10.9|10.9|0.0|0.0|1|1|11.0|10.9|Downward|1476|4,388,772
JASIF|2022-03-29|2022-03-29|1|11.0|11.0|0.0|0.0|1|1|11.0|10.9|Upward|1477|3,750,579
JASIF|2022-03-30|2022-03-30|1|10.9|10.9|0.0|0.0|1|1|11.0|10.9|Downward|1478|3,344,154
JASIF|2022-03-31|2022-03-31|1|11.0|11.0|0.0|0.0|1|1|11.0|10.9|Upward|1479|7,720,546
JASIF|2022-04-01|2022-04-01|1|10.9|10.9|0.0|0.0|1|1|11.0|10.9|Downward|1480|3,582,689
JASIF|2022-04-04|2022-04-04|1|11.0|11.0|0.0|0.0|1|1|11.0|10.9|Upward|1481|8,866,642
JASIF|2022-04-05|2022-04-08|4|10.9|10.8|-0.1|-0.92|0|0|11.0|10.8|Downward|1484|46,126,930
JASIF|2022-04-11|2022-04-22|10|10.9|11.0|0.1|0.92|2|0|11.0|10.8|Upward|1491|34,672,881
JASIF|2022-04-25|2022-04-26|2|10.9|10.8|-0.1|-0.92|0|0|11.0|10.8|Downward|1493|30,127,294
JASIF|2022-04-27|2022-05-10|10|10.9|11.0|0.1|0.92|2|0|11.1|10.8|Upward|1501|125,545,810
JASIF|2022-05-11|2022-05-12|2|10.9|10.9|0.0|0.0|1|0|11.1|10.9|Downward|1503|42,138,755
JASIF|2022-05-13|2022-05-18|4|11.0|11.1|0.1|0.91|2|0|11.1|10.9|Upward|1506|53,882,007
JASIF|2022-05-19|2022-05-23|3|11.0|10.8|-0.2|-1.82|-1|-1|11.1|10.8|Downward|1509|65,182,783
JASIF|2022-05-24|2022-05-31|6|10.9|11.0|0.1|0.92|2|0|11.0|10.8|Upward|1515|48,433,639
JASIF|2022-06-01|2022-06-17|13|10.9|10.5|-0.4|-3.67|-3|-1|11.0|10.4|Downward|1527|203,969,047
JASIF|2022-06-20|2022-06-20|1|10.6|10.6|0.0|0.0|1|1|10.6|10.5|Upward|1528|14,435,313
JASIF|2022-06-21|2022-06-22|2|10.5|10.3|-0.2|-1.9|-1|-1|10.6|10.3|Downward|1530|58,777,152
JASIF|2022-06-23|2022-06-28|4|9.25|9.95|0.7|7.57|15|3|9.95|9.2|Upward|1534|642,006,468
JASIF|2022-06-29|2022-07-05|5|9.75|8.8|-0.95|-9.74|-18|-4|9.95|8.8|Downward|1539|475,737,327
JASIF|2022-07-06|2022-07-07|2|8.9|8.9|0.0|0.0|1|0|9.05|8.6|Upward|1541|101,669,045
JASIF|2022-07-08|2022-07-08|1|8.8|8.8|0.0|0.0|1|1|8.9|8.75|Downward|1542|20,374,264
JASIF|2022-07-11|2022-07-14|4|8.85|8.85|0.0|0.0|1|0|8.9|8.75|Upward|1545|27,955,760
JASIF|2022-07-15|2022-07-15|1|8.8|8.8|0.0|0.0|1|1|8.85|8.7|Downward|1546|10,784,246
JASIF|2022-07-18|2022-07-18|1|8.9|8.9|0.0|0.0|1|1|8.9|8.85|Upward|1547|9,640,342
JASIF|2022-07-19|2022-07-21|3|8.85|8.8|-0.05|-0.56|0|0|8.9|8.8|Downward|1550|28,432,242
JASIF|2022-07-22|2022-07-25|2|8.9|8.9|0.0|0.0|1|0|8.9|8.8|Upward|1552|16,195,203
JASIF|2022-07-26|2022-07-27|2|8.85|8.8|-0.05|-0.56|0|0|8.9|8.8|Downward|1554|29,112,938
JASIF|2022-08-01|2022-08-04|4|8.95|9.1|0.15|1.68|4|1|9.15|8.8|Upward|1558|53,030,442
JASIF|2022-08-05|2022-08-09|3|9.05|8.9|-0.15|-1.66|-2|-1|9.15|8.9|Downward|1561|43,264,326
JASIF|2022-08-10|2022-08-17|6|8.95|9.1|0.15|1.68|4|0|9.1|8.9|Upward|1566|103,348,580
JASIF|2022-08-18|2022-09-08|16|9.05|7.6|-1.45|-16.02|-28|-2|9.1|7.15|Downward|1582|590,465,454
JASIF|2022-09-09|2022-09-09|1|8.05|8.05|0.0|0.0|1|1|8.3|7.6|Upward|1583|116,032,412
JASIF|2022-09-12|2022-09-14|3|7.9|7.85|-0.05|-0.63|0|0|8.25|7.75|Downward|1586|101,598,941
JASIF|2022-09-15|2022-09-23|7|8.0|8.45|0.45|5.62|10|1|8.45|7.95|Upward|1593|142,030,128
JASIF|2022-09-26|2022-10-03|6|8.4|8.05|-0.35|-4.17|-6|-1|8.55|8.05|Downward|1599|92,360,797
JASIF|2022-10-04|2022-10-04|1|8.15|8.15|0.0|0.0|1|1|8.2|8.05|Upward|1600|10,855,432
JASIF|2022-10-05|2022-10-12|6|8.1|8.0|-0.1|-1.23|-1|-1|8.2|7.95|Downward|1606|44,431,678
JASIF|2022-10-17|2022-10-18|2|8.1|8.35|0.25|3.09|6|3|8.35|8.0|Upward|1608|28,645,220
JASIF|2022-10-19|2022-10-26|6|8.0|7.9|-0.1|-1.25|-1|-1|8.15|7.8|Downward|1613|95,439,527
JASIF|2022-10-27|2022-10-28|2|8.0|8.0|0.0|0.0|1|0|8.05|7.9|Upward|1615|12,719,691
JASIF|2022-10-31|2022-10-31|1|7.95|7.95|0.0|0.0|1|1|8.05|7.9|Downward|1616|9,766,033
JASIF|2022-11-01|2022-11-04|4|8.0|8.15|0.15|1.88|4|1|8.15|7.95|Upward|1620|27,655,203
JASIF|2022-11-07|2022-11-07|1|8.1|8.1|0.0|0.0|1|1|8.2|8.1|Downward|1621|6,407,477
JASIF|2022-11-08|2022-11-08|1|8.2|8.2|0.0|0.0|1|1|8.2|8.1|Upward|1622|3,176,386
JASIF|2022-11-09|2022-11-11|3|8.15|8.15|0.0|0.0|1|0|8.2|8.1|Downward|1625|26,160,317
JASIF|2022-11-14|2022-11-17|4|8.2|8.7|0.5|6.1|11|2|8.8|8.15|Upward|1629|117,666,385
JASIF|2022-11-18|2022-11-22|3|8.5|8.05|-0.45|-5.29|-8|-3|8.65|8.05|Downward|1632|67,428,802
JASIF|2022-11-23|2022-11-24|2|8.1|8.15|0.05|0.62|2|1|8.15|8.05|Upward|1634|7,839,072
JASIF|2022-11-25|2022-11-30|4|8.1|8.0|-0.1|-1.23|-1|-1|8.15|7.95|Downward|1638|19,531,054
JASIF|2022-12-01|2022-12-02|2|8.05|8.05|0.0|0.0|1|0|8.05|7.95|Upward|1640|16,193,734
JASIF|2022-12-06|2022-12-09|4|8.0|8.0|0.0|0.0|1|0|8.05|7.95|Downward|1644|16,432,500
JASIF|2022-12-13|2022-12-16|4|8.05|8.05|0.0|0.0|1|0|8.1|8.0|Upward|1648|19,932,502
JASIF|2022-12-19|2022-12-19|1|8.0|8.0|0.0|0.0|1|1|8.1|8.0|Downward|1649|3,086,098
JASIF|2022-12-20|2022-12-21|2|8.05|8.05|0.0|0.0|1|0|8.05|8.0|Upward|1651|4,132,295
JASIF|2022-12-22|2022-12-26|3|8.0|8.0|0.0|0.0|1|0|8.1|7.95|Downward|1654|17,969,777
JASIF|2022-12-27|2022-12-27|1|8.05|8.05|0.0|0.0|1|1|8.05|8.0|Upward|1655|1,607,162
JASIF|2022-12-28|2022-12-28|1|8.0|8.0|0.0|0.0|1|1|8.05|8.0|Downward|1656|3,249,547
JASIF|2022-12-29|2023-01-12|11|8.05|8.25|0.2|2.48|5|0|8.3|8.0|Upward|1666|47,932,471
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|1|1|8.25|8.2|Downward|1667|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|1|0|8.25|8.2|Upward|1669|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|1|1|8.25|8.2|Downward|1670|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|1|0|8.25|8.2|Upward|1674|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|0|0|8.25|8.15|Downward|1678|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|2|1|8.25|8.15|Upward|1680|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|1|1|8.25|8.2|Downward|1681|3,117,519
JASIF|2023-02-03|2023-02-08|4|8.25|8.25|0.0|0.0|1|0|8.25|8.2|Upward|1685|12,746,881
JASIF|2023-02-10|2023-02-15|4|8.2|8.15|-0.05|-0.61|0|0|8.25|8.1|Downward|1689|23,164,926
JMART|2022-02-15|2022-02-18|4|51.5|49.75|-1.75|-3.4|-6|-2|52.0|49.75|Downward|1692|16,147,904
JMART|2022-02-21|2022-02-23|3|50.5|54.0|3.5|6.93|15|5|54.25|49.25|Upward|1695|27,368,563
JMART|2022-02-24|2022-02-24|1|52.75|52.75|0.0|0.0|1|1|55.0|52.0|Downward|1696|17,659,939
JMART|2022-02-25|2022-02-28|2|54.0|56.5|2.5|4.63|11|5|56.5|53.0|Upward|1698|24,269,386
JMART|2022-03-01|2022-03-08|6|56.25|50.75|-5.5|-9.78|-21|-4|56.5|48.75|Downward|1704|50,749,677
JMART|2022-03-09|2022-03-09|1|52.75|52.75|0.0|0.0|1|1|52.75|50.25|Upward|1705|7,640,538
JMART|2022-03-10|2022-03-10|1|52.25|52.25|0.0|0.0|1|1|53.75|52.25|Downward|1706|5,445,308
JMART|2022-03-11|2022-03-11|1|53.0|53.0|0.0|0.0|1|1|53.25|51.75|Upward|1707|2,684,489
JMART|2022-03-14|2022-03-15|2|52.5|52.25|-0.25|-0.48|0|0|53.5|52.0|Downward|1709|4,702,322
JMART|2022-03-16|2022-03-21|4|53.75|55.0|1.25|2.33|6|1|55.5|52.75|Upward|1713|32,370,833
JMART|2022-03-22|2022-03-22|1|54.5|54.5|0.0|0.0|1|1|55.5|54.5|Downward|1714|4,003,662
JMART|2022-03-23|2022-03-23|1|55.75|55.75|0.0|0.0|1|1|56.25|55.0|Upward|1715|6,668,578
JMART|2022-03-24|2022-03-25|2|55.5|55.0|-0.5|-0.9|-1|-1|56.0|54.75|Downward|1717|6,500,119
JMART|2022-03-28|2022-04-08|10|56.0|61.25|5.25|9.38|22|2|61.75|55.0|Upward|1726|114,545,576
JMART|2022-04-11|2022-04-11|1|61.0|61.0|0.0|0.0|1|1|61.25|59.75|Downward|1727|6,313,874
JMART|2022-04-12|2022-04-12|1|63.25|63.25|0.0|0.0|1|1|64.0|60.25|Upward|1728|21,018,673
JMART|2022-04-18|2022-04-20|3|62.25|59.25|-3.0|-4.82|-11|-4|63.5|59.0|Downward|1731|31,717,382
JMART|2022-04-21|2022-04-25|3|60.25|61.5|1.25|2.07|6|2|61.75|59.5|Upward|1734|20,947,760
JMART|2022-04-26|2022-04-27|2|60.5|60.25|-0.25|-0.41|0|0|62.5|59.5|Downward|1736|20,910,894
JMART|2022-04-28|2022-04-29|2|61.5|62.5|1.0|1.63|5|2|62.5|60.0|Upward|1738|14,506,713
JMART|2022-05-03|2022-05-09|5|60.75|54.25|-6.5|-10.7|-25|-5|62.5|53.75|Downward|1742|64,378,726
JMART|2022-05-10|2022-05-10|1|57.5|57.5|0.0|0.0|1|1|57.75|53.75|Upward|1743|13,012,373
JMART|2022-05-11|2022-05-12|2|54.75|51.25|-3.5|-6.39|-13|-7|57.25|51.25|Downward|1745|26,199,697
JMART|2022-05-13|2022-05-18|4|51.5|55.0|3.5|6.8|15|3|55.25|51.0|Upward|1748|32,429,379
JMART|2022-05-19|2022-05-19|1|53.0|53.0|0.0|0.0|1|1|54.25|52.75|Downward|1749|9,492,078
JMART|2022-05-20|2022-05-31|8|54.25|60.75|6.5|11.98|27|3|61.25|54.0|Upward|1757|75,023,821
JMART|2022-06-01|2022-06-02|2|59.5|59.0|-0.5|-0.84|-1|-1|61.5|58.5|Downward|1759|16,159,787
JMART|2022-06-06|2022-06-06|1|59.75|59.75|0.0|0.0|1|1|60.0|58.5|Upward|1760|3,095,793
JMART|2022-06-07|2022-06-07|1|58.25|58.25|0.0|0.0|1|1|59.75|58.25|Downward|1761|5,271,342
JMART|2022-06-08|2022-06-08|1|58.5|58.5|0.0|0.0|1|1|59.0|58.0|Upward|1762|3,337,626
JMART|2022-06-09|2022-06-09|1|56.5|56.5|0.0|0.0|1|1|58.25|56.0|Downward|1763|12,080,072
JMART|2022-06-10|2022-06-10|1|57.25|57.25|0.0|0.0|1|1|57.25|55.75|Upward|1764|5,705,532
JMART|2022-06-13|2022-06-13|1|55.25|55.25|0.0|0.0|1|1|56.75|55.25|Downward|1765|6,846,740
JMART|2022-06-14|2022-06-15|2|55.75|56.25|0.5|0.9|3|1|56.5|54.75|Upward|1767|11,499,586
JMART|2022-06-16|2022-06-16|1|55.0|55.0|0.0|0.0|1|1|57.25|54.75|Downward|1768|8,797,318
JMART|2022-06-17|2022-06-17|1|55.5|55.5|0.0|0.0|1|1|56.0|53.5|Upward|1769|10,720,299
JMART|2022-06-20|2022-06-20|1|52.5|52.5|0.0|0.0|1|1|55.5|52.25|Downward|1770|11,822,325
JMART|2022-06-21|2022-06-21|1|55.0|55.0|0.0|0.0|1|1|55.25|53.5|Upward|1771|8,345,384
JMART|2022-06-22|2022-06-22|1|53.5|53.5|0.0|0.0|1|1|55.0|53.25|Downward|1772|8,720,773
JMART|2022-06-23|2022-06-28|4|53.75|55.0|1.25|2.33|6|1|56.0|53.25|Upward|1776|24,218,155
JMART|2022-06-29|2022-06-30|2|54.0|51.0|-3.0|-5.56|-11|-6|55.25|50.75|Downward|1778|35,178,714
JMART|2022-07-01|2022-07-01|1|51.75|51.75|0.0|0.0|1|1|52.25|49.25|Upward|1779|18,258,697
JMART|2022-07-04|2022-07-06|3|51.0|45.0|-6.0|-11.76|-23|-8|51.75|44.5|Downward|1782|62,443,861

JMT|2023-02-09|2023-02-09|1|52.0|52.0|0.0|0.0|1|1|53.0|50.25|Upward|2171|14,352,623
JMT|2023-02-10|2023-02-13|2|50.5|49.5|-1.0|-1.98|-3|-2|52.0|48.75|Downward|2173|35,100,334
JMT|2023-02-14|2023-02-14|1|50.0|50.0|0.0|0.0|1|1|53.25|49.5|Upward|2174|45,121,902
JMT|2023-02-15|2023-02-15|1|42.75|42.75|0.0|0.0|1|1|50.5|42.0|Downward|2175|75,936,256
KCE|2022-02-15|2022-02-15|1|61.75|61.75|0.0|0.0|1|1|62.0|59.25|Downward|2176|34,956,645
KCE|2022-02-17|2022-02-18|2|62.0|62.75|0.75|1.21|4|2|63.25|61.0|Upward|2178|43,502,299
KCE|2022-02-21|2022-02-22|2|62.5|62.0|-0.5|-0.8|-1|-1|63.0|60.75|Downward|2180|23,766,626
KCE|2022-02-23|2022-02-23|1|62.5|62.5|0.0|0.0|1|1|63.0|61.75|Upward|2181|10,058,608
KCE|2022-02-24|2022-02-24|1|60.5|60.5|0.0|0.0|1|1|62.0|59.75|Downward|2182|16,590,888
KCE|2022-02-25|2022-02-25|1|61.5|61.5|0.0|0.0|1|1|62.0|61.0|Upward|2183|10,694,349
KCE|2022-02-28|2022-02-28|1|60.5|60.5|0.0|0.0|1|1|61.0|58.25|Downward|2184|24,477,952
KCE|2022-03-01|2022-03-01|1|60.75|60.75|0.0|0.0|1|1|61.5|60.25|Upward|2185|7,282,371
KCE|2022-03-02|2022-03-02|1|58.25|58.25|0.0|0.0|1|1|60.75|58.25|Downward|2186|22,015,683
KCE|2022-03-03|2022-03-04|2|58.5|58.5|0.0|0.0|1|0|60.5|54.5|Upward|2188|55,186,539
KCE|2022-03-07|2022-03-08|2|55.75|54.75|-1.0|-1.79|-3|-2|57.0|53.5|Downward|2190|43,860,126
KCE|2022-03-09|2022-03-11|3|56.75|58.5|1.75|3.08|8|2|60.5|54.75|Upward|2193|60,888,462
KCE|2022-03-14|2022-03-15|2|58.0|57.5|-0.5|-0.86|-1|-1|59.0|57.5|Downward|2195|15,282,301
KCE|2022-03-16|2022-03-17|2|63.0|64.25|1.25|1.98|6|3|65.5|58.25|Upward|2197|85,382,582
KCE|2022-03-18|2022-03-21|2|63.75|62.75|-1.0|-1.57|-3|-2|64.75|62.25|Downward|2199|23,514,764
KCE|2022-03-22|2022-03-24|3|63.5|65.25|1.75|2.76|8|2|66.25|61.25|Upward|2202|52,292,907
KCE|2022-03-25|2022-03-28|2|65.0|64.25|-0.75|-1.15|-2|-1|66.5|63.5|Downward|2204|25,716,173
KCE|2022-03-29|2022-03-31|3|64.75|65.5|0.75|1.16|4|1|66.25|64.25|Upward|2207|35,284,942
KCE|2022-04-01|2022-04-04|2|65.25|65.0|-0.25|-0.38|0|0|65.75|64.25|Downward|2209|16,927,284
KCE|2022-04-05|2022-04-05|1|66.5|66.5|0.0|0.0|1|1|67.5|65.5|Upward|2210|19,185,468
KCE|2022-04-07|2022-04-11|3|63.25|61.0|-2.25|-3.56|-8|-3|65.25|60.0|Downward|2213|56,610,306
KCE|2022-04-12|2022-04-18|5|61.25|61.5|0.25|0.41|2|0|62.25|59.5|Upward|2215|16,440,078
KCE|2022-04-19|2022-04-19|1|61.25|61.25|0.0|0.0|1|1|62.5|60.5|Downward|2216|9,398,527
KCE|2022-04-20|2022-04-22|3|62.5|63.25|0.75|1.2|4|1|64.0|61.75|Upward|2219|30,378,487
KCE|2022-04-25|2022-04-27|3|62.5|60.75|-1.75|-2.8|-6|-2|63.75|60.25|Downward|2222|20,515,235
KCE|2022-04-28|2022-04-28|1|62.0|62.0|0.0|0.0|1|1|62.5|60.5|Upward|2223|7,074,812
KCE|2022-04-29|2022-05-03|3|61.5|61.5|0.0|0.0|1|0|62.75|61.25|Downward|2225|12,546,290
KCE|2022-05-05|2022-05-05|1|62.25|62.25|0.0|0.0|1|1|63.75|62.25|Upward|2226|10,551,778
KCE|2022-05-06|2022-05-09|2|61.25|59.25|-2.0|-3.27|-7|-4|61.75|58.5|Downward|2228|26,390,345
KCE|2022-05-10|2022-05-11|2|59.75|61.75|2.0|3.35|9|4|62.0|58.0|Upward|2230|26,663,356
KCE|2022-05-12|2022-05-12|1|61.25|61.25|0.0|0.0|1|1|62.5|60.5|Downward|2231|11,311,071
KCE|2022-05-13|2022-05-18|4|61.75|63.75|2.0|3.24|9|2|64.5|60.75|Upward|2234|33,355,164
KCE|2022-05-19|2022-05-19|1|62.5|62.5|0.0|0.0|1|1|63.0|61.5|Downward|2235|10,033,933
KCE|2022-05-20|2022-05-20|1|63.25|63.25|0.0|0.0|1|1|63.5|62.5|Upward|2236|6,226,695
KCE|2022-05-23|2022-05-25|3|63.0|61.5|-1.5|-2.38|-5|-2|63.75|61.0|Downward|2239|22,731,184
KCE|2022-05-26|2022-05-30|3|61.75|66.25|4.5|7.29|19|6|66.75|61.5|Upward|2242|49,176,005
KCE|2022-05-31|2022-06-07|6|66.0|63.75|-2.25|-3.41|-8|-2|66.5|63.25|Downward|2247|34,760,715
KCE|2022-06-08|2022-06-09|2|64.5|64.5|0.0|0.0|1|0|65.25|63.75|Upward|2249|13,705,523
KCE|2022-06-10|2022-06-13|2|64.25|61.75|-2.5|-3.89|-9|-5|64.25|61.25|Downward|2251|13,729,037
KCE|2022-06-14|2022-06-14|1|62.5|62.5|0.0|0.0|1|1|62.75|60.75|Upward|2252|8,576,008
KCE|2022-06-15|2022-06-16|2|62.25|61.25|-1.0|-1.61|-3|-2|63.75|61.0|Downward|2254|13,850,768
KCE|2022-06-17|2022-06-21|3|61.75|63.0|1.25|2.02|6|2|63.25|60.5|Upward|2257|15,826,637
KCE|2022-06-22|2022-06-23|2|60.5|60.5|0.0|0.0|1|0|63.0|59.5|Downward|2259|22,916,486
KCE|2022-06-24|2022-06-27|2|61.0|62.75|1.75|2.87|8|4|63.25|60.75|Upward|2261|23,575,769
KCE|2022-06-28|2022-06-30|3|62.5|60.25|-2.25|-3.6|-8|-3|63.0|59.5|Downward|2264|18,241,677
KCE|2022-07-01|2022-07-01|1|60.75|60.75|0.0|0.0|1|1|61.25|59.75|Upward|2265|4,970,478
KCE|2022-07-04|2022-07-06|3|56.5|54.75|-1.75|-3.1|-6|-2|60.75|54.0|Downward|2268|57,717,465
KCE|2022-07-07|2022-07-07|1|55.25|55.25|0.0|0.0|1|1|55.5|54.0|Upward|2269|10,691,901
KCE|2022-07-08|2022-07-12|3|55.0|54.75|-0.25|-0.45|0|0|56.5|54.25|Downward|2272|21,976,597
KCE|2022-07-14|2022-07-14|1|55.0|55.0|0.0|0.0|1|1|55.75|54.75|Upward|2273|4,803,578
KCE|2022-07-15|2022-07-15|1|54.0|54.0|0.0|0.0|1|1|55.25|52.25|Downward|2274|16,374,327
KCE|2022-07-18|2022-07-25|6|54.25|58.75|4.5|8.29|19|3|59.0|53.5|Upward|2280|50,776,944
KCE|2022-07-26|2022-07-26|1|58.5|58.5|0.0|0.0|1|1|59.0|58.25|Downward|2281|3,748,025
KCE|2022-07-27|2022-08-01|4|62.75|65.5|2.75|4.38|12|3|65.5|59.5|Upward|2283|57,963,208
KCE|2022-08-02|2022-08-02|1|64.5|64.5|0.0|0.0|1|1|65.5|64.0|Downward|2284|10,319,830
KCE|2022-08-03|2022-08-04|2|64.75|65.5|0.75|1.16|4|2|66.75|64.25|Upward|2286|23,233,754
KCE|2022-08-05|2022-08-11|5|65.25|57.0|-8.25|-12.64|-32|-7|65.75|56.25|Downward|2291|111,510,826
KCE|2022-08-15|2022-08-17|3|57.5|58.25|0.75|1.3|4|1|59.5|56.5|Upward|2294|32,656,740
KCE|2022-08-18|2022-08-22|3|58.0|55.5|-2.5|-4.31|-9|-3|58.25|55.25|Downward|2297|28,270,030
KCE|2022-08-23|2022-08-23|1|55.75|55.75|0.0|0.0|1|1|55.75|54.75|Upward|2298|10,675,326
KCE|2022-08-24|2022-08-24|1|55.25|55.25|0.0|0.0|1|1|55.75|54.75|Downward|2299|7,416,251
KCE|2022-08-25|2022-08-26|2|55.75|56.5|0.75|1.35|4|2|57.25|55.5|Upward|2301|19,478,459
KCE|2022-08-29|2022-09-09|10|55.5|49.25|-6.25|-11.26|-24|-3|55.75|48.25|Downward|2311|139,468,671
KCE|2022-09-12|2022-09-15|4|51.0|52.0|1.0|1.96|5|1|52.5|49.25|Upward|2315|67,843,308
KCE|2022-09-16|2022-09-16|1|51.75|51.75|0.0|0.0|1|1|52.25|51.25|Downward|2316|9,476,267
KCE|2022-09-19|2022-09-19|1|52.25|52.25|0.0|0.0|1|1|53.25|51.75|Upward|2317|18,204,723
KCE|2022-09-20|2022-09-21|2|51.5|50.75|-0.75|-1.46|-2|-1|53.0|50.25|Downward|2319|19,686,329
KCE|2022-09-22|2022-09-22|1|51.0|51.0|0.0|0.0|1|1|51.0|49.25|Upward|2320|13,068,350
KCE|2022-09-23|2022-10-03|7|50.0|42.0|-8.0|-16.0|-31|-5|50.75|41.75|Downward|2327|112,935,320
KCE|2022-10-04|2022-10-06|3|42.75|43.25|0.5|1.17|3|1|44.5|41.25|Upward|2330|45,348,288
KCE|2022-10-07|2022-10-12|4|42.0|40.25|-1.75|-4.17|-6|-2|44.0|40.0|Downward|2334|37,017,923
KCE|2022-10-17|2022-10-18|2|41.0|43.0|2.0|4.88|9|4|43.5|39.75|Upward|2336|20,722,479
KCE|2022-10-19|2022-10-19|1|42.5|42.5|0.0|0.0|1|1|43.75|42.5|Downward|2337|7,073,882
KCE|2022-10-20|2022-10-20|1|43.25|43.25|0.0|0.0|1|1|43.25|41.75|Upward|2338|7,856,631
KCE|2022-10-21|2022-10-21|1|42.0|42.0|0.0|0.0|1|1|43.25|42.0|Downward|2339|6,377,903
KCE|2022-10-25|2022-10-25|1|43.0|43.0|0.0|0.0|1|1|43.5|41.5|Upward|2340|11,870,626
KCE|2022-10-26|2022-10-28|3|42.0|41.25|-0.75|-1.79|-2|-1|43.25|41.25|Downward|2343|17,667,542
KCE|2022-10-31|2022-11-08|7|42.0|47.5|5.5|13.1|23|3|48.25|41.75|Upward|2350|91,509,002
KCE|2022-11-09|2022-11-09|1|45.0|45.0|0.0|0.0|1|1|48.5|44.5|Downward|2351|28,018,966
KCE|2022-11-10|2022-11-15|4|45.25|49.25|4.0|8.84|17|4|50.0|44.5|Upward|2355|58,675,992
KCE|2022-11-16|2022-11-17|2|49.0|47.75|-1.25|-2.55|-4|-2|49.5|47.25|Downward|2357|28,526,891
KCE|2022-11-18|2022-11-18|1|51.25|51.25|0.0|0.0|1|1|52.0|48.25|Upward|2358|43,894,922
KCE|2022-11-21|2022-11-23|3|49.25|47.5|-1.75|-3.55|-6|-2|51.5|47.25|Downward|2361|62,651,087
KCE|2022-11-24|2022-11-24|1|48.0|48.0|0.0|0.0|1|1|48.25|47.0|Upward|2362|8,940,645
KCE|2022-11-25|2022-11-25|1|46.75|46.75|0.0|0.0|1|1|48.0|46.25|Downward|2363|14,716,884
KCE|2022-11-28|2022-11-28|1|47.75|47.75|0.0|0.0|1|1|48.25|46.0|Upward|2364|15,171,528
KCE|2022-11-29|2022-11-29|1|47.5|47.5|0.0|0.0|1|1|48.0|46.25|Downward|2365|20,347,123
KCE|2022-11-30|2022-12-01|2|48.25|50.75|2.5|5.18|11|5|51.75|47.0|Upward|2367|52,645,230
KCE|2022-12-02|2022-12-08|5|50.0|48.75|-1.25|-2.5|-4|-1|51.25|48.25|Downward|2371|46,715,439
KCE|2022-12-09|2022-12-09|1|49.75|49.75|0.0|0.0|1|1|50.25|49.0|Upward|2372|11,097,705
KCE|2022-12-13|2022-12-13|1|49.25|49.25|0.0|0.0|1|1|50.25|49.0|Downward|2373|7,664,263
KCE|2022-12-14|2022-12-14|1|49.75|49.75|0.0|0.0|1|1|50.75|49.5|Upward|2374|7,395,008
KCE|2022-12-15|2022-12-16|2|48.0|47.25|-0.75|-1.56|-2|-1|50.0|46.75|Downward|2376|25,451,858
KCE|2022-12-19|2022-12-19|1|47.5|47.5|0.0|0.0|1|1|48.5|47.25|Upward|2377|8,820,673
KCE|2022-12-20|2022-12-21|2|45.5|45.0|-0.5|-1.1|-1|-1|47.5|44.5|Downward|2379|30,961,451
KCE|2022-12-22|2022-12-22|1|45.75|45.75|0.0|0.0|1|1|46.25|45.0|Upward|2380|10,758,771
KCE|2022-12-23|2022-12-23|1|45.5|45.5|0.0|0.0|1|1|45.5|44.5|Downward|2381|7,870,966
KCE|2022-12-26|2022-12-27|2|46.0|47.0|1.0|2.17|5|2|47.25|45.5|Upward|2383|20,789,331
KCE|2022-12-28|2022-12-30|3|46.75|46.5|-0.25|-0.53|0|0|47.5|46.25|Downward|2386|37,571,835
KCE|2023-01-03|2023-01-03|1|47.25|47.25|0.0|0.0|1|1|48.0|46.25|Upward|2387|28,906,300
KCE|2023-01-04|2023-01-05|2|46.0|45.0|-1.0|-2.17|-3|-2|47.5|44.5|Downward|2389|31,517,549
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|9|3|50.5|44.75|Upward|2392|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|1|1|50.75|49.25|Downward|2393|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|1|1|53.0|49.5|Upward|2394|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-11|-2|53.0|48.5|Downward|2400|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|1|1|50.25|48.75|Upward|2401|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|1|1|51.25|49.25|Downward|2402|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|1|1|50.0|49.25|Upward|2403|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|1|1|50.25|48.75|Downward|2404|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|1|1|50.5|49.0|Upward|2405|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|1|1|50.5|49.5|Downward|2406|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|14|3|58.5|50.5|Upward|2410|214,389,940
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|1|1|57.75|56.25|Downward|2411|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|1|1|57.75|56.0|Upward|2412|17,516,788
KCE|2023-02-08|2023-02-10|3|50.5|47.25|-3.25|-6.44|-12|-4|55.25|47.25|Downward|2415|202,268,953
KCE|2023-02-13|2023-02-13|1|48.0|48.0|0.0|0.0|1|1|48.25|46.75|Upward|2416|16,263,448
KCE|2023-02-14|2023-02-15|2|47.0|46.75|-0.25|-0.53|0|0|48.75|46.75|Downward|2418|32,681,327
MC|2022-02-15|2022-02-15|1|9.8|9.8|0.0|0.0|1|1|9.9|9.65|Downward|2419|2,508,834
MC|2022-02-17|2022-02-18|2|9.9|9.9|0.0|0.0|1|0|10.1|9.75|Upward|2421|5,696,110
MC|2022-02-21|2022-02-22|2|9.8|9.75|-0.05|-0.51|0|0|9.95|9.65|Downward|2423|3,463,085
MC|2022-02-23|2022-02-23|1|9.9|9.9|0.0|0.0|1|1|9.9|9.6|Upward|2424|3,159,136
MC|2022-02-24|2022-02-24|1|9.1|9.1|0.0|0.0|1|1|9.5|9.1|Downward|2425|4,296,137
MC|2022-02-25|2022-02-25|1|9.35|9.35|0.0|0.0|1|1|9.4|9.1|Upward|2426|1,740,810
MC|2022-02-28|2022-03-02|3|9.2|9.1|-0.1|-1.09|-1|-1|9.4|9.05|Downward|2429|2,767,808
MC|2022-03-03|2022-03-03|1|9.25|9.25|0.0|0.0|1|1|9.4|9.15|Upward|2430|1,368,486
MC|2022-03-04|2022-03-07|2|9.15|8.9|-0.25|-2.73|-4|-2|9.25|8.85|Downward|2432|3,541,933
MC|2022-03-08|2022-03-09|2|9.05|9.1|0.05|0.55|2|1|9.1|8.8|Upward|2434|3,297,972
MC|2022-03-10|2022-03-10|1|9.05|9.05|0.0|0.0|1|1|9.15|8.95|Downward|2435|1,246,520
MC|2022-03-11|2022-03-14|2|9.1|9.1|0.0|0.0|1|0|9.1|8.95|Upward|2437|310,001
MC|2022-03-15|2022-03-15|1|9.0|9.0|0.0|0.0|1|1|9.1|8.95|Downward|2438|296,802
MC|2022-03-16|2022-03-17|2|9.05|9.1|0.05|0.55|2|1|9.1|9.0|Upward|2440|574,222
MC|2022-03-18|2022-03-18|1|9.05|9.05|0.0|0.0|1|1|9.1|9.05|Downward|2441|165,464
MC|2022-03-21|2022-03-21|1|9.1|9.1|0.0|0.0|1|1|9.1|9.05|Upward|2442|218,526
MC|2022-03-22|2022-03-29|6|9.05|9.05|0.0|0.0|1|0|9.1|8.95|Downward|2448|1,428,617
MC|2022-03-30|2022-03-30|1|9.1|9.1|0.0|0.0|1|1|9.1|9.05|Upward|2449|126,154
MC|2022-03-31|2022-04-05|4|9.05|9.0|-0.05|-0.55|0|0|9.1|9.0|Downward|2453|2,472,092
MC|2022-04-07|2022-04-08|2|9.05|9.1|0.05|0.55|2|1|9.1|8.95|Upward|2455|909,200
MC|2022-04-11|2022-04-18|6|9.05|9.0|-0.05|-0.55|0|0|9.1|8.95|Downward|2458|1,152,031
MC|2022-04-19|2022-04-20|2|9.05|9.05|0.0|0.0|1|0|9.05|9.0|Upward|2460|792,206
MC|2022-04-21|2022-04-21|1|8.95|8.95|0.0|0.0|1|1|9.05|8.95|Downward|2461|676,422
MC|2022-04-22|2022-04-26|3|9.0|9.05|0.05|0.56|2|0|9.05|8.9|Upward|2464|1,493,232
MC|2022-04-27|2022-04-27|1|9.0|9.0|0.0|0.0|1|1|9.05|8.9|Downward|2465|629,587
MC|2022-04-28|2022-04-29|2|9.05|9.05|0.0|0.0|1|0|9.15|8.95|Upward|2467|1,067,336
MC|2022-05-03|2022-05-09|5|9.0|8.9|-0.1|-1.11|-1|-1|9.1|8.8|Downward|2471|2,918,431
MC|2022-05-10|2022-05-11|2|8.95|8.95|0.0|0.0|1|0|8.95|8.8|Upward|2473|888,174
MC|2022-05-12|2022-05-13|2|8.8|8.8|0.0|0.0|1|0|8.95|8.7|Downward|2475|1,804,828
MC|2022-05-17|2022-05-18|2|8.95|9.0|0.05|0.56|2|1|9.05|8.8|Upward|2477|777,834
MC|2022-05-19|2022-05-19|1|8.95|8.95|0.0|0.0|1|1|9.0|8.9|Downward|2478|136,162
MC|2022-05-20|2022-05-31|8|9.0|9.4|0.4|4.44|9|1|9.45|8.9|Upward|2486|3,966,631
MC|2022-06-01|2022-06-01|1|9.35|9.35|0.0|0.0|1|1|9.4|9.3|Downward|2487|497,341
MC|2022-06-02|2022-06-06|3|9.4|9.5|0.1|1.06|3|1|9.85|9.3|Upward|2489|2,404,788
MC|2022-06-07|2022-06-13|5|9.45|9.3|-0.15|-1.59|-2|-1|9.55|9.25|Downward|2494|3,280,627
MC|2022-06-14|2022-06-14|1|9.35|9.35|0.0|0.0|1|1|9.35|9.2|Upward|2495|364,610
MC|2022-06-15|2022-06-17|3|9.3|9.25|-0.05|-0.54|0|0|9.4|9.1|Downward|2498|1,577,998
MC|2022-06-20|2022-06-21|2|9.4|9.5|0.1|1.06|3|1|9.6|9.25|Upward|2500|1,363,960
MC|2022-06-22|2022-06-23|2|9.4|9.4|0.0|0.0|1|0|9.5|9.35|Downward|2502|938,391
MC|2022-06-24|2022-06-27|2|9.5|9.5|0.0|0.0|1|0|9.55|9.4|Upward|2504|2,335,724
MC|2022-06-28|2022-06-28|1|9.45|9.45|0.0|0.0|1|1|9.5|9.4|Downward|2505|444,928
MC|2022-06-29|2022-06-29|1|9.55|9.55|0.0|0.0|1|1|9.55|9.45|Upward|2506|395,246
MC|2022-06-30|2022-07-06|5|9.45|9.2|-0.25|-2.65|-4|-1|9.55|9.15|Downward|2511|4,386,894
MC|2022-07-07|2022-07-14|6|9.25|9.4|0.15|1.62|4|0|9.45|9.15|Upward|2516|845,652
MC|2022-07-15|2022-07-15|1|9.2|9.2|0.0|0.0|1|1|9.35|9.1|Downward|2517|364,310
MC|2022-07-18|2022-08-01|11|9.3|9.6|0.3|3.23|7|0|9.6|9.2|Upward|2526|2,842,022
MC|2022-08-02|2022-08-02|1|9.55|9.55|0.0|0.0|1|1|9.8|9.45|Downward|2527|720,334
MC|2022-08-03|2022-08-08|4|9.6|9.65|0.05|0.52|2|0|9.65|9.5|Upward|2531|588,489
MC|2022-08-09|2022-08-22|10|9.6|9.55|-0.05|-0.52|0|0|9.7|9.45|Downward|2540|3,159,950
MC|2022-08-23|2022-08-26|4|9.6|9.8|0.2|2.08|5|1|9.8|9.55|Upward|2544|1,832,798
MC|2022-08-29|2022-08-29|1|9.75|9.75|0.0|0.0|1|1|9.8|9.7|Downward|2545|727,654
MC|2022-08-30|2022-08-30|1|9.95|9.95|0.0|0.0|1|1|9.95|9.75|Upward|2546|845,872
MC|2022-08-31|2022-09-01|2|10.0|10.0|0.0|0.0|1|0|10.1|9.85|Downward|2548|1,686,215
MC|2022-09-02|2022-09-05|2|10.2|10.3|0.1|0.98|2|1|10.4|10.0|Upward|2550|1,526,251
MC|2022-09-06|2022-09-06|1|10.1|10.1|0.0|0.0|1|1|10.3|10.0|Downward|2551|487,039
MC|2022-09-07|2022-09-08|2|10.3|10.3|0.0|0.0|1|0|10.4|10.1|Upward|2553|1,080,199
MC|2022-09-09|2022-09-09|1|10.2|10.2|0.0|0.0|1|1|10.3|10.1|Downward|2554|212,228
MC|2022-09-12|2022-09-14|3|10.3|10.4|0.1|0.97|2|0|10.4|10.1|Upward|2557|1,152,365
MC|2022-09-15|2022-09-19|3|10.2|10.1|-0.1|-0.98|0|0|10.4|10.0|Downward|2560|1,169,943
MC|2022-09-20|2022-09-20|1|10.2|10.2|0.0|0.0|1|1|10.2|10.0|Upward|2561|311,587
MC|2022-09-21|2022-09-21|1|10.1|10.1|0.0|0.0|1|1|10.2|9.95|Downward|2562|824,703
MC|2022-09-22|2022-09-27|4|10.2|10.2|0.0|0.0|1|0|10.2|10.0|Upward|2566|1,829,101
MC|2022-09-28|2022-10-07|8|10.0|10.0|0.0|0.0|1|0|10.2|9.85|Downward|2574|3,418,890
MC|2022-10-10|2022-10-11|2|9.95|9.95|0.0|0.0|1|0|9.95|9.9|Upward|2576|894,708
MC|2022-10-12|2022-10-17|4|9.9|10.0|0.1|1.01|3|0|9.95|9.85|Downward|2578|710,653
MC|2022-10-18|2022-10-31|10|10.1|9.95|-0.15|-1.49|-1|-1|9.95|10.0|Upward|2587|7,896,500
MC|2022-11-01|2022-11-02|2|10.0|10.0|0.0|0.0|1|0|10.1|10.0|Downward|2589|1,568,718
MC|2022-11-03|2022-11-04|2|9.8|9.8|0.0|0.0|1|0|9.8|9.65|Upward|2591|782,928
MC|2022-11-07|2022-11-07|1|9.7|9.7|0.0|0.0|1|1|9.8|9.7|Downward|2592|673,196
MC|2022-11-08|2022-11-08|1|9.8|9.8|0.0|0.0|1|1|9.85|9.7|Upward|2593|417,477
MC|2022-11-09|2022-11-09|1|9.7|9.7|0.0|0.0|1|1|9.8|9.7|Downward|2594|225,296
MC|2022-11-10|2022-11-10|1|9.8|9.8|0.0|0.0|1|1|9.8|9.7|Upward|2595|235,349
MC|2022-11-11|2022-11-11|1|10.0|10.0|0.0|0.0|1|1|10.1|9.8|Downward|2596|1,402,470
MC|2022-11-14|2022-11-14|1|9.85|9.85|0.0|0.0|1|1|10.0|9.85|Upward|2597|624,483
MC|2022-11-15|2022-11-15|1|9.8|9.8|0.0|0.0|1|1|9.9|9.75|Downward|2598|463,539
MC|2022-11-16|2022-11-17|2|9.85|9.95|0.1|1.02|3|1|9.95|9.8|Upward|2600|825,510
MC|2022-11-18|2022-11-18|1|10.0|10.0|0.0|0.0|1|1|10.1|9.9|Downward|2601|325,732
MC|2022-11-21|2022-11-21|1|10.1|10.1|0.0|0.0|1|1|10.2|10.0|Upward|2602|666,553
MC|2022-11-22|2022-11-23|2|10.0|10.0|0.0|0.0|1|0|10.2|10.0|Downward|2604|1,391,904
MC|2022-11-24|2022-11-24|1|9.95|9.95|0.0|0.0|1|1|10.1|9.95|Upward|2605|354,368
MC|2022-11-25|2022-12-01|5|10.1|10.0|-0.1|-0.99|0|0|10.2|10.0|Downward|2610|3,314,177
MC|2022-12-02|2022-12-02|1|9.95|9.95|0.0|0.0|1|1|10.1|9.95|Upward|2611|554,246
MC|2022-12-06|2022-12-06|1|10.0|10.0|0.0|0.0|1|1|10.1|9.95|Downward|2612|1,547,236
MC|2022-12-07|2022-12-07|1|10.2|10.2|0.0|0.0|1|1|10.3|10.0|Upward|2613|679,766
MC|2022-12-08|2022-12-09|2|10.1|10.1|0.0|0.0|1|0|10.3|10.1|Downward|2615|443,985
MC|2022-12-13|2022-12-14|2|10.5|10.6|0.1|0.95|2|1|10.7|10.2|Upward|2617|3,051,997
MC|2022-12-15|2022-12-20|4|10.5|10.2|-0.3|-2.86|-2|-1|10.7|10.2|Downward|2621|2,774,493
MC|2022-12-21|2022-12-27|5|10.3|10.6|0.3|2.91|4|0|10.6|10.2|Upward|2626|1,473,945
MC|2022-12-28|2023-01-05|7|10.5|10.5|0.0|0.0|1|0|10.7|10.3|Downward|2632|2,508,185
MC|2023-01-06|2023-01-10|3|10.8|11.2|0.4|3.7|5|1|11.2|10.5|Upward|2635|5,029,087
MC|2023-01-11|2023-01-11|1|11.0|11.0|0.0|0.0|1|1|11.1|10.7|Downward|2636|1,488,870
MC|2023-01-12|2023-01-12|1|11.1|11.1|0.0|0.0|1|1|11.2|10.8|Upward|2637|1,363,029
MC|2023-01-13|2023-01-13|1|11.0|11.0|0.0|0.0|1|1|11.3|11.0|Downward|2638|1,259,169
MC|2023-01-16|2023-01-19|4|11.2|11.7|0.5|4.46|6|1|11.7|11.0|Upward|2642|6,694,798
MC|2023-01-20|2023-01-23|2|11.6|11.3|-0.3|-2.59|-2|-1|11.8|11.3|Downward|2644|2,320,749
MC|2023-01-24|2023-01-26|3|11.6|11.9|0.3|2.59|4|1|11.9|11.3|Upward|2647|4,617,106
MC|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|1|0|11.9|11.7|Downward|2649|900,523
MC|2023-01-31|2023-01-31|1|11.9|11.9|0.0|0.0|1|1|11.9|11.7|Upward|2650|1,180,849
MC|2023-02-01|2023-02-02|2|11.8|11.4|-0.4|-3.39|-3|-2|12.0|11.4|Downward|2652|3,035,796
MC|2023-02-03|2023-02-06|2|11.6|11.7|0.1|0.86|2|1|11.8|11.3|Upward|2654|2,606,769
MC|2023-02-07|2023-02-08|2|11.6|11.6|0.0|0.0|1|0|11.9|11.5|Downward|2656|3,253,713
MC|2023-02-09|2023-02-10|2|11.7|12.2|0.5|4.27|6|3|12.7|11.6|Upward|2658|8,043,176
MC|2023-02-13|2023-02-15|3|12.1|11.9|-0.2|-1.65|-1|-1|12.5|11.7|Downward|2661|7,118,010
MEGA|2022-02-15|2022-02-15|1|43.25|43.25|0.0|0.0|1|1|43.75|42.75|Downward|2662|4,711,865
MEGA|2022-02-17|2022-02-18|2|43.5|43.5|0.0|0.0|1|0|44.25|43.0|Upward|2664|6,560,588
MEGA|2022-02-21|2022-02-22|2|43.25|42.75|-0.5|-1.16|-1|-1|43.5|42.25|Downward|2666|6,398,392
MEGA|2022-02-23|2022-02-23|1|46.0|46.0|0.0|0.0|1|1|46.0|43.25|Upward|2667|8,423,119
MEGA|2022-02-24|2022-02-24|1|42.75|42.75|0.0|0.0|1|1|44.5|42.75|Downward|2668|10,767,502
MEGA|2022-02-25|2022-02-25|1|43.25|43.25|0.0|0.0|1|1|44.0|43.0|Upward|2669|5,077,446
MEGA|2022-02-28|2022-02-28|1|43.0|43.0|0.0|0.0|1|1|43.5|42.25|Downward|2670|4,048,744
MEGA|2022-03-01|2022-03-01|1|44.75|44.75|0.0|0.0|1|1|45.25|43.25|Upward|2671|4,571,006
MEGA|2022-03-02|2022-03-02|1|43.5|43.5|0.0|0.0|1|1|45.0|43.25|Downward|2672|8,987,889
MEGA|2022-03-03|2022-03-03|1|44.5|44.5|0.0|0.0|1|1|45.0|43.75|Upward|2673|4,460,904
MEGA|2022-03-04|2022-03-08|3|43.75|41.5|-2.25|-5.14|-8|-3|44.75|40.25|Downward|2676|13,620,441

In [18]:
os.chdir("C:\\users\\user\\onedrive\\a7\\Ad hoc")
%pwd

'C:\\users\\user\\onedrive\\a7\\Ad hoc'

### call rails runner db/crt_sales.rb

In [19]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-15' AND t.status IN ("B","I", "O", "S")
ORDER BY a.name

In [20]:
df = pd.read_sql(sql, conlite)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('chg_acc = to_price - fm_price',inplace=True)
df['%chg_acc'] = round(df['chg_acc']/df['fm_price']*100,2)
df

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,status,market,chg_acc,%chg_acc
0,BANPU,2023-02-14,2023-02-15,11.00,11.00,219310115,11.30,10.90,B,SET50,0.00,0.00
1,CK,2023-02-14,2023-02-15,22.00,22.00,5278851,22.30,21.60,O,SET100,0.00,0.00
2,CKP,2023-02-08,2023-02-15,4.66,4.28,131875538,4.74,4.24,O,SET100,-0.38,-8.15
3,DIF,2023-02-10,2023-02-15,13.30,13.20,48275264,13.40,13.20,I,SET,-0.10,-0.75
4,IVL,2023-02-15,2023-02-15,40.00,40.00,9498388,40.50,39.50,I,SET50,0.00,0.00
5,JASIF,2023-02-10,2023-02-15,8.20,8.15,23164926,8.25,8.10,I,SET,-0.05,-0.61
6,JMART,2023-02-03,2023-02-15,37.25,28.50,165286876,37.75,28.50,B,SET50,-8.75,-23.49
7,JMT,2023-02-15,2023-02-15,42.75,42.75,75936256,50.50,42.00,B,SET50,0.00,0.00
8,KCE,2023-02-14,2023-02-15,47.00,46.75,32681327,48.75,46.75,B,SET100,-0.25,-0.53
9,MC,2023-02-13,2023-02-15,12.10,11.90,7118010,12.50,11.70,O,sSET,-0.20,-1.65
10,MEGA,2023-02-10,2023-02-15,51.50,48.00,11814734,52.00,47.25,O,SET100,-3.50,-6.80
11,ORI,2023-02-13,2023-02-15,11.80,11.60,17788630,12.00,11.50,I,SET100,-0.20,-1.69
12,PTT,2023-02-14,2023-02-15,32.75,32.75,75401923,32.75,32.25,O,SET50,0.00,0.00
13,RCL,2023-02-13,2023-02-15,29.50,29.00,10038784,30.75,29.00,B,SET100,-0.50,-1.69
14,SAT,2023-02-07,2023-02-15,21.50,20.70,5842395,21.70,20.70,O,SET,-0.80,-3.72
15,SINGER,2023-02-10,2023-02-15,26.75,18.80,158014772,27.50,18.60,B,SET100,-7.95,-29.72
16,TCAP,2023-02-08,2023-02-15,42.75,42.75,8797575,43.00,42.50,O,SET100,0.00,0.00
17,TMT,2023-02-13,2023-02-15,8.05,7.95,728525,8.10,7.85,S,SET,-0.10,-1.24
18,TTB,2023-02-14,2023-02-15,1.40,1.39,361467529,1.42,1.38,O,SET50,-0.01,-0.71
19,WHAIR,2023-02-15,2023-02-15,7.80,7.80,279749,7.90,7.80,I,SET,0.00,0.00