In [1]:
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:@localhost:3306/portfolio_development')
conpf = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

In [2]:
sql = '''
SELECT *
FROM dividends
LIMIT 1'''
struct = pd.read_sql(sql, conpf)
struct.dtypes

id            int64
stock_id      int64
name         object
year          int64
quarter       int64
number        int64
ppu         float64
amt         float64
net         float64
x_date       object
p_date       object
dtype: object

In [3]:
sql = '''
SELECT YEAR(p_date) AS p_year, MONTH(p_date) AS p_month, name, year, quarter, number, ppu, amt, net, x_date, p_date
FROM dividends
WHERE YEAR(p_date) = 2022
'''
dtl_by_month = pd.read_sql(sql, conpf)
dtl_by_month.dtypes

p_year       int64
p_month      int64
name        object
year         int64
quarter      int64
number       int64
ppu        float64
amt        float64
net        float64
x_date      object
p_date      object
dtype: object

In [4]:
dtl_by_month['x_date'] = pd.to_datetime(dtl_by_month['x_date'])
dtl_by_month['p_date'] = pd.to_datetime(dtl_by_month['p_date'])
dtl_by_month.dtypes

p_year              int64
p_month             int64
name               object
year                int64
quarter             int64
number              int64
ppu               float64
amt               float64
net               float64
x_date     datetime64[ns]
p_date     datetime64[ns]
dtype: object

In [5]:
ttl_by_month = dtl_by_month.groupby(['p_year','p_month','name'], as_index=True).agg(
    {
        'net':['sum','count'],
    }
)
ttl_by_month

                           net
                           sum count
p_year p_month name
2022   2       LPF      1547.1     1
       3       AIMIRT   1989.0     1
               CPNCG    1999.8     1
               DIF     15660.0     1
               JASIF   27500.0     1
...                        ...   ...
       12      JASIF   29900.0     1
               RCL     49800.0     1
               TFFIF    1003.0     1
               WHAIR    6818.4     1
               WHART    6893.1     1

[71 rows x 2 columns]

In [6]:
ttl_by_month.sum()

net  sum      661087.04
     count        71.00
dtype: float64

In [7]:
ttl_by_month.groupby(level='p_month').sum()

               net
               sum count
p_month
2          1547.10     1
3         55572.24     6
4         44670.00     6
5        214884.69    19
6         51232.10     5
8          7155.00     2
9        164892.61    21
10         5265.00     1
12       115868.30    10

In [26]:
dtl_by_month.dtypes

name              object
p_date    datetime64[ns]
amt              float64
net              float64
refund           float64
year               int64
q                  int64
dtype: object

In [27]:
dtl_by_month.sort_values(['p_date','name'],ascending=[True,True])

      name     p_date      amt      net  refund  year  q
70     LPF 2022-02-15   1719.0   1547.1   171.9  2021  4
69   CPNCG 2022-03-04   2222.0   1999.8   222.2  2021  4
68     DIF 2022-03-04  15660.0  15660.0     0.0  2021  4
67   JASIF 2022-03-21  27500.0  27500.0     0.0  2021  4
66   WHART 2022-03-25   2390.0   2151.0   239.0  2021  4
..     ...        ...      ...      ...     ...   ... ..
4    WHART 2022-12-13   7659.0   6893.1   765.9  2022  3
2      IVL 2022-12-15    960.0    864.0    96.0  2022  3
3    WHAIR 2022-12-15   7576.0   6818.4   757.6  2022  3
1   GVREIT 2022-12-23   3822.0   3439.8   382.2  2022  3
0    TFFIF 2022-12-28   1003.0   1003.0     0.0  2022  3

[71 rows x 7 columns]

In [28]:
dtl_by_month['net'].sum()

661087.0399999999

In [29]:
sql = '''
SELECT YEAR(p_date) AS pay_year, SUM(amt) AS grs_amt, SUM(net) AS net_amt, SUM(amt-net) AS refund
FROM dividends
GROUP BY pay_year
ORDER BY pay_year DESC'''
ttl_by_year = pd.read_sql(sql, conpf)
ttl_by_year

   pay_year    grs_amt    net_amt    refund
0      2022  708367.91  661087.04  47280.87
1      2021  752315.10  700874.50  51440.60
2      2020  616228.94  576030.84  40198.10
3      2019  552424.34  510266.46  42157.88
4      2018  351895.60  309725.58  42170.02
5      2017  245981.10  219514.23  26466.87

In [31]:
sql = '''
SELECT name, COUNT(*) AS qtrs, SUM(net) AS ttl_net
FROM dividends
GROUP BY name
ORDER BY SUM(net) DESC'''
total = pd.read_sql(sql, conpf)
total.head(10)

      name  qtrs    ttl_net
0    JASIF    19  438400.00
1      MCS    11  312680.00
2      DIF    15  224149.50
3      RCL     4  112200.00
4  CPNREIT    11  106879.10
5      ORI    11  102330.00
6    NOBLE     4  100980.00
7      SAT     5   96040.58
8    TISCO     4   82260.00
9   FSMART     7   80244.00

### Summarized profit by name

In [15]:
sql = '''
SELECT name, sum(profit) AS profit
FROM sells JOIN buys ON sells.buy_id = buys.id
JOIN stocks ON buys.stock_id = stocks.id
GROUP BY stocks.name
ORDER BY sum(profit) DESC LIMIT 10'''
profits_by_stock = pd.read_sql(sql, conpf)
profits_by_stock

      name     profit
0  CPNREIT  545770.06
1    THANI  237046.32
2   BEAUTY  192974.08
3      JMT  175955.98
4      MTC  147177.71
5    ASIAN  141685.61
6       TU  125061.53
7    SAWAD  115506.59
8      SIS  110986.74
9   SINGER   98125.73

In [32]:
sql = '''
SELECT YEAR(date) AS year, MONTH(date) AS month, profit
FROM sells 
WHERE YEAR(date) = 2022
ORDER BY YEAR(date) DESC, MONTH(date) DESC
'''
sells = pd.read_sql(sql, conpf)
sells

     year  month    profit
0    2022     12   6737.52
1    2022     12 -13745.25
2    2022     12 -24772.44
3    2022     12 -23275.75
4    2022     12 -15445.20
..    ...    ...       ...
104  2022      1  18150.32
105  2022      1 -10846.64
106  2022      1    130.89
107  2022      1  -1644.03
108  2022      1   5040.41

[109 rows x 3 columns]

In [33]:
grouped = sells.groupby(['year','month'])
grouped

In [34]:
profit_by_month = grouped['profit'].sum()
profit_by_month

year  month
2022  1        117432.48
      2        -81958.99
      3         35536.86
      4           797.09
      5        -44273.12
      6         -9641.76
      7        -17849.25
      8          3613.24
      9          8317.61
      10       -37156.96
      11      -104006.85
      12       -72223.72
Name: profit, dtype: float64

In [35]:
grouped.agg(['sum','mean', 'max', 'min','count'])

               profit
                  sum          mean       max       min count
year month
2022 1      117432.48   5592.022857  18150.32 -10846.64    21
     2      -81958.99  -3414.957917  15105.18 -64814.00    24
     3       35536.86   4442.107500  15434.37 -12646.75     8
     4         797.09    113.870000   6116.26  -7085.31     7
     5      -44273.12  -3162.365714   5929.44 -14873.22    14
     6       -9641.76  -1377.394286   8215.91 -12624.60     7
     7      -17849.25  -4462.312500    531.21  -9411.98     4
     8        3613.24   1806.620000   3725.88   -112.64     2
     9        8317.61   2079.402500   3643.39    146.83     4
     10     -37156.96  -9289.240000   4121.26 -23879.59     4
     11    -104006.85 -13000.856250   4523.80 -25469.78     8
     12     -72223.72 -12037.286667   6737.52 -24772.44     6

### Temporary process to calculate dividend portion of profit

In [36]:
year = 2022
quarter = 4

In [37]:
sql = """
SELECT name, year, quarter, aq_eps, ay_eps
FROM epss 
WHERE year = %s AND quarter = %s
"""
sql = sql % (year, quarter)
df_epss = pd.read_sql(sql, conlt)
df_epss.head()

     name  year  quarter  aq_eps  ay_eps
0      MC  2022        4  0.6100  0.5600
1   OISHI  2022        4  3.1900  1.4600
2     AOT  2022        4 -0.7800 -1.1400
3  GVREIT  2022        4  0.7888  0.8655
4   TFFIF  2022        4  0.4051  0.2463

In [38]:
sql = '''
SELECT name, dividend
FROM dividend 
'''
df_dividend = pd.read_sql(sql, const)
df_dividend

       name  dividend
0     WHART    0.7583
1        QH    0.1000
2     BANPU    0.7000
3   CPNREIT    0.9059
4       MCS    0.5000
..      ...       ...
80     GFPT    0.1000
81    PTTEP    7.2500
82       MC    0.6000
83      RCL    7.0000
84      TOP    2.6000

[85 rows x 2 columns]

In [39]:
df_merge = pd.merge(df_epss, df_dividend, on='name', how='inner')
df_merge['xxx_pct'] = df_merge.dividend / df_merge.aq_eps * 100
df_merge.set_index('name',inplace=True)
df_merge.sort_values(['xxx_pct'],ascending=[True])

        year  quarter  aq_eps  ay_eps  dividend    xxx_pct
name
TFFIF   2022        4  0.4051  0.2463    0.3721  91.853863
MC      2022        4  0.6100  0.5600    0.6000  98.360656
GVREIT  2022        4  0.7888  0.8655    0.7786  98.706897

In [41]:
df_merge.loc['TFFIF']

year        2022.000000
quarter        4.000000
aq_eps         0.405100
ay_eps         0.246300
dividend       0.372100
xxx_pct       91.853863
Name: TFFIF, dtype: float64