#### SQLite port_lite database: sales, stocks table
#### csv files: daily-watch-list, daily-sales, monitors, stocks-all

### Restart and Run All Cells | daily-watch-list & daily-sales upload to obsidian

In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 2, 16)

### Yesterday = Last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-16
yesterday: 2023-02-15

In [3]:
#cols = 'fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','chg_acc':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','%chg_acc':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### Begin of Tables in the process

In [4]:
sql = """
SELECT * 
FROM sales 
ORDER BY id DESC LIMIT 1
"""
tmp = pd.read_sql(sql, conlite)
tmp["fm_date"] = pd.to_datetime(tmp["fm_date"])
tmp["to_date"] = pd.to_datetime(tmp["to_date"])
tmp["created_at"] = pd.to_datetime(tmp["created_at"])
tmp["updated_at"] = pd.to_datetime(tmp["updated_at"])
tmp.style.format(format_dict)

In [5]:
names = tmp["name"]
type(names)

pandas.core.series.Series

In [6]:
name = names.to_string(index=False)
type(name)

str

In [7]:
sql = """
SELECT * 
FROM stocks
WHERE name = '%s'
"""
sql = sql % name
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'WHAIR'

### End of Tables in the process

In [8]:
sql = """
SELECT DISTINCT a.name
FROM sales a 
WHERE to_date = '%s'
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp

SELECT DISTINCT a.name
FROM sales a
WHERE to_date = '2023-02-15'
ORDER BY a.name

      name
0    BANPU
1       CK
2      CKP
3      DIF
4      IVL
5    JASIF
6    JMART
7      JMT
8      KCE
9       MC
10    MEGA
11     ORI
12     PTT
13     RCL
14     SAT
15  SINGER
16    TCAP
17     TMT
18     TTB
19   WHAIR

In [9]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY t.status, a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-15' AND t.status IN ("B","I", "O", "S")
ORDER BY t.status, a.name

### This statement causes program to hang when there is no data

In [10]:
df = pd.read_sql(sql, conlite)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('chg_acc = to_price - fm_price',inplace=True)
df['%chg_acc'] = round(df['chg_acc']/df['fm_price']*100,2)
df.style.format(format_dict)

### Price change up or down more than 3%

In [13]:
# For each row in the DataFrame, generate a series of dates between the start and end dates
df['dates'] = df.apply(lambda x: pd.date_range(x['fm_date'], x['to_date']), axis=1)

# For each row in the DataFrame, select only the business days (Monday through Friday) from the series of dates
df['business_days'] = df['dates'].apply(lambda x: x[x.isin(pd.date_range(x.min(), x.max(), freq='B'))])

# For each row in the DataFrame, count the number of business days between the start and end dates
df['bdays'] = df['business_days'].apply(lambda x: len(x))

In [15]:
colt =  'name %chg_acc status fm_price to_price market \
fm_date bdays max_price min_price'.split()
watch_list = df.loc[abs(df['%chg_acc']) >= 3,colt]
watch_list.sort_values('%chg_acc',ascending=False)
watch_list

,name,%chg_acc,status,fm_price,to_price,market,fm_date,bdays,max_price,min_price
6,JMART,-10.74,I,37.25,33.25,SET50,2023-02-03,7,37.75,33.0

In [ ]:
# cannot use with column that starts with %
#df.query('abs(%chg_acc) >= 1.0')

In [16]:
file_name = "daily-watch-list.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

watch_list.sort_values(['%chg_acc'],ascending=[False]).to_csv(output_file, index=False)
watch_list.sort_values(['%chg_acc'],ascending=[False]).to_csv(data_file, index=False)
watch_list.sort_values(['%chg_acc'],ascending=[False]).to_csv(data_file, index=False)
watch_list.sort_values(['%chg_acc'],ascending=[False]).to_csv(one_file, index=False)
watch_list.sort_values(['%chg_acc'],ascending=[False]).to_csv(osd_file, index=False)

### Create daily-sales from sales

In [17]:
df[colt].style.format(format_dict)

In [18]:
file_name = "daily-sales.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df[colt].sort_values(['%chg_acc'],ascending=[True]).to_csv(output_file, index=False)
df[colt].sort_values(['%chg_acc'],ascending=[True]).to_csv(data_file, index=False)
df[colt].sort_values(['%chg_acc'],ascending=[True]).to_csv(one_file, index=False)
df[colt].sort_values(['%chg_acc'],ascending=[True]).to_csv(osd_file, index=False)

### Create monitors from orders

In [19]:
sql = """
SELECT name, trade 
FROM orders 
ORDER BY name
"""
monitors = pd.read_sql(sql, conlite)
monitors.set_index(["name"], inplace=True)
monitors.sample(5)

      trade
name
CK        B
BANPU     B
WHAIR     S
SAT       B
IVL       S

In [20]:
sql = """
SELECT trade, COUNT(*) AS 'no. of stocks'
FROM orders 
GROUP BY trade
"""
df_tmp = pd.read_sql(sql, conlite)
df_tmp

  trade  no. of stocks
0     B             12
1     S              8

### output_file = iCloud Drive on PC

In [21]:
file_name = "monitors.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name

monitors.to_csv(data_file, header=None)
monitors.to_csv(output_file)
monitors.to_csv(one_file)

### End of daily process

In [22]:
sql = """
SELECT trade, COUNT(*) AS 'no. of stocks'
FROM orders 
GROUP BY trade
"""
df_tmp = pd.read_sql(sql, conlite)
df_tmp

  trade  no. of stocks
0     B             12
1     S              8

In [23]:
sql = """
SELECT name, status, market
FROM stocks 
ORDER BY status, name
"""
stocks = pd.read_sql(sql, conlite)
stocks.set_index(["name"], inplace=True)
stocks

      status  market
name
BANPU      B   SET50
KCE        B  SET100
RCL        B  SET100
SCCC       B     SET
DIF        I     SET
...      ...     ...
SIRI       X     SET
SPALI      X  SET100
SVI        X     SET
TFG        X     SET
TOP        X   SET50

[62 rows x 2 columns]

In [24]:
file_name = "stocks-all.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name

stocks.to_csv(data_file, header=None)
stocks.to_csv(output_file)
stocks.to_csv(one_file)

In [25]:
sql = """
SELECT name, trade 
FROM orders 
WHERE trade IN ("B")
ORDER BY name
"""
buy_candidates = pd.read_sql(sql, conlite)
buy_candidates.set_index(["name"], inplace=True)
buy_candidates

      trade
name
BANPU     B
CK        B
CKP       B
JMT       B
KCE       B
MC        B
MEGA      B
PTT       B
RCL       B
SAT       B
TCAP      B
TTB       B

In [26]:
buy_candidates.shape[0]

12

In [27]:
sql = """
SELECT name, trade 
FROM orders 
WHERE trade IN ("S")
ORDER BY name
"""
sell_candidates = pd.read_sql(sql, conlite)
sell_candidates.set_index(["name"], inplace=True)
sell_candidates

       trade
name
DIF        S
IVL        S
JASIF      S
JMART      S
ORI        S
SINGER     S
TMT        S
WHAIR      S

In [28]:
sell_candidates.shape[0]

8