In [104]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 8), datetime.date(2023, 2, 7))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-08
yesterday: 2023-02-07

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

### Delete files in folder Datasets, if there is no file, error causes program to stop

In [4]:
for filename in glob.glob(os.path.join(dts_path, '*.xlsx')):
    print(f'Delete {filename}')
    os.remove(filename)

Delete /Users/User/Downloads/Datasets\StockQuotation (1).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (2).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (3).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (4).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (5).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (6).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (7).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (8).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation (9).xlsx
Delete /Users/User/Downloads/Datasets\StockQuotation.xlsx

### SET100, sSET, SETCLMV, SETHD, SETTHSI, SETWB, CONMAT, PFREIT, TRANS, ICT

In [5]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

Moved StockQuotation (1).xlsx to Datasets
Moved StockQuotation (2).xlsx to Datasets
Moved StockQuotation (3).xlsx to Datasets
Moved StockQuotation (4).xlsx to Datasets
Moved StockQuotation (5).xlsx to Datasets
Moved StockQuotation (6).xlsx to Datasets
Moved StockQuotation (7).xlsx to Datasets
Moved StockQuotation (8).xlsx to Datasets
Moved StockQuotation (9).xlsx to Datasets
Moved StockQuotation.xlsx to Datasets

In [6]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [7]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
46,IRPC,3.14,0.10,3.29,3.08,3.18,3.06,215814458,676540.67
86,STGT,11.70,0.30,2.63,11.40,12.00,11.40,29837476,349936.55
84,STA,24.00,0.60,2.56,23.40,24.10,23.20,8936406,212336.01
22,CENTEL,55.25,1.25,2.31,54.00,56.00,53.75,8072835,445100.40
71,PTTGC,50.50,0.75,1.51,49.75,51.25,49.50,12175210,616772.28
...,...,...,...,...,...,...,...,...,...
48,JAS,2.32,-0.04,-1.69,2.36,2.36,2.32,5547578,12971.78
50,JMT,52.00,-1.00,-1.89,53.00,53.25,52.00,4507194,235986.74
81,SINGER,27.25,-0.75,-2.68,28.00,28.00,27.25,2025871,55902.27
31,DELTA,942.00,-28.00,-2.89,976.00,978.00,938.00,1869536,1780362.15
52,KCE,52.75,-4.25,-7.46,54.50,55.25,52.50,50784876,2737275.19

In [8]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
87,RS,18.10,0.80,4.62,17.30,18.40,17.30,17920254,322742.53
79,PRIME,1.59,0.07,4.61,1.52,1.60,1.52,6039705,9451.41
133,UBE,1.58,0.06,3.95,1.53,1.59,1.51,34550897,53909.31
3,AI,6.80,0.20,3.03,6.60,6.85,6.60,753080,5072.84
34,GJS,0.36,0.01,2.86,0.35,0.37,0.35,27955302,10077.61
...,...,...,...,...,...,...,...,...,...
104,SMT,5.55,-0.15,-2.63,5.75,5.85,5.55,4567349,26071.36
99,SIS,26.25,-0.75,-2.78,27.25,27.25,26,459655,12159.39
76,PLUS,9,-0.30,-3.23,9.25,9.25,8.90,6855358,62179.61
0,7UP,0.85,-0.03,-3.41,0.88,0.88,0.84,27288257,23417.34
92,SAMART,5.40,-0.20,-3.57,5.60,5.60,5.30,10291565,55837.41

In [9]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
26,IRPC,3.12,0.08,2.63,3.08,3.18,3.06,215819658,676557.00
49,STGT,11.70,0.30,2.63,11.40,12.00,11.40,29837576,349937.72
52,THCOM,16.40,0.30,1.86,16.10,16.60,16.00,6994475,114385.38
38,PTTGC,50.50,0.75,1.51,49.75,51.25,49.50,12175315,616777.59
33,MINT,33.75,0.50,1.50,33.25,33.75,33.00,8939700,298752.08
...,...,...,...,...,...,...,...,...,...
25,INTUCH,71.75,-0.75,-1.03,72.50,72.75,71.50,1365387,98330.10
51,TASCO,18.10,-0.20,-1.09,18.30,18.30,18.00,2258909,40912.22
40,RBF,12.70,-0.20,-1.55,12.90,12.90,12.70,1333802,17075.92
27,JWD,20.30,-0.40,-1.93,20.70,20.70,19.90,5602788,113116.36
42,SAMART,5.40,-0.20,-3.57,5.60,5.60,5.30,10291565,55837.41

In [10]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
4,BCPG,10.10,0.10,1.00,10.00,10.10,10.00,513073,5138.94
15,ORI,11.80,0.10,0.85,11.80,11.90,11.70,1349460,15913.19
1,AP,12.00,0.10,0.84,11.90,12.10,11.90,9783966,117368.64
22,SCC,340.00,2.00,0.59,338.00,340.00,337.00,1123205,380752.79
20,RATCH,42.75,0.25,0.59,42.75,43.00,42.75,413413,17715.55
...,...,...,...,...,...,...,...,...,...
7,CPF,23.40,-0.20,-0.85,23.60,23.60,23.30,15864508,371658.73
16,OSP,28.25,-0.25,-0.88,28.50,28.50,28.25,1115079,31524.00
11,INTUCH,71.75,-0.75,-1.03,72.50,72.75,71.50,1365487,98337.27
14,LH,9.75,-0.15,-1.52,9.85,9.90,9.75,13033055,127890.52
10,HANA,63.00,-1.00,-1.56,62.75,64.00,61.75,10657134,669752.22

In [11]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
82,RS,18.10,0.80,4.62,17.30,18.40,17.30,17920254,322742.53
53,IRPC,3.14,0.10,3.29,3.08,3.18,3.06,215854758,676666.51
99,STGT,11.70,0.30,2.63,11.40,12.00,11.40,29837576,349937.72
98,STA,24.00,0.60,2.56,23.40,24.10,23.20,9165806,217846.73
102,THCOM,16.50,0.40,2.48,16.10,16.60,16.00,6995675,114405.18
...,...,...,...,...,...,...,...,...,...
66,NER,6.35,-0.10,-1.55,6.45,6.50,6.30,6008289,38430.74
48,HANA,63.00,-1.00,-1.56,62.75,64.00,61.75,10657134,669752.22
56,JWD,20.30,-0.40,-1.93,20.70,20.70,19.90,5602788,113116.36
109,TPIPP,3.42,-0.08,-2.29,3.40,3.42,3.40,3194949,10894.17
34,DELTA,942.00,-28.00,-2.89,976.00,978.00,938.00,1869536,1780362.15

In [12]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
25,STA,24.00,0.60,2.56,23.40,24.10,23.20,9165806,217846.73
28,TVO,29.00,0.25,0.87,28.75,29.00,28.75,79262,2288.10
1,BDMS,29.75,0.25,0.85,29.75,30.00,29.50,9499539,282463.18
4,BJC,38.75,0.25,0.65,38.50,39.50,38.50,7147902,278859.29
16,KEX,18.40,0.10,0.55,18.40,18.40,18.10,1525147,27873.44
...,...,...,...,...,...,...,...,...,...
26,THG,67.25,-0.75,-1.10,68.00,68.50,67.00,2145520,145122.94
14,HMPRO,14.50,-0.20,-1.36,14.70,14.80,14.50,22740397,332449.54
21,RBF,12.70,-0.20,-1.55,12.90,12.90,12.70,1333802,17075.92
15,JWD,20.30,-0.40,-1.93,20.70,20.70,19.90,5602788,113116.36
24,SINGER,27.25,-0.75,-2.68,28.00,28.00,27.25,2026471,55918.74

In [13]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_CONMAT = pd.read_excel(input_file, header=9)
df_CONMAT = df_CONMAT[df_CONMAT['%Change'] != '-']
df_CONMAT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
17,UMI,1.57,0.03,1.95,1.54,1.61,1.53,2509915,3977.22
16,TPIPL,1.85,0.03,1.65,1.82,1.85,1.81,8644306,15825.44
19,WIIK,1.88,0.02,1.08,1.86,1.88,1.86,129800,242.65
9,SCC,340.00,2.00,0.59,338.00,340.00,337.00,1123205,380752.79
18,VNG,5.55,0.00,0.00,5.55,5.55,5.50,474200,2608.57
...,...,...,...,...,...,...,...,...,...
5,EPG,8.65,-0.05,-0.57,8.75,8.75,8.60,1144685,9908.59
7,PPP,2.12,-0.02,-0.93,2.14,2.14,2.12,51300,109.37
12,SKN,5.30,-0.05,-0.93,5.40,5.40,5.25,316401,1680.05
11,SCP,5.15,-0.05,-0.96,5.10,5.15,5.10,6900,35.25
14,TASCO,18.10,-0.20,-1.09,18.30,18.30,18.00,2258909,40912.22

In [14]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
57,URBNPF,2,0.06,3.09,2,2,2,100,0.20
31,M-PAT,4.88,0.12,2.52,4.76,4.88,4.76,1200,5.72
20,HYDROGEN,10.30,0.10,0.98,10.30,10.30,10.30,1100,11.33
0,AIMCG,5.50,0.05,0.92,5.50,5.50,5.40,69300,375.12
12,DREIT,6.25,0.05,0.81,6.20,6.30,6.20,8300,51.73
...,...,...,...,...,...,...,...,...,...
22,INETREIT,11.60,-0.10,-0.85,11.60,11.60,11.60,106900,1240.04
40,PPF,11.40,-0.10,-0.87,11.40,11.40,11.40,1000,11.40
13,ERWPF,4.30,-0.04,-0.92,4.32,4.32,4.30,50200,215.88
48,SRIPANWA,7.20,-0.10,-1.37,7.25,7.25,7.20,31402,226.40
18,GVREIT,9.65,-0.15,-1.53,9.75,9.80,9.55,249806,2429.99

In [15]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
1      AOT    74   0.50    0.68 73.50    74 73.25     11957405       880817.97
22   TFFIF  8.25   0.05    0.61  8.20  8.25  8.15      1272325        10433.97
12     KEX 18.40   0.10    0.55 18.40 18.40 18.10      1525347        27877.12
0      AAV  3.08      0       0  3.08  3.10  3.06     11872808        36565.54
2   ASIMAR  1.85      0       0  1.85  1.85  1.85        23102           42.74
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
25     TTA     8  -0.10   -1.23  8.10  8.10     8      1196451         9616.34
19     PRM  7.90  -0.10   -1.25  8.05  8.05  7.90      4023909        32083.13
9      DMT 12.80  -0.20   -1.54    13    13 12.80       432402         5567.13
11     JWD 20.30  -0.40   -1.93 20.70 20.70 19.90      5602788       113116.36
4       BA 14.50  -0.30   -2.03 14.80 14.80 14.40      2136430        31127.47

[23 rows x 9 columns]

In [16]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
33     TWZ  0.08   0.01   14.29  0.08  0.08  0.07      4439700          319.77
27    SVOA  2.70   0.10    3.85  2.60  2.74  2.60      8052812        21781.41
30   THCOM 16.50   0.40    2.48 16.10 16.60    16      6995675       114405.18
5      DIF 13.70   0.10    0.74 13.60 13.70 13.60      4288912        58496.29
16   JASIF  8.25      0       0  8.20  8.25  8.20       737713         6056.24
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
23  SAMTEL  6.65  -0.15   -2.21  6.80  6.80  6.60       571800         3820.55
18     JTS 41.75     -1   -2.34    43 44.50 41.75      1210435        52004.95
25     SIS 26.25  -0.75   -2.78 27.25 27.25    26       459855        12164.64
22  SAMART  5.35  -0.25   -4.46  5.60  5.60  5.30     10403465        56436.08
24     SDC  0.19  -0.01      -5  0.20  0.21  0.17    339191956        63235.93

[33 rows x 9 columns]

In [17]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_CONMAT, df_PFREIT, df_TRANS, df_ICT])
df.shape

(606, 16)

In [18]:
df.Symbol.nunique()

347

In [19]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(347, 16)

In [20]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [21]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.85,-0.03,-3.41,0.88,0.88,0.84,27288257,23417.34
0,AAV,3.06,-0.02,-0.65,3.08,3.10,3.06,11622808,35795.54
1,ACE,2.56,0.00,0.00,2.54,2.56,2.54,9539330,24300.35
2,ADVANC,196.00,-0.50,-0.25,196.00,196.50,195.00,1645166,321944.39
1,AGE,3.70,0,0,3.72,3.74,3.70,781929,2906.42
...,...,...,...,...,...,...,...,...,...
140,WICE,11.60,-0.10,-0.85,11.80,11.80,11.60,1976161,23060.69
19,WIIK,1.88,0.02,1.08,1.86,1.88,1.86,129800,242.65
141,WORK,18.60,0,0,18.60,18.70,18.50,235692,4377.44
142,XPG,1.43,0,0,1.45,1.45,1.42,5150930,7383.57
143,ZEN,18.20,-0.10,-0.55,18.30,18.40,17.90,598057,10920.10

In [22]:
df.insert(1, 'Date', today)

In [23]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-08,3.06,-0.02,-0.65,3.08,3.10,3.06,11622808,35795.54
1,ACE,2023-02-08,2.56,0.00,0.00,2.54,2.56,2.54,9539330,24300.35
2,ADVANC,2023-02-08,196.00,-0.50,-0.25,196.00,196.50,195.00,1645166,321944.39
3,AMATA,2023-02-08,20.20,0.00,0.00,20.30,20.50,20.20,4293746,87111.36
4,AOT,2023-02-08,74.00,0.50,0.68,73.50,74.00,73.25,11951205,880359.42
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-08,6.65,-0.15,-2.21,6.80,6.80,6.60,571800,3820.55
24,SDC,2023-02-08,0.19,-0.01,-5,0.20,0.21,0.17,339191956,63235.93
27,SVOA,2023-02-08,2.70,0.10,3.85,2.60,2.74,2.60,8052812,21781.41
28,SYMC,2023-02-08,6,0,0,6,6,6,3561,21.36
33,TWZ,2023-02-08,0.08,0.01,14.29,0.08,0.08,0.07,4439700,319.77

In [24]:
file_name = "name-ttl.csv"
input_file = data_path + file_name
input_file

'../data/name-ttl.csv'

In [25]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [26]:
df_out = df[colt]
df_out.shape

(347, 10)

In [27]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(194, 10)

In [28]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [29]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'daily_volume'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'daily_volume'],
      dtype='object')

In [30]:
colp = 'name date price high low volume open'.split()
colp

['name', 'date', 'price', 'high', 'low', 'volume', 'open']

In [31]:
file_name = "Price.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colp].to_csv(output_file, header=None, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [32]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

## Must recall whenever there is change in orders

In [101]:
sql = """
SELECT trade, name, qty, price, active, reason, market, xdate 
FROM orders"""
orders = pd.read_sql(sql, conlite)
orders

   trade     name    qty  price  active   reason   market       xdate
0      B    BANPU   6000  10.80       1      DTD    SET50  2023-04-08
1      B      KCE   1000  47.00       1      CUT   SET100  2023-03-21
2      B      RCL   3000  28.75       1       HD   SET100  2023-03-23
3      B       CK   4500  22.50       1     5pct   SET100  2022-12-22
4      B      CKP  20000   4.50       1       3L   SET100  2022-12-22
..   ...      ...    ...    ...     ...      ...      ...         ...
16     S      IVL   2400  44.25       1      DTD    SET50  2023-05-06
17     S    JMART   3600  41.50       1      DTD    SET50  2023-04-19
18     S      JMT   1500  60.00       1      DTD    SET50  2023-04-19
19     S   SINGER   1200  29.25       1      DTD   SET100  2023-04-29
20     B  CPNREIT  10000  17.90       1  RD05pct  PF&REIT  2022-02-02

[21 rows x 8 columns]

In [105]:
file_name = 'orders.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

orders.to_csv(output_file, header=True, index=False)
orders.to_csv(data_file, header=True, index=False)
orders.to_csv(box_file, header=True, index=False)
orders.to_csv(one_file, header=True, index=False)
orders.to_csv(osd_file, header=True, index=False)

In [97]:
file_name = "orders.csv"
input_file = data_path + file_name

orders = pd.read_csv(input_file)
orders

   trade    name    qty  price  active reason  market       xdate
0      B   BANPU   6000  10.80       0    DTD   SET50  2023-04-08
1      B      CK   4500  22.50       0   5pct  SET100  2022-12-22
2      B     CKP  20000   4.50       0     3L  SET100  2022-12-22
3      B    COM7   3000  30.00       0    XXX   SET50  2022-12-22
4      B     CPF   4000  23.00       0    XXX   SET50  2022-12-22
..   ...     ...    ...    ...     ...    ...     ...         ...
16     S     ORI  15000  12.50       0   CP1S  SET100  2023-05-09
17     S  SINGER   1200  29.25       0    DTD  SET100  2023-04-29
18     S     STA   2500  23.00       0    CUT  SET100  2023-04-19
19     S     TMT  12000   8.70       0   C9.0     SET  2023-04-18
20     S   WHAIR  10000   8.90       0     HD     SET  2023-03-04

[21 rows x 8 columns]

In [106]:
orders

   trade     name    qty  price  active   reason   market       xdate
0      B    BANPU   6000  10.80       1      DTD    SET50  2023-04-08
1      B      KCE   1000  47.00       1      CUT   SET100  2023-03-21
2      B      RCL   3000  28.75       1       HD   SET100  2023-03-23
3      B       CK   4500  22.50       1     5pct   SET100  2022-12-22
4      B      CKP  20000   4.50       1       3L   SET100  2022-12-22
..   ...      ...    ...    ...     ...      ...      ...         ...
16     S      IVL   2400  44.25       1      DTD    SET50  2023-05-06
17     S    JMART   3600  41.50       1      DTD    SET50  2023-04-19
18     S      JMT   1500  60.00       1      DTD    SET50  2023-04-19
19     S   SINGER   1200  29.25       1      DTD   SET100  2023-04-29
20     B  CPNREIT  10000  17.90       1  RD05pct  PF&REIT  2022-02-02

[21 rows x 8 columns]

In [107]:
df_merge2 = pd.merge(orders, df_merge, on = 'name', how='inner')
df_merge2

,trade,name,qty,price_x,active,reason,market,xdate,date,price_y,change,%change,open,high,low,volume,daily_volume
0,B,BANPU,6000,10.80,1,DTD,SET50,2023-04-08,2023-02-08,11.20,0.00,0.00,11.30,11.40,11.10,47601625,533638.74
1,B,KCE,1000,47.00,1,CUT,SET100,2023-03-21,2023-02-08,52.75,-4.25,-7.46,54.50,55.25,52.50,50784876,2737275.19
2,B,RCL,3000,28.75,1,HD,SET100,2023-03-23,2023-02-08,30.75,-0.25,-0.81,31.00,31.25,30.75,1049670,32441.58
3,B,CK,4500,22.50,1,5pct,SET100,2022-12-22,2023-02-08,22.60,0.20,0.89,22.50,22.70,22.40,898831,20250.42
4,B,CKP,20000,4.50,1,3L,SET100,2022-12-22,2023-02-08,4.64,-0.04,-0.85,4.68,4.70,4.64,7030427,32814.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,S,IVL,2400,44.25,1,DTD,SET50,2023-05-06,2023-02-08,41.00,0.50,1.23,40.50,41.50,40.50,9271372,381377.94
17,S,JMART,3600,41.50,1,DTD,SET50,2023-04-19,2023-02-08,36.25,-0.50,-1.36,37.00,37.00,36.00,3395145,123715.36
18,S,JMT,1500,60.00,1,DTD,SET50,2023-04-19,2023-02-08,52.00,-1.00,-1.89,53.00,53.25,52.00,4507194,235986.74
19,S,SINGER,1200,29.25,1,DTD,SET100,2023-04-29,2023-02-08,27.25,-0.75,-2.68,28.00,28.00,27.25,2025871,55902.27
20,B,CPNREIT,10000,17.90,1,RD05pct,PF&REIT,2022-02-02,2023-02-08,18.40,-0.10,-0.54,18.50,18.50,18.30,1148579,21149.18

In [108]:
df_merge2['spd'] = 0
#df_merge2['active'] = 1

In [109]:
colo = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'price_x', 'price_y', 'change', '%change',
        'active', 'xdate']
df_merge2[colo]

,trade,name,spd,reason,market,qty,price_x,price_y,change,%change,active,xdate
0,B,BANPU,0,DTD,SET50,6000,10.80,11.20,0.00,0.00,1,2023-04-08
1,B,KCE,0,CUT,SET100,1000,47.00,52.75,-4.25,-7.46,1,2023-03-21
2,B,RCL,0,HD,SET100,3000,28.75,30.75,-0.25,-0.81,1,2023-03-23
3,B,CK,0,5pct,SET100,4500,22.50,22.60,0.20,0.89,1,2022-12-22
4,B,CKP,0,3L,SET100,20000,4.50,4.64,-0.04,-0.85,1,2022-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...
16,S,IVL,0,DTD,SET50,2400,44.25,41.00,0.50,1.23,1,2023-05-06
17,S,JMART,0,DTD,SET50,3600,41.50,36.25,-0.50,-1.36,1,2023-04-19
18,S,JMT,0,DTD,SET50,1500,60.00,52.00,-1.00,-1.89,1,2023-04-19
19,S,SINGER,0,DTD,SET100,1200,29.25,27.25,-0.75,-2.68,1,2023-04-29
20,B,CPNREIT,0,RD05pct,PF&REIT,10000,17.90,18.40,-0.10,-0.54,1,2022-02-02

In [110]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge2[colo].to_csv(output_file, header=True, index=False)
df_merge2[colo].to_csv(osd_file, header=True, index=False)

### call ruby ruby\order-log-new.rb

In [125]:
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [137]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [138]:
!ruby ruby\\order-log-new.rb

trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
B,BANPU,-4,DTD,SET50,6000,10.8,11.2,0.0,0.0,1,2023-04-08
B,KCE,-23,CUT,SET100,1000,47.0,52.75,-4.25,-7.456140350877193,0,2023-03-21
B,RCL,-8,HD,SET100,3000,28.75,30.75,-0.25,-0.8064516129032258,1,2023-03-23
B,CK,-1,5pct,SET100,4500,22.5,22.6,0.2,0.8928571428571429,1,2022-12-22
B,CKP,-7,3L,SET100,20000,4.5,4.64,-0.04,-0.8547008547008547,1,2022-12-22
B,COM7,-7,XXX,SET50,3000,30.0,31.75,0.0,0.0,1,2022-12-22
B,CPF,-4,XXX,SET50,4000,23.0,23.4,-0.2,-0.847457627118644,1,2022-12-22
B,MEGA,-13,5pct,SET100,2000,48.0,51.25,-0.25,-0.4854368932038835,0,2023-03-08
B,PTT,-2,XXX,SET50,3600,32.0,32.5,0.0,0.0,1,2023-03-03
B,TTB,-1,52WL,SET50,90000,1.4,1.41,-0.01,-0.704225352112676,1,2022-12-22
S,JASIF,5,CP1S,SET,10000,8.5,8.25,0,0,1,2023-03-03
S,DIF,3,CUT,SET,10000,14.0,13.7,0.1,0.7352941176470589,1,2023-02-10
S,WHAIR,18,HD,SET,10000,8.9,8,0,0,0,2023-03-04
S,STA,1,CUT,SET100,2500,24.1,24.0,0.6,2.5641025641025643,2,2023-04-19
S,TMT,12,C9.0,SET,12000,8.7,8.1,-0.05,-0.6134969325153374,0,2023-04-18
S,ORI,7,CP1S,SET100,15000,12.5,11.8,0.1,0.8547008547008547,1,2023-05-09
S,IVL,13,DTD,SET50,2400,44.25,41.0,0.5,1.2345679012345678,0,2023-05-06
S,JMART,21,DTD,SET50,3600,41.5,36.25,-0.5,-1.3605442176870748,0,2023-04-19
S,JMT,32,DTD,SET50,1500,60.0,52.0,-1.0,-1.8867924528301887,0,2023-04-19
S,SINGER,8,DTD,SET100,1200,29.25,27.25,-0.75,-2.6785714285714284,1,2023-04-29
B,CPNREIT,-5,RD05pct,PF&REIT,10000,17.9,18.4,-0.1,-0.5405405405405406,1,2022-02-02

In [139]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [140]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.query('spd >= -3 and spd <= 3')

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
3,B,CK,-1,5pct,SET100,4500,22.50,22.60,0.20,0.89,1,2022-12-22
8,B,PTT,-2,XXX,SET50,3600,32.00,32.50,0.00,0.00,1,2023-03-03
9,B,TTB,-1,52WL,SET50,90000,1.40,1.41,-0.01,-0.70,1,2022-12-22
11,S,DIF,3,CUT,SET,10000,14.00,13.70,0.10,0.74,1,2023-02-10
13,S,STA,1,CUT,SET100,2500,24.10,24.00,0.60,2.56,2,2023-04-19

In [141]:
df.query('active == 1')

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
0,B,BANPU,-4,DTD,SET50,6000,10.80,11.20,0.00,0.00,1,2023-04-08
2,B,RCL,-8,HD,SET100,3000,28.75,30.75,-0.25,-0.81,1,2023-03-23
3,B,CK,-1,5pct,SET100,4500,22.50,22.60,0.20,0.89,1,2022-12-22
4,B,CKP,-7,3L,SET100,20000,4.50,4.64,-0.04,-0.85,1,2022-12-22
5,B,COM7,-7,XXX,SET50,3000,30.00,31.75,0.00,0.00,1,2022-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...
10,S,JASIF,5,CP1S,SET,10000,8.50,8.25,0.00,0.00,1,2023-03-03
11,S,DIF,3,CUT,SET,10000,14.00,13.70,0.10,0.74,1,2023-02-10
15,S,ORI,7,CP1S,SET100,15000,12.50,11.80,0.10,0.85,1,2023-05-09
19,S,SINGER,8,DTD,SET100,1200,29.25,27.25,-0.75,-2.68,1,2023-04-29
20,B,CPNREIT,-5,RD05pct,PF&REIT,10000,17.90,18.40,-0.10,-0.54,1,2022-02-02

In [142]:
df.query('active == 0')

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
1,B,KCE,-23,CUT,SET100,1000,47.00,52.75,-4.25,-7.46,0,2023-03-21
7,B,MEGA,-13,5pct,SET100,2000,48.00,51.25,-0.25,-0.49,0,2023-03-08
12,S,WHAIR,18,HD,SET,10000,8.90,8.00,0.00,0.00,0,2023-03-04
14,S,TMT,12,C9.0,SET,12000,8.70,8.10,-0.05,-0.61,0,2023-04-18
16,S,IVL,13,DTD,SET50,2400,44.25,41.00,0.50,1.23,0,2023-05-06
17,S,JMART,21,DTD,SET50,3600,41.50,36.25,-0.50,-1.36,0,2023-04-19
18,S,JMT,32,DTD,SET50,1500,60.00,52.00,-1.00,-1.89,0,2023-04-19