### Restart and Run All Cells

In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 3, 10), datetime.date(2023, 3, 9))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-03-10
yesterday: 2023-03-09

## Must rerun whenever there is change in orders

In [3]:
sql = """
SELECT trade, name, qty, price, active, reason, market, xdate 
FROM orders
ORDER BY trade, name"""
orders = pd.read_sql(sql, conlite)
orders

   trade   name    qty  price  active   reason  market       xdate
0      B  AMATA   5000  20.00       1      XXX  SET100  2022-12-22
1      B    ASK   4500  28.00       0  RD10pct     SET  2023-02-28
2      B    ASW  12000   8.00       0      XXX     SET  2022-12-22
3      B    AWC  18000   5.60       1      XXX   SET50  2022-12-22
4      B  BANPU   6000  10.40       0  RD10pct   SET50  2023-04-10
..   ...    ...    ...    ...     ...      ...     ...         ...
26     B    WHA  24000   3.90       0      XXX  SET100  2022-12-22
27     B  WHART  10000  10.50       0    C10.5     SET  2023-03-08
28     B   WICE  10000  10.00       0      XXX     SET  2022-12-22
29     S    ORI  15000  13.20       1    20pct  SET100  2023-05-09
30     S    TMT  12000   8.70       0     C9.0     SET  2023-04-18

[31 rows x 8 columns]

In [4]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-03-10,2.44,-0.02,-0.81,2.46,2.46,2.42,19476913,47569.51
1,ADVANC,2023-03-10,209.00,2.00,0.97,206.00,209.00,205.00,7553086,1572997.62
2,AEONTS,2023-03-10,197.00,-1.50,-0.76,197.50,200.00,197.00,187864,37336.70
3,AH,2023-03-10,29.75,-1.25,-4.03,30.75,31.00,29.50,4579854,138001.40
4,AIE,2023-03-10,2.52,0.00,0.00,2.50,2.52,2.48,887202,2218.22
...,...,...,...,...,...,...,...,...,...,...
187,WHAIR,2023-03-10,7.45,-0.15,-1.97,7.50,7.55,7.40,1121832,8374.78
188,WHART,2023-03-10,10.80,-0.30,-2.70,11.00,11.10,10.80,1165814,12708.22
189,WHAUP,2023-03-10,3.92,-0.02,-0.51,3.94,3.96,3.92,2121120,8334.99
190,WICE,2023-03-10,10.40,-0.20,-1.89,10.50,10.60,10.40,1734701,18183.84
191,WORK,2023-03-10,17.60,-0.20,-1.12,17.80,17.80,17.50,119956,2116.80

In [5]:
df_merge  = pd.merge(orders, prices, on = 'name', how='inner')
df_merge

,trade,name,qty,price_x,active,reason,market,xdate,date,price_y,change,%change,open,high,low,volume,value(m)
0,B,AMATA,5000,20.00,1,XXX,SET100,2022-12-22,2023-03-10,21.40,-0.50,-2.28,21.60,21.80,21.40,12454639,268575.67
1,B,ASK,4500,28.00,0,RD10pct,SET,2023-02-28,2023-03-10,28.50,0.00,0.00,28.25,28.75,28.00,988485,28121.82
2,B,ASW,12000,8.00,0,XXX,SET,2022-12-22,2023-03-10,8.70,0.00,0.00,8.60,8.75,8.60,1335755,11608.04
3,B,AWC,18000,5.60,1,XXX,SET50,2022-12-22,2023-03-10,5.65,-0.15,-2.59,5.75,5.80,5.60,47456357,269521.57
4,B,BANPU,6000,10.40,0,RD10pct,SET50,2023-04-10,2023-03-10,10.80,0.00,0.00,10.70,10.80,10.70,37335363,401977.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,B,WHA,24000,3.90,0,XXX,SET100,2022-12-22,2023-03-10,4.16,-0.02,-0.48,4.14,4.18,4.10,106326220,440372.67
27,B,WHART,10000,10.50,0,C10.5,SET,2023-03-08,2023-03-10,10.80,-0.30,-2.70,11.00,11.10,10.80,1165814,12708.22
28,B,WICE,10000,10.00,0,XXX,SET,2022-12-22,2023-03-10,10.40,-0.20,-1.89,10.50,10.60,10.40,1734701,18183.84
29,S,ORI,15000,13.20,1,20pct,SET100,2023-05-09,2023-03-10,12.50,-0.30,-2.34,12.70,12.90,12.50,20149491,254995.27
30,S,TMT,12000,8.70,0,C9.0,SET,2023-04-18,2023-03-10,7.45,0.00,0.00,7.45,7.50,7.40,292600,2185.51

In [6]:
df_merge['spd'] = 0

In [7]:
colo = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'price_x', 'price_y', 'change', '%change',
        'active', 'xdate']
df_merge[colo]

,trade,name,spd,reason,market,qty,price_x,price_y,change,%change,active,xdate
0,B,AMATA,0,XXX,SET100,5000,20.00,21.40,-0.50,-2.28,1,2022-12-22
1,B,ASK,0,RD10pct,SET,4500,28.00,28.50,0.00,0.00,0,2023-02-28
2,B,ASW,0,XXX,SET,12000,8.00,8.70,0.00,0.00,0,2022-12-22
3,B,AWC,0,XXX,SET50,18000,5.60,5.65,-0.15,-2.59,1,2022-12-22
4,B,BANPU,0,RD10pct,SET50,6000,10.40,10.80,0.00,0.00,0,2023-04-10
...,...,...,...,...,...,...,...,...,...,...,...,...
26,B,WHA,0,XXX,SET100,24000,3.90,4.16,-0.02,-0.48,0,2022-12-22
27,B,WHART,0,C10.5,SET,10000,10.50,10.80,-0.30,-2.70,0,2023-03-08
28,B,WICE,0,XXX,SET,10000,10.00,10.40,-0.20,-1.89,0,2022-12-22
29,S,ORI,0,20pct,SET100,15000,13.20,12.50,-0.30,-2.34,1,2023-05-09
30,S,TMT,0,C9.0,SET,12000,8.70,7.45,0.00,0.00,0,2023-04-18

In [8]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colo].to_csv(output_file, header=True, index=False)
df_merge[colo].to_csv(osd_file, header=True, index=False)

### call ruby ruby\order-log-new.rb

In [9]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [10]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [11]:
!ruby ruby\\order-log-new.rb

trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
B,AMATA,-14,XXX,SET100,5000,20.0,21.4,-0.5,-2.2831050228310503,0,2022-12-22
B,ASK,-2,RD10pct,SET,4500,28.0,28.5,0.0,0.0,1,2023-02-28
B,ASW,-14,XXX,SET,12000,8.0,8.7,0.0,0.0,0,2022-12-22
B,AWC,-1,XXX,SET50,18000,5.6,5.65,-0.15,-2.586206896551724,1,2022-12-22
B,BANPU,-4,RD10pct,SET50,6000,10.4,10.8,0.0,0.0,1,2023-04-10
B,BH,-15,5pct,SET50,500,200.0,215.0,0.0,0.0,0,2022-12-22
B,BJC,-10,XXX,SET,2400,35.0,37.5,-0.5,-1.3157894736842106,0,2022-12-22
B,COM7,-7,XXX,SET50,3000,30.0,31.75,0.25,0.7936507936507936,1,2022-12-22
B,CPNREIT,-4,RD30pct,SET,5000,12.6,13.0,-0.1,-0.7633587786259542,2,2023-02-28
B,DIF,-2,CUT,SET,10000,12.7,12.9,-0.2,-1.5267175572519085,1,2023-02-10
B,GULF,-6,XXX,SET50,1800,50.0,51.5,0.0,0.0,1,2022-12-22
B,HANA,-13,XXX,SET100,2000,50.0,53.25,-1.0,-1.8433179723502304,0,2022-12-22
B,ILM,-22,XXX,SET,5000,19.0,21.2,-0.4,-1.851851851851852,0,2022-12-22
B,IVL,-7,RD15pct,SET50,2400,34.0,35.75,0.25,0.704225352112676,1,2023-05-08
B,JMART,-3,RD35pct,SET50,1200,23.5,23.8,-1.45,-5.742574257425742,2,2023-04-11
B,JMT,-2,RD25pct,SET50,1200,42.0,42.5,-0.75,-1.7341040462427746,1,2023-04-11
B,KCE,-15,RD40pct,SET100,1000,44.25,48.0,-0.5,-1.0309278350515465,0,2023-03-21
B,PSH,-6,DTD,SET,7500,12.0,12.6,-0.5,-3.816793893129771,1,2023-03-10
B,QH,-6,XXX,SET100,45000,2.3,2.42,0.0,0.0,1,2023-04-28
B,RCL,-15,HD,SET100,3000,28.75,32.5,0.25,0.7751937984496124,0,2023-03-16
B,SAT,-4,HD,SET,5000,19.0,19.4,-0.4,-2.0202020202020203,1,2023-03-08
B,SC,-5,XXX,SET,20000,4.4,4.5,-0.04,-0.8810572687224669,1,2023-04-29
B,SINGER,-6,RD20pct,SET100,1200,19.4,20.0,-1.1,-5.213270142180095,2,2023-05-03
B,SNC,-2,XXX,SET,7500,13.5,13.7,-0.4,-2.8368794326241136,1,2023-03-02
B,TCAP,-8,,SET100,2400,42.0,44.0,0.5,1.1494252873563218,1,2023-04-19
B,TTB,-3,52WL,SET50,90000,1.35,1.38,-0.01,-0.7194244604316546,1,2022-12-22
B,WHA,-13,XXX,SET100,24000,3.9,4.16,-0.02,-0.4784688995215311,0,2022-12-22
B,WHART,-3,C10.5,SET,10000,10.5,10.8,-0.3,-2.702702702702702,1,2023-03-08
B,WICE,-4,XXX,SET,10000,10.0,10.4,-0.2,-1.8867924528301887,1,2022-12-22
S,ORI,7,20pct,SET100,15000,13.2,12.5,-0.3,-2.34375,1,2023-05-09
S,TMT,25,C9.0,SET,12000,8.7,7.45,0.0,0.0,0,2023-04-18

In [12]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [13]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name

df = pd.read_csv(input_file, sep=',', index_col=None)
df.query('spd >= -3 and spd <= 3')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
1,B,ASK,-2,RD10pct,SET,4500,28.00,28.50,0.00,0.00,1,2023-02-28
3,B,AWC,-1,XXX,SET50,18000,5.60,5.65,-0.15,-2.59,1,2022-12-22
9,B,DIF,-2,CUT,SET,10000,12.70,12.90,-0.20,-1.53,1,2023-02-10
14,B,JMART,-3,RD35pct,SET50,1200,23.50,23.80,-1.45,-5.74,2,2023-04-11
15,B,JMT,-2,RD25pct,SET50,1200,42.00,42.50,-0.75,-1.73,1,2023-04-11
23,B,SNC,-2,XXX,SET,7500,13.50,13.70,-0.40,-2.84,1,2023-03-02
25,B,TTB,-3,52WL,SET50,90000,1.35,1.38,-0.01,-0.72,1,2022-12-22
27,B,WHART,-3,C10.5,SET,10000,10.50,10.80,-0.30,-2.70,1,2023-03-08

In [14]:
df.query('active == 2')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
8,B,CPNREIT,-4,RD30pct,SET,5000,12.60,13.00,-0.10,-0.76,2,2023-02-28
14,B,JMART,-3,RD35pct,SET50,1200,23.50,23.80,-1.45,-5.74,2,2023-04-11
22,B,SINGER,-6,RD20pct,SET100,1200,19.40,20.00,-1.10,-5.21,2,2023-05-03

In [15]:
df.query('active == 1')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
1,B,ASK,-2,RD10pct,SET,4500,28.00,28.50,0.00,0.00,1,2023-02-28
3,B,AWC,-1,XXX,SET50,18000,5.60,5.65,-0.15,-2.59,1,2022-12-22
4,B,BANPU,-4,RD10pct,SET50,6000,10.40,10.80,0.00,0.00,1,2023-04-10
7,B,COM7,-7,XXX,SET50,3000,30.00,31.75,0.25,0.79,1,2022-12-22
9,B,DIF,-2,CUT,SET,10000,12.70,12.90,-0.20,-1.53,1,2023-02-10
...,...,...,...,...,...,...,...,...,...,...,...,...
24,B,TCAP,-8,NaN,SET100,2400,42.00,44.00,0.50,1.15,1,2023-04-19
25,B,TTB,-3,52WL,SET50,90000,1.35,1.38,-0.01,-0.72,1,2022-12-22
27,B,WHART,-3,C10.5,SET,10000,10.50,10.80,-0.30,-2.70,1,2023-03-08
28,B,WICE,-4,XXX,SET,10000,10.00,10.40,-0.20,-1.89,1,2022-12-22
29,S,ORI,7,20pct,SET100,15000,13.20,12.50,-0.30,-2.34,1,2023-05-09

In [16]:
df.query('active == 0')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
0,B,AMATA,-14,XXX,SET100,5000,20.00,21.40,-0.50,-2.28,0,2022-12-22
2,B,ASW,-14,XXX,SET,12000,8.00,8.70,0.00,0.00,0,2022-12-22
5,B,BH,-15,5pct,SET50,500,200.00,215.00,0.00,0.00,0,2022-12-22
6,B,BJC,-10,XXX,SET,2400,35.00,37.50,-0.50,-1.32,0,2022-12-22
11,B,HANA,-13,XXX,SET100,2000,50.00,53.25,-1.00,-1.84,0,2022-12-22
12,B,ILM,-22,XXX,SET,5000,19.00,21.20,-0.40,-1.85,0,2022-12-22
16,B,KCE,-15,RD40pct,SET100,1000,44.25,48.00,-0.50,-1.03,0,2023-03-21
19,B,RCL,-15,HD,SET100,3000,28.75,32.50,0.25,0.78,0,2023-03-16
26,B,WHA,-13,XXX,SET100,24000,3.90,4.16,-0.02,-0.48,0,2022-12-22
30,S,TMT,25,C9.0,SET,12000,8.70,7.45,0.00,0.00,0,2023-04-18

In [17]:
colx = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'target', 'current', 'change', '%change',
        'active', 'xdate']

file_name = "orders-log.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df[colx].to_csv(output_file, header=True, index=False)
df[colx].to_csv(osd_file, header=True, index=False)

### Convert column name to make it valid for df.query

In [18]:
df['percent'] = df['%change']

In [19]:
df.query('percent < -2')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate,percent
0,B,AMATA,-14,XXX,SET100,5000,20.00,21.40,-0.50,-2.28,0,2022-12-22,-2.28
3,B,AWC,-1,XXX,SET50,18000,5.60,5.65,-0.15,-2.59,1,2022-12-22,-2.59
14,B,JMART,-3,RD35pct,SET50,1200,23.50,23.80,-1.45,-5.74,2,2023-04-11,-5.74
17,B,PSH,-6,DTD,SET,7500,12.00,12.60,-0.50,-3.82,1,2023-03-10,-3.82
20,B,SAT,-4,HD,SET,5000,19.00,19.40,-0.40,-2.02,1,2023-03-08,-2.02
22,B,SINGER,-6,RD20pct,SET100,1200,19.40,20.00,-1.10,-5.21,2,2023-05-03,-5.21
23,B,SNC,-2,XXX,SET,7500,13.50,13.70,-0.40,-2.84,1,2023-03-02,-2.84
27,B,WHART,-3,C10.5,SET,10000,10.50,10.80,-0.30,-2.70,1,2023-03-08,-2.70
29,S,ORI,7,20pct,SET100,15000,13.20,12.50,-0.30,-2.34,1,2023-05-09,-2.34

In [20]:
df.query('percent >= 2.00')

Empty DataFrame
Columns: [trade, name, spd, reason, market, qty, target, current, change, %change, active, xdate, percent]
Index: []