In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 14), datetime.date(2023, 2, 13))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-14
yesterday: 2023-02-13

## Must recall whenever there is change in orders

In [4]:
sql = """
SELECT trade, name, qty, price, active, reason, market, xdate 
FROM orders
ORDER BY trade, name"""
orders = pd.read_sql(sql, conlite)
orders

   trade   name    qty  price  active   reason  market       xdate
0      B  BANPU   6000  10.80       0      DTD   SET50  2023-04-08
1      B     CK   4500  22.00       0     5pct  SET100  2022-12-22
2      B    CKP  20000   4.50       0       3L  SET100  2022-12-22
3      B  JMART   1200  30.50       2  RD20pct   SET50  2023-04-11
4      B    JMT   1200  48.75       1  RD10pct   SET50  2023-04-19
..   ...    ...    ...    ...     ...      ...     ...         ...
15     S    IVL   2400  44.25       0      DTD   SET50  2023-05-06
16     S  JASIF  10000   8.50       0     CP1S     SET  2023-03-03
17     S    ORI  15000  12.50       0     CP1S  SET100  2023-05-09
18     S    TMT  12000   8.70       0     C9.0     SET  2023-04-18
19     S  WHAIR  10000   8.90       0       HD     SET  2023-03-04

[20 rows x 8 columns]

In [5]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-02-14,2.44,-0.06,-2.40,2.50,2.52,2.42,16016716,39443.73
1,ADVANC,2023-02-14,208.00,-2.00,-0.95,211.00,211.00,206.00,8697801,1813547.34
2,AH,2023-02-14,29.75,0.25,0.85,29.75,30.25,29.50,1947585,58175.63
3,AIE,2023-02-14,2.88,-0.02,-0.69,2.94,2.94,2.86,1510939,4352.74
4,AIMIRT,2023-02-14,12.20,-0.10,-0.81,12.20,12.30,12.20,10200,124.86
...,...,...,...,...,...,...,...,...,...,...
188,WHAIR,2023-02-14,7.95,0.00,0.00,7.95,8.00,7.85,290250,2308.33
189,WHART,2023-02-14,11.60,0.10,0.87,11.50,11.60,11.50,2133923,24690.58
190,WHAUP,2023-02-14,4.12,0.10,2.49,4.02,4.12,4.02,3580118,14558.41
191,WICE,2023-02-14,10.60,-0.30,-2.75,10.80,10.90,10.60,4243538,45386.14
192,WORK,2023-02-14,17.70,-0.50,-2.75,18.20,18.30,17.70,2162925,38675.06

In [6]:
df_merge  = pd.merge(orders, prices, on = 'name', how='inner')
df_merge

,trade,name,qty,price_x,active,reason,market,xdate,date,price_y,change,%change,open,high,low,volume,value(m)
0,B,BANPU,6000,10.80,0,DTD,SET50,2023-04-08,2023-02-14,11.00,-0.10,-0.90,11.10,11.30,10.90,110882761,1226343.79
1,B,CK,4500,22.00,0,5pct,SET100,2022-12-22,2023-02-14,22.00,-0.30,-1.35,22.30,22.30,21.90,2069131,45535.32
2,B,CKP,20000,4.50,0,3L,SET100,2022-12-22,2023-02-14,4.52,-0.06,-1.31,4.58,4.60,4.50,10416964,47171.30
3,B,JMART,1200,30.50,2,RD20pct,SET50,2023-04-11,2023-02-14,31.50,-1.75,-5.26,33.75,35.00,31.00,40826955,1341446.01
4,B,JMT,1200,48.75,1,RD10pct,SET50,2023-04-19,2023-02-14,50.00,0.50,1.01,50.75,53.25,49.50,45121902,2310801.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,S,IVL,2400,44.25,0,DTD,SET50,2023-05-06,2023-02-14,40.25,0.25,0.62,40.50,40.75,40.00,8413044,339731.56
16,S,JASIF,10000,8.50,0,CP1S,SET,2023-03-03,2023-02-14,8.20,0.00,0.00,8.20,8.25,8.15,4821644,39485.17
17,S,ORI,15000,12.50,0,CP1S,SET100,2023-05-09,2023-02-14,11.80,0.00,0.00,11.80,11.90,11.60,4031384,47515.96
18,S,TMT,12000,8.70,0,C9.0,SET,2023-04-18,2023-02-14,7.95,-0.10,-1.24,8.00,8.05,7.95,270133,2156.39
19,S,WHAIR,10000,8.90,0,HD,SET,2023-03-04,2023-02-14,7.95,0.00,0.00,7.95,8.00,7.85,290250,2308.33

In [7]:
df_merge['spd'] = 0

In [8]:
colo = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'price_x', 'price_y', 'change', '%change',
        'active', 'xdate']
df_merge[colo]

,trade,name,spd,reason,market,qty,price_x,price_y,change,%change,active,xdate
0,B,BANPU,0,DTD,SET50,6000,10.80,11.00,-0.10,-0.90,0,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.00,22.00,-0.30,-1.35,0,2022-12-22
2,B,CKP,0,3L,SET100,20000,4.50,4.52,-0.06,-1.31,0,2022-12-22
3,B,JMART,0,RD20pct,SET50,1200,30.50,31.50,-1.75,-5.26,2,2023-04-11
4,B,JMT,0,RD10pct,SET50,1200,48.75,50.00,0.50,1.01,1,2023-04-19
...,...,...,...,...,...,...,...,...,...,...,...,...
15,S,IVL,0,DTD,SET50,2400,44.25,40.25,0.25,0.62,0,2023-05-06
16,S,JASIF,0,CP1S,SET,10000,8.50,8.20,0.00,0.00,0,2023-03-03
17,S,ORI,0,CP1S,SET100,15000,12.50,11.80,0.00,0.00,0,2023-05-09
18,S,TMT,0,C9.0,SET,12000,8.70,7.95,-0.10,-1.24,0,2023-04-18
19,S,WHAIR,0,HD,SET,10000,8.90,7.95,0.00,0.00,0,2023-03-04

In [9]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colo].to_csv(output_file, header=True, index=False)
df_merge[colo].to_csv(osd_file, header=True, index=False)

### call ruby ruby\order-log-new.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\order-log-new.rb

trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
B,BANPU,-2,DTD,SET50,6000,10.8,11.0,-0.1,-0.9009009009009008,1,2023-04-08
B,CK,0,5pct,SET100,4500,22.0,22.0,-0.3,-1.345291479820628,1,2022-12-22
B,CKP,-1,3L,SET100,20000,4.5,4.52,-0.06,-1.310043668122271,1,2022-12-22
B,JMART,-4,RD20pct,SET50,1200,30.5,31.5,-1.75,-5.2631578947368425,2,2023-04-11
B,JMT,-5,RD10pct,SET50,1200,48.75,50.0,0.5,1.0101010101010102,1,2023-04-19
B,KCE,0,CUT,SET100,1000,47.0,47.0,-1.0,-2.083333333333333,1,2023-03-21
B,MC,-5,DOS,sSET,10000,11.5,12.0,-0.1,-0.8264462809917356,1,2023-02-22
B,MEGA,-4,5pct,SET100,2000,48.0,49.0,-1.75,-3.4482758620689653,1,2023-03-08
B,PTT,-3,XXX,SET50,3600,32.0,32.75,0.5,1.550387596899225,1,2023-03-03
B,RCL,-2,RD25pct,SET100,3000,28.75,29.25,-0.25,-0.847457627118644,2,2023-03-23
B,SAT,-4,XXX,SET,5000,20.5,20.9,0.0,0.0,1,2023-03-07
B,SINGER,-1,RD25pct,SET100,1200,21.0,21.1,-5.4,-20.37735849056604,2,2023-05-03
B,TCAP,-3,XXX,SET100,2400,42.0,42.75,0.0,0.0,1,2023-04-19
B,TTB,0,52WL,SET50,90000,1.4,1.4,-0.01,-0.7092198581560284,1,2022-12-22
S,DIF,1,CUT,SET,10000,13.4,13.3,0.0,0.0,2,2023-02-10
S,IVL,16,DTD,SET50,2400,44.25,40.25,0.25,0.625,0,2023-05-06
S,JASIF,6,CP1S,SET,10000,8.5,8.2,0.0,0.0,1,2023-03-03
S,ORI,7,CP1S,SET100,15000,12.5,11.8,0.0,0.0,1,2023-05-09
S,TMT,15,C9.0,SET,12000,8.7,7.95,-0.1,-1.2422360248447204,0,2023-04-18
S,WHAIR,19,HD,SET,10000,8.9,7.95,0.0,0.0,0,2023-03-04

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.query('spd >= -3 and spd <= 3')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
0,B,BANPU,-2,DTD,SET50,6000,10.80,11.00,-0.10,-0.90,1,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.00,22.00,-0.30,-1.35,1,2022-12-22
2,B,CKP,-1,3L,SET100,20000,4.50,4.52,-0.06,-1.31,1,2022-12-22
5,B,KCE,0,CUT,SET100,1000,47.00,47.00,-1.00,-2.08,1,2023-03-21
8,B,PTT,-3,XXX,SET50,3600,32.00,32.75,0.50,1.55,1,2023-03-03
9,B,RCL,-2,RD25pct,SET100,3000,28.75,29.25,-0.25,-0.85,2,2023-03-23
11,B,SINGER,-1,RD25pct,SET100,1200,21.00,21.10,-5.40,-20.38,2,2023-05-03
12,B,TCAP,-3,XXX,SET100,2400,42.00,42.75,0.00,0.00,1,2023-04-19
13,B,TTB,0,52WL,SET50,90000,1.40,1.40,-0.01,-0.71,1,2022-12-22
14,S,DIF,1,CUT,SET,10000,13.40,13.30,0.00,0.00,2,2023-02-10

In [15]:
df.query('active == 2')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
3,B,JMART,-4,RD20pct,SET50,1200,30.50,31.50,-1.75,-5.26,2,2023-04-11
9,B,RCL,-2,RD25pct,SET100,3000,28.75,29.25,-0.25,-0.85,2,2023-03-23
11,B,SINGER,-1,RD25pct,SET100,1200,21.00,21.10,-5.40,-20.38,2,2023-05-03
14,S,DIF,1,CUT,SET,10000,13.40,13.30,0.00,0.00,2,2023-02-10

In [16]:
df.query('active == 1')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
0,B,BANPU,-2,DTD,SET50,6000,10.80,11.00,-0.10,-0.90,1,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.00,22.00,-0.30,-1.35,1,2022-12-22
2,B,CKP,-1,3L,SET100,20000,4.50,4.52,-0.06,-1.31,1,2022-12-22
4,B,JMT,-5,RD10pct,SET50,1200,48.75,50.00,0.50,1.01,1,2023-04-19
5,B,KCE,0,CUT,SET100,1000,47.00,47.00,-1.00,-2.08,1,2023-03-21
...,...,...,...,...,...,...,...,...,...,...,...,...
10,B,SAT,-4,XXX,SET,5000,20.50,20.90,0.00,0.00,1,2023-03-07
12,B,TCAP,-3,XXX,SET100,2400,42.00,42.75,0.00,0.00,1,2023-04-19
13,B,TTB,0,52WL,SET50,90000,1.40,1.40,-0.01,-0.71,1,2022-12-22
16,S,JASIF,6,CP1S,SET,10000,8.50,8.20,0.00,0.00,1,2023-03-03
17,S,ORI,7,CP1S,SET100,15000,12.50,11.80,0.00,0.00,1,2023-05-09

In [17]:
df.query('active == 0')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
15,S,IVL,16,DTD,SET50,2400,44.25,40.25,0.25,0.62,0,2023-05-06
18,S,TMT,15,C9.0,SET,12000,8.70,7.95,-0.10,-1.24,0,2023-04-18
19,S,WHAIR,19,HD,SET,10000,8.90,7.95,0.00,0.00,0,2023-03-04

In [18]:
colx = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'target', 'current', 'change', '%change',
        'active', 'xdate']

file_name = "orders-log.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df[colx].to_csv(output_file, header=True, index=False)
df[colx].to_csv(osd_file, header=True, index=False)