In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 12), datetime.date(2023, 2, 11))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-12
yesterday: 2023-02-10

## Must recall whenever there is change in orders

In [3]:
sql = """
SELECT trade, name, qty, price, active, reason, market, xdate 
FROM orders
ORDER BY trade, name"""
orders = pd.read_sql(sql, conlite)
orders

   trade    name    qty  price  active reason  market       xdate
0      B   BANPU   6000  10.80       0    DTD   SET50  2023-04-08
1      B      CK   4500  22.00       0   5pct  SET100  2022-12-22
2      B     CKP  20000   4.50       0     3L  SET100  2022-12-22
3      B     KCE   1000  47.00       0    CUT  SET100  2023-03-21
4      B    MEGA   2000  48.00       0   5pct  SET100  2023-03-08
..   ...     ...    ...    ...     ...    ...     ...         ...
15     S     ORI  15000  12.50       0   CP1S  SET100  2023-05-09
16     S    SCCC   1200 153.00       2    CUT     SET  2023-02-24
17     S  SINGER   1200  29.25       0    DTD  SET100  2023-04-29
18     S     TMT  12000   8.70       0   C9.0     SET  2023-04-18
19     S   WHAIR  10000   8.90       0     HD     SET  2023-03-04

[20 rows x 8 columns]

In [4]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-02-10,2.48,-0.04,-1.59,2.52,2.52,2.48,12908381,32137.28
1,ADVANC,2023-02-10,206.00,6.50,3.26,202.00,206.00,201.00,17037520,3473210.18
2,AH,2023-02-10,30.75,-1.25,-3.91,32.00,32.00,30.50,5272428,164452.58
3,AIE,2023-02-10,2.98,-0.06,-1.97,3.04,3.04,2.98,2006091,6024.09
4,AIMIRT,2023-02-10,12.30,0.00,0.00,12.30,12.30,12.20,44600,547.41
...,...,...,...,...,...,...,...,...,...,...
189,WHAIR,2023-02-10,7.90,-0.05,-0.63,7.95,7.95,7.85,321310,2530.39
190,WHART,2023-02-10,11.70,0.10,0.86,11.60,11.70,11.50,632010,7348.34
191,WHAUP,2023-02-10,4.06,-0.04,-0.98,4.10,4.12,4.06,2800220,11415.76
192,WICE,2023-02-10,11.30,-0.10,-0.88,11.40,11.60,11.30,1406725,16009.85
193,WORK,2023-02-10,18.40,0.10,0.55,18.40,18.40,18.30,141505,2595.00

In [5]:
df_merge  = pd.merge(orders, prices, on = 'name', how='inner')
df_merge

,trade,name,qty,price_x,active,reason,market,xdate,date,price_y,change,%change,open,high,low,volume,value(m)
0,B,BANPU,6000,10.80,0,DTD,SET50,2023-04-08,2023-02-10,10.90,0.00,0.00,11.40,11.50,10.80,399453216,4436502.99
1,B,CK,4500,22.00,0,5pct,SET100,2022-12-22,2023-02-10,22.10,-0.40,-1.78,22.50,22.60,22.10,3006254,66679.33
2,B,CKP,20000,4.50,0,3L,SET100,2022-12-22,2023-02-10,4.66,0.00,0.00,4.66,4.70,4.66,8920991,41738.34
3,B,KCE,1000,47.00,0,CUT,SET100,2023-03-21,2023-02-10,47.25,-1.25,-2.58,48.25,49.00,47.25,43292690,2078869.93
4,B,MEGA,2000,48.00,0,5pct,SET100,2023-03-08,2023-02-10,51.50,-0.50,-0.96,51.75,52.00,51.25,1598024,82480.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,S,ORI,15000,12.50,0,CP1S,SET100,2023-05-09,2023-02-10,11.90,0.20,1.71,11.70,11.90,11.60,4834840,57045.85
16,S,SCCC,1200,153.00,2,CUT,SET,2023-02-24,2023-02-10,156.50,0.50,0.32,156.00,156.50,155.50,101734,15886.82
17,S,SINGER,1200,29.25,0,DTD,SET100,2023-04-29,2023-02-10,26.75,-0.75,-2.73,27.25,27.50,26.75,2084092,56358.92
18,S,TMT,12000,8.70,0,C9.0,SET,2023-04-18,2023-02-10,8.20,0.15,1.86,8.05,8.20,8.00,158167,1277.55
19,S,WHAIR,10000,8.90,0,HD,SET,2023-03-04,2023-02-10,7.90,-0.05,-0.63,7.95,7.95,7.85,321310,2530.39

In [6]:
df_merge.columns

Index(['trade', 'name', 'qty', 'price_x', 'active', 'reason', 'market',
       'xdate', 'date', 'price_y', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [7]:
df_merge['spd'] = 0

In [8]:
colo = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'price_x', 'price_y', 'change', '%change',
        'active', 'xdate']
df_merge[colo]

,trade,name,spd,reason,market,qty,price_x,price_y,change,%change,active,xdate
0,B,BANPU,0,DTD,SET50,6000,10.80,10.90,0.00,0.00,0,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.00,22.10,-0.40,-1.78,0,2022-12-22
2,B,CKP,0,3L,SET100,20000,4.50,4.66,0.00,0.00,0,2022-12-22
3,B,KCE,0,CUT,SET100,1000,47.00,47.25,-1.25,-2.58,0,2023-03-21
4,B,MEGA,0,5pct,SET100,2000,48.00,51.50,-0.50,-0.96,0,2023-03-08
...,...,...,...,...,...,...,...,...,...,...,...,...
15,S,ORI,0,CP1S,SET100,15000,12.50,11.90,0.20,1.71,0,2023-05-09
16,S,SCCC,0,CUT,SET,1200,153.00,156.50,0.50,0.32,2,2023-02-24
17,S,SINGER,0,DTD,SET100,1200,29.25,26.75,-0.75,-2.73,0,2023-04-29
18,S,TMT,0,C9.0,SET,12000,8.70,8.20,0.15,1.86,0,2023-04-18
19,S,WHAIR,0,HD,SET,10000,8.90,7.90,-0.05,-0.63,0,2023-03-04

In [9]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colo].to_csv(output_file, header=True, index=False)
df_merge[colo].to_csv(osd_file, header=True, index=False)

### call ruby ruby\order-log-new.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\order-log-new.rb

trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
B,BANPU,-1,DTD,SET50,6000,10.8,10.9,0.0,0.0,1,2023-04-08
B,CK,-1,5pct,SET100,4500,22.0,22.1,-0.4,-1.7777777777777777,1,2022-12-22
B,CKP,-8,3L,SET100,20000,4.5,4.66,0.0,0.0,1,2022-12-22
B,KCE,-1,CUT,SET100,1000,47.0,47.25,-1.25,-2.577319587628866,1,2023-03-21
B,MEGA,-14,5pct,SET100,2000,48.0,51.5,-0.5,-0.9615384615384616,0,2023-03-08
B,PTT,-2,XXX,SET50,3600,32.0,32.5,0.0,0.0,1,2023-03-03
B,RCL,-8,HD,SET100,3000,28.75,30.75,0.25,0.819672131147541,1,2023-03-23
B,SAT,-1,XXX,SET,5000,21.0,21.1,-0.1,-0.4716981132075472,1,2023-03-07
B,TCAP,-3,XXX,SET100,2400,42.0,42.75,0.0,0.0,1,2023-04-19
B,TTB,0,52WL,SET50,90000,1.4,1.4,0.0,0.0,1,2022-12-22
S,DIF,1,CUT,SET,10000,13.4,13.3,-0.2,-1.4814814814814814,1,2023-02-10
S,IVL,15,DTD,SET50,2400,44.25,40.5,-0.25,-0.6134969325153374,0,2023-05-06
S,JASIF,6,CP1S,SET,10000,8.5,8.2,0.05,0.6134969325153374,1,2023-03-03
S,JMART,28,DTD,SET50,3600,41.5,34.5,-1.0,-2.816901408450704,0,2023-04-19
S,JMT,38,DTD,SET50,1500,60.0,50.5,-1.5,-2.8846153846153846,0,2023-04-19
S,ORI,6,CP1S,SET100,15000,12.5,11.9,0.2,1.709401709401709,1,2023-05-09
S,SCCC,-7,CUT,SET,1200,153.0,156.5,0.5,0.3205128205128205,2,2023-02-24
S,SINGER,10,DTD,SET100,1200,29.25,26.75,-0.75,-2.727272727272727,0,2023-04-29
S,TMT,10,C9.0,SET,12000,8.7,8.2,0.15,1.8633540372670807,0,2023-04-18
S,WHAIR,20,HD,SET,10000,8.9,7.9,-0.05,-0.6289308176100629,0,2023-03-04

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.query('spd >= -3 and spd <= 3')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
0,B,BANPU,-1,DTD,SET50,6000,10.80,10.90,0.00,0.00,1,2023-04-08
1,B,CK,-1,5pct,SET100,4500,22.00,22.10,-0.40,-1.78,1,2022-12-22
3,B,KCE,-1,CUT,SET100,1000,47.00,47.25,-1.25,-2.58,1,2023-03-21
5,B,PTT,-2,XXX,SET50,3600,32.00,32.50,0.00,0.00,1,2023-03-03
7,B,SAT,-1,XXX,SET,5000,21.00,21.10,-0.10,-0.47,1,2023-03-07
8,B,TCAP,-3,XXX,SET100,2400,42.00,42.75,0.00,0.00,1,2023-04-19
9,B,TTB,0,52WL,SET50,90000,1.40,1.40,0.00,0.00,1,2022-12-22
10,S,DIF,1,CUT,SET,10000,13.40,13.30,-0.20,-1.48,1,2023-02-10

In [15]:
df.query('active == 2')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
16,S,SCCC,-7,CUT,SET,1200,153.00,156.50,0.50,0.32,2,2023-02-24

In [16]:
df.query('active == 1')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
0,B,BANPU,-1,DTD,SET50,6000,10.80,10.90,0.00,0.00,1,2023-04-08
1,B,CK,-1,5pct,SET100,4500,22.00,22.10,-0.40,-1.78,1,2022-12-22
2,B,CKP,-8,3L,SET100,20000,4.50,4.66,0.00,0.00,1,2022-12-22
3,B,KCE,-1,CUT,SET100,1000,47.00,47.25,-1.25,-2.58,1,2023-03-21
5,B,PTT,-2,XXX,SET50,3600,32.00,32.50,0.00,0.00,1,2023-03-03
...,...,...,...,...,...,...,...,...,...,...,...,...
8,B,TCAP,-3,XXX,SET100,2400,42.00,42.75,0.00,0.00,1,2023-04-19
9,B,TTB,0,52WL,SET50,90000,1.40,1.40,0.00,0.00,1,2022-12-22
10,S,DIF,1,CUT,SET,10000,13.40,13.30,-0.20,-1.48,1,2023-02-10
12,S,JASIF,6,CP1S,SET,10000,8.50,8.20,0.05,0.61,1,2023-03-03
15,S,ORI,6,CP1S,SET100,15000,12.50,11.90,0.20,1.71,1,2023-05-09

In [17]:
df.query('active == 0')

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
4,B,MEGA,-14,5pct,SET100,2000,48.00,51.50,-0.50,-0.96,0,2023-03-08
11,S,IVL,15,DTD,SET50,2400,44.25,40.50,-0.25,-0.61,0,2023-05-06
13,S,JMART,28,DTD,SET50,3600,41.50,34.50,-1.00,-2.82,0,2023-04-19
14,S,JMT,38,DTD,SET50,1500,60.00,50.50,-1.50,-2.88,0,2023-04-19
17,S,SINGER,10,DTD,SET100,1200,29.25,26.75,-0.75,-2.73,0,2023-04-29
18,S,TMT,10,C9.0,SET,12000,8.70,8.20,0.15,1.86,0,2023-04-18
19,S,WHAIR,20,HD,SET,10000,8.90,7.90,-0.05,-0.63,0,2023-03-04

In [18]:
df.columns

Index(['trade', 'name', 'spd', 'reason', 'market', 'qty', 'target', 'current',
       'change', '%change', 'active', 'xdate'],
      dtype='object')

In [19]:
colx = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'target', 'current', 'change', '%change',
        'active', 'xdate']

In [20]:
file_name = "orders-log.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df[colx].to_csv(output_file, header=True, index=False)
df[colx].to_csv(osd_file, header=True, index=False)