##### SQLite port_lite database: stocks table
##### PostgreSQL portpg database: stocks table
##### MySQL stock database: setindex, price, buy tables
##### output csv: 5-day_average, extreme

In [1]:
import calendar
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
today

datetime.date(2023, 2, 14)

### Today is last business day

In [2]:
#today = today - timedelta(days=1)
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
today, yesterday

(datetime.date(2023, 2, 14), datetime.date(2023, 2, 13))

In [3]:
sql = '''
SELECT * FROM setindex WHERE setindex IS Null'''
df = pd.read_sql(sql, const)
df

setindex = pd.read_sql(sql, const)
setindex

         date setindex
0  2023-02-14     None

In [4]:
setindex = 1652.76
sqlUpd = """UPDATE setindex
SET setindex = %s WHERE setindex IS Null"""
sqlUpd = sqlUpd % setindex
print(sqlUpd)

UPDATE setindex
SET setindex = 1652.76 WHERE setindex IS Null

In [5]:
#setindex = 1671.46
sqlUpd = """
UPDATE setindex
SET setindex = %s WHERE date = '%s'"""
sqlUpd = sqlUpd % (setindex, today)
print(sqlUpd)

UPDATE setindex
SET setindex = 1652.76 WHERE date = '2023-02-14'

In [6]:
rp = const.execute(sqlUpd)
rp.rowcount

1

### Restart and run all cells

### Begin of Tables in the process

In [7]:
cols = "name market price_x maxp max_price qty".split()
colt = 'name pct price_x price_y status diff'.split()
colu = "name prc_pct tdy_price avg_price qty_pct tdy_qty avg_qty".split()
colv = "name market price_x minp min_price qty".split()

In [8]:
format_dict = {
    'setindex':'{:,.2f}',
    
    'qty':'{:,}', 'volbuy':'{:,}',   
    'price':'{:.2f}','maxp':'{:.2f}','minp':'{:.2f}',
    'opnp':'{:.2f}','price_x':'{:.2f}','price_y':'{:.2f}',
    'price_today':'{:.2f}','price_yesterday':'{:.2f}',   
    'date':'{:%Y-%m-%d}',
    
    'price_mean':'{:.2f}','price_today':'{:.2f}','diff':'{:.2f}', 
    'tdy_price':'{:.2f}','avg_price':'{:.2f}','dividend':'{:.2f}',
    'tdy_qty':'{:,}','avg_qty':'{:,}',
    'prc_pct':'{:,.2f}%','qty_pct':'{:,.2f}%','pct':'{:,.2f}%',
    'qty_mean':'{:,}','qty_today':'{:,}',    
    
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',   
    'value(m)':'{:,.2f}','beta':'{:,.2f}', 
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',    
    'start_date':'{:%Y-%m-%d}','end_date':'{:%Y-%m-%d}',    
              }

In [9]:
sql = """
SELECT * 
FROM price 
WHERE date = '%s'
ORDER BY name
"""
sql = sql % today
print(sql)

prices = pd.read_sql(sql, const)
prices.sample(5).style.format(format_dict)

SELECT *
FROM price
WHERE date = '2023-02-14'
ORDER BY name

In [10]:
sql = """
SELECT * 
FROM stocks
ORDER BY name
"""
stocks = pd.read_sql(sql, conpg)
stocks['created_at'] = pd.to_datetime(stocks['created_at'])
stocks['updated_at'] = pd.to_datetime(stocks['updated_at'])
stocks.head().style.format(format_dict)

In [11]:
df_merge = pd.merge(prices, stocks, on="name", how="inner")
df_merge.drop(columns=['id','ticker_id','created_at','updated_at','paid_up','market_cap'],inplace=True)
df_merge.head().style.format(format_dict)

### 52 Weeks High

In [12]:
Yearly_High = (df_merge.maxp > df_merge.max_price) & (df_merge.qty > 100000)
Final_High = df_merge[Yearly_High]
Final_High[cols].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [13]:
'New high today: ' + str(df_merge[Yearly_High].shape[0]) + ' stocks'

'New high today: 8 stocks'

### High or Low by Markets

In [14]:
set50H = Final_High["market"].str.contains("SET50")
Final_High[set50H].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

In [15]:
set100H = Final_High["market"].str.contains("SET100")
Final_High[set100H].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

In [16]:
setsmallH = Final_High["market"].str.contains("sSET")
Final_High[setsmallH].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

In [17]:
maiH = Final_High["market"].str.contains("mai")
Final_High[maiH].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

### 52 Weeks Low

In [18]:
Yearly_Low = (df_merge.minp < df_merge.min_price) & (df_merge.qty > 100000)
Final_Low = df_merge[Yearly_Low]
Final_Low[colv].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [19]:
'New low today: ' + str(df_merge[Yearly_Low].shape[0]) + ' stocks'

'New low today: 11 stocks'

### New High or Low by Markets

In [20]:
set50L = Final_Low["market"].str.contains("SET50")
Final_Low[set50L].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

In [21]:
set100L = Final_Low["market"].str.contains("SET100")
Final_Low[set100L].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

In [22]:
setsmallL = Final_Low["market"].str.contains("sSET")
Final_Low[setsmallL].sort_values(by=["name"],ascending=["True"]).style.format(format_dict)

### Break 5-day Average Volume

In [23]:
sql = """
SELECT name, qty, price, date As today
FROM price 
WHERE date = '%s'
ORDER BY name
"""
sql = sql % today
print(sql)

today_vol = pd.read_sql(sql, const)
today_vol.head().style.format(format_dict)

SELECT name, qty, price, date As today
FROM price
WHERE date = '2023-02-14'
ORDER BY name

In [24]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
end_date = today - num_business_days
end_date = end_date.date()
end_date

datetime.date(2023, 2, 13)

In [25]:
# create a new column 'start_date' by subtracting the specified number of business days from the 'end_date'
today_vol['end_date'] = today_vol['today'] - num_business_days
today_vol.head()

     name       qty  price       today   end_date
0     ACE  16016716   2.44  2023-02-14 2023-02-13
1  ADVANC   8697801 208.00  2023-02-14 2023-02-13
2      AH   1947585  29.75  2023-02-14 2023-02-13
3     AIE   1510939   2.88  2023-02-14 2023-02-13
4  AIMIRT     10200  12.20  2023-02-14 2023-02-13

In [26]:
# specify the number of business days
num_days = 4
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
num_business_days
start_date = yesterday - num_business_days
start_date = start_date.date()
start_date

datetime.date(2023, 2, 7)

In [27]:
# create a new column 'start_date' by subtracting the specified number of business days from the 'end_date'
today_vol['start_date'] = today_vol['end_date'] - num_business_days
today_vol.head()

     name       qty  price       today   end_date start_date
0     ACE  16016716   2.44  2023-02-14 2023-02-13 2023-02-07
1  ADVANC   8697801 208.00  2023-02-14 2023-02-13 2023-02-07
2      AH   1947585  29.75  2023-02-14 2023-02-13 2023-02-07
3     AIE   1510939   2.88  2023-02-14 2023-02-13 2023-02-07
4  AIMIRT     10200  12.20  2023-02-14 2023-02-13 2023-02-07

In [28]:
sql = """
SELECT * 
FROM price 
WHERE date BETWEEN '%s' AND '%s'
"""
sql = sql % (start_date, end_date)
print(sql)

five_day_vol = pd.read_sql(sql, const)
five_day_vol.sort_values(by=['name','date'],ascending=[True,True]).head().style.format(format_dict)

SELECT *
FROM price
WHERE date BETWEEN '2023-02-07' AND '2023-02-13'

In [29]:
five_day_mean = five_day_vol.groupby(by=["name"])[["qty","price"]].mean()
five_day_mean.reset_index(inplace=True)
five_day_mean.columns

Index(['name', 'qty', 'price'], dtype='object')

In [30]:
df_merge2 = pd.merge(today_vol, five_day_mean, on=["name"], how="inner", 
                     suffixes=( "_today","_mean"))
df_merge2.columns

Index(['name', 'qty_today', 'price_today', 'today', 'end_date', 'start_date',
       'qty_mean', 'price_mean'],
      dtype='object')

In [31]:
df_merge2["qty_mean"] = df_merge2.qty_mean.astype("int64")
df_merge2.head().style.format(format_dict)

In [32]:
break_five_day_mean = df_merge2[(df_merge2.qty_today > df_merge2.qty_mean)]
break_five_day_mean.head().style.format(format_dict)

In [33]:
sql = """
SELECT name, date, volbuy, price, dividend 
FROM buy 
WHERE active = 1
"""
buys = pd.read_sql(sql, const)
buys.volbuy = buys.volbuy.astype("int64")
buys.sample(5).style.format(format_dict)

In [34]:
df_merge3 = pd.merge(break_five_day_mean, buys, on=["name"], how="inner", suffixes=("_mean","_today"))
df_merge3["qty_pct"] = round((df_merge3.qty_today - df_merge3.qty_mean) / abs(df_merge3.qty_mean) * 100,2)
df_merge3["prc_pct"] = round((df_merge3.price_today - df_merge3.price_mean) / abs(df_merge3.price_mean) * 100,2)
df_merge3.rename(columns={'price_mean':'avg_price','price_today':'tdy_price',
                          'qty_mean':'avg_qty','qty_today':'tdy_qty'},inplace=True)
df_merge3[colu].sort_values(["prc_pct"], ascending=False
).style.format(format_dict)

In [35]:
file_name = '5-day-average.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_merge3[colu].sort_values(["prc_pct"], ascending=False).to_csv(data_file, header=True, index=False)
df_merge3[colu].sort_values(["prc_pct"], ascending=False).to_csv(output_file, header=True, index=False)
df_merge3[colu].sort_values(["prc_pct"], ascending=False).to_csv(one_file, header=True, index=False)
df_merge3[colu].sort_values(["prc_pct"], ascending=False).to_csv(osd_file, header=True, index=False)

### Extreme price discrepancy

In [36]:
sql = '''
SELECT name, status
FROM stocks'''
stocks = pd.read_sql(sql, conlite)
stocks.sample(5).style.format(format_dict)

In [37]:
names = stocks["name"].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'MCS', 'PTTGC', 'JASIF', 'DIF', 'WHAIR', 'STA', 'SCC', 'NER', 'SYNEX', 'BCH', 'KCE', 'TMT', 'RCL', 'WHART', 'ASP', 'SCCC', 'SENA', 'ORI', 'ASK', 'BH', 'IVL', 'BANPU', 'TTB', 'PTTEP', 'CKP', 'GVREIT', 'CPNREIT', 'JMART', 'JMT', 'SAPPE', 'SPALI', 'SVI', 'TFFIF', 'AIT', 'BEM', 'BPP', 'CPALL', 'CPN', 'EA', 'HMPRO', 'ICHI', 'III', 'LH', 'PSH', 'QH', 'SC', 'TFG', 'COM7', 'CPF', 'BDMS', 'CK', 'MEGA', 'SIRI', 'AH', 'SINGER', 'AP', 'BCP', 'PTT', 'TOP', 'SAT', 'TCAP', 'MC'"

In [38]:
type(in_p)

str

In [39]:
sql = """
SELECT name, price 
FROM price 
WHERE date = '%s' AND name IN (%s) 
ORDER BY name"""
sql = sql % (today, in_p)
print(sql)

tdy_prices = pd.read_sql(sql, const)
str(tdy_prices.shape[0]) + ' stocks'

SELECT name, price
FROM price
WHERE date = '2023-02-14' AND name IN ('MCS', 'PTTGC', 'JASIF', 'DIF', 'WHAIR', 'STA', 'SCC', 'NER', 'SYNEX', 'BCH', 'KCE', 'TMT', 'RCL', 'WHART', 'ASP', 'SCCC', 'SENA', 'ORI', 'ASK', 'BH', 'IVL', 'BANPU', 'TTB', 'PTTEP', 'CKP', 'GVREIT', 'CPNREIT', 'JMART', 'JMT', 'SAPPE', 'SPALI', 'SVI', 'TFFIF', 'AIT', 'BEM', 'BPP', 'CPALL', 'CPN', 'EA', 'HMPRO', 'ICHI', 'III', 'LH', 'PSH', 'QH', 'SC', 'TFG', 'COM7', 'CPF', 'BDMS', 'CK', 'MEGA', 'SIRI', 'AH', 'SINGER', 'AP', 'BCP', 'PTT', 'TOP', 'SAT', 'TCAP', 'MC')
ORDER BY name

'59 stocks'

In [40]:
sql = """
SELECT name, price 
FROM price 
WHERE date = '%s' AND name IN (%s) 
ORDER BY name"""
sql = sql % (yesterday, in_p)
print(sql)

ytd_prices = pd.read_sql(sql, const)
str(ytd_prices.shape[0]) + ' stocks'

SELECT name, price
FROM price
WHERE date = '2023-02-13' AND name IN ('MCS', 'PTTGC', 'JASIF', 'DIF', 'WHAIR', 'STA', 'SCC', 'NER', 'SYNEX', 'BCH', 'KCE', 'TMT', 'RCL', 'WHART', 'ASP', 'SCCC', 'SENA', 'ORI', 'ASK', 'BH', 'IVL', 'BANPU', 'TTB', 'PTTEP', 'CKP', 'GVREIT', 'CPNREIT', 'JMART', 'JMT', 'SAPPE', 'SPALI', 'SVI', 'TFFIF', 'AIT', 'BEM', 'BPP', 'CPALL', 'CPN', 'EA', 'HMPRO', 'ICHI', 'III', 'LH', 'PSH', 'QH', 'SC', 'TFG', 'COM7', 'CPF', 'BDMS', 'CK', 'MEGA', 'SIRI', 'AH', 'SINGER', 'AP', 'BCP', 'PTT', 'TOP', 'SAT', 'TCAP', 'MC')
ORDER BY name

'59 stocks'

In [41]:
compare1 = pd.merge(tdy_prices,ytd_prices,on='name',how='inner',suffixes=("_today","_yesterday"))
compare1.sample(5).style.format(format_dict)

In [42]:
compare2 = pd.merge(compare1,stocks,on='name',how='inner')
compare2.head().style.format(format_dict)

In [43]:
compare2.columns

Index(['name', 'price_today', 'price_yesterday', 'status'], dtype='object')

In [44]:
colx = ['name', 'pct', 'price_today', 'price_yesterday', 'status', 'diff']
colx

['name', 'pct', 'price_today', 'price_yesterday', 'status', 'diff']

In [45]:
compare2['diff'] = round((compare2.price_today - compare2.price_yesterday),2)
compare2['pct'] = round(compare2['diff'] / compare2['price_yesterday'] * 100,2)
compare2[colx].sort_values(['pct'],ascending=[False]).sample(5).style.format(format_dict)

In [46]:
criteria = 3
mask = abs(compare2.pct) >= criteria
extremes = compare2[mask].sort_values(['status','pct'],ascending=[True,False])
extremes[colx].sort_values(['status','pct'],ascending=[True,False]).style.format(format_dict)

In [47]:
file_name = 'extremes.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

extremes[colx].sort_values(['status','pct'],ascending=[True,False]).to_csv(data_file, index=False)
extremes[colx].sort_values(['status','pct'],ascending=[True,False]).to_csv(output_file, index=False)
extremes[colx].sort_values(['status','pct'],ascending=[True,False]).to_csv(one_file, index=False)
extremes[colx].sort_values(['status','pct'],ascending=[True,False]).to_csv(osd_file, index=False)