In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 3, 3), datetime.date(2023, 3, 2))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-03-03
Today in mm-dd format: 03-03
yesterday: 2023-03-02 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-02-02 00:00:00   Thursday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASK', 'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'ASW', 'BH', 'BJC', 'COM7', 'GULF', 'PSH', 'QH','SAT', \
'SC', 'SNC', 'TCAP', 'TTB', 'WHA','WICE'"
in_p

"'ASK', 'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'ASW', 'BH', 'BJC', 'COM7', 'GULF', 'PSH', 'QH','SAT', 'SC', 'SNC', 'TCAP', 'TTB', 'WHA','WICE'"

In [13]:
sql = """
SELECT name
FROM orders
ORDER BY trade, name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASK', 'BANPU', 'BH', 'GULF', 'JMART', 'JMT', 'KCE', 'MC', 'PSH', 'RCL', 'SAT', 'SC', 'SINGER', 'SNC', 'TCAP', 'TTB', 'DIF', 'IVL', 'ORI', 'TMT'"

### End of Selection between Buy or Orders

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-02 00:00:00' AND name IN ('ASK', 'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'ASW', 'BH', 'BJC', 'COM7', 'GULF', 'PSH', 'QH','SAT', 'SC', 'SNC', 'TCAP', 'TTB', 'WHA','WICE')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty  maxp  minp
139    BJC  2023-02-13  37.75   2946866 38.50 37.75
206    DIF  2023-02-15  13.20   3828117 13.30 13.20
109    BCH  2023-03-03  19.30  23613889 19.60 19.00
695  SYNEX  2023-02-28  16.10    790040 16.40 16.00
22     ASP  2023-02-02   3.16  10990671  3.24  3.16

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.to_csv(output_file, header=None, index=False)
price.to_csv(osd_file, header=True, index=False)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASK|2023-02-02|2023-02-06|3|33.75|33.75|0.0|0.0|0|0|34.0|33.25||4|1,410,301
ASK|2023-02-07|2023-02-08|2|32.75|32.5|-0.25|-0.76|-1|-1|33.75|32.0|Downward|6|3,065,140
ASK|2023-02-09|2023-02-09|1|32.75|32.75|0.0|0.0|0|0|32.75|32.25|Upward|7|414,178
ASK|2023-02-10|2023-02-10|1|32.5|32.5|0.0|0.0|0|0|33.0|32.5|Downward|8|438,805
ASK|2023-02-13|2023-02-13|1|32.75|32.75|0.0|0.0|0|0|33.0|32.5|Upward|9|315,216
ASK|2023-02-14|2023-02-15|2|32.25|30.75|-1.5|-4.65|-6|-3|33.0|30.5|Downward|11|3,215,182
ASK|2023-02-16|2023-02-16|1|31.0|31.0|0.0|0.0|0|0|31.75|30.75|Upward|12|3,653,445
ASK|2023-02-17|2023-02-17|1|30.25|30.25|0.0|0.0|0|0|31.0|29.25|Downward|13|3,652,773
ASK|2023-02-20|2023-02-23|4|31.25|31.75|0.5|1.6|2|0|32.0|30.5|Upward|17|6,103,912
ASK|2023-02-24|2023-03-03|6|31.5|28.25|-3.25|-10.32|-13|-3|31.75|28.25|Downward|23|11,911,943
ASP|2023-02-02|2023-02-03|2|3.16|3.1|-0.06|-1.9|-3|-2|3.24|3.1|Downward|25|14,858,238
ASP|2023-02-06|2023-02-06|1|3.14|3.14|0.0|0.0|0|0|3.14|3.1|Upward|26|2,481,635
ASP|2023-02-07|2023-02-21|11|3.12|3.04|-0.08|-2.56|-4|-1|3.16|3.0|Downward|37|21,400,201
ASP|2023-02-22|2023-02-22|1|3.08|3.08|0.0|0.0|0|0|3.08|3.04|Upward|38|1,637,637
ASP|2023-02-23|2023-02-28|4|3.06|3.04|-0.02|-0.65|-1|-1|3.08|3.02|Downward|42|10,779,886
ASP|2023-03-01|2023-03-03|3|3.06|3.1|0.04|1.31|2|0|3.14|3.04|Upward|45|10,768,354
ASW|2023-02-02|2023-02-06|3|8.35|8.65|0.3|3.59|6|2|8.75|8.2|Upward|48|17,065,834
ASW|2023-02-07|2023-02-08|2|8.5|8.5|0.0|0.0|0|0|8.7|8.5|Downward|50|3,049,115
ASW|2023-02-09|2023-02-09|1|8.7|8.7|0.0|0.0|0|0|8.7|8.3|Upward|51|2,759,769
ASW|2023-02-10|2023-02-13|2|8.6|8.4|-0.2|-2.33|-4|-2|8.7|8.3|Downward|53|2,469,307
ASW|2023-02-14|2023-02-14|1|8.45|8.45|0.0|0.0|0|0|8.5|8.35|Upward|54|1,006,727
ASW|2023-02-15|2023-02-15|1|8.2|8.2|0.0|0.0|0|0|8.3|8.1|Downward|55|4,297,457
ASW|2023-02-16|2023-02-16|1|8.25|8.25|0.0|0.0|0|0|8.3|8.2|Upward|56|973,650
ASW|2023-02-17|2023-02-17|1|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|57|938,972
ASW|2023-02-20|2023-02-21|2|8.3|8.35|0.05|0.6|1|0|8.4|8.2|Upward|59|785,523
ASW|2023-02-22|2023-02-22|1|8.3|8.3|0.0|0.0|0|0|8.35|8.25|Downward|60|488,746
ASW|2023-02-23|2023-02-24|2|8.4|8.45|0.05|0.6|1|0|8.7|8.25|Upward|62|8,096,714
ASW|2023-02-27|2023-02-27|1|8.3|8.3|0.0|0.0|0|0|8.45|8.25|Downward|63|1,347,901
ASW|2023-02-28|2023-03-03|4|8.4|8.65|0.25|2.98|5|1|8.7|8.3|Upward|67|5,923,610
BANPU|2023-02-02|2023-02-02|1|11.6|11.6|0.0|0.0|0|0|11.7|11.5|Upward|68|54,666,986
BANPU|2023-02-03|2023-02-10|6|11.5|10.9|-0.6|-5.22|-6|-1|11.6|10.7|Downward|74|1,000,663,700
BANPU|2023-02-13|2023-02-13|1|11.1|11.1|0.0|0.0|0|0|11.2|10.9|Upward|75|90,540,091
BANPU|2023-02-14|2023-02-15|2|11.0|11.0|0.0|0.0|0|0|11.3|10.9|Downward|77|219,310,115
BANPU|2023-02-16|2023-02-16|1|11.1|11.1|0.0|0.0|0|0|11.2|11.0|Upward|78|91,249,864
BANPU|2023-02-17|2023-02-17|1|10.9|10.9|0.0|0.0|0|0|11.1|10.9|Downward|79|59,387,401
BANPU|2023-02-20|2023-02-21|2|11.1|11.3|0.2|1.8|2|1|11.3|10.9|Upward|81|202,731,825
BANPU|2023-02-22|2023-02-22|1|11.2|11.2|0.0|0.0|0|0|11.2|11.0|Downward|82|77,378,013
BANPU|2023-02-23|2023-02-23|1|11.3|11.3|0.0|0.0|0|0|11.4|10.8|Upward|83|232,231,875
BANPU|2023-02-24|2023-03-01|4|11.2|10.8|-0.4|-3.57|-4|-1|11.5|10.7|Downward|87|1,187,417,164
BANPU|2023-03-02|2023-03-03|2|10.9|10.9|0.0|0.0|0|0|11.1|10.8|Upward|89|145,793,536
BCH|2023-02-02|2023-02-03|2|21.4|21.5|0.1|0.47|1|0|21.7|21.4|Upward|91|20,439,344
BCH|2023-02-06|2023-02-13|6|21.3|20.5|-0.8|-3.76|-8|-2|21.5|20.3|Downward|97|39,507,871
BCH|2023-02-14|2023-02-21|6|20.9|21.4|0.5|2.39|5|0|21.6|20.4|Upward|103|44,778,248
BCH|2023-02-22|2023-02-22|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|104|3,728,730
BCH|2023-02-23|2023-02-23|1|21.3|21.3|0.0|0.0|0|0|21.3|21.1|Upward|105|4,128,256
BCH|2023-02-24|2023-03-02|5|21.0|19.2|-1.8|-8.57|-18|-4|21.3|19.1|Downward|110|61,347,629
BCH|2023-03-03|2023-03-03|1|19.3|19.3|0.0|0.0|0|0|19.6|19.0|Upward|111|23,613,889
BH|2023-02-02|2023-02-03|2|217.0|217.0|0.0|0.0|0|0|222.0|216.0|Upward|113|4,605,507
BH|2023-02-06|2023-02-13|6|215.0|208.0|-7.0|-3.26|-7|-2|217.0|208.0|Downward|119|12,269,999
BH|2023-02-14|2023-02-14|1|210.0|210.0|0.0|0.0|0|0|212.0|207.0|Upward|120|2,423,646
BH|2023-02-15|2023-02-15|1|209.0|209.0|0.0|0.0|0|0|210.0|208.0|Downward|121|1,178,289
BH|2023-02-16|2023-02-17|2|215.0|217.0|2.0|0.93|2|1|219.0|212.0|Upward|123|8,640,034
BH|2023-02-20|2023-02-20|1|216.0|216.0|0.0|0.0|0|0|218.0|215.0|Downward|124|2,481,477
BH|2023-02-21|2023-02-23|3|217.0|220.0|3.0|1.38|3|1|222.0|216.0|Upward|127|7,809,523
BH|2023-02-24|2023-03-03|6|217.0|210.0|-7.0|-3.23|-7|-2|219.0|208.0|Downward|133|16,248,359
BJC|2023-02-02|2023-02-02|1|38.0|38.0|0.0|0.0|0|0|38.75|38.0|Downward|134|3,704,571
BJC|2023-02-03|2023-02-03|1|38.5|38.5|0.0|0.0|0|0|38.5|38.0|Upward|135|2,533,532
BJC|2023-02-06|2023-02-06|1|38.0|38.0|0.0|0.0|0|0|38.5|37.75|Downward|136|2,973,485
BJC|2023-02-07|2023-02-10|4|38.5|38.75|0.25|0.65|1|0|39.5|37.5|Upward|140|22,737,483
BJC|2023-02-13|2023-02-15|3|37.75|37.25|-0.5|-1.32|-2|-1|38.5|37.0|Downward|143|10,705,015
BJC|2023-02-16|2023-02-16|1|37.75|37.75|0.0|0.0|0|0|38.0|37.25|Upward|144|3,509,131
BJC|2023-02-17|2023-02-20|2|37.5|37.5|0.0|0.0|0|0|38.0|37.25|Downward|146|7,057,108
BJC|2023-02-21|2023-02-22|2|38.0|38.25|0.25|0.66|1|0|38.75|37.0|Upward|148|9,920,404
BJC|2023-02-23|2023-02-27|3|38.0|38.0|0.0|0.0|0|0|38.75|37.25|Downward|151|15,454,271
BJC|2023-02-28|2023-02-28|1|38.5|38.5|0.0|0.0|0|0|38.5|37.75|Upward|152|4,019,649
BJC|2023-03-01|2023-03-03|3|37.75|36.5|-1.25|-3.31|-5|-2|38.75|35.5|Downward|155|16,599,359
COM7|2023-02-02|2023-02-15|10|32.5|29.0|-3.5|-10.77|-14|-2|33.25|28.75|Downward|165|120,505,780
COM7|2023-02-16|2023-02-17|2|29.75|29.75|0.0|0.0|0|0|30.0|28.75|Upward|167|21,115,595
COM7|2023-02-20|2023-02-20|1|29.25|29.25|0.0|0.0|0|0|29.75|29.0|Downward|168|10,440,992
COM7|2023-02-21|2023-02-21|1|30.75|30.75|0.0|0.0|0|0|31.0|29.0|Upward|169|15,595,314
COM7|2023-02-22|2023-02-22|1|30.5|30.5|0.0|0.0|0|0|30.75|30.0|Downward|170|9,455,295
COM7|2023-02-23|2023-02-23|1|31.75|31.75|0.0|0.0|0|0|32.25|31.0|Upward|171|32,407,584
COM7|2023-02-24|2023-02-24|1|31.0|31.0|0.0|0.0|0|0|31.75|31.0|Downward|172|11,270,605
COM7|2023-02-27|2023-02-27|1|31.25|31.25|0.0|0.0|0|0|31.5|31.0|Upward|173|6,197,320
COM7|2023-02-28|2023-02-28|1|30.5|30.5|0.0|0.0|0|0|31.5|30.25|Downward|174|41,921,767
COM7|2023-03-01|2023-03-01|1|30.75|30.75|0.0|0.0|0|0|31.25|30.5|Upward|175|8,631,261
COM7|2023-03-02|2023-03-03|2|30.5|30.5|0.0|0.0|0|0|31.0|30.0|Downward|177|18,506,911
CPNREIT|2023-02-02|2023-02-14|9|19.4|18.2|-1.2|-6.19|-12|-2|19.5|18.2|Downward|186|19,941,645
CPNREIT|2023-02-15|2023-02-16|2|18.5|18.5|0.0|0.0|0|0|18.6|18.2|Upward|188|2,186,664
CPNREIT|2023-02-17|2023-02-17|1|18.3|18.3|0.0|0.0|0|0|18.5|18.2|Downward|189|3,194,164
CPNREIT|2023-02-20|2023-02-20|1|18.4|18.4|0.0|0.0|0|0|18.4|18.2|Upward|190|7,349,990
CPNREIT|2023-02-21|2023-03-03|9|18.2|14.6|-3.6|-19.78|-36|-4|18.4|14.2|Downward|199|39,048,631
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|203|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|204|8,569,954
DIF|2023-02-10|2023-02-15|4|13.3|13.2|-0.1|-0.75|-1|-1|13.4|13.2|Downward|208|48,275,264
DIF|2023-02-16|2023-02-17|2|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|210|6,762,497
DIF|2023-02-20|2023-02-21|2|13.2|13.2|0.0|0.0|0|0|13.4|13.2|Downward|212|13,562,635
DIF|2023-02-22|2023-02-22|1|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|213|5,061,405
DIF|2023-02-23|2023-02-23|1|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|214|2,396,091
DIF|2023-02-24|2023-03-02|5|13.3|13.3|0.0|0.0|0|0|13.4|13.2|Upward|219|32,407,114
DIF|2023-03-03|2023-03-03|1|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|220|2,470,166
GULF|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|54.5|53.75|Downward|221|9,315,414
GULF|2023-02-03|2023-02-03|1|54.0|54.0|0.0|0.0|0|0|54.0|53.5|Upward|222|8,673,708
GULF|2023-02-06|2023-02-06|1|53.75|53.75|0.0|0.0|0|0|54.25|53.5|Downward|223|8,272,063
GULF|2023-02-07|2023-02-07|1|54.0|54.0|0.0|0.0|0|0|54.25|53.75|Upward|224|11,502,957
GULF|2023-02-08|2023-02-09|2|53.5|53.25|-0.25|-0.47|-1|-1|54.25|53.0|Downward|226|27,332,773
GULF|2023-02-10|2023-02-13|2|53.75|54.5|0.75|1.4|3|1|54.5|53.25|Upward|228|24,949,952
GULF|2023-02-14|2023-02-14|1|54.0|54.0|0.0|0.0|0|0|54.5|53.5|Downward|229|16,321,710
GULF|2023-02-15|2023-02-15|1|54.25|54.25|0.0|0.0|0|0|54.25|53.25|Upward|230|13,952,411
GULF|2023-02-16|2023-02-16|1|54.0|54.0|0.0|0.0|0|0|54.5|53.75|Downward|231|8,044,837
GULF|2023-02-17|2023-02-17|1|54.25|54.25|0.0|0.0|0|0|54.5|53.75|Upward|232|15,929,950
GULF|2023-02-20|2023-02-20|1|54.0|54.0|0.0|0.0|0|0|54.5|53.75|Downward|233|7,966,131
GULF|2023-02-21|2023-02-21|1|54.5|54.5|0.0|0.0|0|0|54.5|53.75|Upward|234|14,566,196
GULF|2023-02-22|2023-02-27|4|54.25|52.25|-2.0|-3.69|-8|-2|54.5|51.5|Downward|238|69,076,105
GULF|2023-02-28|2023-02-28|1|52.5|52.5|0.0|0.0|0|0|53.0|52.25|Upward|239|9,704,749
GULF|2023-03-01|2023-03-03|3|51.25|50.25|-1.0|-1.95|-4|-2|52.25|50.0|Downward|242|58,687,332
GVREIT|2023-02-02|2023-02-02|1|9.7|9.7|0.0|0.0|0|0|9.75|9.65|Downward|243|224,521
GVREIT|2023-02-03|2023-02-07|3|9.75|9.8|0.05|0.51|1|0|9.9|9.6|Upward|246|1,566,531
GVREIT|2023-02-08|2023-02-10|3|9.75|9.65|-0.1|-1.03|-2|-1|9.8|9.55|Downward|249|913,806
GVREIT|2023-02-13|2023-02-16|4|9.7|9.8|0.1|1.03|2|0|9.85|9.65|Upward|253|1,832,807
GVREIT|2023-02-17|2023-03-02|10|9.7|9.3|-0.4|-4.12|-8|-1|9.8|9.3|Downward|263|3,683,813
GVREIT|2023-03-03|2023-03-03|1|9.45|9.45|0.0|0.0|0|0|9.45|9.3|Upward|264|94,400
IVL|2023-02-02|2023-02-02|1|40.75|40.75|0.0|0.0|0|0|41.25|40.5|Upward|265|8,485,930
IVL|2023-02-03|2023-02-03|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|266|7,485,590
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|0|0|41.25|39.75|Upward|267|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|268|11,842,657
IVL|2023-02-08|2023-02-09|2|40.75|40.75|0.0|0.0|0|0|41.5|40.25|Upward|270|22,518,750
IVL|2023-02-10|2023-02-13|2|40.5|40.0|-0.5|-1.23|-2|-1|40.75|39.75|Downward|272|18,080,401
IVL|2023-02-14|2023-02-14|1|40.25|40.25|0.0|0.0|0|0|40.75|40.0|Upward|273|8,413,044
IVL|2023-02-15|2023-02-20|4|40.0|38.75|-1.25|-3.13|-5|-2|40.5|38.5|Downward|277|50,931,185
IVL|2023-02-21|2023-02-21|1|39.25|39.25|0.0|0.0|0|0|39.5|38.75|Upward|278|8,052,453
IVL|2023-02-22|2023-03-01|6|39.0|36.5|-2.5|-6.41|-10|-2|39.5|36.5|Downward|284|106,357,314
IVL|2023-03-02|2023-03-03|2|37.0|37.25|0.25|0.68|1|0|37.75|36.5|Upward|286|32,773,083
JASIF|2023-02-02|2023-02-08|5|8.2|8.25|0.05|0.61|1|0|8.25|8.2|Upward|291|15,864,400
JASIF|2023-02-10|2023-02-17|6|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.1|Downward|297|32,237,608
JASIF|2023-02-20|2023-02-23|4|8.2|8.25|0.05|0.61|1|0|8.3|8.15|Upward|301|67,646,312
JASIF|2023-02-24|2023-03-03|6|8.2|7.95|-0.25|-3.05|-5|-1|8.3|7.95|Downward|307|77,979,596
JMART|2023-02-02|2023-02-15|10|37.5|28.5|-9.0|-24.0|-36|-4|38.25|28.5|Downward|317|170,665,969
JMART|2023-02-16|2023-02-16|1|29.5|29.5|0.0|0.0|0|0|30.75|28.0|Upward|318|69,203,823
JMART|2023-02-17|2023-02-17|1|27.25|27.25|0.0|0.0|0|0|29.0|25.75|Downward|319|64,672,279
JMART|2023-02-20|2023-02-20|1|29.25|29.25|0.0|0.0|0|0|29.75|28.25|Upward|320|59,972,500
JMART|2023-02-21|2023-02-22|2|28.75|28.75|0.0|0.0|0|0|29.5|28.25|Downward|322|48,817,262
JMART|2023-02-23|2023-02-23|1|29.0|29.0|0.0|0.0|0|0|29.25|28.5|Upward|323|11,137,272
JMART|2023-02-24|2023-02-24|1|27.75|27.75|0.0|0.0|0|0|29.0|27.75|Downward|324|16,819,177
JMART|2023-02-27|2023-02-28|2|28.0|28.25|0.25|0.89|1|0|28.75|27.0|Upward|326|19,062,955
JMART|2023-03-01|2023-03-03|3|27.5|26.75|-0.75|-2.73|-3|-1|28.5|26.25|Downward|329|29,214,181
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|330|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|331|12,417,267
JMT|2023-02-06|2023-02-08|3|53.75|50.75|-3.0|-5.58|-12|-4|54.75|50.75|Downward|334|33,982,605
JMT|2023-02-09|2023-02-09|1|52.0|52.0|0.0|0.0|0|0|53.0|50.25|Upward|335|14,352,623
JMT|2023-02-10|2023-02-13|2|50.5|49.5|-1.0|-1.98|-4|-2|52.0|48.75|Downward|337|35,100,334
JMT|2023-02-14|2023-02-14|1|50.0|50.0|0.0|0.0|0|0|53.25|49.5|Upward|338|45,121,902
JMT|2023-02-15|2023-02-15|1|42.75|42.75|0.0|0.0|0|0|50.5|42.0|Downward|339|75,936,256
JMT|2023-02-16|2023-02-23|6|45.5|48.5|3.0|6.59|12|2|49.25|42.0|Upward|345|146,280,662
JMT|2023-02-24|2023-03-03|6|47.5|45.0|-2.5|-5.26|-10|-2|49.0|44.25|Downward|351|58,821,946
KCE|2023-02-02|2023-02-02|1|56.75|56.75|0.0|0.0|0|0|57.25|56.0|Downward|352|24,398,027
KCE|2023-02-03|2023-02-03|1|58.0|58.0|0.0|0.0|0|0|58.5|56.5|Upward|353|47,290,254
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|0|0|57.75|56.25|Downward|354|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|0|0|57.75|56.0|Upward|355|17,516,788

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

KCE|2023-02-08|2023-02-10|3|50.5|47.25|-3.25|-6.44|-13|-5|55.25|47.25|Downward|358|202,268,953
KCE|2023-02-13|2023-02-13|1|48.0|48.0|0.0|0.0|0|0|48.25|46.75|Upward|359|16,263,448
KCE|2023-02-14|2023-02-17|4|47.0|46.0|-1.0|-2.13|-4|-1|48.75|45.25|Downward|363|68,009,070
KCE|2023-02-20|2023-02-21|2|47.25|47.75|0.5|1.06|2|1|48.0|46.0|Upward|365|22,182,100
KCE|2023-02-22|2023-02-22|1|46.75|46.75|0.0|0.0|0|0|47.75|46.75|Downward|366|5,344,181
KCE|2023-02-23|2023-02-23|1|47.25|47.25|0.0|0.0|0|0|47.25|46.5|Upward|367|5,977,020
KCE|2023-02-24|2023-02-24|1|46.0|46.0|0.0|0.0|0|0|47.5|45.25|Downward|368|21,559,427
KCE|2023-03-01|2023-03-01|1|47.5|47.5|0.0|0.0|0|0|48.0|46.5|Upward|369|15,233,320
KCE|2023-03-02|2023-03-03|2|47.0|47.0|0.0|0.0|0|0|48.5|46.25|Downward|371|23,593,212
MCS|2023-02-02|2023-02-06|3|9.95|9.9|-0.05|-0.5|-1|-1|10.1|9.9|Downward|374|1,600,212
MCS|2023-02-07|2023-02-07|1|9.95|9.95|0.0|0.0|0|0|10.0|9.9|Upward|375|406,865
MCS|2023-02-08|2023-02-10|3|9.9|9.85|-0.05|-0.51|-1|-1|9.95|9.8|Downward|378|1,491,749
MCS|2023-02-13|2023-02-13|1|9.9|9.9|0.0|0.0|0|0|9.95|9.85|Upward|379|411,280
MCS|2023-02-14|2023-02-17|4|9.85|9.85|0.0|0.0|0|0|9.95|9.7|Downward|383|4,258,651
MCS|2023-02-20|2023-02-20|1|9.95|9.95|0.0|0.0|0|0|10.0|9.8|Upward|384|860,075
MCS|2023-02-21|2023-02-23|3|10.1|10.1|0.0|0.0|0|0|10.2|10.1|Downward|387|2,950,752
MCS|2023-02-24|2023-02-24|1|10.2|10.2|0.0|0.0|0|0|10.3|9.95|Upward|388|1,693,849
MCS|2023-02-27|2023-02-27|1|10.0|10.0|0.0|0.0|0|0|10.2|9.9|Downward|389|1,519,625
MCS|2023-02-28|2023-02-28|1|9.8|9.8|0.0|0.0|0|0|10.0|9.55|Upward|390|2,511,948
MCS|2023-03-01|2023-03-01|1|9.65|9.65|0.0|0.0|0|0|9.85|9.65|Downward|391|1,002,104
MCS|2023-03-02|2023-03-02|1|9.75|9.75|0.0|0.0|0|0|9.75|9.6|Upward|392|1,626,490
MCS|2023-03-03|2023-03-03|1|9.45|9.45|0.0|0.0|0|0|9.7|9.45|Downward|393|1,464,157
NER|2023-02-02|2023-02-03|2|6.4|6.4|0.0|0.0|0|0|6.4|6.3|Downward|395|16,050,686
NER|2023-02-06|2023-02-06|1|6.5|6.5|0.0|0.0|0|0|6.5|6.4|Upward|396|8,375,847
NER|2023-02-07|2023-02-15|7|6.45|5.7|-0.75|-11.63|-15|-3|6.5|5.7|Downward|403|71,851,210
NER|2023-02-16|2023-02-27|8|5.85|6.25|0.4|6.84|8|1|6.3|5.75|Upward|411|79,560,804
NER|2023-02-28|2023-03-02|3|6.15|6.15|0.0|0.0|0|0|6.3|6.1|Downward|414|17,992,952
NER|2023-03-03|2023-03-03|1|6.25|6.25|0.0|0.0|0|0|6.3|6.15|Upward|415|12,061,486
ORI|2023-02-02|2023-02-03|2|12.0|12.0|0.0|0.0|0|0|12.3|11.9|Upward|417|8,612,092
ORI|2023-02-06|2023-02-09|4|11.7|11.7|0.0|0.0|0|0|12.0|11.5|Downward|421|22,908,405
ORI|2023-02-10|2023-02-10|1|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|422|4,834,840
ORI|2023-02-13|2023-02-16|4|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|426|19,889,480
ORI|2023-02-17|2023-02-23|5|11.8|12.1|0.3|2.54|3|0|12.2|11.5|Upward|431|30,191,190
ORI|2023-02-24|2023-02-24|1|11.8|11.8|0.0|0.0|0|0|12.1|11.7|Downward|432|5,574,476
ORI|2023-02-27|2023-02-28|2|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|434|12,282,288
ORI|2023-03-01|2023-03-03|3|11.6|11.6|0.0|0.0|0|0|11.9|11.6|Downward|437|20,639,855
PSH|2023-02-02|2023-02-02|1|13.2|13.2|0.0|0.0|0|0|13.4|13.2|Downward|438|1,958,851
PSH|2023-02-03|2023-02-03|1|13.4|13.4|0.0|0.0|0|0|13.5|13.1|Upward|439|2,688,710
PSH|2023-02-06|2023-02-06|1|13.3|13.3|0.0|0.0|0|0|13.5|13.2|Downward|440|969,907
PSH|2023-02-07|2023-02-07|1|13.4|13.4|0.0|0.0|0|0|13.4|13.2|Upward|441|381,025
PSH|2023-02-08|2023-02-10|3|13.3|13.1|-0.2|-1.5|-2|-1|13.4|12.8|Downward|444|3,313,245
PSH|2023-02-13|2023-02-13|1|13.2|13.2|0.0|0.0|0|0|13.2|13.0|Upward|445|725,888
PSH|2023-02-14|2023-02-15|2|13.1|12.9|-0.2|-1.53|-2|-1|13.2|12.9|Downward|447|1,819,769
PSH|2023-02-16|2023-02-21|4|13.1|13.7|0.6|4.58|6|1|14.0|12.9|Upward|451|10,253,697
PSH|2023-02-22|2023-02-23|2|13.6|13.6|0.0|0.0|0|0|13.8|13.5|Downward|453|3,932,659
PSH|2023-02-24|2023-02-27|2|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|455|2,392,454
PSH|2023-03-01|2023-03-03|3|13.6|13.6|0.0|0.0|0|0|13.7|13.4|Downward|458|3,499,221
PTTGC|2023-02-02|2023-02-06|3|49.75|49.5|-0.25|-0.5|-1|-1|50.25|49.0|Downward|461|20,473,206
PTTGC|2023-02-07|2023-02-14|6|49.75|50.5|0.75|1.51|3|0|52.5|49.25|Upward|467|123,970,421
PTTGC|2023-02-15|2023-02-17|3|49.5|48.75|-0.75|-1.52|-3|-1|50.5|48.25|Downward|470|43,536,945
PTTGC|2023-02-20|2023-02-20|1|49.0|49.0|0.0|0.0|0|0|49.25|48.5|Upward|471|9,154,257
PTTGC|2023-02-21|2023-03-01|7|48.75|47.0|-1.75|-3.59|-7|-1|49.5|46.5|Downward|478|86,448,039
PTTGC|2023-03-02|2023-03-02|1|48.25|48.25|0.0|0.0|0|0|48.5|47.25|Upward|479|16,205,129
PTTGC|2023-03-03|2023-03-03|1|48.0|48.0|0.0|0.0|0|0|48.5|47.75|Downward|480|7,771,327
QH|2023-02-02|2023-02-09|6|2.38|2.34|-0.04|-1.68|-2|-1|2.38|2.32|Downward|486|111,154,952
QH|2023-02-10|2023-02-10|1|2.36|2.36|0.0|0.0|0|0|2.36|2.32|Upward|487|14,689,644
QH|2023-02-13|2023-02-13|1|2.34|2.34|0.0|0.0|0|0|2.36|2.34|Downward|488|4,479,266
QH|2023-02-14|2023-02-15|2|2.36|2.36|0.0|0.0|0|0|2.36|2.34|Upward|490|20,158,953
QH|2023-02-16|2023-02-17|2|2.34|2.32|-0.02|-0.85|-1|-1|2.36|2.32|Downward|492|29,421,730
QH|2023-02-20|2023-02-20|1|2.34|2.34|0.0|0.0|0|0|2.34|2.32|Upward|493|2,244,474
QH|2023-02-21|2023-02-22|2|2.32|2.32|0.0|0.0|0|0|2.36|2.3|Downward|495|26,857,061
QH|2023-02-23|2023-03-03|7|2.34|2.4|0.06|2.56|3|0|2.42|2.3|Upward|502|168,338,528
RCL|2023-02-02|2023-02-07|4|30.25|31.0|0.75|2.48|3|0|31.25|30.0|Upward|506|11,140,469
RCL|2023-02-08|2023-02-09|2|30.5|30.5|0.0|0.0|0|0|31.25|30.25|Downward|508|4,603,482
RCL|2023-02-10|2023-02-10|1|30.75|30.75|0.0|0.0|0|0|30.75|30.25|Upward|509|1,341,212
RCL|2023-02-13|2023-02-15|3|29.5|29.0|-0.5|-1.69|-2|-1|30.75|29.0|Downward|512|10,038,784
RCL|2023-02-16|2023-02-16|1|29.5|29.5|0.0|0.0|0|0|30.0|29.25|Upward|513|1,739,426
RCL|2023-02-17|2023-02-17|1|29.25|29.25|0.0|0.0|0|0|29.5|29.0|Downward|514|1,185,810
RCL|2023-02-20|2023-02-24|5|29.75|31.75|2.0|6.72|8|1|32.5|29.25|Upward|519|26,002,921
RCL|2023-02-27|2023-02-27|1|31.0|31.0|0.0|0.0|0|0|32.25|30.75|Downward|520|10,194,436
RCL|2023-02-28|2023-03-03|4|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|524|24,330,280
SAT|2023-02-02|2023-02-02|1|21.4|21.4|0.0|0.0|0|0|21.6|21.3|Upward|525|549,652
SAT|2023-02-03|2023-02-03|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Downward|526|459,249
SAT|2023-02-06|2023-02-06|1|21.6|21.6|0.0|0.0|0|0|21.8|21.2|Upward|527|1,273,172
SAT|2023-02-07|2023-02-17|9|21.5|20.4|-1.1|-5.12|-11|-2|21.7|20.3|Downward|536|7,375,511
SAT|2023-02-20|2023-02-20|1|20.7|20.7|0.0|0.0|0|0|20.8|20.3|Upward|537|429,665
SAT|2023-02-21|2023-02-21|1|20.5|20.5|0.0|0.0|0|0|20.7|20.4|Downward|538|1,767,905
SAT|2023-02-22|2023-02-24|3|20.8|20.9|0.1|0.48|1|0|21.2|20.5|Upward|541|2,606,720
SAT|2023-02-27|2023-02-28|2|20.8|20.6|-0.2|-0.96|-2|-1|21.2|20.6|Downward|543|1,717,785
SAT|2023-03-01|2023-03-03|3|20.7|21.0|0.3|1.45|3|1|21.2|20.7|Upward|546|2,775,827
SC|2023-02-02|2023-02-03|2|4.68|4.68|0.0|0.0|0|0|4.76|4.62|Upward|548|18,454,829
SC|2023-02-06|2023-02-06|1|4.6|4.6|0.0|0.0|0|0|4.7|4.6|Downward|549|8,374,193
SC|2023-02-07|2023-02-07|1|4.64|4.64|0.0|0.0|0|0|4.7|4.62|Upward|550|6,508,767
SC|2023-02-08|2023-02-09|2|4.54|4.54|0.0|0.0|0|0|4.7|4.4|Downward|552|28,474,503
SC|2023-02-10|2023-02-10|1|4.6|4.6|0.0|0.0|0|0|4.62|4.48|Upward|553|8,687,493
SC|2023-02-13|2023-02-15|3|4.5|4.38|-0.12|-2.67|-6|-2|4.6|4.34|Downward|556|28,390,481
SC|2023-02-16|2023-02-17|2|4.42|4.58|0.16|3.62|8|4|4.62|4.36|Upward|558|49,621,587
SC|2023-02-20|2023-02-20|1|4.54|4.54|0.0|0.0|0|0|4.62|4.52|Downward|559|9,029,168
SC|2023-02-21|2023-02-21|1|4.7|4.7|0.0|0.0|0|0|4.74|4.5|Upward|560|46,183,412
SC|2023-02-22|2023-02-23|2|4.64|4.62|-0.02|-0.43|-1|-1|4.7|4.6|Downward|562|29,880,204
SC|2023-02-24|2023-02-24|1|4.64|4.64|0.0|0.0|0|0|4.66|4.44|Upward|563|32,801,288
SC|2023-02-27|2023-02-27|1|4.62|4.62|0.0|0.0|0|0|4.66|4.58|Downward|564|8,009,116
SC|2023-02-28|2023-02-28|1|4.64|4.64|0.0|0.0|0|0|4.66|4.52|Upward|565|11,721,935
SC|2023-03-01|2023-03-03|3|4.56|4.44|-0.12|-2.63|-6|-2|4.68|4.44|Downward|568|49,078,693
SCC|2023-02-02|2023-02-06|3|338.0|336.0|-2.0|-0.59|-2|-1|343.0|336.0|Downward|571|4,970,202
SCC|2023-02-07|2023-02-10|4|338.0|338.0|0.0|0.0|0|0|340.0|335.0|Upward|575|8,476,335
SCC|2023-02-13|2023-02-13|1|335.0|335.0|0.0|0.0|0|0|339.0|335.0|Downward|576|1,796,324
SCC|2023-02-14|2023-02-14|1|341.0|341.0|0.0|0.0|0|0|341.0|336.0|Upward|577|3,326,298
SCC|2023-02-15|2023-02-15|1|338.0|338.0|0.0|0.0|0|0|340.0|338.0|Downward|578|888,346
SCC|2023-02-16|2023-02-17|2|340.0|340.0|0.0|0.0|0|0|340.0|337.0|Upward|580|2,181,706
SCC|2023-02-20|2023-02-20|1|339.0|339.0|0.0|0.0|0|0|341.0|338.0|Downward|581|520,070
SCC|2023-02-21|2023-02-21|1|340.0|340.0|0.0|0.0|0|0|342.0|338.0|Upward|582|1,152,516
SCC|2023-02-22|2023-02-22|1|336.0|336.0|0.0|0.0|0|0|340.0|335.0|Downward|583|1,864,147
SCC|2023-02-23|2023-02-23|1|338.0|338.0|0.0|0.0|0|0|339.0|336.0|Upward|584|1,093,452
SCC|2023-02-24|2023-03-01|4|331.0|321.0|-10.0|-3.02|-10|-3|338.0|321.0|Downward|588|9,462,137
SCC|2023-03-02|2023-03-02|1|330.0|330.0|0.0|0.0|0|0|332.0|322.0|Upward|589|4,015,702
SCC|2023-03-03|2023-03-03|1|328.0|328.0|0.0|0.0|0|0|333.0|328.0|Downward|590|1,475,661
SENA|2023-02-02|2023-02-02|1|4.02|4.02|0.0|0.0|0|0|4.02|3.96|Downward|591|1,982,432
SENA|2023-02-03|2023-02-06|2|4.04|4.04|0.0|0.0|0|0|4.06|4.0|Upward|593|2,235,000
SENA|2023-02-07|2023-02-08|2|4.0|3.94|-0.06|-1.5|-3|-2|4.04|3.94|Downward|595|2,218,445
SENA|2023-02-09|2023-02-10|2|3.96|3.96|0.0|0.0|0|0|3.98|3.92|Upward|597|1,521,299
SENA|2023-02-13|2023-02-17|5|3.94|3.94|0.0|0.0|0|0|3.96|3.9|Downward|602|2,673,089
SENA|2023-02-20|2023-02-21|2|3.96|3.98|0.02|0.51|1|0|4.0|3.92|Upward|604|1,192,630
SENA|2023-02-22|2023-03-03|8|3.96|3.6|-0.36|-9.09|-18|-3|4.0|3.56|Downward|612|12,132,789
SINGER|2023-02-02|2023-02-08|5|28.5|27.0|-1.5|-5.26|-6|-2|29.25|27.0|Downward|617|20,580,042
SINGER|2023-02-09|2023-02-09|1|27.5|27.5|0.0|0.0|0|0|27.5|26.25|Upward|618|5,240,034
SINGER|2023-02-10|2023-02-17|6|26.75|17.3|-9.45|-35.33|-84|-14|27.5|16.7|Downward|624|291,031,300
SINGER|2023-02-20|2023-02-20|1|21.5|21.5|0.0|0.0|0|0|22.2|17.1|Upward|625|164,519,637
SINGER|2023-02-21|2023-02-21|1|21.0|21.0|0.0|0.0|0|0|21.8|20.7|Downward|626|48,322,744
SINGER|2023-02-22|2023-02-23|2|22.6|22.9|0.3|1.33|3|1|23.8|20.9|Upward|628|118,849,603
SINGER|2023-02-24|2023-02-24|1|22.0|22.0|0.0|0.0|0|0|23.3|21.9|Downward|629|22,689,633
SINGER|2023-02-27|2023-02-27|1|22.7|22.7|0.0|0.0|0|0|22.9|21.8|Upward|630|24,302,313
SINGER|2023-02-28|2023-03-01|2|22.5|21.5|-1.0|-4.44|-10|-5|23.1|21.3|Downward|632|26,214,373
SINGER|2023-03-02|2023-03-02|1|23.1|23.1|0.0|0.0|0|0|23.6|21.9|Upward|633|61,598,983
SINGER|2023-03-03|2023-03-03|1|22.2|22.2|0.0|0.0|0|0|23.0|22.1|Downward|634|23,774,295
SNC|2023-02-02|2023-02-06|3|14.6|14.5|-0.1|-0.68|-1|-1|14.6|14.4|Downward|637|750,233
SNC|2023-02-07|2023-02-07|1|14.6|14.6|0.0|0.0|0|0|14.6|14.5|Upward|638|373,800
SNC|2023-02-08|2023-02-15|6|14.5|13.8|-0.7|-4.83|-7|-2|14.7|13.8|Downward|644|3,658,519
SNC|2023-02-16|2023-02-16|1|14.0|14.0|0.0|0.0|0|0|14.0|13.8|Upward|645|258,010
SNC|2023-02-17|2023-02-17|1|13.8|13.8|0.0|0.0|0|0|14.0|13.7|Downward|646|519,107
SNC|2023-02-20|2023-02-21|2|14.5|14.6|0.1|0.69|1|0|14.7|14.3|Upward|648|5,545,525
SNC|2023-02-22|2023-02-22|1|14.3|14.3|0.0|0.0|0|0|14.6|14.3|Downward|649|2,118,907
SNC|2023-02-23|2023-02-24|2|14.4|14.4|0.0|0.0|0|0|14.6|14.3|Upward|651|2,278,767
SNC|2023-02-27|2023-02-27|1|14.3|14.3|0.0|0.0|0|0|14.5|14.3|Downward|652|605,892
SNC|2023-02-28|2023-03-01|2|14.4|14.4|0.0|0.0|0|0|14.5|14.3|Upward|654|2,122,752
SNC|2023-03-02|2023-03-03|2|14.1|14.0|-0.1|-0.71|-1|-1|14.1|13.8|Downward|656|3,916,963
STA|2023-02-02|2023-02-03|2|22.7|22.3|-0.4|-1.76|-4|-2|22.7|21.9|Downward|658|12,988,072
STA|2023-02-06|2023-02-08|3|22.6|24.5|1.9|8.41|19|6|24.7|22.3|Upward|661|41,947,740
STA|2023-02-09|2023-02-13|3|24.1|23.6|-0.5|-2.07|-5|-2|24.5|23.5|Downward|664|22,887,544
STA|2023-02-14|2023-02-14|1|24.1|24.1|0.0|0.0|0|0|24.3|23.5|Upward|665|10,632,765
STA|2023-02-15|2023-02-16|2|23.8|23.6|-0.2|-0.84|-2|-1|24.1|22.9|Downward|667|14,098,409
STA|2023-02-17|2023-02-23|5|23.8|25.75|1.95|8.19|15|3|25.75|23.6|Upward|672|38,138,825
STA|2023-02-24|2023-02-24|1|25.25|25.25|0.0|0.0|0|0|25.75|25.0|Downward|673|7,323,636
STA|2023-02-27|2023-02-27|1|25.75|25.75|0.0|0.0|0|0|26.0|25.5|Upward|674|3,712,404
STA|2023-02-28|2023-03-03|4|25.25|24.3|-0.95|-3.76|-8|-2|26.0|24.1|Downward|678|24,651,759
SYNEX|2023-02-02|2023-02-02|1|16.5|16.5|0.0|0.0|0|0|16.7|16.5|Downward|679|987,769
SYNEX|2023-02-03|2023-02-07|3|16.6|17.1|0.5|3.01|5|1|17.6|16.4|Upward|682|11,846,121
SYNEX|2023-02-08|2023-02-08|1|16.3|16.3|0.0|0.0|0|0|17.2|16.3|Downward|683|3,347,661
SYNEX|2023-02-09|2023-02-09|1|16.6|16.6|0.0|0.0|0|0|16.6|16.3|Upward|684|1,122,744
SYNEX|2023-02-10|2023-02-14|3|16.5|15.8|-0.7|-4.24|-7|-3|16.7|15.8|Downward|687|4,716,214
SYNEX|2023-02-15|2023-02-16|2|16.1|16.2|0.1|0.62|1|0|16.5|15.6|Upward|689|3,908,567
SYNEX|2023-02-17|2023-02-17|1|16.1|16.1|0.0|0.0|0|0|16.5|15.9|Downward|690|2,500,399
SYNEX|2023-02-20|2023-02-22|3|16.4|16.7|0.3|1.83|3|1|16.7|16.0|Upward|693|2,794,196
SYNEX|2023-02-23|2023-03-01|5|16.4|15.9|-0.5|-3.05|-5|-1|16.8|15.9|Downward|698|3,629,594
SYNEX|2023-03-02|2023-03-02|1|16.0|16.0|0.0|0.0|0|0|16.1|15.9|Upward|699|358,583
SYNEX|2023-03-03|2023-03-03|1|15.6|15.6|0.0|0.0|0|0|16.0|15.5|Downward|700|1,664,125
TCAP|2023-02-02|2023-02-02|1|43.0|43.0|0.0|0.0|0|0|43.5|43.0|Downward|701|2,285,875
TCAP|2023-02-03|2023-02-03|1|43.25|43.25|0.0|0.0|0|0|43.25|43.0|Upward|702|873,185
TCAP|2023-02-06|2023-02-06|1|43.0|43.0|0.0|0.0|0|0|43.25|42.75|Downward|703|2,192,738
TCAP|2023-02-07|2023-02-07|1|43.25|43.25|0.0|0.0|0|0|43.5|42.75|Upward|704|1,622,069
TCAP|2023-02-08|2023-02-16|7|42.75|42.5|-0.25|-0.58|-1|-1|43.0|42.5|Downward|711|11,045,417
TCAP|2023-02-17|2023-02-17|1|42.75|42.75|0.0|0.0|0|0|42.75|42.25|Upward|712|1,904,030
TCAP|2023-02-20|2023-02-20|1|42.5|42.5|0.0|0.0|0|0|43.0|42.5|Downward|713|1,118,202
TCAP|2023-02-21|2023-02-21|1|43.25|43.25|0.0|0.0|0|0|43.5|43.0|Upward|714|2,337,857
TCAP|2023-02-22|2023-02-27|4|43.0|42.5|-0.5|-1.16|-2|-1|43.25|42.25|Downward|718|11,761,986
TCAP|2023-02-28|2023-03-03|4|42.75|43.0|0.25|0.58|1|0|43.0|42.5|Upward|722|8,044,813
TFFIF|2023-02-02|2023-02-03|2|8.15|8.25|0.1|1.23|2|1|8.3|8.15|Upward|724|5,031,233
TFFIF|2023-02-06|2023-02-21|12|8.2|7.9|-0.3|-3.66|-6|-1|8.25|7.85|Downward|736|31,159,347
TFFIF|2023-02-22|2023-02-23|2|7.95|7.95|0.0|0.0|0|0|8.0|7.9|Upward|738|1,911,923
TFFIF|2023-02-24|2023-02-27|2|7.9|7.9|0.0|0.0|0|0|8.0|7.9|Downward|740|3,851,408
TFFIF|2023-02-28|2023-03-01|2|7.95|8.0|0.05|0.63|1|0|8.05|7.85|Upward|742|3,657,878
TFFIF|2023-03-02|2023-03-03|2|7.85|7.85|0.0|0.0|0|0|7.95|7.8|Downward|744|2,475,002
TMT|2023-02-02|2023-02-02|1|8.15|8.15|0.0|0.0|0|0|8.3|8.15|Downward|745|314,612
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|746|162,400
TMT|2023-02-06|2023-02-09|4|8.15|8.05|-0.1|-1.23|-2|-1|8.25|8.0|Downward|750|760,892
TMT|2023-02-10|2023-02-10|1|8.2|8.2|0.0|0.0|0|0|8.2|8.0|Upward|751|158,167
TMT|2023-02-13|2023-02-16|4|8.05|7.9|-0.15|-1.86|-3|-1|8.1|7.8|Downward|755|884,650
TMT|2023-02-17|2023-02-20|2|8.0|8.15|0.15|1.88|3|1|8.15|7.85|Upward|757|178,445
TMT|2023-02-21|2023-03-02|8|8.1|7.4|-0.7|-8.64|-14|-2|8.15|7.35|Downward|765|2,594,520
TMT|2023-03-03|2023-03-03|1|7.45|7.45|0.0|0.0|0|0|7.45|7.35|Upward|766|76,401
TTB|2023-02-02|2023-02-06|3|1.45|1.45|0.0|0.0|0|0|1.47|1.44|Upward|769|309,856,418
TTB|2023-02-07|2023-02-10|4|1.42|1.4|-0.02|-1.41|-2|-1|1.45|1.39|Downward|773|874,455,439
TTB|2023-02-13|2023-02-13|1|1.41|1.41|0.0|0.0|0|0|1.42|1.39|Upward|774|153,475,351
TTB|2023-02-14|2023-02-17|4|1.4|1.36|-0.04|-2.86|-4|-1|1.42|1.36|Downward|778|748,388,635
TTB|2023-02-20|2023-02-21|2|1.4|1.41|0.01|0.71|1|0|1.41|1.36|Upward|780|322,393,282
TTB|2023-02-22|2023-02-23|2|1.39|1.39|0.0|0.0|0|0|1.41|1.38|Downward|782|312,329,992
TTB|2023-02-24|2023-02-28|3|1.4|1.4|0.0|0.0|0|0|1.41|1.39|Upward|785|482,182,873
TTB|2023-03-01|2023-03-02|2|1.39|1.37|-0.02|-1.44|-2|-1|1.41|1.36|Downward|787|485,502,722
TTB|2023-03-03|2023-03-03|1|1.39|1.39|0.0|0.0|0|0|1.39|1.36|Upward|788|260,463,858
WHA|2023-02-02|2023-02-02|1|4.02|4.02|0.0|0.0|0|0|4.02|3.92|Upward|789|245,744,462
WHA|2023-02-03|2023-02-08|4|3.98|3.9|-0.08|-2.01|-4|-1|4.02|3.86|Downward|793|300,886,435

'C:\\users\\user\\onedrive\\a7\\daily'

WHA|2023-02-09|2023-02-10|2|3.92|3.92|0.0|0.0|0|0|3.94|3.84|Upward|795|168,969,404
WHA|2023-02-13|2023-02-14|2|3.86|3.86|0.0|0.0|0|0|3.94|3.82|Downward|797|131,734,151
WHA|2023-02-15|2023-02-15|1|3.88|3.88|0.0|0.0|0|0|3.9|3.84|Upward|798|56,820,956
WHA|2023-02-16|2023-02-16|1|3.84|3.84|0.0|0.0|0|0|3.92|3.84|Downward|799|43,889,180
WHA|2023-02-17|2023-02-21|3|3.86|4.0|0.14|3.63|7|2|4.0|3.82|Upward|802|373,308,103
WHA|2023-02-22|2023-02-23|2|3.94|3.94|0.0|0.0|0|0|4.0|3.9|Downward|804|188,620,138
WHA|2023-02-24|2023-02-27|2|3.98|4.06|0.08|2.01|4|2|4.08|3.94|Upward|806|327,437,526
WHA|2023-02-28|2023-03-03|4|3.94|3.94|0.0|0.0|0|0|4.06|3.92|Downward|810|637,428,200
WHAIR|2023-02-02|2023-02-02|1|8.0|8.0|0.0|0.0|0|0|8.0|7.95|Downward|811|959,018
WHAIR|2023-02-03|2023-02-03|1|8.05|8.05|0.0|0.0|0|0|8.05|8.0|Upward|812|449,631
WHAIR|2023-02-06|2023-02-10|5|8.0|7.9|-0.1|-1.25|-2|-1|8.1|7.85|Downward|817|2,057,078
WHAIR|2023-02-13|2023-02-14|2|7.95|7.95|0.0|0.0|0|0|8.0|7.8|Upward|819|482,551
WHAIR|2023-02-15|2023-02-15|1|7.8|7.8|0.0|0.0|0|0|7.9|7.8|Downward|820|279,749
WHAIR|2023-02-16|2023-02-17|2|7.85|7.85|0.0|0.0|0|0|7.9|7.7|Upward|822|337,446
WHAIR|2023-02-20|2023-02-20|1|7.8|7.8|0.0|0.0|0|0|7.85|7.8|Downward|823|454,128
WHAIR|2023-02-21|2023-02-21|1|7.85|7.85|0.0|0.0|0|0|7.85|7.75|Upward|824|244,305
WHAIR|2023-02-22|2023-02-23|2|7.7|7.6|-0.1|-1.3|-2|-1|7.75|7.55|Downward|826|1,896,503
WHAIR|2023-02-24|2023-02-27|2|7.65|7.7|0.05|0.65|1|0|7.7|7.5|Upward|828|715,774
WHAIR|2023-02-28|2023-03-03|4|7.65|7.6|-0.05|-0.65|-1|-1|7.7|7.5|Downward|832|2,052,255
WHART|2023-02-02|2023-02-07|4|11.8|11.6|-0.2|-1.69|-2|-1|11.9|11.6|Downward|836|3,952,768
WHART|2023-02-08|2023-02-08|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|837|459,646
WHART|2023-02-09|2023-02-09|1|11.6|11.6|0.0|0.0|0|0|11.7|11.5|Downward|838|927,026
WHART|2023-02-10|2023-02-10|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|839|632,010
WHART|2023-02-13|2023-02-13|1|11.5|11.5|0.0|0.0|0|0|11.7|11.5|Downward|840|1,544,552
WHART|2023-02-14|2023-02-14|1|11.6|11.6|0.0|0.0|0|0|11.6|11.5|Upward|841|2,133,923
WHART|2023-02-15|2023-02-15|1|11.3|11.3|0.0|0.0|0|0|11.5|11.3|Downward|842|1,808,207
WHART|2023-02-16|2023-02-16|1|11.5|11.5|0.0|0.0|0|0|11.5|11.2|Upward|843|995,609
WHART|2023-02-17|2023-02-20|2|11.4|11.3|-0.1|-0.88|-1|-1|11.5|11.2|Downward|845|1,068,706
WHART|2023-02-21|2023-02-23|3|11.4|11.4|0.0|0.0|0|0|11.4|11.2|Upward|848|2,653,848
WHART|2023-02-24|2023-02-27|2|11.3|11.2|-0.1|-0.88|-1|-1|11.4|11.2|Downward|850|932,077
WHART|2023-02-28|2023-03-01|2|11.4|11.5|0.1|0.88|1|0|11.5|11.2|Upward|852|1,104,274
WHART|2023-03-02|2023-03-03|2|11.3|11.3|0.0|0.0|0|0|11.5|11.2|Downward|854|946,092
WICE|2023-02-02|2023-02-02|1|11.7|11.7|0.0|0.0|0|0|12.1|11.7|Downward|855|5,299,628
WICE|2023-02-03|2023-02-06|2|11.9|12.0|0.1|0.84|1|0|12.0|11.7|Upward|857|6,502,703
WICE|2023-02-07|2023-02-16|8|11.7|10.1|-1.6|-13.68|-16|-2|12.1|10.0|Downward|865|40,813,818
WICE|2023-02-17|2023-02-22|4|10.2|10.7|0.5|4.9|5|1|11.0|10.0|Upward|869|15,234,027
WICE|2023-02-23|2023-02-24|2|10.6|10.3|-0.3|-2.83|-3|-2|10.9|10.3|Downward|871|8,137,604
WICE|2023-02-27|2023-03-01|3|10.4|10.8|0.4|3.85|4|1|10.8|10.2|Upward|874|5,676,066
WICE|2023-03-02|2023-03-02|1|10.6|10.6|0.0|0.0|0|0|11.0|10.5|Downward|875|6,443,159
WICE|2023-03-03|2023-03-03|1|10.7|10.7|0.0|0.0|0|0|11.0|10.5|Upward|875|3,961,789
ruby/../Data/summary.csv

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'ASW'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'CPNREIT'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')

In [21]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [22]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [23]:
#df.groupby('trend').days.max()

In [24]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median  mean
trend
Downward   12    196    2.00  2.74
Upward      8    183    1.00  1.83

In [25]:
upward_max = df.groupby('trend').days.max().loc['Upward']
downward_max = df.groupby('trend').days.max().loc['Downward']

In [26]:
df.query('days == @upward_max and trend == "Upward"')[cols].style.format(format_dict)

In [27]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
316,TFFIF,02-06,02-21,12,8.20,7.90,-3.66,-6,-1,8.25,7.85,31159347,Downward

### Individual stock analysis

In [28]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [29]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean    8.43  2236514.77  8.53  8.34
std     0.15  2397721.51  0.16  0.14
min     8.20   183512.00  8.25  8.10
25%     8.31   928555.25  8.41  8.25
50%     8.43  1230799.00  8.52  8.30
75%     8.50  2182427.00  8.69  8.45
max     8.70 10067977.00  8.75  8.55

In [30]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [31]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean   17.90  3260049.73 18.18 17.76
std     1.21  2717217.82  0.96  1.24
min    14.60   318901.00 15.30 14.20
25%    17.88  1142954.75 18.20 17.70
50%    18.30  2871383.50 18.45 18.20
75%    18.48  3956269.25 18.50 18.30
max    19.40 10189854.00 19.50 19.30

In [32]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [33]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [34]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-03-03'
ORDER BY name, date

In [35]:
df = pd.read_sql(sql, const)
df

       name        date  price       qty   maxp   minp
0       ACE  2023-03-03   2.42  13779344   2.46   2.42
1    ADVANC  2023-03-03 203.00   4208290 203.00 200.00
2    AEONTS  2023-03-03 199.00    302386 199.50 197.00
3        AH  2023-03-03  31.50   3532628  32.50  31.25
4       AIE  2023-03-03   2.52    671275   2.52   2.50
..      ...         ...    ...       ...    ...    ...
186   WHAIR  2023-03-03   7.60    747319   7.70   7.55
187   WHART  2023-03-03  11.30    603831  11.30  11.20
188   WHAUP  2023-03-03   3.80   3066357   3.86   3.80
189    WICE  2023-03-03  10.70   3961789  11.00  10.50
190    WORK  2023-03-03  17.70     22571  17.80  17.70

[191 rows x 6 columns]