In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 7), datetime.date(2023, 2, 6))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-02-07
Today in mm-dd format: 02-07
yesterday: 2023-02-06 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-09 00:00:00   Monday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

### End of Selection between Buy or Orders

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-09 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

        name        date  price       qty   maxp  minp
226    JASIF  2023-01-17   8.25   2057675   8.25   8.2
110  CPNREIT  2023-01-09  19.50   1864069  19.60  19.4
532    SYNEX  2023-01-13  17.10   2348985  17.50  17.1
287      KCE  2023-01-10  50.00  30442745  50.50  49.0
229    JASIF  2023-01-20   8.25   5704673   8.25   8.2

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2023-01-09|2023-01-10|2|3.02|3.02|0.0|0.0|0|0|3.04|3.0||3|7,716,980
ASP|2023-01-11|2023-01-18|6|3.06|3.1|0.04|1.31|2|0|3.1|3.02|Upward|9|12,156,697
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|11|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|12|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|13|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|14|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|15|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|17|1,798,533
ASP|2023-01-31|2023-01-31|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06|Downward|18|3,048,744
ASP|2023-02-01|2023-02-02|2|3.16|3.16|0.0|0.0|0|0|3.24|3.08|Upward|20|28,871,862
ASP|2023-02-03|2023-02-03|1|3.1|3.1|0.0|0.0|0|0|3.18|3.1|Downward|21|3,867,567
ASP|2023-02-06|2023-02-06|1|3.14|3.14|0.0|0.0|0|0|3.14|3.1|Upward|22|2,481,635
ASP|2023-02-07|2023-02-07|1|3.12|3.12|0.0|0.0|0|0|3.16|3.12|Downward|23|1,291,978
BANPU|2023-01-09|2023-01-12|4|12.5|12.3|-0.2|-1.6|-2|-1|12.6|12.1|Downward|27|485,029,487
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|28|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|32|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|33|193,937,283
BANPU|2023-01-23|2023-02-07|12|12.5|11.2|-1.3|-10.4|-13|-2|12.6|11.1|Downward|45|1,429,582,270
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|46|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|47|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|49|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|51|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|58|46,355,474
BCH|2023-01-26|2023-01-31|4|20.7|21.8|1.1|5.31|11|2|22.0|20.5|Upward|62|55,795,055
BCH|2023-02-01|2023-02-02|2|21.6|21.4|-0.2|-0.93|-2|-1|21.8|21.3|Downward|64|21,808,662
BCH|2023-02-03|2023-02-03|1|21.5|21.5|0.0|0.0|0|0|21.7|21.4|Upward|65|12,718,266
BCH|2023-02-06|2023-02-07|2|21.3|21.1|-0.2|-0.94|-2|-1|21.5|20.9|Downward|67|16,931,889
CK|2023-01-09|2023-01-10|2|23.5|23.5|0.0|0.0|0|0|23.8|23.2|Downward|69|12,839,660
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|71|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|73|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|74|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|75|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|76|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|79|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|80|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|82|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|0|0|23.0|22.6|Upward|83|2,492,389
CK|2023-01-31|2023-02-01|2|22.6|22.6|0.0|0.0|0|0|23.1|22.4|Downward|85|14,195,847
CK|2023-02-02|2023-02-02|1|22.8|22.8|0.0|0.0|0|0|23.2|22.7|Upward|86|6,126,236
CK|2023-02-03|2023-02-07|3|22.7|22.4|-0.3|-1.32|-3|-1|22.9|22.4|Downward|89|8,608,309
CKP|2023-01-09|2023-01-09|1|4.64|4.64|0.0|0.0|0|0|4.64|4.58|Downward|90|5,748,765
CKP|2023-01-10|2023-01-12|3|4.7|4.74|0.04|0.85|2|0|4.76|4.64|Upward|93|41,494,910
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|97|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|99|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|103|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|104|6,963,352
CKP|2023-01-30|2023-01-31|2|4.52|4.52|0.0|0.0|0|0|4.58|4.5|Downward|106|15,946,162
CKP|2023-02-01|2023-02-01|1|4.56|4.56|0.0|0.0|0|0|4.58|4.52|Upward|107|20,374,772
CKP|2023-02-02|2023-02-02|1|4.54|4.54|0.0|0.0|0|0|4.6|4.5|Downward|108|14,870,177
CKP|2023-02-03|2023-02-07|3|4.56|4.68|0.12|2.63|6|2|4.72|4.54|Upward|111|38,604,423
CPNREIT|2023-01-09|2023-01-09|1|19.5|19.5|0.0|0.0|0|0|19.6|19.4|Upward|112|1,864,069
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|113|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|120|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|123|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|125|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|128|3,517,218
CPNREIT|2023-02-01|2023-02-02|2|19.4|19.4|0.0|0.0|0|0|19.5|19.2|Upward|130|1,159,029
CPNREIT|2023-02-03|2023-02-07|3|19.1|18.5|-0.6|-3.14|-6|-2|19.4|18.3|Downward|133|9,472,016
DCC|2023-01-09|2023-01-11|3|2.84|2.8|-0.04|-1.41|-2|-1|2.88|2.78|Downward|136|51,997,401
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|137|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|140|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|141|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|142|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|144|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|145|3,924,289
DCC|2023-01-25|2023-01-25|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|146|6,076,325
DCC|2023-01-26|2023-01-27|2|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Downward|148|21,773,267
DCC|2023-01-30|2023-02-01|3|2.84|2.88|0.04|1.41|2|0|2.9|2.82|Upward|151|42,473,718
DCC|2023-02-02|2023-02-07|4|2.86|2.84|-0.02|-0.7|-1|-1|2.9|2.82|Downward|155|18,520,685
DIF|2023-01-09|2023-01-11|3|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Downward|158|20,954,488
DIF|2023-01-12|2023-01-19|6|13.4|13.7|0.3|2.24|3|0|13.7|13.2|Upward|164|55,494,798
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|167|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|168|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|169|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|170|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|172|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|173|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|177|31,473,792
GVREIT|2023-01-09|2023-01-17|7|9.1|8.9|-0.2|-2.2|-4|-1|9.15|8.9|Downward|184|1,712,191
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|189|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|190|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|191|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|192|281,301
GVREIT|2023-01-30|2023-02-01|3|9.55|9.75|0.2|2.09|4|1|9.75|9.45|Upward|195|669,621
GVREIT|2023-02-02|2023-02-02|1|9.7|9.7|0.0|0.0|0|0|9.75|9.65|Downward|196|224,521
GVREIT|2023-02-03|2023-02-07|3|9.75|9.8|0.05|0.51|1|0|9.9|9.6|Upward|199|1,566,531
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|207|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|208|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|209|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|213|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|215|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|216|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|0|0|41.25|40.5|Upward|217|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|-1|-1|41.25|40.25|Downward|219|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|0|0|41.25|39.75|Upward|220|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|221|11,842,657
JASIF|2023-01-09|2023-01-13|5|8.25|8.2|-0.05|-0.61|-1|-1|8.3|8.15|Downward|226|29,645,456
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|228|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|229|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|233|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|237|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|1|0|8.25|8.15|Upward|239|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|240|3,117,519
JASIF|2023-02-03|2023-02-07|3|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|243|10,368,854
JMART|2023-01-09|2023-01-13|5|41.5|42.5|1.0|2.41|4|0|43.5|40.25|Upward|248|41,806,864
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|257|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|258|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|259|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|1|0|38.25|36.5|Upward|262|17,299,441
JMART|2023-02-03|2023-02-07|3|37.25|36.75|-0.5|-1.34|-2|-1|37.75|36.5|Downward|265|16,118,136
JMT|2023-01-09|2023-01-09|1|68.25|68.25|0.0|0.0|0|0|68.75|66.75|Downward|266|6,880,228
JMT|2023-01-10|2023-01-13|4|68.75|69.5|0.75|1.09|3|0|71.0|68.75|Upward|270|29,169,171
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|279|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|280|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|282|45,047,024
JMT|2023-02-01|2023-02-01|1|54.25|54.25|0.0|0.0|0|0|54.5|53.0|Upward|283|11,053,059
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|284|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|285|12,417,267
JMT|2023-02-06|2023-02-07|2|53.75|53.0|-0.75|-1.4|-3|-2|54.75|52.25|Downward|287|19,909,595
KCE|2023-01-09|2023-01-09|1|48.75|48.75|0.0|0.0|0|0|49.25|47.75|Downward|288|32,427,533
KCE|2023-01-10|2023-01-10|1|50.0|50.0|0.0|0.0|0|0|50.5|49.0|Upward|289|30,442,745
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|290|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|291|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|297|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|298|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|299|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|300|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|301|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|302|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|303|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|13|3|58.5|50.5|Upward|307|214,389,940
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|0|0|57.75|56.25|Downward|308|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|0|0|57.75|56.0|Upward|309|17,516,788
MCS|2023-01-09|2023-01-11|3|9.25|9.55|0.3|3.24|6|2|9.65|9.15|Upward|312|4,574,579
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|313|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|318|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|319|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|320|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|321|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|322|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|323|1,271,966
MCS|2023-01-27|2023-01-31|3|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|326|2,139,488
MCS|2023-02-01|2023-02-01|1|10.0|10.0|0.0|0.0|0|0|10.1|9.9|Downward|327|869,625
MCS|2023-02-02|2023-02-03|2|9.95|9.95|0.0|0.0|0|0|10.1|9.9|Upward|329|947,644
MCS|2023-02-06|2023-02-06|1|9.9|9.9|0.0|0.0|0|0|10.0|9.9|Downward|330|652,568
MCS|2023-02-07|2023-02-07|1|9.95|9.95|0.0|0.0|0|0|10.0|9.9|Upward|331|406,865
NER|2023-01-09|2023-01-10|2|6.25|6.4|0.15|2.4|3|1|6.4|6.2|Upward|333|15,057,397
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|334|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|336|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|341|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|342|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|343|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|345|42,913,468
NER|2023-01-27|2023-02-01|4|6.6|6.35|-0.25|-3.79|-5|-2|6.7|6.3|Downward|349|38,923,402
NER|2023-02-02|2023-02-06|3|6.4|6.5|0.1|1.56|2|0|6.5|6.3|Upward|352|24,426,533
NER|2023-02-07|2023-02-07|1|6.45|6.45|0.0|0.0|0|0|6.5|6.4|Downward|353|5,084,039
ORI|2023-01-09|2023-01-11|3|11.8|11.7|-0.1|-0.85|-1|-1|12.1|11.6|Downward|356|26,428,749
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|359|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|361|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|364|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|367|16,286,040

ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|370|32,777,837
ORI|2023-02-01|2023-02-07|5|12.1|11.7|-0.4|-3.31|-4|-1|12.3|11.5|Downward|375|29,350,727
PTTGC|2023-01-09|2023-01-09|1|47.5|47.5|0.0|0.0|0|0|47.5|46.5|Downward|376|19,856,380
PTTGC|2023-01-10|2023-01-11|2|50.25|50.5|0.25|0.5|1|0|50.5|47.5|Upward|378|98,899,361
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|380|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|383|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|385|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|388|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|389|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|390|13,790,565
PTTGC|2023-01-30|2023-01-31|2|50.0|49.25|-0.75|-1.5|-3|-2|50.5|49.25|Downward|392|24,376,908
PTTGC|2023-02-01|2023-02-01|1|50.0|50.0|0.0|0.0|0|0|50.5|49.25|Upward|393|13,026,320
PTTGC|2023-02-02|2023-02-06|3|49.75|49.5|-0.25|-0.5|-1|-1|50.25|49.0|Downward|396|20,473,206
PTTGC|2023-02-07|2023-02-07|1|49.75|49.75|0.0|0.0|0|0|50.0|49.25|Upward|397|9,366,275
RCL|2023-01-09|2023-01-10|2|31.5|31.75|0.25|0.79|1|0|31.75|30.5|Upward|399|9,090,654
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|400|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|401|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|403|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|405|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|407|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|410|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|411|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|414|12,494,495
RCL|2023-02-01|2023-02-02|2|30.75|30.25|-0.5|-1.63|-2|-1|32.25|30.0|Downward|416|21,219,944
RCL|2023-02-03|2023-02-07|3|30.75|31.0|0.25|0.81|1|0|31.25|30.5|Upward|419|6,209,457
SCC|2023-01-09|2023-01-11|3|352.0|359.0|7.0|1.99|7|2|360.0|351.0|Upward|422|9,014,451
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|425|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|426|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|433|16,632,975
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|435|3,832,045
SCC|2023-01-31|2023-01-31|1|336.0|336.0|0.0|0.0|0|0|343.0|336.0|Downward|436|3,280,199
SCC|2023-02-01|2023-02-01|1|342.0|342.0|0.0|0.0|0|0|343.0|337.0|Upward|437|2,080,273
SCC|2023-02-02|2023-02-06|3|338.0|336.0|-2.0|-0.59|-2|-1|343.0|336.0|Downward|440|4,970,202
SCC|2023-02-07|2023-02-07|1|338.0|338.0|0.0|0.0|0|0|339.0|336.0|Upward|441|2,304,687
SCCC|2023-01-09|2023-01-19|9|158.0|160.0|2.0|1.27|4|0|160.0|157.0|Upward|450|993,579
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|455|597,538
SCCC|2023-01-27|2023-02-01|4|158.5|160.5|2.0|1.26|4|1|162.0|157.0|Upward|459|750,023
SCCC|2023-02-02|2023-02-07|4|159.5|157.5|-2.0|-1.25|-4|-1|161.0|157.0|Downward|463|946,348
SENA|2023-01-09|2023-01-13|5|3.94|3.92|-0.02|-0.51|-1|-1|3.94|3.9|Downward|468|8,345,924
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|470|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|472|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|474|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|475|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|476|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|478|2,050,656
SENA|2023-01-30|2023-02-06|6|3.94|4.04|0.1|2.54|5|0|4.06|3.9|Upward|484|13,631,211
SENA|2023-02-07|2023-02-07|1|4.0|4.0|0.0|0.0|0|0|4.04|4.0|Downward|485|499,009
SINGER|2023-01-09|2023-01-10|2|29.75|29.25|-0.5|-1.68|-2|-1|30.0|27.0|Downward|487|20,138,521
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|490|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|496|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|497|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|499|11,350,118
SINGER|2023-01-27|2023-02-02|5|27.5|28.5|1.0|3.64|4|0|29.25|27.0|Upward|504|26,173,063
SINGER|2023-02-03|2023-02-07|3|28.25|28.0|-0.25|-0.88|-1|-1|28.75|27.75|Downward|507|7,718,541
STA|2023-01-09|2023-01-11|3|21.7|21.2|-0.5|-2.3|-5|-2|21.8|20.9|Downward|510|18,481,972
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|512|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|513|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|514|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|515|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|516|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|518|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|522|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|524|17,280,360
STA|2023-02-01|2023-02-02|2|22.0|22.7|0.7|3.18|7|3|22.7|21.7|Upward|526|12,309,899
STA|2023-02-03|2023-02-03|1|22.3|22.3|0.0|0.0|0|0|22.7|22.2|Downward|527|4,951,737
STA|2023-02-06|2023-02-07|2|22.6|23.4|0.8|3.54|8|4|23.6|22.3|Upward|529|22,542,130
SYNEX|2023-01-09|2023-01-09|1|17.2|17.2|0.0|0.0|0|0|17.5|17.1|Upward|530|2,620,670
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|531|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|533|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|539|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|541|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|543|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|545|2,438,448
SYNEX|2023-01-31|2023-01-31|1|16.1|16.1|0.0|0.0|0|0|16.3|16.0|Downward|546|1,438,207
SYNEX|2023-02-01|2023-02-07|5|16.5|17.1|0.6|3.64|6|1|17.6|16.2|Upward|551|14,528,451
TFFIF|2023-01-09|2023-01-09|1|7.8|7.8|0.0|0.0|0|0|7.8|7.75|Upward|552|1,795,834
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|553|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|563|26,912,214
TFFIF|2023-01-25|2023-01-31|5|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.1|Downward|568|12,364,080
TFFIF|2023-02-01|2023-02-01|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|569|2,482,129
TFFIF|2023-02-02|2023-02-02|1|8.15|8.15|0.0|0.0|0|0|8.25|8.15|Downward|570|1,039,802
TFFIF|2023-02-03|2023-02-03|1|8.25|8.25|0.0|0.0|0|0|8.3|8.15|Upward|571|3,991,431
TFFIF|2023-02-06|2023-02-07|2|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|573|3,818,515
TMT|2023-01-09|2023-01-09|1|7.8|7.8|0.0|0.0|0|0|7.8|7.7|Downward|574|263,528
TMT|2023-01-10|2023-01-24|11|7.95|8.45|0.5|6.29|10|0|8.45|7.8|Upward|585|5,574,028
TMT|2023-01-25|2023-02-02|7|8.35|8.15|-0.2|-2.4|-4|-1|8.45|8.15|Downward|592|1,939,587
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|593|162,400
TMT|2023-02-06|2023-02-07|2|8.15|8.15|0.0|0.0|0|0|8.25|8.1|Downward|595|262,804
TTB|2023-01-09|2023-01-09|1|1.45|1.45|0.0|0.0|0|0|1.47|1.45|Downward|596|270,596,956
TTB|2023-01-10|2023-01-10|1|1.46|1.46|0.0|0.0|0|0|1.46|1.44|Upward|597|228,849,744
TTB|2023-01-11|2023-01-13|3|1.44|1.41|-0.03|-2.08|-3|-1|1.47|1.4|Downward|600|765,226,385
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|604|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|605|509,121,072
TTB|2023-01-23|2023-02-01|8|1.44|1.47|0.03|2.08|3|0|1.48|1.4|Upward|613|2,259,173,623
TTB|2023-02-02|2023-02-07|4|1.45|1.42|-0.03|-2.07|-3|-1|1.47|1.42|Downward|617|504,093,134
WHAIR|2023-01-09|2023-01-11|3|7.45|7.45|0.0|0.0|0|0|7.55|7.45|Downward|620|2,572,986
WHAIR|2023-01-12|2023-01-20|7|7.5|7.95|0.45|6.0|9|1|8.0|7.4|Upward|627|11,421,149
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|629|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|631|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|633|3,620,824
WHAIR|2023-01-31|2023-02-03|4|7.95|8.05|0.1|1.26|2|0|8.05|7.8|Upward|637|3,326,380
WHAIR|2023-02-06|2023-02-07|2|8.0|8.0|0.0|0.0|0|0|8.1|8.0|Downward|639|1,308,418
WHART|2023-01-09|2023-01-10|2|10.8|10.7|-0.1|-0.93|-1|-1|10.8|10.7|Downward|641|2,622,477
WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|642|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|643|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|648|20,924,999
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|653|15,575,456
WHART|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|655|1,943,970
WHART|2023-01-31|2023-01-31|1|11.6|11.6|0.0|0.0|0|0|11.8|11.5|Downward|656|1,239,474
WHART|2023-02-01|2023-02-03|3|11.7|11.8|0.1|0.85|1|0|11.8|11.5|Upward|659|3,044,650
WHART|2023-02-06|2023-02-07|2|11.6|11.6|0.0|0.0|0|0|11.9|11.6|Downward|660|1,507,517
ruby/../Data/summary.csv

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'SYNEX'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'BANPU'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')

In [21]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [22]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [23]:
#df.groupby('trend').days.max()

In [23]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward   12    140     2.0  2.428571
Upward     11    131     2.0  2.427481

In [24]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [25]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [26]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
17,BANPU,01-23,02-07,12,12.5,11.2,-10.4,-13,-2,12.6,11.1,1429582270,Downward

### Individual stock analysis

In [27]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [28]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty   maxp   minp
count  22.00       22.00  22.00  22.00
mean   16.72  2145977.14  17.00  16.60
std     0.40  1463048.93   0.44   0.42
min    15.90   761131.00  16.20  15.80
25%    16.50  1238510.25  16.70  16.25
50%    16.80  1541342.00  17.05  16.65
75%    17.10  2353804.50  17.38  16.98
max    17.20  6475566.00  17.60  17.10

In [29]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [30]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price           qty   maxp   minp
count  22.00  2.200000e+01  22.00  22.00
mean   12.15  1.117673e+08  12.25  11.98
std     0.46  8.368953e+07   0.40   0.43
min    11.20  3.089415e+07  11.50  11.10
25%    11.70  5.549074e+07  12.00  11.62
50%    12.35  9.824566e+07  12.40  12.20
75%    12.50  1.499730e+08  12.50  12.28
max    12.70  4.159035e+08  12.70  12.40

In [31]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [32]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [33]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-07'
ORDER BY name, date

In [34]:
df = pd.read_sql(sql, const)
df

        name        date   price        qty    maxp    minp
0        ACE  2023-02-07    2.56   23915176    2.58    2.54
1     ADVANC  2023-02-07  196.50    3223977  198.00  196.00
2         AH  2023-02-07   32.75    1688685   33.25   32.50
3        AIE  2023-02-07    3.00    5198687    3.00    2.88
4     AIMIRT  2023-02-07   12.30     122600   12.40   12.30
5        AIT  2023-02-07    6.60    1178324    6.70    6.60
6         AJ  2023-02-07   12.90     296417   13.10   12.80
7      AMATA  2023-02-07   20.20    6175226   20.30   19.90
8       ANAN  2023-02-07    1.42    9665714    1.44    1.41
9        AOT  2023-02-07   73.50   19882884   74.00   73.25
10        AP  2023-02-07   11.90   16341272   11.90   11.70
11     ASIAN  2023-02-07   13.90     740963   14.00   13.80
12       ASP  2023-02-07    3.12    1291978    3.16    3.12
13       ASW  2023-02-07    8.50     925083    8.65    8.50
14       AWC  2023-02-07    5.85   19377717    5.90    5.80
15        BA  2023-02-07   14.80    9344082   14.90   14.20
16       BAM  2023-02-07   15.80   20470183   16.10   15.80
17     BANPU  2023-02-07   11.20  161516144   11.50   11.20
18       BBL  2023-02-07  160.50    3101777  161.50  160.00
19       BCH  2023-02-07   21.10   11021734   21.40   20.90
20       BCP  2023-02-07   35.50    5801589   36.00   35.25
21      BCPG  2023-02-07   10.00    1404493   10.10   10.00
22      BDMS  2023-02-07   29.50   21781654   30.00   29.50
23    BEAUTY  2023-02-07    1.59  261554760    1.61    1.44
24       BEC  2023-02-07   10.30    1424600   10.50   10.30
25       BEM  2023-02-07    9.60   58793587    9.75    9.55
26       BGC  2023-02-07   10.30     321738   10.40   10.20
27     BGRIM  2023-02-07   40.75    9101197   40.75   39.75
28        BH  2023-02-07  214.00    2593682  215.00  211.00
29       BJC  2023-02-07   38.50    4774943   38.75   37.50
30       BKI  2023-02-07  291.00      21207  292.00  290.00
31       BLA  2023-02-07   30.00    5138658   30.50   29.75
32       BPP  2023-02-07   17.10     551835   17.10   16.80
33       BTS  2023-02-07    8.25   52782066    8.40    8.20
34    BTSGIF  2023-02-07    3.90    1226642    3.92    3.88
35       CBG  2023-02-07  102.00    1768116  103.50  101.50
36    CENTEL  2023-02-07   54.00    2843307   54.25   53.25
37       CHG  2023-02-07    3.88   34601807    3.92    3.84
38        CK  2023-02-07   22.40    5067398   22.80   22.40
39       CKP  2023-02-07    4.68   24336619    4.72    4.60
40      COM7  2023-02-07   31.75   15549744   32.25   31.25
41     COTTO  2023-02-07    2.06    1119925    2.08    2.04
42     CPALL  2023-02-07   66.75   17353807   67.00   66.50
43       CPF  2023-02-07   23.60   17028962   23.70   23.50
44       CPN  2023-02-07   73.00    6999054   73.25   72.50
45     CPNCG  2023-02-07   11.70     165600   11.70   11.60
46   CPNREIT  2023-02-07   18.50    2548603   18.70   18.30
47     CPTGF  2023-02-07    7.70     693623    7.80    7.55
48       CRC  2023-02-07   44.25   10167453   44.50   43.75
49       DCC  2023-02-07    2.84    5323644    2.86    2.82
50      DCON  2023-02-07    0.44   10327040    0.45    0.43
51     DELTA  2023-02-07  970.00    4132116  996.00  962.00
52       DIF  2023-02-07   13.60    7390171   13.70   13.60
53    DOHOME  2023-02-07   13.90    8237603   14.10   13.80
54       DRT  2023-02-07    8.25     137355    8.30    8.25
55      DTAC  2023-02-07   49.75    3615781   50.00   49.25
56        EA  2023-02-07   90.50   20532822   91.25   89.00
57     EASTW  2023-02-07    5.45    1512018    5.50    5.25
58      EGCO  2023-02-07  172.00     944769  173.00  171.00
59       EPG  2023-02-07    8.70    1349939    8.75    8.65
60      ESSO  2023-02-07    9.20   18877150    9.30    9.15
61     FORTH  2023-02-07   42.00    3803210   43.25   41.75
62    FTREIT  2023-02-07   11.70     196402   11.90   11.70
63      GFPT  2023-02-07   12.60   13964192   13.30   12.60
64    GLOBAL  2023-02-07   20.90   11074770   21.00   20.70
65      GPSC  2023-02-07   69.50    3829162   69.75   69.00
66      GULF  2023-02-07   54.00   11502957   54.25   53.75
67    GUNKUL  2023-02-07    4.94   52248036    5.05    4.94
68    GVREIT  2023-02-07    9.80     417700    9.85    9.80
69      HANA  2023-02-07   64.00   14815331   65.00   63.00
70       HFT  2023-02-07    6.70     366701    6.75    6.65
71     HMPRO  2023-02-07   14.70   11804881   14.80   14.60
72       HTC  2023-02-07   31.50     521964   32.25   31.50
73      ICHI  2023-02-07   12.40    3613668   12.70   12.40
74       III  2023-02-07   14.90    2849592   15.20   14.80
75       ILM  2023-02-07   19.60    1496504   19.80   19.10
76    IMPACT  2023-02-07   13.80     911982   13.80   13.60
77    INTUCH  2023-02-07   72.50    1572591   73.00   72.25
78      IRPC  2023-02-07    3.04   19508263    3.08    3.04
79       IVL  2023-02-07   40.50   11842657   41.00   40.25
80     JASIF  2023-02-07    8.25    3589348    8.25    8.20
81     JMART  2023-02-07   36.75    8468235   37.50   36.50
82       JMT  2023-02-07   53.00   14084684   54.25   52.25
83       JWD  2023-02-07   20.70    5033514   21.00   20.50
84     KBANK  2023-02-07  143.50    7124224  144.50  143.50
85       KCE  2023-02-07   57.00   17516788   57.75   56.00
86       KEX  2023-02-07   18.30    2231293   18.70   18.20
87       KGI  2023-02-07    5.15    3031912    5.20    5.10
88       KKP  2023-02-07   67.50    9986259   68.50   67.25
89       KSL  2023-02-07    3.66    4525592    3.70    3.64
90       KTB  2023-02-07   17.20   37917040   17.40   17.20
91       KTC  2023-02-07   58.00   13144003   59.00   57.50
92     LALIN  2023-02-07    9.50     157023    9.50    9.45
93     LANNA  2023-02-07   15.90    1423636   16.10   15.80
94        LH  2023-02-07    9.90   17389859    9.90    9.80
95       LPF  2023-02-07   14.20     366099   14.30   14.00
96       LPH  2023-02-07    5.70     191700    5.75    5.65
97       LPN  2023-02-07    4.64    2602752    4.64    4.58
98         M  2023-02-07   56.25    1610798   57.00   56.00
99      MACO  2023-02-07    0.62   59064093    0.62    0.59
100    MAJOR  2023-02-07   18.60    1235687   18.80   18.40
101       MC  2023-02-07   11.60     913070   11.80   11.60
102      MCS  2023-02-07    9.95     406865   10.00    9.90
103     MEGA  2023-02-07   51.50    2419856   52.00   50.50
104     MINT  2023-02-07   33.25   26462523   33.75   33.00
105      MTC  2023-02-07   37.00   35140049   39.00   36.75
106      NER  2023-02-07    6.45    5084039    6.50    6.40
107    NOBLE  2023-02-07    5.65    4374247    5.75    5.65
108     ONEE  2023-02-07    8.00    3169559    8.05    7.95
109       OR  2023-02-07   22.30   10067522   22.50   22.30
110      ORI  2023-02-07   11.70    8430180   11.80   11.50
111      OSP  2023-02-07   28.50    5471542   28.50   28.00
112    PLANB  2023-02-07    8.90   32374692    9.00    8.70
113     POPF  2023-02-07   11.70     435600   11.70   11.60
114      PRM  2023-02-07    8.00   10279852    8.00    7.85
115      PSH  2023-02-07   13.40     381025   13.40   13.20
116      PSL  2023-02-07   16.10    4381392   16.40   16.00
117      PTG  2023-02-07   13.30    5654769   13.60   13.30
118      PTT  2023-02-07   32.50   33729036   33.00   32.50
119    PTTEP  2023-02-07  165.00   15544249  165.50  164.00
120    PTTGC  2023-02-07   49.75    9366275   50.00   49.25
121       QH  2023-02-07    2.36   20156462    2.38    2.34
122    RATCH  2023-02-07   42.50    2231778   42.75   42.25
123      RBF  2023-02-07   12.90    3377331   13.00   12.80
124      RCL  2023-02-07   31.00    1864108   31.25   30.75
125      RJH  2023-02-07   31.25     367902   31.50   31.00
126    ROJNA  2023-02-07    6.20    2363196    6.40    6.15
127       RS  2023-02-07   17.30    4053447   17.60   17.20
128      S11  2023-02-07    5.30      44790    5.30    5.25
129    SABUY  2023-02-07   13.00   41170399   13.50   13.00
130    SAPPE  2023-02-07   52.50    2552941   52.50   50.00
131      SAT  2023-02-07   21.50     438245   21.70   21.30
132    SAWAD  2023-02-07   55.50   10005330   56.50   55.00
133       SC  2023-02-07    4.64    6508767    4.70    4.62
134      SCB  2023-02-07  103.50    7684973  104.00  102.50
135      SCC  2023-02-07  338.00    2304687  339.00  336.00
136     SCCC  2023-02-07  157.50     417258  158.50  157.00
137     SCGP  2023-02-07   53.50    5797609   53.75   53.00
138     SENA  2023-02-07    4.00     499009    4.04    4.00
139   SINGER  2023-02-07   28.00    1866964   28.50   28.00
140     SIRI  2023-02-07    1.92  249162219    1.92    1.87
141      SIS  2023-02-07   27.00     287202   27.00   26.50
142      SKN  2023-02-07    5.35     149400    5.35    5.25
143     SMPC  2023-02-07   13.30     479502   13.30   13.10
144      SNC  2023-02-07   14.60     373800   14.60   14.50
145    SPALI  2023-02-07   24.50   17117094   24.70   24.10
146     SPCG  2023-02-07   14.40     983344   14.60   14.20
147     SPRC  2023-02-07   11.40   30955605   11.50   11.20
148   SPRIME  2023-02-07    7.30      47215    7.35    7.30
149      SSP  2023-02-07    9.95    1153621   10.00    9.90
150      STA  2023-02-07   23.40   17792391   23.60   22.60
151   STANLY  2023-02-07  190.00      41029  190.50  188.00
152    STARK  2023-02-07    2.94   57344552    3.02    2.92
153     STGT  2023-02-07   11.40   26522526   11.60   11.00
154    SUPER  2023-02-07    0.63   42611749    0.64    0.62
155    SYNEX  2023-02-07   17.10    6475566   17.60   17.00
156    TASCO  2023-02-07   18.30    6759324   18.50   18.20
157     TCAP  2023-02-07   43.25    1622069   43.50   42.75
158    TFFIF  2023-02-07    8.20    1051610    8.25    8.15
159    THANI  2023-02-07    4.06   18301546    4.12    4.06
160      THG  2023-02-07   68.00   11758723   71.75   67.00
161   TIDLOR  2023-02-07   29.50   24357489   30.00   29.25
162    TIPCO  2023-02-07    9.15     303310    9.25    9.10
163     TIPH  2023-02-07   51.75    3291675   52.50   51.25
164    TISCO  2023-02-07  102.50    3757061  103.00  102.00
165       TK  2023-02-07    8.45    1346001    8.60    8.40
166      TKN  2023-02-07   11.60    6892972   11.70   11.30
167      TKS  2023-02-07   13.40    1934281   13.60   13.30
168      TMT  2023-02-07    8.15     121777    8.25    8.10
169      TOA  2023-02-07   34.25     308244   34.75   34.25
170      TOP  2023-02-07   57.00    9125904   58.00   56.75
171    TPIPL  2023-02-07    1.82    8860867    1.84    1.82
172    TPIPP  2023-02-07    3.50    9303552    3.52    3.48
173      TQM  2023-02-07   42.75    1743121   44.00   42.50
174     TRUE  2023-02-07    4.84   24359071    4.88    4.82
175      TSE  2023-02-07    2.56    1955738    2.56    2.54
176     TSTH  2023-02-07    1.17    2418600    1.18    1.15
177      TTA  2023-02-07    8.10    3759691    8.15    8.00
178      TTB  2023-02-07    1.42  194236716    1.45    1.42
179    TTLPF  2023-02-07   22.70       9105   22.70   22.70
180      TTW  2023-02-07    9.70    6681864    9.75    9.45
181       TU  2023-02-07   16.20   16289493   16.40   16.10
182      TVI  2023-02-07   12.70     374109   13.20   12.70
183      TVO  2023-02-07   28.75     298190   29.25   28.75
184      UTP  2023-02-07   15.60     230347   15.60   15.50
185      VGI  2023-02-07    4.98   16941119    5.00    4.92
186    VIBHA  2023-02-07    2.78    9523459    2.80    2.72
187      VNG  2023-02-07    5.55     746211    5.60    5.45
188      WHA  2023-02-07    3.90   73616885    3.94    3.86
189    WHAIR  2023-02-07    8.00     846450    8.05    8.00
190    WHART  2023-02-07   11.60     484312   11.70   11.60
191    WHAUP  2023-02-07    4.12    1427266    4.14    4.08
192     WICE  2023-02-07   11.70    6565095   12.10   11.60
193     WORK  2023-02-07   18.60     584418   18.80   18.50