In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 3), datetime.date(2023, 2, 2))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-02-03
Today in mm-dd format: 02-03
yesterday: 2023-02-02 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-05 00:00:00   Thursday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

### End of Selection between Buy or Orders

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-05 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

        name        date   price      qty    maxp    minp
440     SCCC  2023-01-05  157.50   259922  157.50  155.50
118  CPNREIT  2023-01-17   19.60   790638   19.80   19.60
152      DCC  2023-02-02    2.86  4917179    2.90    2.86
114  CPNREIT  2023-01-11   19.30  1069463   19.40   19.20
17       ASP  2023-01-30    3.10   778835    3.12    3.10

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2023-01-05|2023-01-05|1|2.96|2.96|0.0|0.0|0|0|2.98|2.94||2|2,283,237
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|11|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|13|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|14|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|15|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|16|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|17|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|19|1,798,533
ASP|2023-01-31|2023-01-31|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06|Downward|20|3,048,744
ASP|2023-02-01|2023-02-02|2|3.16|3.16|0.0|0.0|0|0|3.24|3.08|Upward|22|28,871,862
ASP|2023-02-03|2023-02-03|1|3.1|3.1|0.0|0.0|0|0|3.18|3.1|Downward|23|3,867,567
BANPU|2023-01-05|2023-01-06|2|12.8|12.3|-0.5|-3.91|-5|-3|12.9|12.3|Downward|25|444,860,834
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|27|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|29|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|30|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|34|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|35|193,937,283
BANPU|2023-01-23|2023-02-03|10|12.5|11.5|-1.0|-8.0|-10|-1|12.6|11.3|Downward|45|1,153,288,175
BCH|2023-01-05|2023-01-05|1|21.3|21.3|0.0|0.0|0|0|21.3|20.8|Downward|46|15,859,341
BCH|2023-01-06|2023-01-06|1|21.9|21.9|0.0|0.0|0|0|22.0|21.3|Upward|47|22,547,400
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|48|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|49|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|51|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|53|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|60|46,355,474
BCH|2023-01-26|2023-01-31|4|20.7|21.8|1.1|5.31|11|2|22.0|20.5|Upward|64|55,795,055
BCH|2023-02-01|2023-02-02|2|21.6|21.4|-0.2|-0.93|-2|-1|21.8|21.3|Downward|66|21,808,662
BCH|2023-02-03|2023-02-03|1|21.5|21.5|0.0|0.0|0|0|21.7|21.4|Upward|67|12,718,266
CK|2023-01-05|2023-01-05|1|23.7|23.7|0.0|0.0|0|0|24.1|23.5|Upward|68|8,328,300
CK|2023-01-06|2023-01-10|3|23.6|23.5|-0.1|-0.42|-1|-1|23.9|23.2|Downward|71|18,886,271
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|73|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|75|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|76|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|77|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|78|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|81|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|82|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|84|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|0|0|23.0|22.6|Upward|85|2,492,389
CK|2023-01-31|2023-02-01|2|22.6|22.6|0.0|0.0|0|0|23.1|22.4|Downward|87|14,195,847
CK|2023-02-02|2023-02-02|1|22.8|22.8|0.0|0.0|0|0|23.2|22.7|Upward|88|6,126,236
CK|2023-02-03|2023-02-03|1|22.7|22.7|0.0|0.0|0|0|22.9|22.6|Downward|89|2,679,847
CKP|2023-01-05|2023-01-06|2|4.6|4.6|0.0|0.0|0|0|4.64|4.58|Downward|91|10,674,218
CKP|2023-01-09|2023-01-12|4|4.64|4.74|0.1|2.16|5|1|4.76|4.58|Upward|95|47,243,675
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|99|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|101|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|105|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|106|6,963,352
CKP|2023-01-30|2023-01-31|2|4.52|4.52|0.0|0.0|0|0|4.58|4.5|Downward|108|15,946,162
CKP|2023-02-01|2023-02-01|1|4.56|4.56|0.0|0.0|0|0|4.58|4.52|Upward|109|20,374,772
CKP|2023-02-02|2023-02-02|1|4.54|4.54|0.0|0.0|0|0|4.6|4.5|Downward|110|14,870,177
CKP|2023-02-03|2023-02-03|1|4.56|4.56|0.0|0.0|0|0|4.58|4.54|Upward|111|2,760,309
CPNREIT|2023-01-05|2023-01-09|3|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Upward|114|3,656,825
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|115|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|122|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|125|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|127|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|130|3,517,218
CPNREIT|2023-02-01|2023-02-02|2|19.4|19.4|0.0|0.0|0|0|19.5|19.2|Upward|132|1,159,029
CPNREIT|2023-02-03|2023-02-03|1|19.1|19.1|0.0|0.0|0|0|19.4|19.1|Downward|133|1,088,208
DCC|2023-01-05|2023-01-05|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|134|6,618,739
DCC|2023-01-06|2023-01-10|3|2.84|2.84|0.0|0.0|0|0|2.88|2.82|Upward|137|37,756,732
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|138|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|139|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|142|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|143|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|144|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|146|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|147|3,924,289
DCC|2023-01-25|2023-01-25|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|148|6,076,325
DCC|2023-01-26|2023-01-27|2|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Downward|150|21,773,267
DCC|2023-01-30|2023-02-01|3|2.84|2.88|0.04|1.41|2|0|2.9|2.82|Upward|153|42,473,718
DCC|2023-02-02|2023-02-03|2|2.86|2.86|0.0|0.0|0|0|2.9|2.84|Downward|155|9,442,155
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|157|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|166|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|169|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|170|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|171|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|172|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|174|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|175|8,966,593
DIF|2023-02-02|2023-02-03|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|177|18,803,174
GVREIT|2023-01-05|2023-01-06|2|9.05|9.0|-0.05|-0.55|-1|-1|9.1|9.0|Downward|179|415,108
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|180|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|186|1,449,890
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|191|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|192|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|193|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|194|281,301
GVREIT|2023-01-30|2023-02-01|3|9.55|9.75|0.2|2.09|4|1|9.75|9.45|Upward|197|669,621
GVREIT|2023-02-02|2023-02-02|1|9.7|9.7|0.0|0.0|0|0|9.75|9.65|Downward|198|224,521
GVREIT|2023-02-03|2023-02-03|1|9.75|9.75|0.0|0.0|0|0|9.8|9.6|Upward|199|438,861
IVL|2023-01-05|2023-01-05|1|39.75|39.75|0.0|0.0|0|0|40.0|39.5|Upward|200|9,696,817
IVL|2023-01-06|2023-01-06|1|37.75|37.75|0.0|0.0|0|0|39.75|37.0|Downward|201|76,125,229
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|209|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|210|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|211|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|215|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|217|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|218|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|0|0|41.25|40.5|Upward|219|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|-1|-1|41.25|40.25|Downward|221|15,971,520
JASIF|2023-01-05|2023-01-05|1|8.1|8.1|0.0|0.0|0|0|8.15|8.1|Downward|222|2,989,943
JASIF|2023-01-06|2023-01-12|5|8.15|8.25|0.1|1.23|2|0|8.3|8.1|Upward|227|28,092,266
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|228|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|230|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|231|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|235|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|239|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|1|0|8.25|8.15|Upward|241|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|242|3,117,519
JASIF|2023-02-03|2023-02-03|1|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|243|2,898,474
JMART|2023-01-05|2023-01-13|7|40.0|42.5|2.5|6.25|10|1|43.5|40.0|Upward|250|49,256,065
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|259|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|260|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|261|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|1|0|38.25|36.5|Upward|264|17,299,441
JMART|2023-02-03|2023-02-03|1|37.25|37.25|0.0|0.0|0|0|37.75|37.0|Downward|265|4,467,158
JMT|2023-01-05|2023-01-06|2|66.25|66.0|-0.25|-0.38|-1|-1|66.75|65.25|Downward|267|8,106,970
JMT|2023-01-09|2023-01-13|5|68.25|69.5|1.25|1.83|5|1|71.0|66.75|Upward|272|36,049,399
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|281|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|282|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|284|45,047,024
JMT|2023-02-01|2023-02-01|1|54.25|54.25|0.0|0.0|0|0|54.5|53.0|Upward|285|11,053,059
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|286|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|287|12,417,267
KCE|2023-01-05|2023-01-10|4|45.0|50.0|5.0|11.11|20|5|50.5|44.5|Upward|291|139,713,670
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|292|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|293|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|299|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|300|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|301|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|302|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|303|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|304|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|305|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|13|3|58.5|50.5|Upward|309|214,389,940
MCS|2023-01-05|2023-01-06|2|9.3|9.3|0.0|0.0|0|0|9.35|9.15|Upward|311|2,354,146
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|312|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|314|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|315|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|320|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|321|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|322|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|323|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|324|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|325|1,271,966
MCS|2023-01-27|2023-01-31|3|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|328|2,139,488
MCS|2023-02-01|2023-02-01|1|10.0|10.0|0.0|0.0|0|0|10.1|9.9|Downward|329|869,625
MCS|2023-02-02|2023-02-03|2|9.95|9.95|0.0|0.0|0|0|10.1|9.9|Upward|331|947,644
NER|2023-01-05|2023-01-06|2|6.25|6.3|0.05|0.8|1|0|6.4|6.2|Upward|333|15,538,644
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|334|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|335|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|336|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|338|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|343|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|344|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|345|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|347|42,913,468
NER|2023-01-27|2023-02-01|4|6.6|6.35|-0.25|-3.79|-5|-2|6.7|6.3|Downward|351|38,923,402
NER|2023-02-02|2023-02-03|2|6.4|6.4|0.0|0.0|0|0|6.4|6.3|Upward|353|16,050,686
ORI|2023-01-05|2023-01-09|3|11.6|11.8|0.2|1.72|2|0|12.0|11.4|Upward|356|47,911,861
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|358|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|361|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|363|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|366|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|369|16,286,040
ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|372|32,777,837
ORI|2023-02-01|2023-02-03|3|12.1|12.0|-0.1|-0.83|-1|-1|12.3|11.9|Downward|375|15,266,865
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|377|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|380|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|382|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|385|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|387|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|390|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|391|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|392|13,790,565
PTTGC|2023-01-30|2023-01-31|2|50.0|49.25|-0.75|-1.5|-3|-2|50.5|49.25|Downward|394|24,376,908

PTTGC|2023-02-01|2023-02-01|1|50.0|50.0|0.0|0.0|0|0|50.5|49.25|Upward|395|13,026,320
PTTGC|2023-02-02|2023-02-03|2|49.75|49.5|-0.25|-0.5|-1|-1|50.25|49.25|Downward|397|14,074,141
RCL|2023-01-05|2023-01-05|1|29.5|29.5|0.0|0.0|0|0|29.75|29.0|Downward|398|3,639,489
RCL|2023-01-06|2023-01-10|3|30.5|31.75|1.25|4.1|5|1|31.75|29.75|Upward|401|13,311,119
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|402|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|403|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|405|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|407|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|409|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|412|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|413|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|416|12,494,495
RCL|2023-02-01|2023-02-02|2|30.75|30.25|-0.5|-1.63|-2|-1|32.25|30.0|Downward|418|21,219,944
RCL|2023-02-03|2023-02-03|1|30.75|30.75|0.0|0.0|0|0|31.0|30.5|Upward|419|2,057,453
SCC|2023-01-05|2023-01-11|5|349.0|359.0|10.0|2.87|10|2|360.0|344.0|Upward|424|13,236,301
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|427|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|428|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|435|16,632,975
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|437|3,832,045
SCC|2023-01-31|2023-01-31|1|336.0|336.0|0.0|0.0|0|0|343.0|336.0|Downward|438|3,280,199
SCC|2023-02-01|2023-02-01|1|342.0|342.0|0.0|0.0|0|0|343.0|337.0|Upward|439|2,080,273
SCC|2023-02-02|2023-02-03|2|338.0|338.0|0.0|0.0|0|0|343.0|337.0|Downward|441|4,027,206
SCCC|2023-01-05|2023-01-05|1|157.5|157.5|0.0|0.0|0|0|157.5|155.5|Downward|442|259,922
SCCC|2023-01-06|2023-01-06|1|158.5|158.5|0.0|0.0|0|0|159.0|157.5|Upward|443|252,131
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|446|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|452|713,373
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|457|597,538
SCCC|2023-01-27|2023-02-01|4|158.5|160.5|2.0|1.26|4|1|162.0|157.0|Upward|461|750,023
SCCC|2023-02-02|2023-02-03|2|159.5|158.5|-1.0|-0.63|-2|-1|161.0|158.0|Downward|463|296,466
SENA|2023-01-05|2023-01-05|1|3.9|3.9|0.0|0.0|0|0|3.94|3.9|Downward|464|983,669
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|467|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|470|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|472|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|474|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|476|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|477|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|478|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|480|2,050,656
SENA|2023-01-30|2023-02-03|5|3.94|4.04|0.1|2.54|5|1|4.06|3.9|Upward|485|13,159,121
SINGER|2023-01-05|2023-01-09|3|27.0|29.75|2.75|10.19|11|3|30.0|26.75|Upward|488|27,556,821
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|489|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|492|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|498|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|499|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|501|11,350,118
SINGER|2023-01-27|2023-02-02|5|27.5|28.5|1.0|3.64|4|0|29.25|27.0|Upward|506|26,173,063
SINGER|2023-02-03|2023-02-03|1|28.25|28.25|0.0|0.0|0|0|28.75|28.0|Downward|507|3,563,122
STA|2023-01-05|2023-01-06|2|21.1|21.1|0.0|0.0|0|0|21.3|20.6|Downward|509|11,861,353
STA|2023-01-09|2023-01-09|1|21.7|21.7|0.0|0.0|0|0|21.8|21.1|Upward|510|7,366,097
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|512|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|514|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|515|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|516|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|517|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|518|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|520|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|524|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|526|17,280,360
STA|2023-02-01|2023-02-02|2|22.0|22.7|0.7|3.18|7|3|22.7|21.7|Upward|528|12,309,899
STA|2023-02-03|2023-02-03|1|22.3|22.3|0.0|0.0|0|0|22.7|22.2|Downward|529|4,951,737
SYNEX|2023-01-05|2023-01-05|1|16.5|16.5|0.0|0.0|0|0|16.9|16.4|Downward|530|2,113,136
SYNEX|2023-01-06|2023-01-09|2|17.0|17.2|0.2|1.18|2|1|17.5|16.4|Upward|532|5,424,286
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|533|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|535|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|541|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|543|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|545|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|547|2,438,448
SYNEX|2023-01-31|2023-01-31|1|16.1|16.1|0.0|0.0|0|0|16.3|16.0|Downward|548|1,438,207
SYNEX|2023-02-01|2023-02-03|3|16.5|16.6|0.1|0.61|1|0|16.7|16.2|Upward|551|3,911,604
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|554|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|555|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|565|26,912,214
TFFIF|2023-01-25|2023-01-31|5|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.1|Downward|570|12,364,080
TFFIF|2023-02-01|2023-02-01|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|571|2,482,129
TFFIF|2023-02-02|2023-02-02|1|8.15|8.15|0.0|0.0|0|0|8.25|8.15|Downward|572|1,039,802
TFFIF|2023-02-03|2023-02-03|1|8.25|8.25|0.0|0.0|0|0|8.3|8.15|Upward|573|3,991,431
TMT|2023-01-05|2023-01-24|14|7.65|8.45|0.8|10.46|16|1|8.45|7.55|Upward|587|6,336,167
TMT|2023-01-25|2023-02-02|7|8.35|8.15|-0.2|-2.4|-4|-1|8.45|8.15|Downward|594|1,939,587
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|595|162,400
TTB|2023-01-05|2023-01-10|4|1.42|1.46|0.04|2.82|4|1|1.47|1.41|Upward|599|1,568,122,782
TTB|2023-01-11|2023-01-13|3|1.44|1.41|-0.03|-2.08|-3|-1|1.47|1.4|Downward|602|765,226,385
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|606|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|607|509,121,072
TTB|2023-01-23|2023-02-01|8|1.44|1.47|0.03|2.08|3|0|1.48|1.4|Upward|615|2,259,173,623
TTB|2023-02-02|2023-02-03|2|1.45|1.45|0.0|0.0|0|0|1.47|1.44|Downward|617|269,959,098
WHAIR|2023-01-05|2023-01-11|5|7.55|7.45|-0.1|-1.32|-2|-1|7.6|7.45|Downward|622|3,757,659
WHAIR|2023-01-12|2023-01-20|7|7.5|7.95|0.45|6.0|9|1|8.0|7.4|Upward|629|11,421,149
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|631|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|633|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|635|3,620,824
WHAIR|2023-01-31|2023-02-03|4|7.95|8.05|0.1|1.26|2|0|8.05|7.8|Upward|639|3,326,380
WHART|2023-01-05|2023-01-09|3|10.7|10.8|0.1|0.93|1|0|10.9|10.7|Upward|642|3,163,090
WHART|2023-01-10|2023-01-10|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|643|1,251,002
WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|644|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|645|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|650|20,924,999
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|655|15,575,456
WHART|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|657|1,943,970
WHART|2023-01-31|2023-01-31|1|11.6|11.6|0.0|0.0|0|0|11.8|11.5|Downward|658|1,239,474
WHART|2023-02-01|2023-02-03|3|11.7|11.8|0.1|0.85|1|0|11.8|11.5|Upward|660|3,044,650
ruby/../Data/summary.csv

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'KCE'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'BANPU'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')

In [21]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [22]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [23]:
#df.groupby('trend').days.max()

In [23]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward   10    139     2.0  2.201439
Upward     14    139     2.0  2.539568

In [24]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [25]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [26]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
17,BANPU,01-23,02-03,10,12.5,11.5,-8.0,-10,-1,12.6,11.3,1153288175,Downward

### Individual stock analysis

In [27]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [28]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price           qty   maxp   minp
count  22.00  2.200000e+01  22.00  22.00
mean   50.82  2.971414e+07  51.65  49.80
std     3.06  2.288157e+07   3.00   2.88
min    45.00  8.352469e+06  46.00  44.50
25%    49.06  1.385323e+07  50.06  48.75
50%    49.88  2.214165e+07  50.62  49.25
75%    51.88  3.714419e+07  52.81  50.69
max    58.00  1.042389e+08  58.50  56.50

In [29]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [30]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price           qty   maxp   minp
count  22.00  2.200000e+01  22.00  22.00
mean   12.27  1.194295e+08  12.37  12.10
std     0.37  9.213075e+07   0.35   0.36
min    11.50  3.089415e+07  11.60  11.30
25%    12.30  5.549074e+07  12.30  12.02
50%    12.40  9.824566e+07  12.50  12.20
75%    12.50  1.509636e+08  12.58  12.30
max    12.80  4.159035e+08  12.90  12.70

In [31]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [32]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [33]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-03'
ORDER BY name, date

In [34]:
df = pd.read_sql(sql, const)
df

        name        date   price        qty    maxp    minp
0        ACE  2023-02-03    2.54   16419256    2.58    2.54
1     ADVANC  2023-02-03  198.50    2401870  198.50  197.00
2         AH  2023-02-03   32.25    1850308   32.75   32.00
3        AIE  2023-02-03    2.80    1129796    2.86    2.80
4     AIMIRT  2023-02-03   12.50       7300   12.50   12.40
5        AIT  2023-02-03    6.75    5803841    6.85    6.65
6         AJ  2023-02-03   12.90     179424   13.00   12.80
7      AMATA  2023-02-03   20.40    5934269   20.60   20.40
8       ANAN  2023-02-03    1.43    2919055    1.45    1.43
9        AOT  2023-02-03   73.75   26206978   74.25   73.75
10        AP  2023-02-03   12.00   32643218   12.20   11.80
11     ASIAN  2023-02-03   13.70     471092   13.80   13.60
12       ASP  2023-02-03    3.10    3867567    3.18    3.10
13       ASW  2023-02-03    8.50   10067977    8.75    8.50
14       AWC  2023-02-03    5.80   28670015    5.85    5.75
15        BA  2023-02-03   14.40    1357219   14.60   14.40
16       BAM  2023-02-03   16.20   27923235   16.40   16.00
17     BANPU  2023-02-03   11.50   95309751   11.60   11.40
18       BBL  2023-02-03  161.50    4208050  162.00  161.00
19       BCH  2023-02-03   21.50   12718266   21.70   21.40
20       BCP  2023-02-03   36.00    8487723   37.00   36.00
21      BCPG  2023-02-03   10.00    3122417   10.10    9.95
22      BDMS  2023-02-03   30.00   23772918   30.00   29.75
23    BEAUTY  2023-02-03    1.42    7356130    1.44    1.42
24       BEC  2023-02-03   10.50    1009611   10.70   10.50
25       BEM  2023-02-03    9.75   26266207    9.75    9.65
26       BGC  2023-02-03   10.30    1206705   10.30   10.10
27     BGRIM  2023-02-03   40.50    8051413   41.00   40.25
28        BH  2023-02-03  217.00    1401506  218.00  216.00
29       BJC  2023-02-03   38.50    2533532   38.50   38.00
30       BKI  2023-02-03  294.00      20089  294.00  292.00
31       BLA  2023-02-03   29.00    4007523   29.25   28.50
32       BPP  2023-02-03   16.70    3629943   17.20   16.50
33       BTS  2023-02-03    8.40   11151434    8.45    8.40
34    BTSGIF  2023-02-03    3.88    1677838    3.90    3.88
35       CBG  2023-02-03  103.50    2215883  104.00  102.50
36    CENTEL  2023-02-03   52.75    4402630   53.50   52.25
37       CHG  2023-02-03    3.92  111439706    4.02    3.86
38        CK  2023-02-03   22.70    2679847   22.90   22.60
39       CKP  2023-02-03    4.56    2760309    4.58    4.54
40      COM7  2023-02-03   32.25   11906309   32.75   32.00
41     COTTO  2023-02-03    2.06    1884836    2.08    2.04
42     CPALL  2023-02-03   67.50   10259905   67.75   66.50
43       CPF  2023-02-03   23.80   17347127   24.00   23.70
44       CPN  2023-02-03   74.75   10958827   75.50   73.00
45     CPNCG  2023-02-03   11.70      90810   11.70   11.60
46   CPNREIT  2023-02-03   19.10    1088208   19.40   19.10
47     CPTGF  2023-02-03    7.45     124100    7.45    7.40
48       CRC  2023-02-03   44.75   11471504   45.00   43.75
49       DCC  2023-02-03    2.86    4524976    2.88    2.84
50      DCON  2023-02-03    0.44   15327004    0.46    0.43
51     DELTA  2023-02-03  950.00    4281310  950.00  916.00
52       DIF  2023-02-03   13.60    4520652   13.70   13.60
53    DOHOME  2023-02-03   14.20   17953368   14.40   13.80
54       DRT  2023-02-03    8.30      89617    8.35    8.25
55      DTAC  2023-02-03   50.00    3045956   50.00   49.75
56        EA  2023-02-03   89.50   25257481   90.25   87.50
57     EASTW  2023-02-03    5.40    1258447    5.40    5.30
58      EGCO  2023-02-03  173.50     625964  175.00  173.00
59       EPG  2023-02-03    8.60    2543845    8.75    8.60
60      ESSO  2023-02-03    9.25   13528935    9.30    9.20
61     FORTH  2023-02-03   44.00    4509083   45.50   43.50
62    FTREIT  2023-02-03   11.70     348562   11.80   11.70
63      GFPT  2023-02-03   13.10    2839525   13.30   13.00
64    GLOBAL  2023-02-03   21.10   11370359   21.20   20.70
65      GPSC  2023-02-03   69.50    5412736   70.00   69.25
66      GULF  2023-02-03   54.00    8673708   54.00   53.50
67    GUNKUL  2023-02-03    5.00    5591740    5.00    4.98
68    GVREIT  2023-02-03    9.75     438861    9.80    9.60
69      HANA  2023-02-03   64.75   17132030   65.00   63.00
70       HFT  2023-02-03    6.90    2272034    6.95    6.55
71     HMPRO  2023-02-03   14.90   23586766   14.90   14.40
72       HTC  2023-02-03   30.50      75918   30.75   30.50
73      ICHI  2023-02-03   12.50    4300978   12.50   12.30
74       III  2023-02-03   14.70    1470860   14.80   14.60
75       ILM  2023-02-03   19.60    3356812   19.80   18.70
76    IMPACT  2023-02-03   13.90     253564   14.10   13.90
77    INTUCH  2023-02-03   73.75    1837690   74.00   72.75
78      IRPC  2023-02-03    3.04   65003715    3.08    3.02
79       IVL  2023-02-03   40.50    7485590   41.00   40.25
80     JASIF  2023-02-03    8.25    2898474    8.25    8.20
81     JMART  2023-02-03   37.25    4467158   37.75   37.00
82       JMT  2023-02-03   54.75   12417267   55.25   53.75
83       JWD  2023-02-03   21.40    3268808   21.50   21.20
84     KBANK  2023-02-03  144.00    9657948  145.00  143.50
85       KCE  2023-02-03   58.00   47290254   58.50   56.50
86       KEX  2023-02-03   18.70    1277161   19.00   18.50
87       KGI  2023-02-03    5.10    8315814    5.20    5.10
88       KKP  2023-02-03   68.25    6493185   68.75   68.00
89       KSL  2023-02-03    3.64    4199856    3.72    3.64
90       KTB  2023-02-03   17.60   15929719   17.70   17.50
91       KTC  2023-02-03   59.25    3081409   59.25   58.25
92     LALIN  2023-02-03    9.40     674230    9.45    9.35
93     LANNA  2023-02-03   15.80     550882   15.80   15.60
94        LH  2023-02-03    9.95   33158917    9.95    9.80
95       LPF  2023-02-03   14.20     433911   14.30   14.10
96       LPH  2023-02-03    5.70     193066    5.70    5.65
97       LPN  2023-02-03    4.64     978381    4.66    4.62
98         M  2023-02-03   57.00     630732   57.50   56.50
99      MACO  2023-02-03    0.59    7179924    0.59    0.58
100    MAJOR  2023-02-03   18.70    1175031   18.80   18.50
101       MC  2023-02-03   11.60    1951666   11.70   11.30
102      MCS  2023-02-03    9.95     398713   10.00    9.90
103     MEGA  2023-02-03   51.25    1374224   52.00   51.25
104     MINT  2023-02-03   33.75   21650600   34.00   33.25
105      MTC  2023-02-03   39.50   12405941   39.75   39.25
106      NER  2023-02-03    6.40    5933273    6.40    6.30
107    NOBLE  2023-02-03    5.70    1006929    5.70    5.65
108     ONEE  2023-02-03    8.00    7342901    8.00    7.85
109       OR  2023-02-03   22.50    8745567   22.70   22.40
110      ORI  2023-02-03   12.00    4160275   12.10   11.90
111      OSP  2023-02-03   28.50    2396582   28.50   28.25
112    PLANB  2023-02-03    8.95   12149571    8.95    8.75
113     POPF  2023-02-03   11.60     352700   11.70   11.60
114      PRM  2023-02-03    7.90    4980032    7.90    7.80
115      PSH  2023-02-03   13.40    2688710   13.50   13.10
116      PSL  2023-02-03   16.40    3063774   16.50   16.20
117      PTG  2023-02-03   13.50    3824866   13.60   13.40
118      PTT  2023-02-03   33.00   52001720   33.00   32.50
119    PTTEP  2023-02-03  166.00   25486746  169.50  164.50
120    PTTGC  2023-02-03   49.50    6436841   50.00   49.25
121       QH  2023-02-03    2.38   21168667    2.38    2.34
122    RATCH  2023-02-03   43.00    1833521   43.25   42.75
123      RBF  2023-02-03   13.00    2172626   13.10   12.80
124      RCL  2023-02-03   30.75    2057453   31.00   30.50
125      RJH  2023-02-03   30.75     102631   30.75   30.50
126    ROJNA  2023-02-03    6.55    4609487    6.60    6.45
127       RS  2023-02-03   17.40   17689800   17.40   17.00
128      S11  2023-02-03    5.30     265100    5.35    5.20
129    SABUY  2023-02-03   12.90   18990503   13.20   12.80
130    SAPPE  2023-02-03   47.00     272911   47.25   46.50
131      SAT  2023-02-03   21.30     459249   21.50   21.20
132    SAWAD  2023-02-03   57.75    8400002   58.00   57.00
133       SC  2023-02-03    4.68    9481680    4.72    4.62
134      SCB  2023-02-03  105.00    2699209  105.50  104.50
135      SCC  2023-02-03  338.00    2642472  340.00  337.00
136     SCCC  2023-02-03  158.50     192878  160.50  158.00
137     SCGP  2023-02-03   53.50    5460017   53.75   53.00
138     SENA  2023-02-03    4.04    1762910    4.06    4.02
139   SINGER  2023-02-03   28.25    3563122   28.75   28.00
140     SIRI  2023-02-03    1.93  403221627    1.95    1.88
141      SIS  2023-02-03   27.00     136417   27.25   26.75
142      SKN  2023-02-03    5.25     140828    5.35    5.20
143     SMPC  2023-02-03   13.40     209857   13.40   13.30
144      SNC  2023-02-03   14.50     161162   14.60   14.40
145    SPALI  2023-02-03   24.30    5391630   24.50   24.10
146     SPCG  2023-02-03   14.50     189639   14.60   14.50
147     SPRC  2023-02-03   11.20   20968905   11.50   11.10
148   SPRIME  2023-02-03    7.20     137600    7.25    7.20
149      SSP  2023-02-03   10.00     670659   10.10   10.00
150      STA  2023-02-03   22.30    4951737   22.70   22.20
151   STANLY  2023-02-03  189.00      20900  189.00  186.50
152    STARK  2023-02-03    2.96   33303920    3.02    2.96
153     STGT  2023-02-03   11.10   22059692   11.60   11.00
154    SUPER  2023-02-03    0.64   90450338    0.65    0.63
155    SYNEX  2023-02-03   16.60    1229274   16.70   16.40
156    TASCO  2023-02-03   18.10    5955726   18.20   17.70
157     TCAP  2023-02-03   43.25     873185   43.25   43.00
158    TFFIF  2023-02-03    8.25    3991431    8.30    8.15
159    THANI  2023-02-03    4.16    6202991    4.18    4.14
160      THG  2023-02-03   70.50    3950828   71.00   69.75
161   TIDLOR  2023-02-03   30.25   32278657   30.50   29.00
162    TIPCO  2023-02-03    9.15     147658    9.25    9.15
163     TIPH  2023-02-03   50.25    1248824   51.00   50.25
164    TISCO  2023-02-03  101.50    1464003  102.50  101.50
165       TK  2023-02-03    8.70     216361    8.70    8.55
166      TKN  2023-02-03   11.50    5338981   11.50   11.20
167      TKS  2023-02-03   13.60    1649733   13.80   13.50
168      TMT  2023-02-03    8.20     162400    8.20    8.10
169      TOA  2023-02-03   34.75     578033   35.00   33.75
170      TOP  2023-02-03   57.25   12427477   58.00   56.75
171    TPIPL  2023-02-03    1.83    6630638    1.85    1.83
172    TPIPP  2023-02-03    3.52    3955250    3.54    3.50
173      TQM  2023-02-03   42.25    1757830   43.00   42.00
174     TRUE  2023-02-03    4.88   16573857    4.90    4.86
175      TSE  2023-02-03    2.52    1839200    2.56    2.52
176     TSTH  2023-02-03    1.19    2743800    1.22    1.19
177      TTA  2023-02-03    8.05    2506354    8.15    8.05
178      TTB  2023-02-03    1.45  164138233    1.46    1.44
179      TTW  2023-02-03    9.45    1130027    9.50    9.45
180       TU  2023-02-03   16.10    8247740   16.20   16.00
181      TVI  2023-02-03   12.90     192529   13.00   12.70
182      TVO  2023-02-03   29.00     973815   29.25   29.00
183      UTP  2023-02-03   15.50     849850   15.80   15.50
184      VGI  2023-02-03    5.05    6353776    5.10    5.00
185    VIBHA  2023-02-03    2.70    1687039    2.72    2.70
186      VNG  2023-02-03    5.55     697810    5.60    5.50
187      WHA  2023-02-03    3.98   76099032    4.02    3.94
188    WHAIR  2023-02-03    8.05     449631    8.05    8.00
189    WHART  2023-02-03   11.80     932206   11.80   11.60
190    WHAUP  2023-02-03    4.12   11632453    4.20    4.06
191     WICE  2023-02-03   11.90    4764194   12.00   11.70
192     WORK  2023-02-03   18.30     355565   18.40   18.30