In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 15), datetime.date(2023, 2, 14))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-02-15
Today in mm-dd format: 02-15
yesterday: 2023-02-14 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-17 00:00:00   Tuesday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'MC', 'SAT', 'TCAP'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'MC', 'SAT', 'TCAP'"

In [7]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'BANPU', 'CK', 'CKP', 'COM7', 'CPF', 'CPNREIT', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MEGA', 'ORI', 'PTT', 'RCL', 'SINGER', 'STA', 'TMT', 'TTB', 'WHAIR'"

### End of Selection between Buy or Orders

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-17 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'MC', 'SAT', 'TCAP')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty  maxp  minp
162  JASIF  2023-01-30   8.15   6349430  8.20  8.15
584  WHAIR  2023-02-06   8.00    461968  8.10  8.00
254     MC  2023-02-06  11.70    655103 11.80 11.50
28   BANPU  2023-01-25  12.50  30894152 12.50 12.40
319    ORI  2023-02-03  12.00   4160275 12.10 11.90

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.to_csv(output_file, header=None, index=False)
price.to_csv(osd_file, header=True, index=False)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2023-01-17|2023-01-18|2|3.1|3.1|0.0|0.0|0|0|3.1|3.08||3|1,754,573
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|5|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|6|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|7|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|8|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|9|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|11|1,798,533
ASP|2023-01-31|2023-01-31|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06|Downward|12|3,048,744
ASP|2023-02-01|2023-02-02|2|3.16|3.16|0.0|0.0|0|0|3.24|3.08|Upward|14|28,871,862
ASP|2023-02-03|2023-02-03|1|3.1|3.1|0.0|0.0|0|0|3.18|3.1|Downward|15|3,867,567
ASP|2023-02-06|2023-02-06|1|3.14|3.14|0.0|0.0|0|0|3.14|3.1|Upward|16|2,481,635
ASP|2023-02-07|2023-02-15|7|3.12|3.04|-0.08|-2.56|-4|-1|3.16|3.02|Downward|23|15,531,017
BANPU|2023-01-17|2023-01-19|3|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|26|195,444,107
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|27|193,937,283
BANPU|2023-01-23|2023-02-10|15|12.5|10.9|-1.6|-12.8|-16|-2|12.6|10.7|Downward|42|2,058,642,124
BANPU|2023-02-13|2023-02-13|1|11.1|11.1|0.0|0.0|0|0|11.2|10.9|Upward|43|90,540,091
BANPU|2023-02-14|2023-02-15|2|11.0|11.0|0.0|0.0|0|0|11.3|10.9|Downward|45|219,310,115
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|52|46,355,474
BCH|2023-01-26|2023-01-31|4|20.7|21.8|1.1|5.31|11|2|22.0|20.5|Upward|56|55,795,055
BCH|2023-02-01|2023-02-02|2|21.6|21.4|-0.2|-0.93|-2|-1|21.8|21.3|Downward|58|21,808,662
BCH|2023-02-03|2023-02-03|1|21.5|21.5|0.0|0.0|0|0|21.7|21.4|Upward|59|12,718,266
BCH|2023-02-06|2023-02-13|6|21.3|20.5|-0.8|-3.76|-8|-2|21.5|20.3|Downward|65|39,507,871
BCH|2023-02-14|2023-02-15|2|20.9|21.1|0.2|0.96|2|1|21.2|20.4|Upward|67|17,558,681
CPNREIT|2023-01-17|2023-01-19|3|19.6|20.6|1.0|5.1|10|3|20.6|19.6|Upward|70|6,367,343
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|73|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|75|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|78|3,517,218
CPNREIT|2023-02-01|2023-02-02|2|19.4|19.4|0.0|0.0|0|0|19.5|19.2|Upward|80|1,159,029
CPNREIT|2023-02-03|2023-02-14|8|19.1|18.2|-0.9|-4.71|-9|-2|19.4|18.2|Downward|88|19,622,744
CPNREIT|2023-02-15|2023-02-15|1|18.5|18.5|0.0|0.0|0|0|18.5|18.2|Upward|89|916,951
DIF|2023-01-17|2023-01-19|3|13.5|13.7|0.2|1.48|2|0|13.7|13.5|Upward|92|21,907,869
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|95|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|96|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|97|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|98|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|100|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|101|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|105|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|106|8,569,954
DIF|2023-02-10|2023-02-15|4|13.3|13.2|-0.1|-0.75|-1|-1|13.4|13.2|Downward|110|48,275,264
GVREIT|2023-01-17|2023-01-17|1|8.9|8.9|0.0|0.0|0|0|9.0|8.9|Downward|111|316,324
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|116|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|117|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|118|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|119|281,301
GVREIT|2023-01-30|2023-02-01|3|9.55|9.75|0.2|2.09|4|1|9.75|9.45|Upward|122|669,621
GVREIT|2023-02-02|2023-02-02|1|9.7|9.7|0.0|0.0|0|0|9.75|9.65|Downward|123|224,521
GVREIT|2023-02-03|2023-02-07|3|9.75|9.8|0.05|0.51|1|0|9.9|9.6|Upward|126|1,566,531
GVREIT|2023-02-08|2023-02-10|3|9.75|9.65|-0.1|-1.03|-2|-1|9.8|9.55|Downward|129|913,806
GVREIT|2023-02-13|2023-02-15|3|9.7|9.75|0.05|0.52|1|0|9.8|9.65|Upward|132|1,346,918
IVL|2023-01-17|2023-01-18|2|42.0|42.25|0.25|0.6|1|0|42.75|41.5|Upward|134|38,744,297
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|135|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|136|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|140|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|142|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|143|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|0|0|41.25|40.5|Upward|144|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|-1|-1|41.25|40.25|Downward|146|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|0|0|41.25|39.75|Upward|147|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|148|11,842,657
IVL|2023-02-08|2023-02-09|2|40.75|40.75|0.0|0.0|0|0|41.5|40.25|Upward|150|22,518,750
IVL|2023-02-10|2023-02-13|2|40.5|40.0|-0.5|-1.23|-2|-1|40.75|39.75|Downward|152|18,080,401
IVL|2023-02-14|2023-02-14|1|40.25|40.25|0.0|0.0|0|0|40.75|40.0|Upward|153|8,413,044
IVL|2023-02-15|2023-02-15|1|40.0|40.0|0.0|0.0|0|0|40.5|39.5|Downward|154|9,498,388
JASIF|2023-01-17|2023-01-18|2|8.25|8.2|-0.05|-0.61|-1|-1|8.25|8.2|Downward|156|4,802,219
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|160|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|164|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|1|0|8.25|8.15|Upward|166|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|167|3,117,519
JASIF|2023-02-03|2023-02-08|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|171|12,746,881
JASIF|2023-02-10|2023-02-15|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.1|Downward|175|23,164,926
JMART|2023-01-17|2023-01-26|8|41.25|35.5|-5.75|-13.94|-23|-3|42.25|35.25|Downward|183|111,582,249
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|184|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|185|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|1|0|38.25|36.5|Upward|188|17,299,441
JMART|2023-02-03|2023-02-15|9|37.25|28.5|-8.75|-23.49|-35|-4|37.75|28.5|Downward|197|165,286,876
JMT|2023-01-17|2023-01-26|8|67.25|53.75|-13.5|-20.07|-54|-7|68.25|53.75|Downward|205|123,625,182
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|206|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|208|45,047,024
JMT|2023-02-01|2023-02-01|1|54.25|54.25|0.0|0.0|0|0|54.5|53.0|Upward|209|11,053,059
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|210|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|211|12,417,267
JMT|2023-02-06|2023-02-08|3|53.75|50.75|-3.0|-5.58|-12|-4|54.75|50.75|Downward|214|33,982,605
JMT|2023-02-09|2023-02-09|1|52.0|52.0|0.0|0.0|0|0|53.0|50.25|Upward|215|14,352,623
JMT|2023-02-10|2023-02-13|2|50.5|49.5|-1.0|-1.98|-4|-2|52.0|48.75|Downward|217|35,100,334
JMT|2023-02-14|2023-02-14|1|50.0|50.0|0.0|0.0|0|0|53.25|49.5|Upward|218|45,121,902
JMT|2023-02-15|2023-02-15|1|42.75|42.75|0.0|0.0|0|0|50.5|42.0|Downward|219|75,936,256
KCE|2023-01-17|2023-01-20|4|50.75|49.0|-1.75|-3.45|-7|-2|52.0|48.5|Downward|223|69,519,050
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|224|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|225|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|226|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|227|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|228|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|229|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|13|3|58.5|50.5|Upward|233|214,389,940
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|0|0|57.75|56.25|Downward|234|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|0|0|57.75|56.0|Upward|235|17,516,788
KCE|2023-02-08|2023-02-10|3|50.5|47.25|-3.25|-6.44|-13|-5|55.25|47.25|Downward|238|202,268,953
KCE|2023-02-13|2023-02-13|1|48.0|48.0|0.0|0.0|0|0|48.25|46.75|Upward|239|16,263,448
KCE|2023-02-14|2023-02-15|2|47.0|46.75|-0.25|-0.53|-1|-1|48.75|46.75|Downward|241|32,681,327
MC|2023-01-17|2023-01-17|1|11.5|11.5|0.0|0.0|0|0|11.6|11.2|Downward|242|2,436,920
MC|2023-01-18|2023-01-19|2|11.6|11.7|0.1|0.86|1|0|11.7|11.4|Upward|244|3,003,054
MC|2023-01-20|2023-01-23|2|11.6|11.3|-0.3|-2.59|-3|-2|11.8|11.3|Downward|246|2,320,749
MC|2023-01-24|2023-01-26|3|11.6|11.9|0.3|2.59|3|1|11.9|11.3|Upward|249|4,617,106
MC|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.9|11.7|Downward|251|900,523
MC|2023-01-31|2023-01-31|1|11.9|11.9|0.0|0.0|0|0|11.9|11.7|Upward|252|1,180,849
MC|2023-02-01|2023-02-02|2|11.8|11.4|-0.4|-3.39|-4|-2|12.0|11.4|Downward|254|3,035,796
MC|2023-02-03|2023-02-06|2|11.6|11.7|0.1|0.86|1|0|11.8|11.3|Upward|256|2,606,769
MC|2023-02-07|2023-02-08|2|11.6|11.6|0.0|0.0|0|0|11.9|11.5|Downward|258|3,253,713
MC|2023-02-09|2023-02-10|2|11.7|12.2|0.5|4.27|5|2|12.7|11.6|Upward|260|8,043,176
MC|2023-02-13|2023-02-15|3|12.1|11.9|-0.2|-1.65|-2|-1|12.5|11.7|Downward|263|7,118,010
MCS|2023-01-17|2023-01-18|2|9.75|9.75|0.0|0.0|0|0|9.75|9.65|Downward|265|1,061,706
MCS|2023-01-19|2023-01-19|1|9.8|9.8|0.0|0.0|0|0|9.8|9.65|Upward|266|840,490
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|267|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|268|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|269|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|270|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|271|1,271,966
MCS|2023-01-27|2023-01-31|3|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|274|2,139,488
MCS|2023-02-01|2023-02-01|1|10.0|10.0|0.0|0.0|0|0|10.1|9.9|Downward|275|869,625
MCS|2023-02-02|2023-02-03|2|9.95|9.95|0.0|0.0|0|0|10.1|9.9|Upward|277|947,644
MCS|2023-02-06|2023-02-06|1|9.9|9.9|0.0|0.0|0|0|10.0|9.9|Downward|278|652,568
MCS|2023-02-07|2023-02-07|1|9.95|9.95|0.0|0.0|0|0|10.0|9.9|Upward|279|406,865
MCS|2023-02-08|2023-02-10|3|9.9|9.85|-0.05|-0.51|-1|-1|9.95|9.8|Downward|282|1,491,749
MCS|2023-02-13|2023-02-13|1|9.9|9.9|0.0|0.0|0|0|9.95|9.85|Upward|283|411,280
MCS|2023-02-14|2023-02-15|2|9.85|9.85|0.0|0.0|0|0|9.95|9.75|Downward|285|1,691,499
NER|2023-01-17|2023-01-20|4|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|289|10,202,955
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|290|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|291|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|293|42,913,468
NER|2023-01-27|2023-02-01|4|6.6|6.35|-0.25|-3.79|-5|-2|6.7|6.3|Downward|297|38,923,402
NER|2023-02-02|2023-02-06|3|6.4|6.5|0.1|1.56|2|0|6.5|6.3|Upward|300|24,426,533
NER|2023-02-07|2023-02-15|7|6.45|5.7|-0.75|-11.63|-15|-3|6.5|5.7|Downward|307|71,851,210
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|309|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|312|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|315|16,286,040
ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|318|32,777,837
ORI|2023-02-01|2023-02-09|7|12.1|11.7|-0.4|-3.31|-4|-1|12.3|11.5|Downward|325|38,175,270
ORI|2023-02-10|2023-02-10|1|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|326|4,834,840
ORI|2023-02-13|2023-02-15|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|329|17,788,630
PTTGC|2023-01-17|2023-01-20|4|51.5|50.0|-1.5|-2.91|-6|-2|51.75|49.75|Downward|333|77,410,908
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|336|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|337|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|338|13,790,565
PTTGC|2023-01-30|2023-01-31|2|50.0|49.25|-0.75|-1.5|-3|-2|50.5|49.25|Downward|340|24,376,908
PTTGC|2023-02-01|2023-02-01|1|50.0|50.0|0.0|0.0|0|0|50.5|49.25|Upward|341|13,026,320
PTTGC|2023-02-02|2023-02-06|3|49.75|49.5|-0.25|-0.5|-1|-1|50.25|49.0|Downward|344|20,473,206
PTTGC|2023-02-07|2023-02-14|6|49.75|50.5|0.75|1.51|3|0|52.5|49.25|Upward|350|123,970,421
PTTGC|2023-02-15|2023-02-15|1|49.5|49.5|0.0|0.0|0|0|50.5|49.5|Downward|351|17,953,966
RCL|2023-01-17|2023-01-20|4|31.75|31.0|-0.75|-2.36|-3|-1|32.0|31.0|Downward|355|6,165,221
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|358|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|359|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|362|12,494,495
RCL|2023-02-01|2023-02-02|2|30.75|30.25|-0.5|-1.63|-2|-1|32.25|30.0|Downward|364|21,219,944
RCL|2023-02-03|2023-02-07|3|30.75|31.0|0.25|0.81|1|0|31.25|30.5|Upward|367|6,209,457
RCL|2023-02-08|2023-02-09|2|30.5|30.5|0.0|0.0|0|0|31.25|30.25|Downward|369|4,603,482

RCL|2023-02-10|2023-02-10|1|30.75|30.75|0.0|0.0|0|0|30.75|30.25|Upward|370|1,341,212
RCL|2023-02-13|2023-02-15|3|29.5|29.0|-0.5|-1.69|-2|-1|30.75|29.0|Downward|373|10,038,784
SAT|2023-01-17|2023-01-18|2|21.3|21.1|-0.2|-0.94|-2|-1|21.5|21.0|Downward|375|2,415,272
SAT|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.1|Upward|376|1,125,554
SAT|2023-01-20|2023-01-23|2|21.1|21.1|0.0|0.0|0|0|21.5|20.8|Downward|378|2,257,736
SAT|2023-01-24|2023-01-25|2|21.4|21.5|0.1|0.47|1|0|21.7|21.1|Upward|380|3,388,826
SAT|2023-01-26|2023-01-26|1|21.1|21.1|0.0|0.0|0|0|21.5|21.1|Downward|381|1,465,304
SAT|2023-01-27|2023-01-27|1|21.6|21.6|0.0|0.0|0|0|21.6|21.3|Upward|382|1,055,229
SAT|2023-01-30|2023-01-30|1|21.2|21.2|0.0|0.0|0|0|21.6|21.1|Downward|383|1,628,098
SAT|2023-01-31|2023-02-01|2|21.4|21.5|0.1|0.47|1|0|21.6|21.1|Upward|385|1,777,880
SAT|2023-02-02|2023-02-03|2|21.4|21.3|-0.1|-0.47|-1|-1|21.6|21.2|Downward|387|1,008,901
SAT|2023-02-06|2023-02-06|1|21.6|21.6|0.0|0.0|0|0|21.8|21.2|Upward|388|1,273,172
SAT|2023-02-07|2023-02-15|7|21.5|20.7|-0.8|-3.72|-8|-2|21.7|20.7|Downward|395|5,842,395
SCC|2023-01-17|2023-01-26|8|359.0|334.0|-25.0|-6.96|-25|-4|359.0|332.0|Downward|403|18,563,771
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|405|3,832,045
SCC|2023-01-31|2023-01-31|1|336.0|336.0|0.0|0.0|0|0|343.0|336.0|Downward|406|3,280,199
SCC|2023-02-01|2023-02-01|1|342.0|342.0|0.0|0.0|0|0|343.0|337.0|Upward|407|2,080,273
SCC|2023-02-02|2023-02-06|3|338.0|336.0|-2.0|-0.59|-2|-1|343.0|336.0|Downward|410|4,970,202
SCC|2023-02-07|2023-02-10|4|338.0|338.0|0.0|0.0|0|0|340.0|335.0|Upward|414|8,476,335
SCC|2023-02-13|2023-02-13|1|335.0|335.0|0.0|0.0|0|0|339.0|335.0|Downward|415|1,796,324
SCC|2023-02-14|2023-02-14|1|341.0|341.0|0.0|0.0|0|0|341.0|336.0|Upward|416|3,326,298
SCC|2023-02-15|2023-02-15|1|338.0|338.0|0.0|0.0|0|0|340.0|338.0|Downward|417|888,346
SENA|2023-01-17|2023-01-19|3|3.94|3.92|-0.02|-0.51|-1|-1|3.94|3.9|Downward|420|3,132,743
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|422|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|423|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|424|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|426|2,050,656
SENA|2023-01-30|2023-02-06|6|3.94|4.04|0.1|2.54|5|0|4.06|3.9|Upward|432|13,631,211
SENA|2023-02-07|2023-02-08|2|4.0|3.94|-0.06|-1.5|-3|-2|4.04|3.94|Downward|434|2,218,445
SENA|2023-02-09|2023-02-10|2|3.96|3.96|0.0|0.0|0|0|3.98|3.92|Upward|436|1,521,299
SENA|2023-02-13|2023-02-15|3|3.94|3.94|0.0|0.0|0|0|3.96|3.9|Downward|439|1,969,230
SINGER|2023-01-17|2023-01-23|5|29.5|28.0|-1.5|-5.08|-6|-2|30.0|27.75|Downward|444|26,611,709
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|445|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|447|11,350,118
SINGER|2023-01-27|2023-02-02|5|27.5|28.5|1.0|3.64|4|0|29.25|27.0|Upward|452|26,173,063
SINGER|2023-02-03|2023-02-08|4|28.25|27.0|-1.25|-4.42|-5|-2|28.75|27.0|Downward|456|12,047,147
SINGER|2023-02-09|2023-02-09|1|27.5|27.5|0.0|0.0|0|0|27.5|26.25|Upward|457|5,240,034
SINGER|2023-02-10|2023-02-15|4|26.75|18.8|-7.95|-29.72|-69|-18|27.5|18.6|Downward|461|158,014,772
STA|2023-01-17|2023-01-18|2|21.3|21.0|-0.3|-1.41|-3|-2|21.7|20.9|Downward|463|8,437,859
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|464|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|466|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|470|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|472|17,280,360
STA|2023-02-01|2023-02-02|2|22.0|22.7|0.7|3.18|7|3|22.7|21.7|Upward|474|12,309,899
STA|2023-02-03|2023-02-03|1|22.3|22.3|0.0|0.0|0|0|22.7|22.2|Downward|475|4,951,737
STA|2023-02-06|2023-02-08|3|22.6|24.5|1.9|8.41|19|6|24.7|22.3|Upward|478|41,947,740
STA|2023-02-09|2023-02-13|3|24.1|23.6|-0.5|-2.07|-5|-2|24.5|23.5|Downward|481|22,887,544
STA|2023-02-14|2023-02-14|1|24.1|24.1|0.0|0.0|0|0|24.3|23.5|Upward|482|10,632,765
STA|2023-02-15|2023-02-15|1|23.8|23.8|0.0|0.0|0|0|24.1|23.7|Downward|483|4,677,813
SYNEX|2023-01-17|2023-01-20|4|16.9|16.6|-0.3|-1.78|-3|-1|17.3|16.5|Downward|487|6,405,791
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|489|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|491|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|493|2,438,448
SYNEX|2023-01-31|2023-01-31|1|16.1|16.1|0.0|0.0|0|0|16.3|16.0|Downward|494|1,438,207
SYNEX|2023-02-01|2023-02-07|5|16.5|17.1|0.6|3.64|6|1|17.6|16.2|Upward|499|14,528,451
SYNEX|2023-02-08|2023-02-08|1|16.3|16.3|0.0|0.0|0|0|17.2|16.3|Downward|500|3,347,661
SYNEX|2023-02-09|2023-02-09|1|16.6|16.6|0.0|0.0|0|0|16.6|16.3|Upward|501|1,122,744
SYNEX|2023-02-10|2023-02-14|3|16.5|15.8|-0.7|-4.24|-7|-3|16.7|15.8|Downward|504|4,716,214
SYNEX|2023-02-15|2023-02-15|1|16.1|16.1|0.0|0.0|0|0|16.2|15.6|Upward|505|2,259,313
TCAP|2023-01-17|2023-01-17|1|43.25|43.25|0.0|0.0|0|0|43.5|43.0|Upward|506|2,438,530
TCAP|2023-01-18|2023-01-18|1|42.75|42.75|0.0|0.0|0|0|43.25|42.75|Downward|507|3,050,969
TCAP|2023-01-19|2023-01-19|1|43.25|43.25|0.0|0.0|0|0|43.25|42.5|Upward|508|2,089,680
TCAP|2023-01-20|2023-01-25|4|42.75|42.5|-0.25|-0.58|-1|-1|43.25|42.5|Downward|512|8,545,310
TCAP|2023-01-26|2023-01-30|3|42.75|43.0|0.25|0.58|1|0|43.5|42.5|Upward|515|5,373,604
TCAP|2023-01-31|2023-01-31|1|42.75|42.75|0.0|0.0|0|0|43.0|42.75|Downward|516|1,512,084
TCAP|2023-02-01|2023-02-03|3|43.0|43.25|0.25|0.58|1|0|43.5|42.5|Upward|519|6,242,631
TCAP|2023-02-06|2023-02-06|1|43.0|43.0|0.0|0.0|0|0|43.25|42.75|Downward|520|2,192,738
TCAP|2023-02-07|2023-02-07|1|43.25|43.25|0.0|0.0|0|0|43.5|42.75|Upward|521|1,622,069
TCAP|2023-02-08|2023-02-15|6|42.75|42.75|0.0|0.0|0|0|43.0|42.5|Downward|527|8,797,575
TFFIF|2023-01-17|2023-01-17|1|8.0|8.0|0.0|0.0|0|0|8.05|7.95|Downward|528|2,175,439
TFFIF|2023-01-18|2023-01-24|5|8.1|8.2|0.1|1.23|2|0|8.2|8.0|Upward|533|15,915,581
TFFIF|2023-01-25|2023-01-31|5|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.1|Downward|538|12,364,080
TFFIF|2023-02-01|2023-02-01|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|539|2,482,129
TFFIF|2023-02-02|2023-02-02|1|8.15|8.15|0.0|0.0|0|0|8.25|8.15|Downward|540|1,039,802
TFFIF|2023-02-03|2023-02-03|1|8.25|8.25|0.0|0.0|0|0|8.3|8.15|Upward|541|3,991,431
TFFIF|2023-02-06|2023-02-15|8|8.2|8.0|-0.2|-2.44|-4|-1|8.25|7.95|Downward|549|19,558,109
TMT|2023-01-17|2023-01-17|1|8.0|8.0|0.0|0.0|0|0|8.05|8.0|Downward|550|356,285
TMT|2023-01-18|2023-01-24|5|8.05|8.45|0.4|4.97|8|1|8.45|8.0|Upward|555|3,289,220
TMT|2023-01-25|2023-02-02|7|8.35|8.15|-0.2|-2.4|-4|-1|8.45|8.15|Downward|562|1,939,587
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|563|162,400
TMT|2023-02-06|2023-02-09|4|8.15|8.05|-0.1|-1.23|-2|-1|8.25|8.0|Downward|567|760,892
TMT|2023-02-10|2023-02-10|1|8.2|8.2|0.0|0.0|0|0|8.2|8.0|Upward|568|158,167
TMT|2023-02-13|2023-02-15|3|8.05|7.95|-0.1|-1.24|-2|-1|8.1|7.85|Downward|571|728,525
WHAIR|2023-01-17|2023-01-17|1|7.55|7.55|0.0|0.0|0|0|7.55|7.45|Downward|572|2,022,633
WHAIR|2023-01-18|2023-01-20|3|7.6|7.95|0.35|4.61|7|2|8.0|7.5|Upward|575|4,432,763
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|577|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|579|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|581|3,620,824
WHAIR|2023-01-31|2023-02-03|4|7.95|8.05|0.1|1.26|2|0|8.05|7.8|Upward|585|3,326,380
WHAIR|2023-02-06|2023-02-10|5|8.0|7.9|-0.1|-1.25|-2|-1|8.1|7.85|Downward|590|2,057,078
WHAIR|2023-02-13|2023-02-14|2|7.95|7.95|0.0|0.0|0|0|8.0|7.8|Upward|592|482,551
WHAIR|2023-02-15|2023-02-15|1|7.8|7.8|0.0|0.0|0|0|7.9|7.8|Downward|593|279,749
WHART|2023-01-17|2023-01-17|1|11.2|11.2|0.0|0.0|0|0|11.2|11.0|Downward|594|2,181,709
WHART|2023-01-18|2023-01-19|2|11.5|12.0|0.5|4.35|5|2|12.2|11.2|Upward|596|15,116,751
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|601|15,575,456
WHART|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|603|1,943,970
WHART|2023-01-31|2023-01-31|1|11.6|11.6|0.0|0.0|0|0|11.8|11.5|Downward|604|1,239,474
WHART|2023-02-01|2023-02-03|3|11.7|11.8|0.1|0.85|1|0|11.8|11.5|Upward|607|3,044,650
WHART|2023-02-06|2023-02-07|2|11.6|11.6|0.0|0.0|0|0|11.9|11.6|Downward|609|1,507,517
WHART|2023-02-08|2023-02-08|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|610|459,646
WHART|2023-02-09|2023-02-09|1|11.6|11.6|0.0|0.0|0|0|11.7|11.5|Downward|611|927,026
WHART|2023-02-10|2023-02-10|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|612|632,010
WHART|2023-02-13|2023-02-13|1|11.5|11.5|0.0|0.0|0|0|11.7|11.5|Downward|613|1,544,552
WHART|2023-02-14|2023-02-14|1|11.6|11.6|0.0|0.0|0|0|11.6|11.5|Upward|614|2,133,923
WHART|2023-02-15|2023-02-15|1|11.3|11.3|0.0|0.0|0|0|11.5|11.3|Downward|614|1,808,207
ruby/../Data/summary.csv

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'BCH'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'SINGER'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')

In [21]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [22]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [23]:
#df.groupby('trend').days.max()

In [24]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median  mean
trend
Downward   15    140    2.00  2.68
Upward      6    120    1.50  1.98

In [25]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [26]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [27]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
14,BANPU,01-23,02-10,15,12.50,10.90,-12.80,-16,-2,12.60,10.70,2058642124,Downward

### Individual stock analysis

In [28]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [29]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean   21.10  8806545.86 21.30 20.92
std     0.32  5310881.72  0.32  0.32
min    20.50  2886815.00 20.70 20.30
25%    20.90  5802609.50 21.10 20.70
50%    21.10  7959848.00 21.20 20.90
75%    21.28 10880297.25 21.50 21.18
max    21.80 28254332.00 22.00 21.40

In [30]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [31]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean   27.12 11055333.91 28.00 26.75
std     2.45 21125512.64  1.64  2.45
min    18.80  1866964.00 21.40 18.60
25%    27.12  2781818.00 27.75 26.81
50%    27.88  3982281.50 28.25 27.50
75%    28.25  7810460.75 28.69 27.94
max    29.50 78498773.00 30.00 29.25

In [32]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [33]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [34]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-15'
ORDER BY name, date

In [35]:
df = pd.read_sql(sql, const)
df

       name        date  price       qty   maxp   minp
0       ACE  2023-02-15   2.44  17679778   2.46   2.42
1    ADVANC  2023-02-15 209.00   5608181 210.00 206.00
2        AH  2023-02-15  29.25   1687626  30.25  29.25
3       AIE  2023-02-15   2.84   1197610   2.90   2.84
4    AIMIRT  2023-02-15  12.20     70500  12.30  12.20
..      ...         ...    ...       ...    ...    ...
189   WHAIR  2023-02-15   7.80    279749   7.90   7.80
190   WHART  2023-02-15  11.30   1808207  11.50  11.30
191   WHAUP  2023-02-15   4.04   2462426   4.12   4.04
192    WICE  2023-02-15  10.40   2922846  10.70  10.40
193    WORK  2023-02-15  17.60    519059  17.80  17.50

[194 rows x 6 columns]