In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 3, 10), datetime.date(2023, 3, 9))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-03-10
Today in mm-dd format: 03-10
yesterday: 2023-03-09 00:00:00

In [3]:
#yesterday = date(2023, 3, 3)
yesterday

Timestamp('2023-03-09 00:00:00')

In [4]:
#yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-02-09 00:00:00   Thursday

In [5]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [6]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASK', 'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [7]:
in_p = in_p + ", 'AMATA','ASW', 'AWC','BH', 'BJC', 'COM7', 'GULF', 'HANA','PSH', \
'QH','SAT', \
'SC', 'SIRI','SNC', 'TCAP', 'TTB', 'WHA','WICE'"
in_p

"'ASK', 'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'AMATA','ASW', 'AWC','BH', 'BJC', 'COM7', 'GULF', 'HANA','PSH', 'QH','SAT', 'SC', 'SIRI','SNC', 'TCAP', 'TTB', 'WHA','WICE'"

### Bypass this statement if aboce statement is executed

In [10]:
sql = """
SELECT name
FROM orders
ORDER BY trade, name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'AMATA', 'ASK', 'ASW', 'AWC', 'BANPU', 'BH', 'BJC', 'COM7', 'CPNREIT', 'DIF', 'GULF', 'HANA', 'ILM', 'JMART', 'JMT', 'KCE', 'PSH', 'QH', 'RCL', 'SAT', 'SC', 'SINGER', 'SNC', 'TCAP', 'TTB', 'WHA', 'WHART', 'WICE', 'IVL', 'ORI', 'TMT'"

### End of Selection between Buy or Orders

In [8]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-09 00:00:00' AND name IN ('ASK', 'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'AMATA','ASW', 'AWC','BH', 'BJC', 'COM7', 'GULF', 'HANA','PSH', 'QH','SAT', 'SC', 'SIRI','SNC', 'TCAP', 'TTB', 'WHA','WICE')
ORDER BY name, date

In [9]:
price = pd.read_sql(sql, const)
price.sample(5)

       name        date  price       qty   maxp   minp
282  GVREIT  2023-02-23   9.70    245500   9.70   9.65
478     ORI  2023-03-10  12.50  20149491  12.90  12.50
537      QH  2023-03-07   2.38  21995335   2.40   2.36
308    HANA  2023-03-02  57.00  14195388  59.75  56.75
154      BH  2023-02-20 216.00   2481477 218.00 215.00

In [10]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.to_csv(output_file, header=None, index=False)
price.to_csv(osd_file, header=True, index=False)

### Call ruby ruby\crt-summary.rb

In [11]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [12]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [13]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
AMATA|2023-02-09|2023-02-09|1|20.2|20.2|0.0|0.0|0|0|20.2|19.8||2|8,308,239
AMATA|2023-02-10|2023-02-15|4|19.9|19.7|-0.2|-1.01|-2|-1|20.1|19.7|Downward|6|24,404,532
AMATA|2023-02-16|2023-02-16|1|19.9|19.9|0.0|0.0|0|0|20.1|19.7|Upward|7|5,515,642
AMATA|2023-02-17|2023-02-17|1|19.8|19.8|0.0|0.0|0|0|20.0|19.6|Downward|8|3,923,919
AMATA|2023-02-20|2023-02-22|3|19.9|20.3|0.4|2.01|4|1|20.5|19.7|Upward|11|18,105,681
AMATA|2023-02-23|2023-02-23|1|20.1|20.1|0.0|0.0|0|0|20.4|20.0|Downward|12|4,154,116
AMATA|2023-02-24|2023-02-24|1|20.3|20.3|0.0|0.0|0|0|20.4|19.9|Upward|13|8,897,712
AMATA|2023-02-27|2023-02-28|2|20.2|19.9|-0.3|-1.49|-3|-2|20.3|19.7|Downward|15|10,798,567
AMATA|2023-03-01|2023-03-01|1|20.3|20.3|0.0|0.0|0|0|20.4|20.0|Upward|16|10,627,362
AMATA|2023-03-02|2023-03-02|1|20.2|20.2|0.0|0.0|0|0|20.5|20.0|Downward|17|18,822,292
AMATA|2023-03-03|2023-03-09|5|20.9|21.9|1.0|4.78|10|2|21.9|20.2|Upward|21|68,759,854
AMATA|2023-03-10|2023-03-10|1|21.4|21.4|0.0|0.0|0|0|21.8|21.4|Downward|22|12,454,639
ASK|2023-02-09|2023-02-10|2|32.75|32.5|-0.25|-0.76|-1|-1|33.0|32.25|Downward|24|852,983
ASK|2023-02-13|2023-02-13|1|32.75|32.75|0.0|0.0|0|0|33.0|32.5|Upward|25|315,216
ASK|2023-02-14|2023-02-15|2|32.25|30.75|-1.5|-4.65|-6|-3|33.0|30.5|Downward|27|3,215,182
ASK|2023-02-16|2023-02-16|1|31.0|31.0|0.0|0.0|0|0|31.75|30.75|Upward|28|3,653,445
ASK|2023-02-17|2023-02-17|1|30.25|30.25|0.0|0.0|0|0|31.0|29.25|Downward|29|3,652,773
ASK|2023-02-20|2023-02-23|4|31.25|31.75|0.5|1.6|2|0|32.0|30.5|Upward|33|6,103,912
ASK|2023-02-24|2023-03-03|6|31.5|28.25|-3.25|-10.32|-13|-3|31.75|28.25|Downward|39|11,911,943
ASK|2023-03-07|2023-03-07|1|28.5|28.5|0.0|0.0|0|0|29.0|28.25|Upward|40|1,434,956
ASK|2023-03-08|2023-03-08|1|28.25|28.25|0.0|0.0|0|0|28.5|28.0|Downward|41|397,189
ASK|2023-03-09|2023-03-10|2|28.5|28.5|0.0|0.0|0|0|28.75|28.0|Upward|43|1,358,548
ASP|2023-02-09|2023-02-10|2|3.12|3.12|0.0|0.0|0|0|3.14|3.1|Upward|45|2,669,930
ASP|2023-02-13|2023-02-21|7|3.1|3.04|-0.06|-1.94|-3|-1|3.12|3.0|Downward|52|15,133,961
ASP|2023-02-22|2023-02-22|1|3.08|3.08|0.0|0.0|0|0|3.08|3.04|Upward|53|1,637,637
ASP|2023-02-23|2023-02-28|4|3.06|3.04|-0.02|-0.65|-1|-1|3.08|3.02|Downward|57|10,779,886
ASP|2023-03-01|2023-03-07|5|3.06|3.12|0.06|1.96|3|0|3.14|3.04|Upward|61|16,870,811
ASP|2023-03-08|2023-03-10|3|2.96|2.96|0.0|0.0|0|0|3.0|2.94|Downward|64|10,456,735
ASW|2023-02-09|2023-02-13|3|8.7|8.4|-0.3|-3.45|-6|-2|8.7|8.3|Downward|67|5,229,076
ASW|2023-02-14|2023-02-14|1|8.45|8.45|0.0|0.0|0|0|8.5|8.35|Upward|68|1,006,727
ASW|2023-02-15|2023-02-15|1|8.2|8.2|0.0|0.0|0|0|8.3|8.1|Downward|69|4,297,457
ASW|2023-02-16|2023-02-16|1|8.25|8.25|0.0|0.0|0|0|8.3|8.2|Upward|70|973,650
ASW|2023-02-17|2023-02-17|1|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|71|938,972
ASW|2023-02-20|2023-02-21|2|8.3|8.35|0.05|0.6|1|0|8.4|8.2|Upward|73|785,523
ASW|2023-02-22|2023-02-22|1|8.3|8.3|0.0|0.0|0|0|8.35|8.25|Downward|74|488,746
ASW|2023-02-23|2023-02-24|2|8.4|8.45|0.05|0.6|1|0|8.7|8.25|Upward|76|8,096,714
ASW|2023-02-27|2023-02-27|1|8.3|8.3|0.0|0.0|0|0|8.45|8.25|Downward|77|1,347,901
ASW|2023-02-28|2023-03-07|6|8.4|8.75|0.35|4.17|7|1|8.85|8.3|Upward|82|9,240,050
ASW|2023-03-08|2023-03-10|3|8.7|8.7|0.0|0.0|0|0|8.85|8.5|Downward|85|7,811,214
AWC|2023-02-09|2023-02-09|1|5.7|5.7|0.0|0.0|0|0|5.8|5.65|Downward|86|78,670,481
AWC|2023-02-10|2023-02-13|2|5.85|5.9|0.05|0.85|1|0|5.9|5.65|Upward|88|75,567,060
AWC|2023-02-14|2023-02-16|3|5.75|5.75|0.0|0.0|0|0|5.9|5.75|Downward|91|53,708,789
AWC|2023-02-17|2023-02-23|5|5.85|6.05|0.2|3.42|4|0|6.05|5.75|Upward|96|212,255,377
AWC|2023-02-24|2023-03-01|4|6.0|5.8|-0.2|-3.33|-4|-1|6.1|5.8|Downward|100|209,828,280
AWC|2023-03-02|2023-03-02|1|5.9|5.9|0.0|0.0|0|0|5.95|5.8|Upward|101|37,607,786
AWC|2023-03-03|2023-03-03|1|5.8|5.8|0.0|0.0|0|0|5.9|5.65|Downward|102|51,659,055
AWC|2023-03-07|2023-03-07|1|5.9|5.9|0.0|0.0|0|0|5.95|5.7|Upward|103|40,538,104
AWC|2023-03-08|2023-03-10|3|5.85|5.65|-0.2|-3.42|-4|-2|5.85|5.6|Downward|106|173,265,810
BANPU|2023-02-09|2023-02-10|2|10.9|10.9|0.0|0.0|0|0|11.5|10.7|Downward|108|493,055,980
BANPU|2023-02-13|2023-02-13|1|11.1|11.1|0.0|0.0|0|0|11.2|10.9|Upward|109|90,540,091
BANPU|2023-02-14|2023-02-15|2|11.0|11.0|0.0|0.0|0|0|11.3|10.9|Downward|111|219,310,115
BANPU|2023-02-16|2023-02-16|1|11.1|11.1|0.0|0.0|0|0|11.2|11.0|Upward|112|91,249,864
BANPU|2023-02-17|2023-02-17|1|10.9|10.9|0.0|0.0|0|0|11.1|10.9|Downward|113|59,387,401
BANPU|2023-02-20|2023-02-21|2|11.1|11.3|0.2|1.8|2|1|11.3|10.9|Upward|115|202,731,825
BANPU|2023-02-22|2023-02-22|1|11.2|11.2|0.0|0.0|0|0|11.2|11.0|Downward|116|77,378,013
BANPU|2023-02-23|2023-02-23|1|11.3|11.3|0.0|0.0|0|0|11.4|10.8|Upward|117|232,231,875
BANPU|2023-02-24|2023-03-01|4|11.2|10.8|-0.4|-3.57|-4|-1|11.5|10.7|Downward|121|1,187,417,164
BANPU|2023-03-02|2023-03-03|2|10.9|10.9|0.0|0.0|0|0|11.1|10.8|Upward|123|145,793,536
BANPU|2023-03-07|2023-03-07|1|10.8|10.8|0.0|0.0|0|0|11.0|10.8|Downward|124|85,811,828
BANPU|2023-03-08|2023-03-08|1|10.9|10.9|0.0|0.0|0|0|11.0|10.7|Upward|125|134,356,776
BANPU|2023-03-09|2023-03-10|2|10.8|10.8|0.0|0.0|0|0|11.0|10.7|Downward|127|108,523,338
BCH|2023-02-09|2023-02-13|3|20.9|20.5|-0.4|-1.91|-4|-2|21.2|20.3|Downward|130|19,421,365
BCH|2023-02-14|2023-02-21|6|20.9|21.4|0.5|2.39|5|0|21.6|20.4|Upward|136|44,778,248
BCH|2023-02-22|2023-02-22|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|137|3,728,730
BCH|2023-02-23|2023-02-23|1|21.3|21.3|0.0|0.0|0|0|21.3|21.1|Upward|138|4,128,256
BCH|2023-02-24|2023-03-02|5|21.0|19.2|-1.8|-8.57|-18|-4|21.3|19.1|Downward|143|61,347,629
BCH|2023-03-03|2023-03-07|3|19.3|19.5|0.2|1.04|2|0|19.6|19.0|Upward|145|30,512,706
BCH|2023-03-08|2023-03-08|1|19.3|19.3|0.0|0.0|0|0|19.5|19.2|Downward|146|5,545,726
BCH|2023-03-09|2023-03-10|2|19.9|20.0|0.1|0.5|1|0|20.0|19.3|Upward|148|15,792,715
BH|2023-02-09|2023-02-09|1|212.0|212.0|0.0|0.0|0|0|213.0|210.0|Upward|149|2,397,652
BH|2023-02-10|2023-02-13|2|210.0|208.0|-2.0|-0.95|-2|-1|212.0|208.0|Downward|151|2,894,365
BH|2023-02-14|2023-02-14|1|210.0|210.0|0.0|0.0|0|0|212.0|207.0|Upward|152|2,423,646
BH|2023-02-15|2023-02-15|1|209.0|209.0|0.0|0.0|0|0|210.0|208.0|Downward|153|1,178,289
BH|2023-02-16|2023-02-17|2|215.0|217.0|2.0|0.93|2|1|219.0|212.0|Upward|155|8,640,034
BH|2023-02-20|2023-02-20|1|216.0|216.0|0.0|0.0|0|0|218.0|215.0|Downward|156|2,481,477
BH|2023-02-21|2023-02-23|3|217.0|220.0|3.0|1.38|3|1|222.0|216.0|Upward|159|7,809,523
BH|2023-02-24|2023-03-03|6|217.0|210.0|-7.0|-3.23|-7|-2|219.0|208.0|Downward|165|16,248,359
BH|2023-03-07|2023-03-08|2|213.0|216.0|3.0|1.41|3|1|216.0|209.0|Upward|167|4,842,176
BH|2023-03-09|2023-03-10|2|215.0|215.0|0.0|0.0|0|0|217.0|214.0|Downward|169|3,073,391
BJC|2023-02-09|2023-02-15|5|38.75|37.25|-1.5|-3.87|-6|-2|38.75|37.0|Downward|174|18,293,840
BJC|2023-02-16|2023-02-16|1|37.75|37.75|0.0|0.0|0|0|38.0|37.25|Upward|175|3,509,131
BJC|2023-02-17|2023-02-20|2|37.5|37.5|0.0|0.0|0|0|38.0|37.25|Downward|177|7,057,108
BJC|2023-02-21|2023-02-22|2|38.0|38.25|0.25|0.66|1|0|38.75|37.0|Upward|179|9,920,404
BJC|2023-02-23|2023-02-27|3|38.0|38.0|0.0|0.0|0|0|38.75|37.25|Downward|182|15,454,271
BJC|2023-02-28|2023-02-28|1|38.5|38.5|0.0|0.0|0|0|38.5|37.75|Upward|183|4,019,649
BJC|2023-03-01|2023-03-03|3|37.75|36.5|-1.25|-3.31|-5|-2|38.75|35.5|Downward|186|16,599,359
BJC|2023-03-07|2023-03-08|2|37.25|38.5|1.25|3.36|5|2|38.75|36.25|Upward|188|11,802,844
BJC|2023-03-09|2023-03-10|2|38.0|37.5|-0.5|-1.32|-2|-1|38.75|37.0|Downward|190|8,823,800
COM7|2023-02-09|2023-02-15|5|31.0|29.0|-2.0|-6.45|-8|-2|31.5|28.75|Downward|195|71,330,650
COM7|2023-02-16|2023-02-17|2|29.75|29.75|0.0|0.0|0|0|30.0|28.75|Upward|197|21,115,595
COM7|2023-02-20|2023-02-20|1|29.25|29.25|0.0|0.0|0|0|29.75|29.0|Downward|198|10,440,992
COM7|2023-02-21|2023-02-21|1|30.75|30.75|0.0|0.0|0|0|31.0|29.0|Upward|199|15,595,314
COM7|2023-02-22|2023-02-22|1|30.5|30.5|0.0|0.0|0|0|30.75|30.0|Downward|200|9,455,295
COM7|2023-02-23|2023-02-23|1|31.75|31.75|0.0|0.0|0|0|32.25|31.0|Upward|201|32,407,584
COM7|2023-02-24|2023-02-24|1|31.0|31.0|0.0|0.0|0|0|31.75|31.0|Downward|202|11,270,605
COM7|2023-02-27|2023-02-27|1|31.25|31.25|0.0|0.0|0|0|31.5|31.0|Upward|203|6,197,320
COM7|2023-02-28|2023-02-28|1|30.5|30.5|0.0|0.0|0|0|31.5|30.25|Downward|204|41,921,767
COM7|2023-03-01|2023-03-01|1|30.75|30.75|0.0|0.0|0|0|31.25|30.5|Upward|205|8,631,261
COM7|2023-03-02|2023-03-03|2|30.5|30.5|0.0|0.0|0|0|31.0|30.0|Downward|207|18,506,911
COM7|2023-03-07|2023-03-07|1|31.5|31.5|0.0|0.0|0|0|31.5|30.25|Upward|208|11,929,085
COM7|2023-03-08|2023-03-08|1|30.5|30.5|0.0|0.0|0|0|31.0|30.5|Downward|209|8,055,401
COM7|2023-03-09|2023-03-10|2|31.5|31.75|0.25|0.79|1|0|32.0|30.5|Upward|211|27,745,672
CPNREIT|2023-02-09|2023-02-10|2|18.4|18.4|0.0|0.0|0|0|18.5|18.3|Upward|213|2,375,363
CPNREIT|2023-02-13|2023-02-14|2|18.3|18.2|-0.1|-0.55|-1|-1|18.5|18.2|Downward|215|4,028,822
CPNREIT|2023-02-15|2023-02-16|2|18.5|18.5|0.0|0.0|0|0|18.6|18.2|Upward|217|2,186,664
CPNREIT|2023-02-17|2023-02-17|1|18.3|18.3|0.0|0.0|0|0|18.5|18.2|Downward|218|3,194,164
CPNREIT|2023-02-20|2023-02-20|1|18.4|18.4|0.0|0.0|0|0|18.4|18.2|Upward|219|7,349,990
CPNREIT|2023-02-21|2023-03-10|14|18.2|13.0|-5.2|-28.57|-52|-4|18.4|12.8|Downward|232|68,253,084
DIF|2023-02-10|2023-02-15|4|13.3|13.2|-0.1|-0.75|-1|-1|13.4|13.2|Downward|236|48,275,264
DIF|2023-02-16|2023-02-17|2|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|238|6,762,497
DIF|2023-02-20|2023-02-21|2|13.2|13.2|0.0|0.0|0|0|13.4|13.2|Downward|240|13,562,635
DIF|2023-02-22|2023-02-22|1|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|241|5,061,405
DIF|2023-02-23|2023-02-23|1|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|242|2,396,091
DIF|2023-02-24|2023-03-02|5|13.3|13.3|0.0|0.0|0|0|13.4|13.2|Upward|247|32,407,114
DIF|2023-03-03|2023-03-03|1|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|248|2,470,166
DIF|2023-03-07|2023-03-07|1|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|249|5,839,157
DIF|2023-03-08|2023-03-10|3|13.2|12.9|-0.3|-2.27|-3|-1|13.3|12.8|Downward|252|101,256,874
GULF|2023-02-09|2023-02-09|1|53.25|53.25|0.0|0.0|0|0|53.75|53.0|Downward|253|19,464,363
GULF|2023-02-10|2023-02-13|2|53.75|54.5|0.75|1.4|3|1|54.5|53.25|Upward|255|24,949,952
GULF|2023-02-14|2023-02-14|1|54.0|54.0|0.0|0.0|0|0|54.5|53.5|Downward|256|16,321,710
GULF|2023-02-15|2023-02-15|1|54.25|54.25|0.0|0.0|0|0|54.25|53.25|Upward|257|13,952,411
GULF|2023-02-16|2023-02-16|1|54.0|54.0|0.0|0.0|0|0|54.5|53.75|Downward|258|8,044,837
GULF|2023-02-17|2023-02-17|1|54.25|54.25|0.0|0.0|0|0|54.5|53.75|Upward|259|15,929,950
GULF|2023-02-20|2023-02-20|1|54.0|54.0|0.0|0.0|0|0|54.5|53.75|Downward|260|7,966,131
GULF|2023-02-21|2023-02-21|1|54.5|54.5|0.0|0.0|0|0|54.5|53.75|Upward|261|14,566,196
GULF|2023-02-22|2023-02-27|4|54.25|52.25|-2.0|-3.69|-8|-2|54.5|51.5|Downward|265|69,076,105
GULF|2023-02-28|2023-02-28|1|52.5|52.5|0.0|0.0|0|0|53.0|52.25|Upward|266|9,704,749
GULF|2023-03-01|2023-03-03|3|51.25|50.25|-1.0|-1.95|-4|-2|52.25|50.0|Downward|269|58,687,332
GULF|2023-03-07|2023-03-07|1|51.0|51.0|0.0|0.0|0|0|51.5|50.25|Upward|270|10,639,784
GULF|2023-03-08|2023-03-08|1|50.5|50.5|0.0|0.0|0|0|51.0|50.0|Downward|271|18,742,377
GULF|2023-03-09|2023-03-10|2|51.5|51.5|0.0|0.0|0|0|51.75|50.5|Upward|273|31,245,428
GVREIT|2023-02-09|2023-02-09|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Upward|274|376,500
GVREIT|2023-02-10|2023-02-10|1|9.65|9.65|0.0|0.0|0|0|9.75|9.65|Downward|275|161,500
GVREIT|2023-02-13|2023-02-16|4|9.7|9.8|0.1|1.03|2|0|9.85|9.65|Upward|279|1,832,807
GVREIT|2023-02-17|2023-03-02|10|9.7|9.3|-0.4|-4.12|-8|-1|9.8|9.3|Downward|289|3,683,813
GVREIT|2023-03-03|2023-03-03|1|9.45|9.45|0.0|0.0|0|0|9.45|9.3|Upward|290|94,400
GVREIT|2023-03-07|2023-03-07|1|9.35|9.35|0.0|0.0|0|0|9.45|9.35|Downward|291|111,400
GVREIT|2023-03-08|2023-03-08|1|9.45|9.45|0.0|0.0|0|0|9.45|9.3|Upward|292|161,300
GVREIT|2023-03-09|2023-03-10|2|9.4|9.2|-0.2|-2.13|-4|-2|9.45|9.2|Downward|294|386,100
HANA|2023-02-09|2023-02-13|3|59.5|58.25|-1.25|-2.1|-5|-2|61.0|57.75|Downward|297|30,250,531
HANA|2023-02-14|2023-02-15|2|58.5|59.25|0.75|1.28|3|1|61.0|58.25|Upward|299|19,690,681
HANA|2023-02-16|2023-02-17|2|58.25|57.25|-1.0|-1.72|-4|-2|61.25|56.75|Downward|301|20,880,228
HANA|2023-02-20|2023-02-21|2|58.0|58.5|0.5|0.86|2|1|58.75|57.25|Upward|303|6,207,144
HANA|2023-02-22|2023-02-22|1|55.5|55.5|0.0|0.0|0|0|58.75|55.25|Downward|304|13,519,957
HANA|2023-02-23|2023-02-23|1|56.75|56.75|0.0|0.0|0|0|56.75|54.75|Upward|305|6,729,599
HANA|2023-02-24|2023-02-24|1|55.5|55.5|0.0|0.0|0|0|56.75|55.25|Downward|306|5,029,030
HANA|2023-02-27|2023-03-01|3|55.75|59.75|4.0|7.17|16|5|61.0|54.75|Upward|309|44,401,673
HANA|2023-03-02|2023-03-08|5|57.0|52.25|-4.75|-8.33|-19|-4|59.75|51.0|Downward|313|71,899,107
HANA|2023-03-09|2023-03-09|1|54.25|54.25|0.0|0.0|0|0|54.5|52.0|Upward|314|7,402,809
HANA|2023-03-10|2023-03-10|1|53.25|53.25|0.0|0.0|0|0|54.75|53.0|Downward|315|4,951,066
IVL|2023-02-09|2023-02-13|3|40.75|40.0|-0.75|-1.84|-3|-1|41.0|39.75|Downward|318|27,085,678
IVL|2023-02-14|2023-02-14|1|40.25|40.25|0.0|0.0|0|0|40.75|40.0|Upward|319|8,413,044
IVL|2023-02-15|2023-02-20|4|40.0|38.75|-1.25|-3.13|-5|-2|40.5|38.5|Downward|323|50,931,185
IVL|2023-02-21|2023-02-21|1|39.25|39.25|0.0|0.0|0|0|39.5|38.75|Upward|324|8,052,453
IVL|2023-02-22|2023-03-01|6|39.0|36.5|-2.5|-6.41|-10|-2|39.5|36.5|Downward|330|106,357,314
IVL|2023-03-02|2023-03-03|2|37.0|37.25|0.25|0.68|1|0|37.75|36.5|Upward|332|32,773,083
IVL|2023-03-07|2023-03-09|3|36.75|35.5|-1.25|-3.4|-5|-2|37.25|35.0|Downward|335|69,807,175
IVL|2023-03-10|2023-03-10|1|35.75|35.75|0.0|0.0|0|0|36.25|35.25|Upward|336|13,245,243
JASIF|2023-02-10|2023-02-14|3|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Upward|339|12,837,375
JASIF|2023-02-15|2023-02-17|3|8.15|8.15|0.0|0.0|0|0|8.2|8.1|Downward|342|19,400,233
JASIF|2023-02-20|2023-02-23|4|8.2|8.25|0.05|0.61|1|0|8.3|8.15|Upward|346|67,646,312
JASIF|2023-02-24|2023-03-08|9|8.2|7.95|-0.25|-3.05|-5|-1|8.3|7.9|Downward|354|108,179,202
JASIF|2023-03-09|2023-03-09|1|8.05|8.05|0.0|0.0|0|0|8.05|7.9|Upward|355|23,682,306
JASIF|2023-03-10|2023-03-10|1|8.0|8.0|0.0|0.0|0|0|8.05|7.95|Downward|356|11,354,707
JMART|2023-02-09|2023-02-15|5|35.5|28.5|-7.0|-19.72|-28|-6|35.75|28.5|Downward|361|139,842,990
JMART|2023-02-16|2023-02-16|1|29.5|29.5|0.0|0.0|0|0|30.75|28.0|Upward|362|69,203,823
JMART|2023-02-17|2023-02-17|1|27.25|27.25|0.0|0.0|0|0|29.0|25.75|Downward|363|64,672,279
JMART|2023-02-20|2023-02-20|1|29.25|29.25|0.0|0.0|0|0|29.75|28.25|Upward|364|59,972,500
JMART|2023-02-21|2023-02-22|2|28.75|28.75|0.0|0.0|0|0|29.5|28.25|Downward|366|48,817,262
JMART|2023-02-23|2023-02-23|1|29.0|29.0|0.0|0.0|0|0|29.25|28.5|Upward|367|11,137,272
JMART|2023-02-24|2023-02-24|1|27.75|27.75|0.0|0.0|0|0|29.0|27.75|Downward|368|16,819,177
JMART|2023-02-27|2023-02-28|2|28.0|28.25|0.25|0.89|1|0|28.75|27.0|Upward|370|19,062,955
JMART|2023-03-01|2023-03-03|3|27.5|26.75|-0.75|-2.73|-3|-1|28.5|26.25|Downward|373|29,214,181
JMART|2023-03-07|2023-03-07|1|27.0|27.0|0.0|0.0|0|0|27.75|27.0|Upward|374|8,514,272
JMART|2023-03-08|2023-03-10|3|26.5|23.8|-2.7|-10.19|-18|-6|27.0|23.7|Downward|377|78,605,981
JMT|2023-02-09|2023-02-13|3|52.0|49.5|-2.5|-4.81|-10|-4|53.0|48.75|Downward|380|49,452,957
JMT|2023-02-14|2023-02-14|1|50.0|50.0|0.0|0.0|0|0|53.25|49.5|Upward|381|45,121,902
JMT|2023-02-15|2023-02-15|1|42.75|42.75|0.0|0.0|0|0|50.5|42.0|Downward|382|75,936,256
JMT|2023-02-16|2023-02-23|6|45.5|48.5|3.0|6.59|12|2|49.25|42.0|Upward|388|146,280,662
JMT|2023-02-24|2023-03-10|11|47.5|42.5|-5.0|-10.53|-20|-2|49.0|42.25|Downward|398|94,001,753
KCE|2023-02-09|2023-02-10|2|48.5|47.25|-1.25|-2.58|-5|-3|50.25|47.25|Downward|400|105,751,338
KCE|2023-02-13|2023-02-13|1|48.0|48.0|0.0|0.0|0|0|48.25|46.75|Upward|401|16,263,448
KCE|2023-02-14|2023-02-17|4|47.0|46.0|-1.0|-2.13|-4|-1|48.75|45.25|Downward|405|68,009,070
KCE|2023-02-20|2023-02-21|2|47.25|47.75|0.5|1.06|2|1|48.0|46.0|Upward|407|22,182,100
KCE|2023-02-22|2023-02-22|1|46.75|46.75|0.0|0.0|0|0|47.75|46.75|Downward|408|5,344,181
KCE|2023-02-23|2023-02-23|1|47.25|47.25|0.0|0.0|0|0|47.25|46.5|Upward|409|5,977,020
KCE|2023-02-24|2023-02-24|1|46.0|46.0|0.0|0.0|0|0|47.5|45.25|Downward|410|21,559,427
KCE|2023-03-01|2023-03-01|1|47.5|47.5|0.0|0.0|0|0|48.0|46.5|Upward|411|15,233,320
KCE|2023-03-02|2023-03-03|2|47.0|47.0|0.0|0.0|0|0|48.5|46.25|Downward|413|23,593,212
KCE|2023-03-07|2023-03-07|1|48.5|48.5|0.0|0.0|0|0|48.5|47.25|Upward|414|14,589,292
KCE|2023-03-08|2023-03-08|1|48.0|48.0|0.0|0.0|0|0|48.0|47.25|Downward|415|9,532,328
KCE|2023-03-09|2023-03-09|1|48.5|48.5|0.0|0.0|0|0|49.0|48.0|Upward|416|9,962,798
KCE|2023-03-10|2023-03-10|1|48.0|48.0|0.0|0.0|0|0|48.5|47.5|Downward|417|4,682,548
MCS|2023-02-09|2023-02-10|2|9.9|9.85|-0.05|-0.51|-1|-1|9.95|9.8|Downward|419|964,554
MCS|2023-02-13|2023-02-13|1|9.9|9.9|0.0|0.0|0|0|9.95|9.85|Upward|420|411,280
MCS|2023-02-14|2023-02-17|4|9.85|9.85|0.0|0.0|0|0|9.95|9.7|Downward|424|4,258,651
MCS|2023-02-20|2023-02-20|1|9.95|9.95|0.0|0.0|0|0|10.0|9.8|Upward|425|860,075
MCS|2023-02-21|2023-02-23|3|10.1|10.1|0.0|0.0|0|0|10.2|10.1|Downward|428|2,950,752
MCS|2023-02-24|2023-02-24|1|10.2|10.2|0.0|0.0|0|0|10.3|9.95|Upward|429|1,693,849
MCS|2023-02-27|2023-02-27|1|10.0|10.0|0.0|0.0|0|0|10.2|9.9|Downward|430|1,519,625

In [14]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

MCS|2023-02-28|2023-02-28|1|9.8|9.8|0.0|0.0|0|0|10.0|9.55|Upward|431|2,511,948
MCS|2023-03-01|2023-03-01|1|9.65|9.65|0.0|0.0|0|0|9.85|9.65|Downward|432|1,002,104
MCS|2023-03-02|2023-03-02|1|9.75|9.75|0.0|0.0|0|0|9.75|9.6|Upward|433|1,626,490
MCS|2023-03-03|2023-03-08|4|9.45|9.2|-0.25|-2.65|-5|-2|9.7|9.15|Downward|436|3,455,997
MCS|2023-03-09|2023-03-10|2|9.25|9.35|0.1|1.08|2|1|9.4|9.15|Upward|438|1,177,098
NER|2023-02-09|2023-02-09|1|6.3|6.3|0.0|0.0|0|0|6.35|6.2|Upward|439|6,922,412
NER|2023-02-10|2023-02-15|4|6.25|5.7|-0.55|-8.8|-11|-3|6.25|5.7|Downward|443|46,758,804
NER|2023-02-16|2023-02-27|8|5.85|6.25|0.4|6.84|8|1|6.3|5.75|Upward|451|79,560,804
NER|2023-02-28|2023-03-02|3|6.15|6.15|0.0|0.0|0|0|6.3|6.1|Downward|454|17,992,952
NER|2023-03-03|2023-03-03|1|6.25|6.25|0.0|0.0|0|0|6.3|6.15|Upward|455|12,061,486
NER|2023-03-07|2023-03-10|4|6.15|6.1|-0.05|-0.81|-1|-1|6.25|6.1|Downward|459|16,995,191
ORI|2023-02-09|2023-02-09|1|11.7|11.7|0.0|0.0|0|0|11.8|11.5|Downward|460|5,918,070
ORI|2023-02-10|2023-02-10|1|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|461|4,834,840
ORI|2023-02-13|2023-02-16|4|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|465|19,889,480
ORI|2023-02-17|2023-02-23|5|11.8|12.1|0.3|2.54|3|0|12.2|11.5|Upward|470|30,191,190
ORI|2023-02-24|2023-02-24|1|11.8|11.8|0.0|0.0|0|0|12.1|11.7|Downward|471|5,574,476
ORI|2023-02-27|2023-02-28|2|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|473|12,282,288
ORI|2023-03-01|2023-03-03|3|11.6|11.6|0.0|0.0|0|0|11.9|11.6|Downward|476|20,639,855
ORI|2023-03-07|2023-03-09|3|11.9|12.8|0.9|7.56|9|3|12.8|11.6|Upward|479|48,097,416
ORI|2023-03-10|2023-03-10|1|12.5|12.5|0.0|0.0|0|0|12.9|12.5|Downward|480|20,149,491
PSH|2023-02-09|2023-02-10|2|13.2|13.1|-0.1|-0.76|-1|-1|13.3|12.8|Downward|482|2,860,482
PSH|2023-02-13|2023-02-13|1|13.2|13.2|0.0|0.0|0|0|13.2|13.0|Upward|483|725,888
PSH|2023-02-14|2023-02-15|2|13.1|12.9|-0.2|-1.53|-2|-1|13.2|12.9|Downward|485|1,819,769
PSH|2023-02-16|2023-02-21|4|13.1|13.7|0.6|4.58|6|1|14.0|12.9|Upward|489|10,253,697
PSH|2023-02-22|2023-02-23|2|13.6|13.6|0.0|0.0|0|0|13.8|13.5|Downward|491|3,932,659
PSH|2023-02-24|2023-02-27|2|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|493|2,392,454
PSH|2023-03-01|2023-03-03|3|13.6|13.6|0.0|0.0|0|0|13.7|13.4|Downward|496|3,499,221
PSH|2023-03-07|2023-03-08|2|13.7|13.8|0.1|0.73|1|0|13.9|13.5|Upward|498|6,337,743
PSH|2023-03-09|2023-03-10|2|13.1|12.6|-0.5|-3.82|-5|-3|13.1|12.6|Downward|500|4,606,404
PTTGC|2023-02-09|2023-02-17|7|50.5|48.75|-1.75|-3.47|-7|-1|52.5|48.25|Downward|507|139,656,403
PTTGC|2023-02-20|2023-02-20|1|49.0|49.0|0.0|0.0|0|0|49.25|48.5|Upward|508|9,154,257
PTTGC|2023-02-21|2023-03-01|7|48.75|47.0|-1.75|-3.59|-7|-1|49.5|46.5|Downward|515|86,448,039
PTTGC|2023-03-02|2023-03-02|1|48.25|48.25|0.0|0.0|0|0|48.5|47.25|Upward|516|16,205,129
PTTGC|2023-03-03|2023-03-07|3|48.0|48.0|0.0|0.0|0|0|48.75|47.5|Downward|518|18,813,714
PTTGC|2023-03-08|2023-03-08|1|48.25|48.25|0.0|0.0|0|0|48.25|47.25|Upward|519|14,256,791
PTTGC|2023-03-09|2023-03-10|2|48.0|47.25|-0.75|-1.56|-3|-2|48.25|47.0|Downward|521|24,363,349
QH|2023-02-09|2023-02-09|1|2.34|2.34|0.0|0.0|0|0|2.36|2.32|Downward|522|21,356,277
QH|2023-02-10|2023-02-10|1|2.36|2.36|0.0|0.0|0|0|2.36|2.32|Upward|523|14,689,644
QH|2023-02-13|2023-02-13|1|2.34|2.34|0.0|0.0|0|0|2.36|2.34|Downward|524|4,479,266
QH|2023-02-14|2023-02-15|2|2.36|2.36|0.0|0.0|0|0|2.36|2.34|Upward|526|20,158,953
QH|2023-02-16|2023-02-17|2|2.34|2.32|-0.02|-0.85|-1|-1|2.36|2.32|Downward|528|29,421,730
QH|2023-02-20|2023-02-20|1|2.34|2.34|0.0|0.0|0|0|2.34|2.32|Upward|529|2,244,474
QH|2023-02-21|2023-02-22|2|2.32|2.32|0.0|0.0|0|0|2.36|2.3|Downward|531|26,857,061
QH|2023-02-23|2023-03-03|7|2.34|2.4|0.06|2.56|3|0|2.42|2.3|Upward|538|168,338,528
QH|2023-03-07|2023-03-07|1|2.38|2.38|0.0|0.0|0|0|2.4|2.36|Downward|539|21,995,335
QH|2023-03-08|2023-03-10|3|2.42|2.42|0.0|0.0|0|0|2.44|2.38|Upward|542|57,748,672
RCL|2023-02-09|2023-02-10|2|30.5|30.75|0.25|0.82|1|0|30.75|30.25|Upward|544|3,606,683
RCL|2023-02-13|2023-02-15|3|29.5|29.0|-0.5|-1.69|-2|-1|30.75|29.0|Downward|547|10,038,784
RCL|2023-02-16|2023-02-16|1|29.5|29.5|0.0|0.0|0|0|30.0|29.25|Upward|548|1,739,426
RCL|2023-02-17|2023-02-17|1|29.25|29.25|0.0|0.0|0|0|29.5|29.0|Downward|549|1,185,810
RCL|2023-02-20|2023-02-24|5|29.75|31.75|2.0|6.72|8|1|32.5|29.25|Upward|554|26,002,921
RCL|2023-02-27|2023-02-27|1|31.0|31.0|0.0|0.0|0|0|32.25|30.75|Downward|555|10,194,436
RCL|2023-02-28|2023-03-10|9|31.25|32.5|1.25|4.0|5|0|33.0|31.0|Upward|563|48,355,981
SAT|2023-02-09|2023-02-09|1|21.2|21.2|0.0|0.0|0|0|21.3|20.9|Upward|564|1,461,605
SAT|2023-02-10|2023-02-17|6|21.1|20.4|-0.7|-3.32|-7|-2|21.2|20.3|Downward|570|4,631,582
SAT|2023-02-20|2023-02-20|1|20.7|20.7|0.0|0.0|0|0|20.8|20.3|Upward|571|429,665
SAT|2023-02-21|2023-02-21|1|20.5|20.5|0.0|0.0|0|0|20.7|20.4|Downward|572|1,767,905
SAT|2023-02-22|2023-02-24|3|20.8|20.9|0.1|0.48|1|0|21.2|20.5|Upward|575|2,606,720
SAT|2023-02-27|2023-02-28|2|20.8|20.6|-0.2|-0.96|-2|-1|21.2|20.6|Downward|577|1,717,785
SAT|2023-03-01|2023-03-07|5|20.7|21.3|0.6|2.9|6|1|21.3|20.7|Upward|581|5,500,772
SAT|2023-03-08|2023-03-10|3|20.2|19.4|-0.8|-3.96|-8|-3|20.2|19.4|Downward|584|4,033,380
SC|2023-02-09|2023-02-09|1|4.54|4.54|0.0|0.0|0|0|4.54|4.4|Downward|585|13,133,000
SC|2023-02-10|2023-02-10|1|4.6|4.6|0.0|0.0|0|0|4.62|4.48|Upward|586|8,687,493
SC|2023-02-13|2023-02-15|3|4.5|4.38|-0.12|-2.67|-6|-2|4.6|4.34|Downward|589|28,390,481
SC|2023-02-16|2023-02-17|2|4.42|4.58|0.16|3.62|8|4|4.62|4.36|Upward|591|49,621,587
SC|2023-02-20|2023-02-20|1|4.54|4.54|0.0|0.0|0|0|4.62|4.52|Downward|592|9,029,168
SC|2023-02-21|2023-02-21|1|4.7|4.7|0.0|0.0|0|0|4.74|4.5|Upward|593|46,183,412
SC|2023-02-22|2023-02-23|2|4.64|4.62|-0.02|-0.43|-1|-1|4.7|4.6|Downward|595|29,880,204
SC|2023-02-24|2023-02-24|1|4.64|4.64|0.0|0.0|0|0|4.66|4.44|Upward|596|32,801,288
SC|2023-02-27|2023-02-27|1|4.62|4.62|0.0|0.0|0|0|4.66|4.58|Downward|597|8,009,116
SC|2023-02-28|2023-02-28|1|4.64|4.64|0.0|0.0|0|0|4.66|4.52|Upward|598|11,721,935
SC|2023-03-01|2023-03-03|3|4.56|4.44|-0.12|-2.63|-6|-2|4.68|4.44|Downward|601|49,078,693
SC|2023-03-07|2023-03-08|2|4.58|4.62|0.04|0.87|2|1|4.66|4.36|Upward|603|32,724,444
SC|2023-03-09|2023-03-10|2|4.54|4.5|-0.04|-0.88|-2|-1|4.64|4.48|Downward|605|18,657,344
SCC|2023-02-09|2023-02-13|3|338.0|335.0|-3.0|-0.89|-3|-1|340.0|335.0|Downward|608|5,853,005
SCC|2023-02-14|2023-02-14|1|341.0|341.0|0.0|0.0|0|0|341.0|336.0|Upward|609|3,326,298
SCC|2023-02-15|2023-02-15|1|338.0|338.0|0.0|0.0|0|0|340.0|338.0|Downward|610|888,346
SCC|2023-02-16|2023-02-17|2|340.0|340.0|0.0|0.0|0|0|340.0|337.0|Upward|612|2,181,706
SCC|2023-02-20|2023-02-20|1|339.0|339.0|0.0|0.0|0|0|341.0|338.0|Downward|613|520,070
SCC|2023-02-21|2023-02-21|1|340.0|340.0|0.0|0.0|0|0|342.0|338.0|Upward|614|1,152,516
SCC|2023-02-22|2023-02-22|1|336.0|336.0|0.0|0.0|0|0|340.0|335.0|Downward|615|1,864,147
SCC|2023-02-23|2023-02-23|1|338.0|338.0|0.0|0.0|0|0|339.0|336.0|Upward|616|1,093,452
SCC|2023-02-24|2023-03-01|4|331.0|321.0|-10.0|-3.02|-10|-3|338.0|321.0|Downward|620|9,462,137
SCC|2023-03-02|2023-03-02|1|330.0|330.0|0.0|0.0|0|0|332.0|322.0|Upward|621|4,015,702
SCC|2023-03-03|2023-03-03|1|328.0|328.0|0.0|0.0|0|0|333.0|328.0|Downward|622|1,475,661
SCC|2023-03-07|2023-03-07|1|334.0|334.0|0.0|0.0|0|0|337.0|332.0|Upward|623|3,774,900
SCC|2023-03-08|2023-03-10|3|331.0|331.0|0.0|0.0|0|0|333.0|327.0|Downward|626|6,616,155
SENA|2023-02-09|2023-02-17|7|3.96|3.94|-0.02|-0.51|-1|-1|3.98|3.9|Downward|633|4,194,388
SENA|2023-02-20|2023-02-21|2|3.96|3.98|0.02|0.51|1|0|4.0|3.92|Upward|635|1,192,630
SENA|2023-02-22|2023-03-08|11|3.96|3.56|-0.4|-10.1|-20|-2|4.0|3.52|Downward|645|15,422,436
SENA|2023-03-09|2023-03-09|1|3.58|3.58|0.0|0.0|0|0|3.58|3.52|Upward|646|1,563,247
SENA|2023-03-10|2023-03-10|1|3.52|3.52|0.0|0.0|0|0|3.58|3.48|Downward|647|3,819,263
SINGER|2023-02-09|2023-02-17|7|27.5|17.3|-10.2|-37.09|-87|-13|27.5|16.7|Downward|654|296,271,334
SINGER|2023-02-20|2023-02-20|1|21.5|21.5|0.0|0.0|0|0|22.2|17.1|Upward|655|164,519,637
SINGER|2023-02-21|2023-02-21|1|21.0|21.0|0.0|0.0|0|0|21.8|20.7|Downward|656|48,322,744
SINGER|2023-02-22|2023-02-23|2|22.6|22.9|0.3|1.33|3|1|23.8|20.9|Upward|658|118,849,603
SINGER|2023-02-24|2023-02-24|1|22.0|22.0|0.0|0.0|0|0|23.3|21.9|Downward|659|22,689,633
SINGER|2023-02-27|2023-02-27|1|22.7|22.7|0.0|0.0|0|0|22.9|21.8|Upward|660|24,302,313
SINGER|2023-02-28|2023-03-01|2|22.5|21.5|-1.0|-4.44|-10|-5|23.1|21.3|Downward|662|26,214,373
SINGER|2023-03-02|2023-03-02|1|23.1|23.1|0.0|0.0|0|0|23.6|21.9|Upward|663|61,598,983
SINGER|2023-03-03|2023-03-10|6|22.2|20.0|-2.2|-9.91|-22|-4|23.0|19.9|Downward|668|70,360,143
SIRI|2023-02-09|2023-02-09|1|1.85|1.85|0.0|0.0|0|0|1.87|1.77|Downward|669|338,773,040
SIRI|2023-02-10|2023-02-10|1|1.87|1.87|0.0|0.0|0|0|1.88|1.85|Upward|670|102,916,128
SIRI|2023-02-13|2023-02-15|3|1.85|1.81|-0.04|-2.16|-4|-2|1.89|1.81|Downward|673|292,367,715
SIRI|2023-02-16|2023-02-16|1|1.84|1.84|0.0|0.0|0|0|1.86|1.82|Upward|674|95,375,102
SIRI|2023-02-17|2023-02-17|1|1.82|1.82|0.0|0.0|0|0|1.84|1.8|Downward|675|91,361,381
SIRI|2023-02-20|2023-02-21|2|1.85|1.92|0.07|3.78|7|3|1.93|1.82|Upward|677|337,870,781
SIRI|2023-02-22|2023-02-22|1|1.87|1.87|0.0|0.0|0|0|1.91|1.87|Downward|678|190,134,325
SIRI|2023-02-23|2023-02-23|1|1.88|1.88|0.0|0.0|0|0|1.91|1.86|Upward|679|232,638,565
SIRI|2023-02-24|2023-02-24|1|1.86|1.86|0.0|0.0|0|0|1.89|1.85|Downward|680|99,801,836
SIRI|2023-02-27|2023-03-01|3|1.89|1.92|0.03|1.59|3|1|1.94|1.85|Upward|682|360,282,638
SIRI|2023-03-02|2023-03-03|2|1.88|1.88|0.0|0.0|0|0|1.93|1.87|Downward|684|237,806,836
SIRI|2023-03-07|2023-03-08|2|1.92|1.93|0.01|0.52|1|0|1.94|1.88|Upward|686|265,800,574
SIRI|2023-03-09|2023-03-09|1|1.86|1.86|0.0|0.0|0|0|1.96|1.81|Downward|687|706,104,452
SIRI|2023-03-10|2023-03-10|1|1.88|1.88|0.0|0.0|0|0|1.9|1.84|Upward|688|207,141,766
SNC|2023-02-09|2023-02-09|1|14.5|14.5|0.0|0.0|0|0|14.5|14.3|Upward|689|446,810
SNC|2023-02-10|2023-02-15|4|14.3|13.8|-0.5|-3.5|-5|-2|14.5|13.8|Downward|693|2,249,841
SNC|2023-02-16|2023-02-16|1|14.0|14.0|0.0|0.0|0|0|14.0|13.8|Upward|694|258,010
SNC|2023-02-17|2023-02-17|1|13.8|13.8|0.0|0.0|0|0|14.0|13.7|Downward|695|519,107
SNC|2023-02-20|2023-02-21|2|14.5|14.6|0.1|0.69|1|0|14.7|14.3|Upward|697|5,545,525
SNC|2023-02-22|2023-02-22|1|14.3|14.3|0.0|0.0|0|0|14.6|14.3|Downward|698|2,118,907
SNC|2023-02-23|2023-02-24|2|14.4|14.4|0.0|0.0|0|0|14.6|14.3|Upward|700|2,278,767
SNC|2023-02-27|2023-02-27|1|14.3|14.3|0.0|0.0|0|0|14.5|14.3|Downward|701|605,892
SNC|2023-02-28|2023-03-01|2|14.4|14.4|0.0|0.0|0|0|14.5|14.3|Upward|703|2,122,752
SNC|2023-03-02|2023-03-03|2|14.1|14.0|-0.1|-0.71|-1|-1|14.1|13.8|Downward|705|3,916,963
SNC|2023-03-07|2023-03-07|1|14.4|14.4|0.0|0.0|0|0|14.5|14.0|Upward|706|1,455,470
SNC|2023-03-08|2023-03-10|3|14.2|13.7|-0.5|-3.52|-5|-2|14.3|13.7|Downward|709|2,943,783
STA|2023-02-09|2023-02-13|3|24.1|23.6|-0.5|-2.07|-5|-2|24.5|23.5|Downward|712|22,887,544
STA|2023-02-14|2023-02-14|1|24.1|24.1|0.0|0.0|0|0|24.3|23.5|Upward|713|10,632,765
STA|2023-02-15|2023-02-16|2|23.8|23.6|-0.2|-0.84|-2|-1|24.1|22.9|Downward|715|14,098,409
STA|2023-02-17|2023-02-23|5|23.8|25.75|1.95|8.19|15|3|25.75|23.6|Upward|720|38,138,825
STA|2023-02-24|2023-02-24|1|25.25|25.25|0.0|0.0|0|0|25.75|25.0|Downward|721|7,323,636
STA|2023-02-27|2023-02-27|1|25.75|25.75|0.0|0.0|0|0|26.0|25.5|Upward|722|3,712,404
STA|2023-02-28|2023-03-10|9|25.25|23.3|-1.95|-7.72|-18|-2|26.0|22.9|Downward|730|48,037,733
SYNEX|2023-02-09|2023-02-14|4|16.6|15.8|-0.8|-4.82|-8|-2|16.7|15.8|Downward|734|5,838,958
SYNEX|2023-02-15|2023-02-16|2|16.1|16.2|0.1|0.62|1|0|16.5|15.6|Upward|736|3,908,567
SYNEX|2023-02-17|2023-02-17|1|16.1|16.1|0.0|0.0|0|0|16.5|15.9|Downward|737|2,500,399
SYNEX|2023-02-20|2023-02-22|3|16.4|16.7|0.3|1.83|3|1|16.7|16.0|Upward|740|2,794,196
SYNEX|2023-02-23|2023-03-01|5|16.4|15.9|-0.5|-3.05|-5|-1|16.8|15.9|Downward|745|3,629,594
SYNEX|2023-03-02|2023-03-02|1|16.0|16.0|0.0|0.0|0|0|16.1|15.9|Upward|746|358,583
SYNEX|2023-03-03|2023-03-03|1|15.6|15.6|0.0|0.0|0|0|16.0|15.5|Downward|747|1,664,125
SYNEX|2023-03-07|2023-03-08|2|16.0|16.1|0.1|0.63|1|0|16.1|15.7|Upward|749|2,136,193
SYNEX|2023-03-09|2023-03-10|2|15.6|15.5|-0.1|-0.64|-1|-1|15.8|15.5|Downward|751|1,821,644
TCAP|2023-02-09|2023-02-16|6|42.75|42.5|-0.25|-0.58|-1|-1|43.0|42.5|Downward|757|8,547,398
TCAP|2023-02-17|2023-02-17|1|42.75|42.75|0.0|0.0|0|0|42.75|42.25|Upward|758|1,904,030
TCAP|2023-02-20|2023-02-20|1|42.5|42.5|0.0|0.0|0|0|43.0|42.5|Downward|759|1,118,202
TCAP|2023-02-21|2023-02-21|1|43.25|43.25|0.0|0.0|0|0|43.5|43.0|Upward|760|2,337,857
TCAP|2023-02-22|2023-02-27|4|43.0|42.5|-0.5|-1.16|-2|-1|43.25|42.25|Downward|764|11,761,986
TCAP|2023-02-28|2023-03-10|9|42.75|44.0|1.25|2.92|5|0|44.25|42.5|Upward|772|26,688,950
TFFIF|2023-02-09|2023-02-13|3|8.15|8.15|0.0|0.0|0|0|8.2|8.1|Upward|775|7,392,881
TFFIF|2023-02-14|2023-02-21|6|8.1|7.9|-0.2|-2.47|-4|-1|8.15|7.85|Downward|781|18,541,826
TFFIF|2023-02-22|2023-02-23|2|7.95|7.95|0.0|0.0|0|0|8.0|7.9|Upward|783|1,911,923
TFFIF|2023-02-24|2023-02-27|2|7.9|7.9|0.0|0.0|0|0|8.0|7.9|Downward|785|3,851,408
TFFIF|2023-02-28|2023-03-01|2|7.95|8.0|0.05|0.63|1|0|8.05|7.85|Upward|787|3,657,878
TFFIF|2023-03-02|2023-03-08|5|7.85|7.75|-0.1|-1.27|-2|-1|7.95|7.75|Downward|791|4,497,410
TFFIF|2023-03-09|2023-03-09|1|7.8|7.8|0.0|0.0|0|0|7.8|7.75|Upward|792|1,670,400
TFFIF|2023-03-10|2023-03-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.7|Downward|793|1,318,406
TMT|2023-02-09|2023-02-09|1|8.05|8.05|0.0|0.0|0|0|8.1|8.0|Downward|794|279,047
TMT|2023-02-10|2023-02-10|1|8.2|8.2|0.0|0.0|0|0|8.2|8.0|Upward|795|158,167
TMT|2023-02-13|2023-02-16|4|8.05|7.9|-0.15|-1.86|-3|-1|8.1|7.8|Downward|799|884,650
TMT|2023-02-17|2023-02-20|2|8.0|8.15|0.15|1.88|3|1|8.15|7.85|Upward|801|178,445
TMT|2023-02-21|2023-03-02|8|8.1|7.4|-0.7|-8.64|-14|-2|8.15|7.35|Downward|809|2,594,520
TMT|2023-03-03|2023-03-07|3|7.45|7.45|0.0|0.0|0|0|7.5|7.35|Upward|811|285,390
TMT|2023-03-08|2023-03-08|1|7.4|7.4|0.0|0.0|0|0|7.45|7.35|Downward|812|160,309
TMT|2023-03-09|2023-03-10|2|7.45|7.45|0.0|0.0|0|0|7.5|7.4|Upward|814|424,433
TTB|2023-02-09|2023-02-13|3|1.4|1.41|0.01|0.71|1|0|1.42|1.39|Upward|817|657,198,127
TTB|2023-02-14|2023-02-17|4|1.4|1.36|-0.04|-2.86|-4|-1|1.42|1.36|Downward|821|748,388,635
TTB|2023-02-20|2023-02-21|2|1.4|1.41|0.01|0.71|1|0|1.41|1.36|Upward|823|322,393,282
TTB|2023-02-22|2023-02-23|2|1.39|1.39|0.0|0.0|0|0|1.41|1.38|Downward|825|312,329,992
TTB|2023-02-24|2023-02-28|3|1.4|1.4|0.0|0.0|0|0|1.41|1.39|Upward|828|482,182,873
TTB|2023-03-01|2023-03-02|2|1.39|1.37|-0.02|-1.44|-2|-1|1.41|1.36|Downward|830|485,502,722
TTB|2023-03-03|2023-03-07|3|1.39|1.39|0.0|0.0|0|0|1.4|1.36|Upward|832|394,262,673
TTB|2023-03-08|2023-03-08|1|1.38|1.38|0.0|0.0|0|0|1.39|1.37|Downward|833|257,348,226
TTB|2023-03-09|2023-03-09|1|1.39|1.39|0.0|0.0|0|0|1.39|1.37|Upward|834|223,967,154

'C:\\users\\user\\onedrive\\a7\\daily'

TTB|2023-03-10|2023-03-10|1|1.38|1.38|0.0|0.0|0|0|1.4|1.38|Downward|835|155,094,010
WHA|2023-02-09|2023-02-14|4|3.92|3.86|-0.06|-1.53|-3|-1|3.94|3.82|Downward|839|300,703,555
WHA|2023-02-15|2023-02-15|1|3.88|3.88|0.0|0.0|0|0|3.9|3.84|Upward|840|56,820,956
WHA|2023-02-16|2023-02-16|1|3.84|3.84|0.0|0.0|0|0|3.92|3.84|Downward|841|43,889,180
WHA|2023-02-17|2023-02-21|3|3.86|4.0|0.14|3.63|7|2|4.0|3.82|Upward|844|373,308,103
WHA|2023-02-22|2023-02-23|2|3.94|3.94|0.0|0.0|0|0|4.0|3.9|Downward|846|188,620,138
WHA|2023-02-24|2023-02-27|2|3.98|4.06|0.08|2.01|4|2|4.08|3.94|Upward|848|327,437,526
WHA|2023-02-28|2023-03-03|4|3.94|3.94|0.0|0.0|0|0|4.06|3.92|Downward|852|637,428,200
WHA|2023-03-07|2023-03-09|3|3.96|4.18|0.22|5.56|11|3|4.18|3.9|Upward|855|598,375,883
WHA|2023-03-10|2023-03-10|1|4.16|4.16|0.0|0.0|0|0|4.18|4.1|Downward|856|106,326,220
WHAIR|2023-02-09|2023-02-10|2|7.95|7.9|-0.05|-0.63|-1|-1|7.95|7.85|Downward|858|584,057
WHAIR|2023-02-13|2023-02-14|2|7.95|7.95|0.0|0.0|0|0|8.0|7.8|Upward|860|482,551
WHAIR|2023-02-15|2023-02-15|1|7.8|7.8|0.0|0.0|0|0|7.9|7.8|Downward|861|279,749
WHAIR|2023-02-16|2023-02-17|2|7.85|7.85|0.0|0.0|0|0|7.9|7.7|Upward|863|337,446
WHAIR|2023-02-20|2023-02-20|1|7.8|7.8|0.0|0.0|0|0|7.85|7.8|Downward|864|454,128
WHAIR|2023-02-21|2023-02-21|1|7.85|7.85|0.0|0.0|0|0|7.85|7.75|Upward|865|244,305
WHAIR|2023-02-22|2023-02-23|2|7.7|7.6|-0.1|-1.3|-2|-1|7.75|7.55|Downward|867|1,896,503
WHAIR|2023-02-24|2023-02-27|2|7.65|7.7|0.05|0.65|1|0|7.7|7.5|Upward|869|715,774
WHAIR|2023-02-28|2023-03-03|4|7.65|7.6|-0.05|-0.65|-1|-1|7.7|7.5|Downward|873|2,052,255
WHAIR|2023-03-07|2023-03-08|2|7.7|7.7|0.0|0.0|0|0|7.75|7.6|Upward|875|845,002
WHAIR|2023-03-09|2023-03-10|2|7.6|7.45|-0.15|-1.97|-3|-2|7.7|7.4|Downward|877|1,494,943
WHART|2023-02-09|2023-02-09|1|11.6|11.6|0.0|0.0|0|0|11.7|11.5|Downward|878|927,026
WHART|2023-02-10|2023-02-10|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|879|632,010
WHART|2023-02-13|2023-02-13|1|11.5|11.5|0.0|0.0|0|0|11.7|11.5|Downward|880|1,544,552
WHART|2023-02-14|2023-02-14|1|11.6|11.6|0.0|0.0|0|0|11.6|11.5|Upward|881|2,133,923
WHART|2023-02-15|2023-02-15|1|11.3|11.3|0.0|0.0|0|0|11.5|11.3|Downward|882|1,808,207
WHART|2023-02-16|2023-02-16|1|11.5|11.5|0.0|0.0|0|0|11.5|11.2|Upward|883|995,609
WHART|2023-02-17|2023-02-20|2|11.4|11.3|-0.1|-0.88|-1|-1|11.5|11.2|Downward|885|1,068,706
WHART|2023-02-21|2023-02-23|3|11.4|11.4|0.0|0.0|0|0|11.4|11.2|Upward|888|2,653,848
WHART|2023-02-24|2023-02-27|2|11.3|11.2|-0.1|-0.88|-1|-1|11.4|11.2|Downward|890|932,077
WHART|2023-02-28|2023-03-01|2|11.4|11.5|0.1|0.88|1|0|11.5|11.2|Upward|892|1,104,274
WHART|2023-03-02|2023-03-08|5|11.3|11.0|-0.3|-2.65|-3|-1|11.5|11.0|Downward|896|6,695,599
WHART|2023-03-09|2023-03-09|1|11.1|11.1|0.0|0.0|0|0|11.1|11.0|Upward|897|919,551
WHART|2023-03-10|2023-03-10|1|10.8|10.8|0.0|0.0|0|0|11.1|10.8|Downward|898|1,165,814
WICE|2023-02-09|2023-02-16|6|11.4|10.1|-1.3|-11.4|-13|-3|11.6|10.0|Downward|904|28,359,561
WICE|2023-02-17|2023-02-22|4|10.2|10.7|0.5|4.9|5|1|11.0|10.0|Upward|908|15,234,027
WICE|2023-02-23|2023-02-24|2|10.6|10.3|-0.3|-2.83|-3|-2|10.9|10.3|Downward|910|8,137,604
WICE|2023-02-27|2023-03-01|3|10.4|10.8|0.4|3.85|4|1|10.8|10.2|Upward|913|5,676,066
WICE|2023-03-02|2023-03-02|1|10.6|10.6|0.0|0.0|0|0|11.0|10.5|Downward|914|6,443,159
WICE|2023-03-03|2023-03-07|3|10.7|11.0|0.3|2.8|3|1|11.1|10.5|Upward|916|10,218,980
WICE|2023-03-08|2023-03-10|3|10.7|10.4|-0.3|-2.8|-3|-1|10.8|10.4|Downward|918|6,984,212
ruby/../Data/summary.csv

In [15]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [16]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [17]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [18]:
name_up = 'RCL'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [19]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [20]:
name_down = 'CPNREIT'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [21]:
df_groupby_trend = df.groupby('trend')

In [22]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [23]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [24]:
#df.groupby('trend').days.max()

In [25]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median  mean
trend
Downward   14    218    2.00  2.56
Upward      9    196    1.00  1.94

In [26]:
upward_max = df.groupby('trend').days.max().loc['Upward']
downward_max = df.groupby('trend').days.max().loc['Downward']

In [27]:
df.query('days == @upward_max and trend == "Upward"')[cols].style.format(format_dict)

In [28]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
107,CPNREIT,02-21,03-10,14,18.20,13.00,-28.57,-52,-4,18.40,12.80,68253084,Downward

### Individual stock analysis

In [29]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [30]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  21.00       21.00 21.00 21.00
mean   30.86  4815430.52 31.29 30.50
std     1.08  3259722.29  1.04  1.04
min    29.00  1185810.00 29.50 29.00
25%    29.75  2319547.00 30.75 29.25
50%    31.00  3923532.00 31.50 30.75
75%    31.75  6586026.00 32.00 31.25
max    32.50 14017609.00 33.00 32.25

In [31]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [32]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  21.00       21.00 21.00 21.00
mean   16.88  4161337.48 17.23 16.74
std     1.95  3624572.78  1.74  1.99
min    13.00   798531.00 13.10 12.80
25%    15.00  1274661.00 16.10 14.90
50%    18.10  3194164.00 18.20 18.00
75%    18.30  6304864.00 18.50 18.20
max    18.50 13698456.00 18.60 18.40

In [33]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [34]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [35]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-03-09'
ORDER BY name, date

In [36]:
df = pd.read_sql(sql, const)
df

       name        date  price       qty   maxp   minp
0       ACE  2023-03-09   2.46  20644153   2.46   2.42
1    ADVANC  2023-03-09 207.00   9664819 208.00 203.00
2    AEONTS  2023-03-09 198.50    270157 199.00 194.50
3        AH  2023-03-09  31.00   2921120  32.00  30.50
4       AIE  2023-03-09   2.52    688667   2.56   2.50
..      ...         ...    ...       ...    ...    ...
186   WHAIR  2023-03-09   7.60    373111   7.70   7.60
187   WHART  2023-03-09  11.10    919551  11.10  11.00
188   WHAUP  2023-03-09   3.94   1515263   3.96   3.90
189    WICE  2023-03-09  10.60   1783338  10.80  10.50
190    WORK  2023-03-09  17.80     56185  17.80  17.70

[191 rows x 6 columns]