In [1]:
import numpy as np
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
#data_path = "\\users\\user\\onedrive\\a7\\Data"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 2, 15)

### Today = Last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-15
yesterday: 2023-02-14

In [3]:
cols = 'name fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','percent':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### Begin of Tables in the process

In [4]:
sql = """
SELECT * 
FROM sales 
ORDER BY id DESC LIMIT 1
"""
tmp = pd.read_sql(sql, conlite)
tmp["fm_date"] = pd.to_datetime(tmp["fm_date"])
tmp["to_date"] = pd.to_datetime(tmp["to_date"])
tmp["created_at"] = pd.to_datetime(tmp["created_at"])
tmp["updated_at"] = pd.to_datetime(tmp["updated_at"])
tmp.style.format(format_dict)

In [5]:
names = tmp["name"]
type(names)

pandas.core.series.Series

In [6]:
name = names.to_string(index=False)
type(name)

str

In [7]:
sql = """
SELECT * 
FROM stocks
WHERE name = '%s'
"""
sql = sql % name
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'SINGER'

### End of Tables in the process

In [8]:
sql = """
SELECT DISTINCT a.name
FROM sales a 
WHERE to_date = '%s'
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp

SELECT DISTINCT a.name
FROM sales a
WHERE to_date = '2023-02-14'
ORDER BY a.name

      name
0    BANPU
1       CK
2      CKP
3      DIF
4      IVL
5    JASIF
6    JMART
7      JMT
8      KCE
9       MC
10    MEGA
11     ORI
12     PTT
13     RCL
14     SAT
15  SINGER
16    TCAP
17     TMT
18     TTB
19   WHAIR

In [9]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY t.status, a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-14' AND t.status IN ("B","I", "O", "S")
ORDER BY t.status, a.name

### This statement causes program to hang when there is no data

In [10]:
df = pd.read_sql(sql, conlite)
#df.set_index(["name"], inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('diff = to_price - fm_price',inplace=True)
df['percent'] = round(df['diff']/df['fm_price']*100,2)
df.style.format(format_dict)

In [11]:
df.shape

(20, 12)

### IF the above count not equal number of orders, there must be something incorrect

### Create daily-sales from sales

In [12]:
df[cols].style.format(format_dict)

In [13]:
file_name = "daily-sales.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(one_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(osd_file, header=True, index=False)

In [14]:
df[cols].shape

(20, 10)

In [15]:
sales = df[cols]
sales

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status
0,BANPU,2023-02-13,2023-02-14,11.10,11.00,201422852,11.20,10.90,-0.90,B
1,JMART,2023-02-14,2023-02-14,33.25,31.50,40826955,37.75,31.50,-5.26,B
2,JMT,2023-02-14,2023-02-14,49.50,50.00,45121902,52.00,48.75,1.01,B
3,KCE,2023-02-13,2023-02-14,48.00,47.00,33078428,48.25,46.75,-2.08,B
4,RCL,2023-02-13,2023-02-14,29.50,29.25,7719237,30.75,29.25,-0.85,B
5,SINGER,2023-02-14,2023-02-14,26.50,21.10,78498773,27.50,21.10,-20.38,B
6,DIF,2023-02-10,2023-02-14,13.30,13.30,44447147,13.40,13.20,0.00,I
7,IVL,2023-02-14,2023-02-14,40.00,40.25,8413044,40.75,39.75,0.62,I
8,JASIF,2023-02-10,2023-02-14,8.20,8.20,12837375,8.25,8.15,0.00,I
9,ORI,2023-02-13,2023-02-14,11.80,11.80,11032444,12.00,11.70,0.00,I
10,WHAIR,2023-02-13,2023-02-14,7.95,7.95,482551,7.95,7.80,0.00,I
11,CK,2023-02-13,2023-02-14,22.30,22.00,4467418,22.30,22.00,-1.35,O
12,CKP,2023-02-14,2023-02-14,4.58,4.52,10416964,4.74,4.52,-1.31,O
13,MC,2023-02-13,2023-02-14,12.10,12.00,5844588,12.50,12.00,-0.83,O
14,MEGA,2023-02-14,2023-02-14,50.75,49.00,4450869,52.00,49.00,-3.45,O
15,PTT,2023-02-14,2023-02-14,32.25,32.75,59583856,32.75,32.25,1.55,O
16,SAT,2023-02-14,2023-02-14,20.90,20.90,1506410,21.70,20.70,0.00,O
17,TCAP,2023-02-08,2023-02-14,42.75,42.75,7123317,43.00,42.50,0.00,O
18,TTB,2023-02-13,2023-02-14,1.41,1.40,339012403,1.42,1.39,-0.71,O
19,TMT,2023-02-13,2023-02-14,8.05,7.95,558286,8.10,7.95,-1.24,S

In [16]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-02-15,2.44,0.00,0.000000,2.44,2.46,2.42,17679778,4.312626e+04
1,ADVANC,2023-02-15,209.00,1.00,0.480769,207.00,210.00,206.00,5608181,1.168261e+06
2,AH,2023-02-15,29.25,-0.50,-1.680672,30.00,30.25,29.25,1687626,4.990630e+04
3,AIE,2023-02-15,2.84,-0.04,-1.388889,2.88,2.90,2.84,1197610,3.441659e+03
4,AIMIRT,2023-02-15,12.20,0.00,0.000000,12.30,12.30,12.20,70500,8.607700e+02
...,...,...,...,...,...,...,...,...,...,...
189,WHAIR,2023-02-15,7.80,-0.15,-1.886792,7.90,7.90,7.80,279749,2.192855e+03
190,WHART,2023-02-15,11.30,-0.30,-2.586207,11.50,11.50,11.30,1808207,2.057640e+04
191,WHAUP,2023-02-15,4.04,-0.08,-1.941748,4.12,4.12,4.04,2462426,9.997730e+03
192,WICE,2023-02-15,10.40,-0.20,-1.886792,10.50,10.70,10.40,2922846,3.068420e+04
193,WORK,2023-02-15,17.60,-0.10,-0.564972,17.60,17.80,17.50,519059,9.146772e+03

In [17]:
df_merge = pd.merge(sales,prices,on='name', how='inner')
df_merge

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,date,price,change,%change,open,high,low,volume,value(m)
0,BANPU,2023-02-13,2023-02-14,11.10,11.00,201422852,11.20,10.90,-0.90,B,2023-02-15,11.00,0.00,0.000000,11.00,11.20,10.90,108427354,1.198843e+06
1,JMART,2023-02-14,2023-02-14,33.25,31.50,40826955,37.75,31.50,-5.26,B,2023-02-15,28.50,-3.00,-9.523810,31.75,31.75,28.50,52678770,1.552593e+06
2,JMT,2023-02-14,2023-02-14,49.50,50.00,45121902,52.00,48.75,1.01,B,2023-02-15,42.75,-7.25,-14.500000,50.25,50.50,42.00,75936256,3.451159e+06
3,KCE,2023-02-13,2023-02-14,48.00,47.00,33078428,48.25,46.75,-2.08,B,2023-02-15,46.75,-0.25,-0.531915,47.25,48.00,46.75,15866347,7.495584e+05
4,RCL,2023-02-13,2023-02-14,29.50,29.25,7719237,30.75,29.25,-0.85,B,2023-02-15,29.00,-0.25,-0.854701,29.25,29.75,29.00,2319547,6.799622e+04
5,SINGER,2023-02-14,2023-02-14,26.50,21.10,78498773,27.50,21.10,-20.38,B,2023-02-15,18.80,-2.30,-10.900474,21.40,21.40,18.60,73247847,1.439565e+06
6,DIF,2023-02-10,2023-02-14,13.30,13.30,44447147,13.40,13.20,0.00,I,2023-02-15,13.20,-0.10,-0.751880,13.30,13.30,13.20,3828117,5.083159e+04
7,IVL,2023-02-14,2023-02-14,40.00,40.25,8413044,40.75,39.75,0.62,I,2023-02-15,40.00,-0.25,-0.621118,40.25,40.50,39.50,9498388,3.795711e+05
8,JASIF,2023-02-10,2023-02-14,8.20,8.20,12837375,8.25,8.15,0.00,I,2023-02-15,8.15,-0.05,-0.609756,8.20,8.20,8.10,10327551,8.418775e+04
9,ORI,2023-02-13,2023-02-14,11.80,11.80,11032444,12.00,11.70,0.00,I,2023-02-15,11.60,-0.20,-1.694915,11.70,11.80,11.50,6756186,7.835246e+04
10,WHAIR,2023-02-13,2023-02-14,7.95,7.95,482551,7.95,7.80,0.00,I,2023-02-15,7.80,-0.15,-1.886792,7.90,7.90,7.80,279749,2.192855e+03
11,CK,2023-02-13,2023-02-14,22.30,22.00,4467418,22.30,22.00,-1.35,O,2023-02-15,22.00,0.00,0.000000,22.00,22.00,21.60,3209720,7.010767e+04
12,CKP,2023-02-14,2023-02-14,4.58,4.52,10416964,4.74,4.52,-1.31,O,2023-02-15,4.28,-0.24,-5.309735,4.52,4.54,4.24,57268016,2.513670e+05
13,MC,2023-02-13,2023-02-14,12.10,12.00,5844588,12.50,12.00,-0.83,O,2023-02-15,11.90,-0.10,-0.833333,11.90,12.10,11.90,1273422,1.523249e+04
14,MEGA,2023-02-14,2023-02-14,50.75,49.00,4450869,52.00,49.00,-3.45,O,2023-02-15,48.00,-1.00,-2.040816,48.50,48.75,47.25,3256981,1.564510e+05
15,PTT,2023-02-14,2023-02-14,32.25,32.75,59583856,32.75,32.25,1.55,O,2023-02-15,32.75,0.00,0.000000,32.50,32.75,32.50,15818067,5.164614e+05
16,SAT,2023-02-14,2023-02-14,20.90,20.90,1506410,21.70,20.70,0.00,O,2023-02-15,20.70,-0.20,-0.956938,20.80,20.90,20.70,458838,9.523102e+03
17,TCAP,2023-02-08,2023-02-14,42.75,42.75,7123317,43.00,42.50,0.00,O,2023-02-15,42.75,0.00,0.000000,42.75,43.00,42.50,1674258,7.151942e+04
18,TTB,2023-02-13,2023-02-14,1.41,1.40,339012403,1.42,1.39,-0.71,O,2023-02-15,1.39,-0.01,-0.714286,1.41,1.41,1.38,175930477,2.450210e+05
19,TMT,2023-02-13,2023-02-14,8.05,7.95,558286,8.10,7.95,-1.24,S,2023-02-15,7.95,0.00,0.000000,7.90,8.00,7.85,170239,1.348741e+03

In [18]:
colu = 'name fm_date to_date fm_price to_price qty max_price min_price percent status \
price change volume date'.split()
colu

['name',
 'fm_date',
 'to_date',
 'fm_price',
 'to_price',
 'qty',
 'max_price',
 'min_price',
 'percent',
 'status',
 'price',
 'change',
 'volume',
 'date']

In [19]:
df_merge[colu]

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,price,change,volume,date
0,BANPU,2023-02-13,2023-02-14,11.10,11.00,201422852,11.20,10.90,-0.90,B,11.00,0.00,108427354,2023-02-15
1,JMART,2023-02-14,2023-02-14,33.25,31.50,40826955,37.75,31.50,-5.26,B,28.50,-3.00,52678770,2023-02-15
2,JMT,2023-02-14,2023-02-14,49.50,50.00,45121902,52.00,48.75,1.01,B,42.75,-7.25,75936256,2023-02-15
3,KCE,2023-02-13,2023-02-14,48.00,47.00,33078428,48.25,46.75,-2.08,B,46.75,-0.25,15866347,2023-02-15
4,RCL,2023-02-13,2023-02-14,29.50,29.25,7719237,30.75,29.25,-0.85,B,29.00,-0.25,2319547,2023-02-15
5,SINGER,2023-02-14,2023-02-14,26.50,21.10,78498773,27.50,21.10,-20.38,B,18.80,-2.30,73247847,2023-02-15
6,DIF,2023-02-10,2023-02-14,13.30,13.30,44447147,13.40,13.20,0.00,I,13.20,-0.10,3828117,2023-02-15
7,IVL,2023-02-14,2023-02-14,40.00,40.25,8413044,40.75,39.75,0.62,I,40.00,-0.25,9498388,2023-02-15
8,JASIF,2023-02-10,2023-02-14,8.20,8.20,12837375,8.25,8.15,0.00,I,8.15,-0.05,10327551,2023-02-15
9,ORI,2023-02-13,2023-02-14,11.80,11.80,11032444,12.00,11.70,0.00,I,11.60,-0.20,6756186,2023-02-15
10,WHAIR,2023-02-13,2023-02-14,7.95,7.95,482551,7.95,7.80,0.00,I,7.80,-0.15,279749,2023-02-15
11,CK,2023-02-13,2023-02-14,22.30,22.00,4467418,22.30,22.00,-1.35,O,22.00,0.00,3209720,2023-02-15
12,CKP,2023-02-14,2023-02-14,4.58,4.52,10416964,4.74,4.52,-1.31,O,4.28,-0.24,57268016,2023-02-15
13,MC,2023-02-13,2023-02-14,12.10,12.00,5844588,12.50,12.00,-0.83,O,11.90,-0.10,1273422,2023-02-15
14,MEGA,2023-02-14,2023-02-14,50.75,49.00,4450869,52.00,49.00,-3.45,O,48.00,-1.00,3256981,2023-02-15
15,PTT,2023-02-14,2023-02-14,32.25,32.75,59583856,32.75,32.25,1.55,O,32.75,0.00,15818067,2023-02-15
16,SAT,2023-02-14,2023-02-14,20.90,20.90,1506410,21.70,20.70,0.00,O,20.70,-0.20,458838,2023-02-15
17,TCAP,2023-02-08,2023-02-14,42.75,42.75,7123317,43.00,42.50,0.00,O,42.75,0.00,1674258,2023-02-15
18,TTB,2023-02-13,2023-02-14,1.41,1.40,339012403,1.42,1.39,-0.71,O,1.39,-0.01,175930477,2023-02-15
19,TMT,2023-02-13,2023-02-14,8.05,7.95,558286,8.10,7.95,-1.24,S,7.95,0.00,170239,2023-02-15

In [20]:
df_merge[colu].shape

(20, 14)

In [21]:
df_merge.shape

(20, 19)

In [22]:
file_name = "daily-sales-prices.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(output_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(data_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(one_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(osd_file, header=True, index=False)

### Call ruby ruby\daily-out-new.rb

In [23]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [24]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [25]:
!ruby ruby\\daily-out-new.rb

Name      From Date    To Date   From     To     Pct     Shares    Max    Min S Action
BANPU    2023-02-15 2023-02-15  11.00  11.00     0.0  108427354  11.20  10.90 B Insert
CK       2023-02-15 2023-02-15  22.00  22.00     0.0    3209720  22.30  22.00 O Insert
CKP      2023-02-15 2023-02-15   4.52   4.28   -5.31   57268016   4.74   4.52 O Insert
DIF      2023-02-10 2023-02-15  13.30  13.20   -0.75    3828117  13.40  13.20 I Update
IVL      2023-02-14 2023-02-15  40.00  40.00     0.0    9498388  40.75  39.75 I Update
JASIF    2023-02-10 2023-02-15   8.20   8.15   -0.61   10327551   8.25   8.15 I Update
JMART    2023-02-15 2023-02-15  31.50  28.50   -9.52   52678770  37.75  31.50 B Insert
JMT      2023-02-14 2023-02-15  49.50  42.75  -13.64   75936256  52.00  48.75 B Update
KCE      2023-02-15 2023-02-15  47.00  46.75   -0.53   15866347  48.25  46.75 B Insert
MC       2023-02-15 2023-02-15  12.00  11.90   -0.83    1273422  12.50  12.00 O Insert
MEGA     2023-02-15 2023-02-15  49.00  48.00   -2.04    3256981  52.00  49.00 O Insert
ORI      2023-02-13 2023-02-15  11.80  11.60   -1.69    6756186  12.00  11.70 I Update
PTT      2023-02-14 2023-02-15  32.25  32.75    1.55   15818067  32.75  32.25 O Update
RCL      2023-02-15 2023-02-15  29.25  29.00   -0.85    2319547  30.75  29.25 B Insert
SAT      2023-02-14 2023-02-15  20.90  20.70   -0.96     458838  21.70  20.70 O Update
SINGER   2023-02-15 2023-02-15  21.10  18.80   -10.9   73247847  27.50  21.10 B Insert
TCAP     2023-02-08 2023-02-15  42.75  42.75     0.0    1674258  43.00  42.50 O Update
TMT      2023-02-15 2023-02-15   7.95   7.95     0.0     170239   8.10   7.95 S Insert
TTB      2023-02-15 2023-02-15   1.40   1.39   -0.71  175930477   1.42   1.39 O Insert
WHAIR    2023-02-13 2023-02-15   7.95   7.80   -1.89     279749   7.95   7.80 I Update

In [26]:
os.chdir("C:\\users\\user\\onedrive\\a7\\Daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\Daily'

### cd\ruby\port_lite
### rails runner db/ins_sales.rb