In [1]:
import numpy as np
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
#data_path = "\\users\\user\\onedrive\\a7\\Data"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 2, 14)

### Today = Last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-14
yesterday: 2023-02-13

In [3]:
cols = 'name fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','percent':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### Begin of Tables in the process

In [4]:
sql = """
SELECT * 
FROM sales 
ORDER BY id DESC LIMIT 1
"""
tmp = pd.read_sql(sql, conlite)
tmp["fm_date"] = pd.to_datetime(tmp["fm_date"])
tmp["to_date"] = pd.to_datetime(tmp["to_date"])
tmp["created_at"] = pd.to_datetime(tmp["created_at"])
tmp["updated_at"] = pd.to_datetime(tmp["updated_at"])
tmp.style.format(format_dict)

In [5]:
names = tmp["name"]
type(names)

pandas.core.series.Series

In [6]:
name = names.to_string(index=False)
type(name)

str

In [7]:
sql = """
SELECT * 
FROM stocks
WHERE name = '%s'
"""
sql = sql % name
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'WHAIR'

### End of Tables in the process

In [8]:
sql = """
SELECT DISTINCT a.name
FROM sales a 
WHERE to_date = '%s'
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp

SELECT DISTINCT a.name
FROM sales a
WHERE to_date = '2023-02-13'
ORDER BY a.name

      name
0    BANPU
1       CK
2      CKP
3      DIF
4      IVL
5    JASIF
6    JMART
7      JMT
8      KCE
9       MC
10    MEGA
11     ORI
12     PTT
13     RCL
14     SAT
15  SINGER
16    TCAP
17     TMT
18     TTB
19   WHAIR

In [9]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY t.status, a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-13' AND t.status IN ("B","I", "O", "S")
ORDER BY t.status, a.name

### This statement causes program to hang when there is no data

In [10]:
df = pd.read_sql(sql, conlite)
#df.set_index(["name"], inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('diff = to_price - fm_price',inplace=True)
df['percent'] = round(df['diff']/df['fm_price']*100,2)
df.style.format(format_dict)

In [11]:
df.shape

(20, 12)

### IF the above count not equal number of orders, there must be something incorrect

### Create daily-sales from sales

In [12]:
df[cols].style.format(format_dict)

In [13]:
file_name = "daily-sales.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(one_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(osd_file, header=True, index=False)

In [14]:
df[cols].shape

(20, 10)

In [15]:
df.shape

(20, 12)

In [16]:
sales = df[cols]
sales

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status
0,BANPU,2023-02-13,2023-02-13,11.10,11.10,90540091,11.20,10.90,0.00,B
1,JMT,2023-02-10,2023-02-13,50.50,49.50,35100334,52.00,48.75,-1.98,B
2,KCE,2023-02-13,2023-02-13,48.00,48.00,16263448,48.25,46.75,0.00,B
3,RCL,2023-02-13,2023-02-13,29.50,29.50,4790203,30.75,29.25,0.00,B
4,DIF,2023-02-10,2023-02-13,13.30,13.30,27112524,13.40,13.20,0.00,I
5,IVL,2023-02-10,2023-02-13,40.50,40.00,18080401,40.75,39.75,-1.23,I
6,JASIF,2023-02-10,2023-02-13,8.20,8.20,8015731,8.25,8.15,0.00,I
7,JMART,2023-02-03,2023-02-13,37.25,33.25,71781151,37.75,33.00,-10.74,I
8,ORI,2023-02-13,2023-02-13,11.80,11.80,7001060,12.00,11.70,0.00,I
9,SINGER,2023-02-10,2023-02-13,26.75,26.50,6268152,27.50,26.25,-0.93,I
10,WHAIR,2023-02-13,2023-02-13,7.95,7.95,192301,7.95,7.80,0.00,I
11,CK,2023-02-13,2023-02-13,22.30,22.30,2398287,22.30,22.00,0.00,O
12,CKP,2023-02-08,2023-02-13,4.66,4.58,64190558,4.74,4.54,-1.72,O
13,MC,2023-02-13,2023-02-13,12.10,12.10,2731504,12.50,12.10,0.00,O
14,MEGA,2023-02-10,2023-02-13,51.50,50.75,4106884,52.00,50.00,-1.46,O
15,PTT,2023-02-09,2023-02-13,32.50,32.25,90879375,32.75,32.25,-0.77,O
16,SAT,2023-02-07,2023-02-13,21.50,20.90,3877147,21.70,20.70,-2.79,O
17,TCAP,2023-02-08,2023-02-13,42.75,42.75,4890441,43.00,42.50,0.00,O
18,TTB,2023-02-13,2023-02-13,1.41,1.41,153475351,1.42,1.39,0.00,O
19,TMT,2023-02-13,2023-02-13,8.05,8.05,288153,8.10,8.00,0.00,S

In [17]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-02-14,2.44,-0.06,-2.400000,2.50,2.52,2.42,16016716,3.944373e+04
1,ADVANC,2023-02-14,208.00,-2.00,-0.952381,211.00,211.00,206.00,8697801,1.813547e+06
2,AH,2023-02-14,29.75,0.25,0.847458,29.75,30.25,29.50,1947585,5.817563e+04
3,AIE,2023-02-14,2.88,-0.02,-0.689655,2.94,2.94,2.86,1510939,4.352744e+03
4,AIMIRT,2023-02-14,12.20,-0.10,-0.813008,12.20,12.30,12.20,10200,1.248600e+02
...,...,...,...,...,...,...,...,...,...,...
188,WHAIR,2023-02-14,7.95,0.00,0.000000,7.95,8.00,7.85,290250,2.308330e+03
189,WHART,2023-02-14,11.60,0.10,0.869565,11.50,11.60,11.50,2133923,2.469058e+04
190,WHAUP,2023-02-14,4.12,0.10,2.487562,4.02,4.12,4.02,3580118,1.455841e+04
191,WICE,2023-02-14,10.60,-0.30,-2.752294,10.80,10.90,10.60,4243538,4.538614e+04
192,WORK,2023-02-14,17.70,-0.50,-2.747253,18.20,18.30,17.70,2162925,3.867506e+04

In [18]:
df_merge = pd.merge(sales,prices,on='name', how='inner')
df_merge

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,date,price,change,%change,open,high,low,volume,value(m)
0,BANPU,2023-02-13,2023-02-13,11.10,11.10,90540091,11.20,10.90,0.00,B,2023-02-14,11.00,-0.10,-0.900901,11.10,11.30,10.90,110882761,1.226344e+06
1,JMT,2023-02-10,2023-02-13,50.50,49.50,35100334,52.00,48.75,-1.98,B,2023-02-14,50.00,0.50,1.010101,50.75,53.25,49.50,45121902,2.310802e+06
2,KCE,2023-02-13,2023-02-13,48.00,48.00,16263448,48.25,46.75,0.00,B,2023-02-14,47.00,-1.00,-2.083333,48.25,48.75,47.00,16814980,8.023380e+05
3,RCL,2023-02-13,2023-02-13,29.50,29.50,4790203,30.75,29.25,0.00,B,2023-02-14,29.25,-0.25,-0.847458,29.50,29.75,29.25,2929034,8.618751e+04
4,DIF,2023-02-10,2023-02-13,13.30,13.30,27112524,13.40,13.20,0.00,I,2023-02-14,13.30,0.00,0.000000,13.30,13.40,13.20,17334623,2.305759e+05
5,IVL,2023-02-10,2023-02-13,40.50,40.00,18080401,40.75,39.75,-1.23,I,2023-02-14,40.25,0.25,0.625000,40.50,40.75,40.00,8413044,3.397316e+05
6,JASIF,2023-02-10,2023-02-13,8.20,8.20,8015731,8.25,8.15,0.00,I,2023-02-14,8.20,0.00,0.000000,8.20,8.25,8.15,4821644,3.948517e+04
7,JMART,2023-02-03,2023-02-13,37.25,33.25,71781151,37.75,33.00,-10.74,I,2023-02-14,31.50,-1.75,-5.263158,33.75,35.00,31.00,40826955,1.341446e+06
8,ORI,2023-02-13,2023-02-13,11.80,11.80,7001060,12.00,11.70,0.00,I,2023-02-14,11.80,0.00,0.000000,11.80,11.90,11.60,4031384,4.751596e+04
9,SINGER,2023-02-10,2023-02-13,26.75,26.50,6268152,27.50,26.25,-0.93,I,2023-02-14,21.10,-5.40,-20.377358,27.00,27.50,20.50,78498773,1.779962e+06
10,WHAIR,2023-02-13,2023-02-13,7.95,7.95,192301,7.95,7.80,0.00,I,2023-02-14,7.95,0.00,0.000000,7.95,8.00,7.85,290250,2.308330e+03
11,CK,2023-02-13,2023-02-13,22.30,22.30,2398287,22.30,22.00,0.00,O,2023-02-14,22.00,-0.30,-1.345291,22.30,22.30,21.90,2069131,4.553532e+04
12,CKP,2023-02-08,2023-02-13,4.66,4.58,64190558,4.74,4.54,-1.72,O,2023-02-14,4.52,-0.06,-1.310044,4.58,4.60,4.50,10416964,4.717130e+04
13,MC,2023-02-13,2023-02-13,12.10,12.10,2731504,12.50,12.10,0.00,O,2023-02-14,12.00,-0.10,-0.826446,12.10,12.30,11.70,3113084,3.747200e+04
14,MEGA,2023-02-10,2023-02-13,51.50,50.75,4106884,52.00,50.00,-1.46,O,2023-02-14,49.00,-1.75,-3.448276,50.00,50.25,48.50,4450869,2.178391e+05
15,PTT,2023-02-09,2023-02-13,32.50,32.25,90879375,32.75,32.25,-0.77,O,2023-02-14,32.75,0.50,1.550388,32.50,32.75,32.25,59583856,1.939518e+06
16,SAT,2023-02-07,2023-02-13,21.50,20.90,3877147,21.70,20.70,-2.79,O,2023-02-14,20.90,0.00,0.000000,21.00,21.00,20.70,1506410,3.140434e+04
17,TCAP,2023-02-08,2023-02-13,42.75,42.75,4890441,43.00,42.50,0.00,O,2023-02-14,42.75,0.00,0.000000,43.00,43.00,42.50,2232876,9.546409e+04
18,TTB,2023-02-13,2023-02-13,1.41,1.41,153475351,1.42,1.39,0.00,O,2023-02-14,1.40,-0.01,-0.709220,1.41,1.42,1.40,185537052,2.609208e+05
19,TMT,2023-02-13,2023-02-13,8.05,8.05,288153,8.10,8.00,0.00,S,2023-02-14,7.95,-0.10,-1.242236,8.00,8.05,7.95,270133,2.156389e+03

In [19]:
colu = 'name fm_date to_date fm_price to_price qty max_price min_price percent status \
price change volume date'.split()
colu

['name',
 'fm_date',
 'to_date',
 'fm_price',
 'to_price',
 'qty',
 'max_price',
 'min_price',
 'percent',
 'status',
 'price',
 'change',
 'volume',
 'date']

In [20]:
df_merge[colu]

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,price,change,volume,date
0,BANPU,2023-02-13,2023-02-13,11.10,11.10,90540091,11.20,10.90,0.00,B,11.00,-0.10,110882761,2023-02-14
1,JMT,2023-02-10,2023-02-13,50.50,49.50,35100334,52.00,48.75,-1.98,B,50.00,0.50,45121902,2023-02-14
2,KCE,2023-02-13,2023-02-13,48.00,48.00,16263448,48.25,46.75,0.00,B,47.00,-1.00,16814980,2023-02-14
3,RCL,2023-02-13,2023-02-13,29.50,29.50,4790203,30.75,29.25,0.00,B,29.25,-0.25,2929034,2023-02-14
4,DIF,2023-02-10,2023-02-13,13.30,13.30,27112524,13.40,13.20,0.00,I,13.30,0.00,17334623,2023-02-14
5,IVL,2023-02-10,2023-02-13,40.50,40.00,18080401,40.75,39.75,-1.23,I,40.25,0.25,8413044,2023-02-14
6,JASIF,2023-02-10,2023-02-13,8.20,8.20,8015731,8.25,8.15,0.00,I,8.20,0.00,4821644,2023-02-14
7,JMART,2023-02-03,2023-02-13,37.25,33.25,71781151,37.75,33.00,-10.74,I,31.50,-1.75,40826955,2023-02-14
8,ORI,2023-02-13,2023-02-13,11.80,11.80,7001060,12.00,11.70,0.00,I,11.80,0.00,4031384,2023-02-14
9,SINGER,2023-02-10,2023-02-13,26.75,26.50,6268152,27.50,26.25,-0.93,I,21.10,-5.40,78498773,2023-02-14
10,WHAIR,2023-02-13,2023-02-13,7.95,7.95,192301,7.95,7.80,0.00,I,7.95,0.00,290250,2023-02-14
11,CK,2023-02-13,2023-02-13,22.30,22.30,2398287,22.30,22.00,0.00,O,22.00,-0.30,2069131,2023-02-14
12,CKP,2023-02-08,2023-02-13,4.66,4.58,64190558,4.74,4.54,-1.72,O,4.52,-0.06,10416964,2023-02-14
13,MC,2023-02-13,2023-02-13,12.10,12.10,2731504,12.50,12.10,0.00,O,12.00,-0.10,3113084,2023-02-14
14,MEGA,2023-02-10,2023-02-13,51.50,50.75,4106884,52.00,50.00,-1.46,O,49.00,-1.75,4450869,2023-02-14
15,PTT,2023-02-09,2023-02-13,32.50,32.25,90879375,32.75,32.25,-0.77,O,32.75,0.50,59583856,2023-02-14
16,SAT,2023-02-07,2023-02-13,21.50,20.90,3877147,21.70,20.70,-2.79,O,20.90,0.00,1506410,2023-02-14
17,TCAP,2023-02-08,2023-02-13,42.75,42.75,4890441,43.00,42.50,0.00,O,42.75,0.00,2232876,2023-02-14
18,TTB,2023-02-13,2023-02-13,1.41,1.41,153475351,1.42,1.39,0.00,O,1.40,-0.01,185537052,2023-02-14
19,TMT,2023-02-13,2023-02-13,8.05,8.05,288153,8.10,8.00,0.00,S,7.95,-0.10,270133,2023-02-14

In [21]:
df_merge[colu].shape

(20, 14)

In [22]:
df_merge.shape

(20, 19)

In [23]:
file_name = "daily-sales-prices.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(output_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(data_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(one_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(osd_file, header=True, index=False)

### Call ruby ruby\daily-out-new.rb

In [24]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [25]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [26]:
!ruby ruby\\daily-out-new.rb

Name      From Date    To Date   From     To     Pct     Shares    Max    Min S Action
BANPU    2023-02-13 2023-02-14  11.10  11.00    -0.9  110882761  11.20  10.90 B Update
CK       2023-02-13 2023-02-14  22.30  22.00   -1.35    2069131  22.30  22.00 O Update
CKP      2023-02-14 2023-02-14   4.58   4.52   -1.31   10416964   4.74   4.54 O Insert
DIF      2023-02-10 2023-02-14  13.30  13.30     0.0   17334623  13.40  13.20 I Update
IVL      2023-02-14 2023-02-14  40.00  40.25    0.63    8413044  40.75  39.75 I Insert
JASIF    2023-02-10 2023-02-14   8.20   8.20     0.0    4821644   8.25   8.15 I Update
JMART    2023-02-14 2023-02-14  33.25  31.50   -5.26   40826955  37.75  33.00 I Insert
JMT      2023-02-14 2023-02-14  49.50  50.00    1.01   45121902  52.00  48.75 B Insert
KCE      2023-02-13 2023-02-14  48.00  47.00   -2.08   16814980  48.25  46.75 B Update
MC       2023-02-13 2023-02-14  12.10  12.00   -0.83    3113084  12.50  12.10 O Update
MEGA     2023-02-14 2023-02-14  50.75  49.00   -3.45    4450869  52.00  50.00 O Insert
ORI      2023-02-13 2023-02-14  11.80  11.80     0.0    4031384  12.00  11.70 I Update
PTT      2023-02-14 2023-02-14  32.25  32.75    1.55   59583856  32.75  32.25 O Insert
RCL      2023-02-13 2023-02-14  29.50  29.25   -0.85    2929034  30.75  29.25 B Update
SAT      2023-02-14 2023-02-14  20.90  20.90     0.0    1506410  21.70  20.70 O Insert
SINGER   2023-02-14 2023-02-14  26.50  21.10  -20.38   78498773  27.50  26.25 I Insert
TCAP     2023-02-08 2023-02-14  42.75  42.75     0.0    2232876  43.00  42.50 O Update
TMT      2023-02-13 2023-02-14   8.05   7.95   -1.24     270133   8.10   8.00 S Update
TTB      2023-02-13 2023-02-14   1.41   1.40   -0.71  185537052   1.42   1.39 O Update
WHAIR    2023-02-13 2023-02-14   7.95   7.95     0.0     290250   7.95   7.80 I Update

In [27]:
os.chdir("C:\\users\\user\\onedrive\\a7\\Daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\Daily'

### cd\ruby\port_lite
### rails runner db/ins_sales.rb