In [1]:
import numpy as np
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
#data_path = "\\users\\user\\onedrive\\a7\\Data"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 2, 10)

### Today = Last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-10
yesterday: 2023-02-09

In [3]:
cols = 'name fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','percent':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### Begin of Tables in the process

In [4]:
sql = """
SELECT * 
FROM sales 
ORDER BY id DESC LIMIT 1
"""
tmp = pd.read_sql(sql, conlite)
tmp["fm_date"] = pd.to_datetime(tmp["fm_date"])
tmp["to_date"] = pd.to_datetime(tmp["to_date"])
tmp["created_at"] = pd.to_datetime(tmp["created_at"])
tmp["updated_at"] = pd.to_datetime(tmp["updated_at"])
tmp.style.format(format_dict)

In [5]:
names = tmp["name"]
type(names)

pandas.core.series.Series

In [6]:
name = names.to_string(index=False)
type(name)

str

In [7]:
sql = """
SELECT * 
FROM stocks
WHERE name = '%s'
"""
sql = sql % name
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'TTB'

### End of Tables in the process

In [8]:
sql = """
SELECT DISTINCT a.name
FROM sales a 
WHERE to_date = '%s'
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp

SELECT DISTINCT a.name
FROM sales a
WHERE to_date = '2023-02-09'
ORDER BY a.name

      name
0    BANPU
1       CK
2      CKP
3     COM7
4      CPF
5      IVL
6    JMART
7      JMT
8      KCE
9     MEGA
10     ORI
11     PTT
12     RCL
13  SINGER
14     STA
15     TMT
16     TTB
17   WHAIR

In [9]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY t.status, a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-09' AND t.status IN ("B","I", "O", "S")
ORDER BY t.status, a.name

### This statement causes program to hang when there is no data

In [10]:
df = pd.read_sql(sql, conlite)
#df.set_index(["name"], inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('diff = to_price - fm_price',inplace=True)
df['percent'] = round(df['diff']/df['fm_price']*100,2)
df.style.format(format_dict)

In [11]:
df.shape

(18, 12)

### IF the above count not equal number of orders, there must be something incorrect

### Create daily-sales from sales

In [12]:
df[cols].style.format(format_dict)

In [13]:
file_name = "daily-sales.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(one_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(osd_file, header=True, index=False)

In [14]:
df[cols].shape

(18, 10)

In [15]:
df.shape

(18, 12)

In [16]:
sales = df[cols]
sales

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status
0,BANPU,2023-02-08,2023-02-09,11.20,10.90,141204389,12.60,10.90,-2.68,B
1,KCE,2023-02-09,2023-02-09,52.75,48.50,62458648,58.50,48.50,-8.06,B
2,RCL,2023-02-03,2023-02-09,30.75,30.50,9524598,31.00,30.50,-0.81,B
3,STA,2023-02-03,2023-02-09,22.30,24.10,46763601,24.10,22.20,8.07,B
4,IVL,2023-02-06,2023-02-09,40.50,40.75,46717485,41.25,40.25,0.62,I
5,JMART,2023-02-09,2023-02-09,36.25,35.50,23786917,37.75,35.50,-2.07,I
6,JMT,2023-02-09,2023-02-09,52.00,52.00,14352623,55.25,52.00,0.00,I
7,ORI,2023-02-07,2023-02-09,11.70,11.70,15697710,12.30,11.70,0.00,I
8,SINGER,2023-02-09,2023-02-09,27.25,27.50,5240034,28.75,27.25,0.92,I
9,WHAIR,2023-01-31,2023-02-09,7.95,7.95,4955645,8.05,7.80,0.00,I
10,CK,2023-02-08,2023-02-09,22.40,22.50,4639535,22.90,22.40,0.45,O
11,CKP,2023-02-03,2023-02-09,4.56,4.66,58053296,4.68,4.54,2.19,O
12,COM7,2023-02-08,2023-02-09,31.75,31.00,17460938,33.25,31.00,-2.36,O
13,CPF,2023-02-09,2023-02-09,23.40,23.20,30068400,24.00,23.20,-0.85,O
14,MEGA,2023-02-03,2023-02-09,51.25,52.00,8141026,52.00,51.25,1.46,O
15,PTT,2023-02-08,2023-02-09,32.50,32.50,70754060,34.00,32.50,0.00,O
16,TTB,2023-02-09,2023-02-09,1.41,1.40,252820767,1.47,1.40,-0.71,O
17,TMT,2023-02-09,2023-02-09,8.10,8.05,279047,8.20,8.05,-0.62,S

In [17]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-02-10,2.48,-0.04,-1.587302,2.52,2.52,2.48,12908381,3.213728e+04
1,ADVANC,2023-02-10,206.00,6.50,3.258145,202.00,206.00,201.00,17037520,3.473210e+06
2,AH,2023-02-10,30.75,-1.25,-3.906250,32.00,32.00,30.50,5272428,1.644526e+05
3,AIE,2023-02-10,2.98,-0.06,-1.973684,3.04,3.04,2.98,2006091,6.024086e+03
4,AIMIRT,2023-02-10,12.30,0.00,0.000000,12.30,12.30,12.20,44600,5.474100e+02
...,...,...,...,...,...,...,...,...,...,...
189,WHAIR,2023-02-10,7.90,-0.05,-0.628931,7.95,7.95,7.85,321310,2.530394e+03
190,WHART,2023-02-10,11.70,0.10,0.862069,11.60,11.70,11.50,632010,7.348336e+03
191,WHAUP,2023-02-10,4.06,-0.04,-0.975610,4.10,4.12,4.06,2800220,1.141576e+04
192,WICE,2023-02-10,11.30,-0.10,-0.877193,11.40,11.60,11.30,1406725,1.600985e+04
193,WORK,2023-02-10,18.40,0.10,0.546448,18.40,18.40,18.30,141505,2.595003e+03

In [18]:
df_merge = pd.merge(sales,prices,on='name', how='inner')

In [19]:
df_merge

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,date,price,change,%change,open,high,low,volume,value(m)
0,BANPU,2023-02-08,2023-02-09,11.20,10.90,141204389,12.60,10.90,-2.68,B,2023-02-10,10.90,0.00,0.000000,11.40,11.50,10.80,399453216,4.436503e+06
1,KCE,2023-02-09,2023-02-09,52.75,48.50,62458648,58.50,48.50,-8.06,B,2023-02-10,47.25,-1.25,-2.577320,48.25,49.00,47.25,43292690,2.078870e+06
2,RCL,2023-02-03,2023-02-09,30.75,30.50,9524598,31.00,30.50,-0.81,B,2023-02-10,30.75,0.25,0.819672,30.50,30.75,30.25,1341212,4.101640e+04
3,STA,2023-02-03,2023-02-09,22.30,24.10,46763601,24.10,22.20,8.07,B,2023-02-10,23.90,-0.20,-0.829876,24.00,24.30,23.60,7751013,1.857553e+05
4,IVL,2023-02-06,2023-02-09,40.50,40.75,46717485,41.25,40.25,0.62,I,2023-02-10,40.50,-0.25,-0.613497,40.75,40.75,40.25,7953007,3.219915e+05
5,JMART,2023-02-09,2023-02-09,36.25,35.50,23786917,37.75,35.50,-2.07,I,2023-02-10,34.50,-1.00,-2.816901,35.25,35.50,34.50,7973040,2.772278e+05
6,JMT,2023-02-09,2023-02-09,52.00,52.00,14352623,55.25,52.00,0.00,I,2023-02-10,50.50,-1.50,-2.884615,51.75,52.00,50.25,11528715,5.863542e+05
7,ORI,2023-02-07,2023-02-09,11.70,11.70,15697710,12.30,11.70,0.00,I,2023-02-10,11.90,0.20,1.709402,11.70,11.90,11.60,4834840,5.704585e+04
8,SINGER,2023-02-09,2023-02-09,27.25,27.50,5240034,28.75,27.25,0.92,I,2023-02-10,26.75,-0.75,-2.727273,27.25,27.50,26.75,2084092,5.635892e+04
9,WHAIR,2023-01-31,2023-02-09,7.95,7.95,4955645,8.05,7.80,0.00,I,2023-02-10,7.90,-0.05,-0.628931,7.95,7.95,7.85,321310,2.530394e+03
10,CK,2023-02-08,2023-02-09,22.40,22.50,4639535,22.90,22.40,0.45,O,2023-02-10,22.10,-0.40,-1.777778,22.50,22.60,22.10,3006254,6.667933e+04
11,CKP,2023-02-03,2023-02-09,4.56,4.66,58053296,4.68,4.54,2.19,O,2023-02-10,4.66,0.00,0.000000,4.66,4.70,4.66,8920991,4.173834e+04
12,COM7,2023-02-08,2023-02-09,31.75,31.00,17460938,33.25,31.00,-2.36,O,2023-02-10,30.50,-0.50,-1.612903,30.75,31.00,30.50,6267187,1.922266e+05
13,CPF,2023-02-09,2023-02-09,23.40,23.20,30068400,24.00,23.20,-0.85,O,2023-02-10,22.90,-0.30,-1.293103,23.10,23.20,22.90,28297908,6.502490e+05
14,MEGA,2023-02-03,2023-02-09,51.25,52.00,8141026,52.00,51.25,1.46,O,2023-02-10,51.50,-0.50,-0.961538,51.75,52.00,51.25,1598024,8.248069e+04
15,PTT,2023-02-08,2023-02-09,32.50,32.50,70754060,34.00,32.50,0.00,O,2023-02-10,32.50,0.00,0.000000,32.25,32.50,32.25,29952200,9.728683e+05
16,TTB,2023-02-09,2023-02-09,1.41,1.40,252820767,1.47,1.40,-0.71,O,2023-02-10,1.40,0.00,0.000000,1.40,1.41,1.39,250902009,3.513238e+05
17,TMT,2023-02-09,2023-02-09,8.10,8.05,279047,8.20,8.05,-0.62,S,2023-02-10,8.20,0.15,1.863354,8.05,8.20,8.00,158167,1.277551e+03

In [20]:
df_merge.columns

Index(['name', 'fm_date', 'to_date', 'fm_price', 'to_price', 'qty',
       'max_price', 'min_price', 'percent', 'status', 'date', 'price',
       'change', '%change', 'open', 'high', 'low', 'volume', 'value(m)'],
      dtype='object')

In [21]:
colu = 'name fm_date to_date fm_price to_price qty max_price min_price percent status \
price change volume date'.split()
colu

['name',
 'fm_date',
 'to_date',
 'fm_price',
 'to_price',
 'qty',
 'max_price',
 'min_price',
 'percent',
 'status',
 'price',
 'change',
 'volume',
 'date']

In [22]:
df_merge[colu]

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,price,change,volume,date
0,BANPU,2023-02-08,2023-02-09,11.20,10.90,141204389,12.60,10.90,-2.68,B,10.90,0.00,399453216,2023-02-10
1,KCE,2023-02-09,2023-02-09,52.75,48.50,62458648,58.50,48.50,-8.06,B,47.25,-1.25,43292690,2023-02-10
2,RCL,2023-02-03,2023-02-09,30.75,30.50,9524598,31.00,30.50,-0.81,B,30.75,0.25,1341212,2023-02-10
3,STA,2023-02-03,2023-02-09,22.30,24.10,46763601,24.10,22.20,8.07,B,23.90,-0.20,7751013,2023-02-10
4,IVL,2023-02-06,2023-02-09,40.50,40.75,46717485,41.25,40.25,0.62,I,40.50,-0.25,7953007,2023-02-10
5,JMART,2023-02-09,2023-02-09,36.25,35.50,23786917,37.75,35.50,-2.07,I,34.50,-1.00,7973040,2023-02-10
6,JMT,2023-02-09,2023-02-09,52.00,52.00,14352623,55.25,52.00,0.00,I,50.50,-1.50,11528715,2023-02-10
7,ORI,2023-02-07,2023-02-09,11.70,11.70,15697710,12.30,11.70,0.00,I,11.90,0.20,4834840,2023-02-10
8,SINGER,2023-02-09,2023-02-09,27.25,27.50,5240034,28.75,27.25,0.92,I,26.75,-0.75,2084092,2023-02-10
9,WHAIR,2023-01-31,2023-02-09,7.95,7.95,4955645,8.05,7.80,0.00,I,7.90,-0.05,321310,2023-02-10
10,CK,2023-02-08,2023-02-09,22.40,22.50,4639535,22.90,22.40,0.45,O,22.10,-0.40,3006254,2023-02-10
11,CKP,2023-02-03,2023-02-09,4.56,4.66,58053296,4.68,4.54,2.19,O,4.66,0.00,8920991,2023-02-10
12,COM7,2023-02-08,2023-02-09,31.75,31.00,17460938,33.25,31.00,-2.36,O,30.50,-0.50,6267187,2023-02-10
13,CPF,2023-02-09,2023-02-09,23.40,23.20,30068400,24.00,23.20,-0.85,O,22.90,-0.30,28297908,2023-02-10
14,MEGA,2023-02-03,2023-02-09,51.25,52.00,8141026,52.00,51.25,1.46,O,51.50,-0.50,1598024,2023-02-10
15,PTT,2023-02-08,2023-02-09,32.50,32.50,70754060,34.00,32.50,0.00,O,32.50,0.00,29952200,2023-02-10
16,TTB,2023-02-09,2023-02-09,1.41,1.40,252820767,1.47,1.40,-0.71,O,1.40,0.00,250902009,2023-02-10
17,TMT,2023-02-09,2023-02-09,8.10,8.05,279047,8.20,8.05,-0.62,S,8.20,0.15,158167,2023-02-10

In [23]:
df_merge[colu].shape

(18, 14)

In [24]:
df_merge.shape

(18, 19)

In [25]:
file_name = "daily-sales-prices.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(output_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(data_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(one_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(osd_file, header=True, index=False)

### Call ruby ruby\daily-out-new.rb

In [26]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [27]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [28]:
!ruby ruby\\daily-out-new.rb

Name      From Date    To Date   From     To     Pct     Shares    Max    Min S Action
BANPU    2023-02-10 2023-02-10  10.90  10.90     0.0  399453216  12.60  10.90 B Insert
CK       2023-02-08 2023-02-10  22.40  22.10   -1.34    3006254  22.90  22.40 O Update
CKP      2023-02-03 2023-02-10   4.56   4.66    2.19    8920991   4.68   4.54 O Update
COM7     2023-02-10 2023-02-10  31.00  30.50   -1.61    6267187  33.25  31.00 O Insert
CPF      2023-02-10 2023-02-10  23.20  22.90   -1.29   28297908  24.00  23.20 O Insert
IVL      2023-02-06 2023-02-10  40.50  40.50     0.0    7953007  41.25  40.25 I Update
JMART    2023-02-10 2023-02-10  35.50  34.50   -2.82    7973040  37.75  35.50 I Insert
JMT      2023-02-09 2023-02-10  52.00  50.50   -2.88   11528715  55.25  52.00 I Update
KCE      2023-02-10 2023-02-10  48.50  47.25   -2.58   43292690  58.50  48.50 B Insert
MEGA     2023-02-03 2023-02-10  51.25  51.50    0.49    1598024  52.00  51.25 O Update
ORI      2023-02-07 2023-02-10  11.70  11.90    1.71    4834840  12.30  11.70 I Update
PTT      2023-02-08 2023-02-10  32.50  32.50     0.0   29952200  34.00  32.50 O Update
RCL      2023-02-10 2023-02-10  30.50  30.75    0.82    1341212  31.00  30.50 B Insert
SINGER   2023-02-09 2023-02-10  27.25  26.75   -1.83    2084092  28.75  27.25 I Update
STA      2023-02-03 2023-02-10  22.30  23.90    7.17    7751013  24.10  22.20 B Update
TMT      2023-02-10 2023-02-10   8.05   8.20    1.86     158167   8.20   8.05 S Insert
TTB      2023-02-10 2023-02-10   1.40   1.40     0.0  250902009   1.47   1.40 O Insert
WHAIR    2023-01-31 2023-02-10   7.95   7.90   -0.63     321310   8.05   7.80 I Update

In [29]:
os.chdir("C:\\users\\user\\onedrive\\a7\\Daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\Daily'

### cd\ruby\port_lite
### rails runner db/ins_sales.rb