#### Restart and Run All

In [1]:
import numpy as np
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
#data_path = "\\users\\user\\onedrive\\a7\\Data"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 3, 11)

### Today = Last business day

In [11]:
today = date(2023, 3, 10)
today

datetime.date(2023, 3, 10)

In [12]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-03-10
yesterday: 2023-03-09

In [4]:
cols = 'name fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','percent':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### Begin of Tables in the process

In [5]:
sql = """
SELECT * 
FROM sales 
ORDER BY id DESC LIMIT 1
"""
tmp = pd.read_sql(sql, conlite)
tmp["fm_date"] = pd.to_datetime(tmp["fm_date"])
tmp["to_date"] = pd.to_datetime(tmp["to_date"])
tmp["created_at"] = pd.to_datetime(tmp["created_at"])
tmp["updated_at"] = pd.to_datetime(tmp["updated_at"])
tmp.style.format(format_dict)

In [6]:
names = tmp["name"]
type(names)

pandas.core.series.Series

In [7]:
name = names.to_string(index=False)
type(name)

str

In [9]:
sql = """
SELECT * 
FROM stocks
WHERE name = '%s'
"""
sql = sql % name
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'SNC'

### End of Tables in the process

In [13]:
sql = """
SELECT DISTINCT a.name
FROM sales a 
WHERE to_date = '%s'
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp

SELECT DISTINCT a.name
FROM sales a
WHERE to_date = '2023-03-09'
ORDER BY a.name

       name
0       ASK
1        BH
2       BJC
3   CPNREIT
4      GULF
5      HANA
6      ICHI
7     JMART
8       JMT
9        SC
10      SNC

In [14]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY t.status, a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-03-09' AND t.status IN ("B","I", "O", "S")
ORDER BY t.status, a.name

### This statement causes program to hang when there is no data

In [15]:
df = pd.read_sql(sql, conlite)
#df.set_index(["name"], inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('diff = to_price - fm_price',inplace=True)
df['percent'] = round(df['diff']/df['fm_price']*100,2)
df.style.format(format_dict)

In [12]:
df.shape

(11, 12)

### IF the above count not equal number of orders, there must be something incorrect

### Create daily-sales from sales

In [13]:
df[cols].style.format(format_dict)

In [14]:
file_name = "daily-sales.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(one_file, header=True, index=False)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(osd_file, header=True, index=False)

In [15]:
df[cols].shape

(11, 10)

In [16]:
sales = df[cols]
sales

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status
0,ASK,2023-02-24,2023-03-03,31.50,28.25,11911943,31.75,28.25,-10.32,B
1,CPNREIT,2023-02-21,2023-03-03,18.20,14.60,39048631,18.40,14.20,-19.78,B
2,JMART,2023-03-01,2023-03-03,27.50,26.75,29214181,28.50,26.25,-2.73,B
3,JMT,2023-02-24,2023-03-03,47.50,45.00,58821946,49.00,44.25,-5.26,B
4,BH,2023-02-24,2023-03-03,217.00,210.00,16248359,219.00,208.00,-3.23,O
5,BJC,2023-03-01,2023-03-03,37.75,36.50,16599359,38.75,35.50,-3.31,O
6,GULF,2023-03-01,2023-03-03,51.25,50.25,58687332,52.25,50.00,-1.95,O
7,HANA,2023-03-02,2023-03-03,57.00,54.50,51812994,59.75,51.75,-4.39,O
8,ICHI,2023-03-01,2023-03-03,12.60,12.40,28786415,13.00,12.30,-1.59,O
9,SC,2023-03-01,2023-03-03,4.56,4.44,49078693,4.68,4.44,-2.63,O
10,SNC,2023-03-02,2023-03-03,14.10,14.00,3916963,14.10,13.80,-0.71,O

In [17]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-03-09,2.46,0.04,1.652893,2.42,2.46,2.42,20644153,5.048300e+04
1,ADVANC,2023-03-09,207.00,3.00,1.470588,205.00,208.00,203.00,9664819,1.994800e+06
2,AEONTS,2023-03-09,198.50,3.00,1.534527,196.00,199.00,194.50,270157,5.339706e+04
3,AH,2023-03-09,31.00,0.25,0.813008,31.00,32.00,30.50,2921120,9.100374e+04
4,AIE,2023-03-09,2.52,0.00,0.000000,2.50,2.56,2.50,688667,1.733497e+03
...,...,...,...,...,...,...,...,...,...,...
186,WHAIR,2023-03-09,7.60,-0.10,-1.298701,7.70,7.70,7.60,373111,2.863005e+03
187,WHART,2023-03-09,11.10,0.10,0.909091,11.00,11.10,11.00,919551,1.014386e+04
188,WHAUP,2023-03-09,3.94,0.04,1.025641,3.90,3.96,3.90,1515263,5.962086e+03
189,WICE,2023-03-09,10.60,-0.10,-0.934579,10.70,10.80,10.50,1783338,1.897677e+04
190,WORK,2023-03-09,17.80,0.00,0.000000,17.70,17.80,17.70,56185,9.964430e+02

In [18]:
df_merge = pd.merge(sales,prices,on='name', how='inner')
df_merge

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,date,price,change,%change,open,high,low,volume,value(m)
0,ASK,2023-02-24,2023-03-03,31.50,28.25,11911943,31.75,28.25,-10.32,B,2023-03-09,28.50,0.25,0.884956,28.50,28.75,28.25,370063,10543.60725
1,CPNREIT,2023-02-21,2023-03-03,18.20,14.60,39048631,18.40,14.20,-19.78,B,2023-03-09,13.10,-1.10,-7.746479,14.20,14.40,12.80,13698456,182581.92270
2,JMART,2023-03-01,2023-03-03,27.50,26.75,29214181,28.50,26.25,-2.73,B,2023-03-09,25.25,-1.25,-4.716981,26.50,27.00,24.80,28249487,723527.38430
3,JMT,2023-02-24,2023-03-03,47.50,45.00,58821946,49.00,44.25,-5.26,B,2023-03-09,43.25,-1.00,-2.259887,44.50,45.25,43.25,10552470,463928.09925
4,BH,2023-02-24,2023-03-03,217.00,210.00,16248359,219.00,208.00,-3.23,O,2023-03-09,215.00,-1.00,-0.462963,215.00,216.00,214.00,1657574,356597.38800
5,BJC,2023-03-01,2023-03-03,37.75,36.50,16599359,38.75,35.50,-3.31,O,2023-03-09,38.00,-0.50,-1.298701,38.50,38.75,38.00,5663841,216673.51500
6,GULF,2023-03-01,2023-03-03,51.25,50.25,58687332,52.25,50.00,-1.95,O,2023-03-09,51.50,1.00,1.980198,50.75,51.75,50.50,15342892,785281.72950
7,HANA,2023-03-02,2023-03-03,57.00,54.50,51812994,59.75,51.75,-4.39,O,2023-03-09,54.25,2.00,3.827751,52.00,54.50,52.00,7402809,397655.94075
8,ICHI,2023-03-01,2023-03-03,12.60,12.40,28786415,13.00,12.30,-1.59,O,2023-03-09,13.10,0.40,3.149606,12.60,13.20,12.50,20651819,268027.61360
9,SC,2023-03-01,2023-03-03,4.56,4.44,49078693,4.68,4.44,-2.63,O,2023-03-09,4.54,-0.08,-1.731602,4.64,4.64,4.52,13052743,59672.41292
10,SNC,2023-03-02,2023-03-03,14.10,14.00,3916963,14.10,13.80,-0.71,O,2023-03-09,14.10,-0.10,-0.704225,14.20,14.30,14.10,993548,14057.77180

In [19]:
colu = 'name fm_date to_date fm_price to_price qty max_price min_price percent status \
price change volume date'.split()
colu

['name',
 'fm_date',
 'to_date',
 'fm_price',
 'to_price',
 'qty',
 'max_price',
 'min_price',
 'percent',
 'status',
 'price',
 'change',
 'volume',
 'date']

In [20]:
df_merge[colu]

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,price,change,volume,date
0,ASK,2023-02-24,2023-03-03,31.50,28.25,11911943,31.75,28.25,-10.32,B,28.50,0.25,370063,2023-03-09
1,CPNREIT,2023-02-21,2023-03-03,18.20,14.60,39048631,18.40,14.20,-19.78,B,13.10,-1.10,13698456,2023-03-09
2,JMART,2023-03-01,2023-03-03,27.50,26.75,29214181,28.50,26.25,-2.73,B,25.25,-1.25,28249487,2023-03-09
3,JMT,2023-02-24,2023-03-03,47.50,45.00,58821946,49.00,44.25,-5.26,B,43.25,-1.00,10552470,2023-03-09
4,BH,2023-02-24,2023-03-03,217.00,210.00,16248359,219.00,208.00,-3.23,O,215.00,-1.00,1657574,2023-03-09
5,BJC,2023-03-01,2023-03-03,37.75,36.50,16599359,38.75,35.50,-3.31,O,38.00,-0.50,5663841,2023-03-09
6,GULF,2023-03-01,2023-03-03,51.25,50.25,58687332,52.25,50.00,-1.95,O,51.50,1.00,15342892,2023-03-09
7,HANA,2023-03-02,2023-03-03,57.00,54.50,51812994,59.75,51.75,-4.39,O,54.25,2.00,7402809,2023-03-09
8,ICHI,2023-03-01,2023-03-03,12.60,12.40,28786415,13.00,12.30,-1.59,O,13.10,0.40,20651819,2023-03-09
9,SC,2023-03-01,2023-03-03,4.56,4.44,49078693,4.68,4.44,-2.63,O,4.54,-0.08,13052743,2023-03-09
10,SNC,2023-03-02,2023-03-03,14.10,14.00,3916963,14.10,13.80,-0.71,O,14.10,-0.10,993548,2023-03-09

In [21]:
df_merge[colu].shape

(11, 14)

In [22]:
df_merge.shape

(11, 19)

In [23]:
file_name = "daily-sales-prices.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(output_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(data_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(one_file, header=True, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(osd_file, header=True, index=False)

### Call ruby ruby\daily-out-new.rb

In [24]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [25]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [26]:
!ruby ruby\\daily-out-new.rb

Name      From Date    To Date   From     To     Pct     Shares    Max    Min S Action
ASK      2023-03-09 2023-03-09  28.25  28.50    0.88     370063  31.75  28.25 B Insert
BH       2023-03-09 2023-03-09 210.00 215.00    2.38    1657574 219.00 208.00 O Insert
BJC      2023-03-09 2023-03-09  36.50  38.00    4.11    5663841  38.75  35.50 O Insert
CPNREIT  2023-03-09 2023-03-09  14.60  13.10  -10.27   13698456  18.40  14.20 B Insert
GULF     2023-03-09 2023-03-09  50.25  51.50    2.49   15342892  52.25  50.00 O Insert
HANA     2023-03-09 2023-03-09  54.50  54.25   -0.46    7402809  59.75  51.75 O Insert
ICHI     2023-03-09 2023-03-09  12.40  13.10    5.65   20651819  13.00  12.30 O Insert
JMART    2023-03-09 2023-03-09  26.75  25.25   -5.61   28249487  28.50  26.25 B Insert
JMT      2023-03-09 2023-03-09  45.00  43.25   -3.89   10552470  49.00  44.25 B Insert
SC       2023-03-09 2023-03-09   4.44   4.54    2.25   13052743   4.68   4.44 O Insert
SNC      2023-03-09 2023-03-09  14.00  14.10    0.71     993548  14.10  13.80 O Insert

In [27]:
os.chdir("C:\\users\\user\\onedrive\\a7\\Daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\Daily'

### cd\ruby\port_lite
### rails runner db/ins_sales.rb