In [28]:
import numpy as np
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 2, 7)

### Yesterday = Last business day

In [29]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-07
yesterday: 2023-02-06

In [30]:
cols = 'fm_date to_date fm_price to_price qty max_price min_price percent status'.split()

format_dict = {
    'fm_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    'pct':'{:,.2f}%','percent':'{:,.2f}%',   
    'fm_date':'{:%Y-%m-%d}','to_date':'{:%Y-%m-%d}',
    'created_at':'{:%Y-%m-%d}','updated_at':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
}

### Begin of Tables in the process

In [31]:
sql = """
SELECT * 
FROM sales 
ORDER BY id DESC LIMIT 1
"""
tmp = pd.read_sql(sql, conlite)
tmp["fm_date"] = pd.to_datetime(tmp["fm_date"])
tmp["to_date"] = pd.to_datetime(tmp["to_date"])
tmp["created_at"] = pd.to_datetime(tmp["created_at"])
tmp["updated_at"] = pd.to_datetime(tmp["updated_at"])
tmp.style.format(format_dict)

In [32]:
names = tmp["name"]
type(names)

pandas.core.series.Series

In [33]:
name = names.to_string(index=False)
type(name)

str

In [34]:
sql = """
SELECT * 
FROM stocks
WHERE name = '%s'
"""
sql = sql % name
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'PTT'

### End of Tables in the process

In [35]:
sql = """
SELECT DISTINCT a.name
FROM sales a 
WHERE to_date = '%s'
ORDER BY a.name
"""
sql = sql % yesterday
print(sql)
tmp = pd.read_sql(sql, conlite)
tmp

SELECT DISTINCT a.name
FROM sales a
WHERE to_date = '2023-02-06'
ORDER BY a.name

      name
0    BANPU
1       CK
2      CKP
3     COM7
4      CPF
5      DIF
6      IVL
7    JASIF
8    JMART
9      JMT
10     KCE
11    MEGA
12     ORI
13     PTT
14     RCL
15  SINGER
16     STA
17     TMT
18     TTB
19   WHAIR

In [36]:
sql = """
SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a 
JOIN stocks t ON a.name = t.name 
WHERE to_date = '%s' AND t.status IN ("B","I", "O", "S") 
ORDER BY t.status, a.name
"""
sql = sql % yesterday
print(sql)

SELECT a.name,fm_date,to_date,fm_price,to_price,
a.qty,a.max_price,a.min_price,t.status,t.market
FROM sales a
JOIN stocks t ON a.name = t.name
WHERE to_date = '2023-02-06' AND t.status IN ("B","I", "O", "S")
ORDER BY t.status, a.name

### This statement causes program to hang when there is no data

In [37]:
df = pd.read_sql(sql, conlite)
df.set_index(["name"], inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df.eval('diff = to_price - fm_price',inplace=True)
df['percent'] = round(df['diff']/df['fm_price']*100,2)
df.style.format(format_dict)

In [38]:
df.shape

(20, 11)

### IF the above count not equal number of orders, there must be something incorrect

### Create daily-sales from sales

In [39]:
df[cols].style.format(format_dict)

In [40]:
file_name = "daily-sales.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(output_file,header=None)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(data_file,header=None)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(box_file)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(one_file)
df[cols].sort_values(['status','percent'],ascending=[True,True]).to_csv(osd_file)

In [41]:
df[cols].shape

(20, 9)

In [42]:
df.shape

(20, 11)

In [43]:
sales = df[cols]
sales

,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status
name,,,,,,,,,
BANPU,2023-02-06,2023-02-06,11.50,11.30,114777951,12.60,11.30,-1.74,B
KCE,2023-01-31,2023-02-06,54.75,56.50,239642338,58.50,50.50,3.20,B
RCL,2023-02-03,2023-02-06,30.75,31.00,4345349,31.00,30.50,0.81,B
DIF,2023-02-02,2023-02-06,13.60,13.60,24083621,13.70,13.60,0.00,I
IVL,2023-02-06,2023-02-06,40.50,41.00,16598179,41.25,40.25,1.23,I
JASIF,2023-02-03,2023-02-06,8.25,8.25,6779506,8.25,8.20,0.00,I
JMART,2023-02-03,2023-02-06,37.25,37.25,7649901,37.75,37.00,0.00,I
JMT,2023-02-03,2023-02-06,54.75,53.75,18242178,55.25,53.75,-1.83,I
ORI,2023-02-06,2023-02-06,12.00,11.70,5653682,12.30,11.70,-2.50,I
SINGER,2023-02-03,2023-02-06,28.25,28.25,5851577,28.75,28.00,0.00,I
STA,2023-02-03,2023-02-06,22.30,22.60,9701476,22.70,22.20,1.35,I
WHAIR,2023-01-31,2023-02-06,7.95,8.00,3788348,8.05,7.80,0.63,I
CK,2023-02-03,2023-02-06,22.70,22.70,3540911,22.90,22.60,0.00,O
CKP,2023-02-03,2023-02-06,4.56,4.60,14267804,4.60,4.54,0.88,O
COM7,2023-02-06,2023-02-06,32.25,32.25,4787998,33.25,32.00,0.00,O
CPF,2023-02-02,2023-02-06,23.80,23.60,42537865,24.00,23.60,-0.84,O
MEGA,2023-02-03,2023-02-06,51.25,51.75,2808644,52.00,51.25,0.98,O
PTT,2023-02-06,2023-02-06,33.00,32.75,34781194,34.00,32.50,-0.76,O
TTB,2023-02-02,2023-02-06,1.45,1.45,309856418,1.47,1.44,0.00,O
TMT,2023-02-03,2023-02-06,8.20,8.15,303427,8.20,8.10,-0.61,S

In [53]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,chg_amt,chg_pct,open,high,low,volume,daily_volume
0,ACE,2023-02-07,2.56,0.00,0.000000,2.56,2.58,2.54,23915176,61242.85760
1,ADVANC,2023-02-07,196.50,-0.50,-0.253807,197.00,198.00,196.00,3223977,633905.66650
2,AH,2023-02-07,32.75,-0.25,-0.757576,33.00,33.25,32.50,1688685,55467.10525
3,AIE,2023-02-07,3.00,0.14,4.895105,2.90,3.00,2.88,5198687,15360.20196
4,AIMIRT,2023-02-07,12.30,-0.10,-0.806452,12.40,12.40,12.30,122600,1508.11000
...,...,...,...,...,...,...,...,...,...,...
189,WHAIR,2023-02-07,8.00,0.00,0.000000,8.05,8.05,8.00,846450,6771.94520
190,WHART,2023-02-07,11.60,0.00,0.000000,11.60,11.70,11.60,484312,5621.89920
191,WHAUP,2023-02-07,4.12,0.00,0.000000,4.12,4.14,4.08,1427266,5862.84376
192,WICE,2023-02-07,11.70,-0.30,-2.500000,12.00,12.10,11.60,6565095,77325.61610
193,WORK,2023-02-07,18.60,0.00,0.000000,18.60,18.80,18.50,584418,10880.59270

In [54]:
df_merge = pd.merge(sales,prices,on='name', how='inner')

In [55]:
df_merge

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,date,price,chg_amt,chg_pct,open,high,low,volume,daily_volume
0,BANPU,2023-02-06,2023-02-06,11.50,11.30,114777951,12.60,11.30,-1.74,B,2023-02-07,11.20,-0.10,-0.884956,11.30,11.50,11.20,161516144,1.831534e+06
1,KCE,2023-01-31,2023-02-06,54.75,56.50,239642338,58.50,50.50,3.20,B,2023-02-07,57.00,0.50,0.884956,56.00,57.75,56.00,17516788,9.975574e+05
2,RCL,2023-02-03,2023-02-06,30.75,31.00,4345349,31.00,30.50,0.81,B,2023-02-07,31.00,0.00,0.000000,31.00,31.25,30.75,1864108,5.775278e+04
3,DIF,2023-02-02,2023-02-06,13.60,13.60,24083621,13.70,13.60,0.00,I,2023-02-07,13.60,0.00,0.000000,13.60,13.70,13.60,7390171,1.008499e+05
4,IVL,2023-02-06,2023-02-06,40.50,41.00,16598179,41.25,40.25,1.23,I,2023-02-07,40.50,-0.50,-1.219512,40.75,41.00,40.25,11842657,4.811257e+05
5,JASIF,2023-02-03,2023-02-06,8.25,8.25,6779506,8.25,8.20,0.00,I,2023-02-07,8.25,0.00,0.000000,8.25,8.25,8.20,3589348,2.953335e+04
6,JMART,2023-02-03,2023-02-06,37.25,37.25,7649901,37.75,37.00,0.00,I,2023-02-07,36.75,-0.50,-1.342282,37.25,37.50,36.50,8468235,3.136440e+05
7,JMT,2023-02-03,2023-02-06,54.75,53.75,18242178,55.25,53.75,-1.83,I,2023-02-07,53.00,-0.75,-1.395349,54.00,54.25,52.25,14084684,7.469663e+05
8,ORI,2023-02-06,2023-02-06,12.00,11.70,5653682,12.30,11.70,-2.50,I,2023-02-07,11.70,0.00,0.000000,11.80,11.80,11.50,8430180,9.813846e+04
9,SINGER,2023-02-03,2023-02-06,28.25,28.25,5851577,28.75,28.00,0.00,I,2023-02-07,28.00,-0.25,-0.884956,28.50,28.50,28.00,1866964,5.252393e+04
10,STA,2023-02-03,2023-02-06,22.30,22.60,9701476,22.70,22.20,1.35,I,2023-02-07,23.40,0.80,3.539823,22.60,23.60,22.60,17792391,4.106533e+05
11,WHAIR,2023-01-31,2023-02-06,7.95,8.00,3788348,8.05,7.80,0.63,I,2023-02-07,8.00,0.00,0.000000,8.05,8.05,8.00,846450,6.771945e+03
12,CK,2023-02-03,2023-02-06,22.70,22.70,3540911,22.90,22.60,0.00,O,2023-02-07,22.40,-0.30,-1.321586,22.60,22.80,22.40,5067398,1.142969e+05
13,CKP,2023-02-03,2023-02-06,4.56,4.60,14267804,4.60,4.54,0.88,O,2023-02-07,4.68,0.08,1.739130,4.64,4.72,4.60,24336619,1.136986e+05
14,COM7,2023-02-06,2023-02-06,32.25,32.25,4787998,33.25,32.00,0.00,O,2023-02-07,31.75,-0.50,-1.550388,32.00,32.25,31.25,15549744,4.951029e+05
15,CPF,2023-02-02,2023-02-06,23.80,23.60,42537865,24.00,23.60,-0.84,O,2023-02-07,23.60,0.00,0.000000,23.60,23.70,23.50,17028962,4.011831e+05
16,MEGA,2023-02-03,2023-02-06,51.25,51.75,2808644,52.00,51.25,0.98,O,2023-02-07,51.50,-0.25,-0.483092,51.75,52.00,50.50,2419856,1.241901e+05
17,PTT,2023-02-06,2023-02-06,33.00,32.75,34781194,34.00,32.50,-0.76,O,2023-02-07,32.50,-0.25,-0.763359,32.75,33.00,32.50,33729036,1.100507e+06
18,TTB,2023-02-02,2023-02-06,1.45,1.45,309856418,1.47,1.44,0.00,O,2023-02-07,1.42,-0.03,-2.068966,1.44,1.45,1.42,194236716,2.768448e+05
19,TMT,2023-02-03,2023-02-06,8.20,8.15,303427,8.20,8.10,-0.61,S,2023-02-07,8.15,0.00,0.000000,8.25,8.25,8.10,121777,9.952165e+02

In [56]:
df_merge.columns

Index(['name', 'fm_date', 'to_date', 'fm_price', 'to_price', 'qty',
       'max_price', 'min_price', 'percent', 'status', 'date', 'price',
       'chg_amt', 'chg_pct', 'open', 'high', 'low', 'volume', 'daily_volume'],
      dtype='object')

In [57]:
colu = 'name fm_date to_date fm_price to_price qty max_price min_price percent status \
price chg_amt volume date'.split()
colu

['name',
 'fm_date',
 'to_date',
 'fm_price',
 'to_price',
 'qty',
 'max_price',
 'min_price',
 'percent',
 'status',
 'price',
 'chg_amt',
 'volume',
 'date']

In [58]:
df_merge[colu]

,name,fm_date,to_date,fm_price,to_price,qty,max_price,min_price,percent,status,price,chg_amt,volume,date
0,BANPU,2023-02-06,2023-02-06,11.50,11.30,114777951,12.60,11.30,-1.74,B,11.20,-0.10,161516144,2023-02-07
1,KCE,2023-01-31,2023-02-06,54.75,56.50,239642338,58.50,50.50,3.20,B,57.00,0.50,17516788,2023-02-07
2,RCL,2023-02-03,2023-02-06,30.75,31.00,4345349,31.00,30.50,0.81,B,31.00,0.00,1864108,2023-02-07
3,DIF,2023-02-02,2023-02-06,13.60,13.60,24083621,13.70,13.60,0.00,I,13.60,0.00,7390171,2023-02-07
4,IVL,2023-02-06,2023-02-06,40.50,41.00,16598179,41.25,40.25,1.23,I,40.50,-0.50,11842657,2023-02-07
5,JASIF,2023-02-03,2023-02-06,8.25,8.25,6779506,8.25,8.20,0.00,I,8.25,0.00,3589348,2023-02-07
6,JMART,2023-02-03,2023-02-06,37.25,37.25,7649901,37.75,37.00,0.00,I,36.75,-0.50,8468235,2023-02-07
7,JMT,2023-02-03,2023-02-06,54.75,53.75,18242178,55.25,53.75,-1.83,I,53.00,-0.75,14084684,2023-02-07
8,ORI,2023-02-06,2023-02-06,12.00,11.70,5653682,12.30,11.70,-2.50,I,11.70,0.00,8430180,2023-02-07
9,SINGER,2023-02-03,2023-02-06,28.25,28.25,5851577,28.75,28.00,0.00,I,28.00,-0.25,1866964,2023-02-07
10,STA,2023-02-03,2023-02-06,22.30,22.60,9701476,22.70,22.20,1.35,I,23.40,0.80,17792391,2023-02-07
11,WHAIR,2023-01-31,2023-02-06,7.95,8.00,3788348,8.05,7.80,0.63,I,8.00,0.00,846450,2023-02-07
12,CK,2023-02-03,2023-02-06,22.70,22.70,3540911,22.90,22.60,0.00,O,22.40,-0.30,5067398,2023-02-07
13,CKP,2023-02-03,2023-02-06,4.56,4.60,14267804,4.60,4.54,0.88,O,4.68,0.08,24336619,2023-02-07
14,COM7,2023-02-06,2023-02-06,32.25,32.25,4787998,33.25,32.00,0.00,O,31.75,-0.50,15549744,2023-02-07
15,CPF,2023-02-02,2023-02-06,23.80,23.60,42537865,24.00,23.60,-0.84,O,23.60,0.00,17028962,2023-02-07
16,MEGA,2023-02-03,2023-02-06,51.25,51.75,2808644,52.00,51.25,0.98,O,51.50,-0.25,2419856,2023-02-07
17,PTT,2023-02-06,2023-02-06,33.00,32.75,34781194,34.00,32.50,-0.76,O,32.50,-0.25,33729036,2023-02-07
18,TTB,2023-02-02,2023-02-06,1.45,1.45,309856418,1.47,1.44,0.00,O,1.42,-0.03,194236716,2023-02-07
19,TMT,2023-02-03,2023-02-06,8.20,8.15,303427,8.20,8.10,-0.61,S,8.15,0.00,121777,2023-02-07

In [59]:
df_merge[colu].shape

(20, 14)

In [60]:
df_merge.shape

(20, 19)

In [61]:
file_name = "daily-sales-prices.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(output_file,header=None, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(data_file,header=None, index=False)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(box_file)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(one_file)
df_merge[colu].sort_values(['name'],ascending=[True]).to_csv(osd_file)

In [ ]:
### Call ruby ruby\daily-out-new.rb